(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
var rect; // used to reference frame bounds
lib.ssMetadata = [
		{name:"index_atlas_1", frames: [[1247,317,188,226],[1247,0,232,315],[0,0,1245,767]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.KING_1_52_26957 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.位图11 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.位图5 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.KING_1_16_26042复制4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A9AE4Qh0AAgEhxIAAhRQhYgkhHhRQgtgxgmhEIAYAKQCEAyBWAAIAAiFQAAh4B4AAMAxJAAAIAAgBIJdAAIAAgBIDNAAQB4AAAAB5IAAGEQgCA4geAcQgeAcg6AAIjAAAIAAAAIhqAAIAAACg");
	this.shape.setTransform(221.925,31);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.KING_1_16_26042复制4, rect = new cjs.Rectangle(0,-0.1,443.9,62.3), [rect]);


(lib.KING_1_16_26042复制3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Egj9AE4Qh0AAgEhxIAAhRQhYgkhHhRQgtgxgmhEIAYAKQCEAyBWAAIAAiFQAAh4B4AAMA/DAAAIAAgBIJdAAIAAgBIDNAAQB4AAAAB5IAAGEQgCA4geAcQgeAcg6AAIjAAAIAAAAIhqAAIAAACg");
	this.shape.setTransform(266.425,31);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.KING_1_16_26042复制3, rect = new cjs.Rectangle(0,-0.1,532.9,62.3), [rect]);


(lib.KING_1_16_26042复制2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EghOAE4Qh0AAgEhxIAAhRQhYgkhHhRQgtgxgmhEIAYAKQCEAyBWAAIAAiFQAAh4B4AAMA8HAAAIAAgBIG7AAIAAgBIDNAAQB4AAAAB5IAAGEQgCA4geAcQgeAcg6AAIjAAAIAAAAIjvAAIAAACg");
	this.shape.setTransform(248.925,31);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.KING_1_16_26042复制2, rect = new cjs.Rectangle(0,-0.1,497.9,62.3), [rect]);


(lib.KING_1_13_34484 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AzmDrIAAnVMAnNAAAIAAHVg");
	this.shape.setTransform(125.475,22.5);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = null;
p.frameBounds = [rect, rect, rect, new cjs.Rectangle(0,-1,251,47)];


(lib.KING_1_5_85426 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.149)").s().p("AgkA8QgQgZAAgjQAAgiAQgYQAPgZAVAAQAWAAAPAZQAQAYAAAiQAAAjgQAZQgPAYgWAAQgVAAgPgYg");
	this.shape.setTransform(-10.8637,248.8558,1.2014,1.2014);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFAED").s().p("AgkA8QgQgZAAgjQAAgiAQgYQAPgZAVAAQAWAAAPAZQAQAYAAAiQAAAjgQAZQgPAYgWAAQgVAAgPgYg");
	this.shape_1.setTransform(-10.8637,248.8558,1.2014,1.2014);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},4).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = null;
p.frameBounds = [rect, rect=new cjs.Rectangle(-17.2,238.8,12.6,20.2), rect, rect, rect, rect, rect];


(lib.KING_1_3_43229 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#F99703").ss(0.5,1,1).p("AgMgKIAZAAQAFAAADADQADADAAAEIAAAAQAAAFgDADQgDADgFAAIgZAAQgFAAgDgDQgDgDAAgFIAAAAQAAgEADgDQADgDAFAAg");
	this.shape.setTransform(20.2734,10.9751,0.7179,0.7183,-1.0066);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F99703").s().p("AgMALQgFAAgDgDQgDgDAAgFIAAAAQAAgEADgDQADgDAFAAIAZAAQAFAAADADQADADAAAEIAAAAQAAAFgDADQgDADgFAAg");
	this.shape_1.setTransform(20.2734,10.9751,0.7179,0.7183,-1.0066);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAACsQgKABgIgJQgIgHAAgLIAAkjQAAgLAIgIQAIgHAKAAIAAAAQALAAAIAHQAIAIAAALIAAEjQAAALgIAHQgIAJgLgBg");
	this.shape_2.setTransform(22.5783,22.4041,0.3436,0.269);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAACsQgKABgIgJQgIgHAAgLIAAkjQAAgLAIgIQAIgHAKAAIAAAAQALAAAIAHQAIAIAAALIAAEjQAAALgIAHQgIAJgLgBg");
	this.shape_3.setTransform(18.0283,22.4041,0.3436,0.269);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F99703").s().p("Ai9BQQghAAgXgYQgYgXAAghQAAggAYgYQAXgXAhAAIF7AAQAhAAAYAXQAXAYAAAgQAAAhgXAXQgYAYghAAg");
	this.shape_4.setTransform(20.1509,14.1754,0.3437,0.344,-0.2262);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F99703").s().p("Ag2BgQglAAAAglIgNiYIgBgBIABgBIDQAAIACACIAAAAIgSCYQAAAlgmAAg");
	this.shape_5.setTransform(20.3762,23.3401,0.7179,0.7184);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#F99703").ss(3,1,1).p("AiQCQQg8g7AAhVQAAhUA8g8QA8g8BUAAQBUAAA8A8QAJAIAHAJQADAEAEAFQAmA0AABCQAABVg9A7Qg8A9hUAAQhUAAg8g9g");
	this.shape_6.setTransform(20.475,20.475);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AiQCQQg8g7AAhVQAAhUA8g8QA8g8BUAAQBUAAA8A8IAQARIAHAJQAmA0AABCQAABVg9A7Qg8A9hUAAQhUAAg8g9g");
	this.shape_7.setTransform(20.475,20.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-1.5,-1.5,44,44);
p.frameBounds = [rect, rect];


(lib.KING_1_2_47761 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#F69602").ss(6,1,1).p("AhBhxIAADjABChxIAADj");
	this.shape.setTransform(20.4957,20.4917,0.7181,0.7185);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#F69602").ss(3,1,1).p("AjJDIQhThSAAh2QAAh1BThUQBUhTB1AAQB2AABTBTQBUBUAAB1QAAB2hUBSQhTBVh2AAQh1AAhUhVg");
	this.shape_1.setTransform(20.4598,20.4917,0.7181,0.7185);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AjJDIQhThSAAh2QAAh1BThUQBUhTB1AAQB2AABTBTQBUBUAAB1QAAB2hUBSQhTBVh2AAQh1AAhUhVg");
	this.shape_2.setTransform(20.4598,20.4917,0.7181,0.7185);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-1.5,-1.5,44,44);
p.frameBounds = [rect, rect];


(lib.KING_1_1_84633 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F99703").s().p("Ah9CPQgHgHgBgIIgBj7QABgIAEgHIAEgEQAIgIAMAAQAFAAAFACIDcB/IABACQAFAEACAFQACAFAAAFQAAAGgCAEQgCAFgFAEIgEAFIjZB9QgFACgFAAQgMAAgIgIg");
	this.shape.setTransform(23.281,20.4775,0.684,0.6844);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#F99703").ss(3,1,1).p("AiKCKQg6g5AAhRQAAhQA6g6QA6g5BQAAQBRAAA6A5QA6A6AABQQAABRg6A5Qg6A6hRAAQhQAAg6g6g");
	this.shape_1.setTransform(20.4871,20.4731,1.0426,1.0432);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AiKCKQg5g5gBhRQABhQA5g6QA5g5BRAAQBRAAA5A5QA7A6AABQQAABRg7A5Qg5A6hRAAQhRAAg5g6g");
	this.shape_2.setTransform(20.4871,20.4731,1.0426,1.0432);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-1.5,-1.5,44,44);
p.frameBounds = [rect, rect];


(lib.KING_1_12_80080 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.isSingleFrame = false;
	// timeline functions:
	this.frame_0 = function() {
		if(this.isSingleFrame) {
			return;
		}
		if(this.totalFrames == 1) {
			this.isSingleFrame = true;
		}
		var _this = this;
		_this.stop();
		// 初始化状态
		function init(showPlay) {
		    _this.b_play.visible = showPlay;  // 根据参数控制播放按钮的显示
		    _this.b_pause.visible = !showPlay; // 根据参数控制暂停按钮的显示
		}
		_this.setStu=function(showPlay){
		    _this.b_play.visible = showPlay;  // 根据参数控制播放按钮的显示
		    _this.b_pause.visible = !showPlay; // 根据参数控制暂停按钮的显示
		}
		
		// 事件监听
		this.b_play.addEventListener("click", () => fl_MouseClickHandler_3(true));
		this.b_pause.addEventListener("click", () => fl_MouseClickHandler_3(false));
		
		function fl_MouseClickHandler_3(isPlay) { 
		    if (isPlay) {
		        _this.parent.onPlay();
		        _this.b_play.visible = false; 
		        _this.b_pause.visible = true;  
		    } else {
		        _this.parent.onPause();
		        _this.b_play.visible = true; 
		        _this.b_pause.visible = false;  
		    }
		    //_this.parent.isPlaying = !_this.parent.isPlaying; // 切换播放状态
		}
		
		// 调用初始化方法，初始状态为播放按钮显示
		init(true);
		
		
		this.b_clear.addEventListener("click", fl_MouseClickHandler_4.bind(this));
		
		function fl_MouseClickHandler_4()
		{
			_this.parent.onClear();
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// 图层_1
	this.b_clear = new lib.KING_1_3_43229();
	this.b_clear.name = "b_clear";
	this.b_clear.setTransform(76.2,20.4,1,1,0,0,0,20.4,20.4);
	new cjs.ButtonHelper(this.b_clear, 0, 1, 1);

	this.b_pause = new lib.KING_1_2_47761();
	this.b_pause.name = "b_pause";
	this.b_pause.setTransform(20.4,20.4,1,1,0,0,0,20.4,20.4);
	new cjs.ButtonHelper(this.b_pause, 0, 1, 1);

	this.b_play = new lib.KING_1_1_84633();
	this.b_play.name = "b_play";
	this.b_play.setTransform(20.4,20.4,1,1,0,0,0,20.4,20.4);
	new cjs.ButtonHelper(this.b_play, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.b_play},{t:this.b_pause},{t:this.b_clear}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.KING_1_12_80080, rect = new cjs.Rectangle(-1.5,-1.5,99.8,44), [rect]);


(lib.KING_1_8_13991复制4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));

	// 图层_3
	this.instance = new lib.KING_1_13_34484();
	this.instance.setTransform(234,30,1.6024,1.0226,0,0,0,125.8,23.8);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.KING_1_13_34484(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AGkBSQAKAAAGgDQAGgCAEgGQAEgFACgJIgrhsIATAAIAhBaIABAAIAghaIARAAIgnBoQgFAOgGAKQgGAKgJAFQgKAFgQAAgAjsBgIgMgBIAAgPIANACIANAAQASAAAJgHQAJgJAAgSIAAgMQgDALgJAEQgIAGgPAAQgSAAgKgHQgKgHgEgMQgEgMAAgSQAAgOAEgNQAEgMAKgIQAKgHASAAQAKAAAIADQAHADAEAFQAEAFACAHIAAgVIARAAIAABlQAAAWgNANQgMAMgcAAIgOgBgAjuggQgGAFgCAJQgCAKAAAJQAAAMACAJQACAJAGAGQAGAFANABQANAAAHgGQAIgEADgJQADgKgBgNQABgLgDgKQgDgJgIgFQgHgEgNAAQgNgBgGAHgAcEA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgAcMgjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgAYxA7QgRAAgLgIQgKgJgGgRIgBgJIgBgIIAAgFQAAgRAHgNQAHgMAOgIIALgFIAKgBIACAAQASAAANATIAAgEIARAAIAAA5IABAUIADATIgBAAIgQAAQgBAAAAAAQAAgBAAAAQAAgBgBgBQAAAAAAgCIgCgMIgDAFIgFAFQgFAEgGACQgGACgHAAgAYkgfQgJAGgFAMIgCAIIgBAIIAAAEQAAAKAFAJQAEAIAIAHIAHADIAHAAIAEAAQAfABAAgnIAAgGQAAgPgFgKQgGgJgLgDIgDAAIgDAAQgNAAgIAGgAU+A2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAGIAAAHIhKAEQAAAMADAHQADAIAIAEQAIADANAAQAJAAAJgBQAJgCAHgEIAAAQIgJADIgNADIgPABQgQAAgLgFgAVFgjQgHAFgCAIQgDAIAAALIA6gFQAAgHgCgIQgCgHgFgFQgGgDgMAAQgMAAgHADgANQA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQAQAAAMAFQALAFAGANQAFAMAAAVQAAAVgFAMQgGANgLAFQgMAFgQAAQgQAAgLgFgANYgjQgHAEgDAKQgDAIAAAQQAAAQADAIQADAJAHAFQAHADAMAAQAMAAAHgDQAHgFADgJQADgIAAgQQAAgQgDgIQgDgKgHgEQgHgDgMAAQgMAAgHADgAKnA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgAKvgjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgAFFA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAGIAAAHIhKAEQAAAMADAHQADAIAIAEQAIADANAAQAJAAAJgBQAJgCAHgEIAAAQIgJADIgNADIgPABQgQAAgLgFgAFMgjQgHAFgCAIQgDAIAAALIA6gFQAAgHgCgIQgCgHgFgFQgGgDgMAAQgMAAgHADgAlwA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQAQAAAMAFQALAFAGANQAFAMAAAVQAAAVgFAMQgGANgLAFQgMAFgQAAQgQAAgLgFgAlogjQgHAEgDAKQgDAIAAAQQAAAQADAIQADAJAHAFQAHADAMAAQAMAAAHgDQAHgFADgJQADgIAAgQQAAgQgDgIQgDgKgHgEQgHgDgMAAQgMAAgHADgAq0A2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQAMgFAQAAQAQAAALAFQALAFAGANQAGAMAAAVQAAAVgGAMQgGANgLAFQgLAFgQAAQgQAAgMgFgAqrgjQgHAEgDAKQgDAIAAAQQAAAQADAIQADAJAHAFQAHADAMAAQAMAAAHgDQAHgFADgJQADgIgBgQQABgQgDgIQgEgKgHgEQgHgDgLAAQgMAAgHADgAxIA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgAxAgjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgAz/A7QgRAAgLgIQgKgJgGgRIgBgJIgBgIIAAgFQAAgRAHgNQAHgMAOgIIALgFIAKgBIACAAQASAAANATIAAgEIARAAIAAA5IABAUIADATIgBAAIgQAAQAAAAgBAAQAAgBAAAAQAAgBgBgBQAAAAAAgCIgCgMIgDAFIgFAFQgFAEgGACQgGACgHAAgA0MgfQgJAGgFAMIgCAIIgBAIIAAAEQAAAKAFAJQAEAIAIAHIAHADIAHAAIAEAAQAfABAAgnIAAgGQAAgPgFgKQgGgJgLgDIgDAAIgDAAQgNAAgIAGgA25A2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgA2xgjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgA56A2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgA5ygjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgAd1A6QgFAAgDAAQgDgCgBgDQgBgCAAgGQAAgHADgDQADgDAHABQAHgBADADQADADAAAHQAAAGgCACQgBADgDACIgEAAIgDAAgAgXA6QgFAAgCAAQgDgCgBgDQgCgCAAgGQAAgHADgDQADgDAHABQAHgBADADQADADAAAHQAAAGgBACQgBADgDACIgFAAIgDAAgAR7A3QgHgCgDgIQgEgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIASAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQABAFAEACQADACAGgBIAHAAIAFAAIAAAOIgGABIgGAAIgDAAQgKAAgGgDgAuhA3QgHgCgDgIQgEgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIASAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQABAFAEACQADACAGgBIAHAAIAFAAIAAAOIgGABIgGAAIgDAAQgKAAgGgDgAXcA1QgGgGAAgMIAAiCIARAAIAAB+QAAAHADADQACADAGgBIAEAAIAEAAIAAAOIgFABIgHAAIgCAAQgKAAgGgFgAhrA6IgLAAIgMgBIgIgDIAAgOIAJACIALABIALABQANAAAGgDQAGgFAAgJQABgGgCgEQgCgDgFgCQgGgDgKgCQgMgDgHgEQgGgCgDgHQgDgGAAgIQABgOAJgIQAKgIAUAAIAPABIAMADIgBAOQgFgCgHAAQgHgCgHAAQgMAAgFADQgGAEAAAJQAAAGABADQACADAFABQAEACAJACQAMADAIADQAHAEADAGQAEAGAAAKQAAARgLAIQgKAHgSAAIgDAAgAbKA5IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAHAAIAlgsIAWAAIguAyIAxA6gAT4A5IAAhEQAAgIgCgHQgBgFgFgEQgEgDgJABQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAiYIARAAIAAA7QADgGAGgEQAGgEAGgCIAOgBQAOAAAIAFQAIAEADAIQAEAIgBAKIAABLgAQDA5IAAhEQAAgIgBgHQgCgFgEgEQgFgDgIABQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAhsIARAAIAAAPQAEgGAGgEQAFgEAHgCIANgBQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgAJKA5IAAhsIARAAIAAAUQAEgJAGgFQAFgEAHgDIANgBIACAAIAAAQIgDAAQgHgBgGACQgHACgFAGQgFAFgEAKIAABGgAD/A5IAAhEQAAgIgCgHQgBgFgFgEQgEgDgJABQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAiYIARAAIAAA7QADgGAGgEQAGgEAGgCIAOgBQAOAAAIAFQAIAEADAIQAEAIgBAKIAABLgABnA5IAAh7IgpAAIAAgQIBkAAIAAAQIgpAAIAAB7gAnNA5IAAhsIARAAIAAAUQADgJAGgFQAGgEAGgDIAOgBIACAAIgBAQIgCAAQgHgBgHACQgGACgGAGQgFAFgDAKIAABGgAoQA5IAAheIgSAAIAAgOIASAAIAAgBQAAgSAFgLQAEgJAIgDQAJgEALAAIAGABIAGABIAAANIgFAAIgHAAQgIgBgEADQgEADgCAHQgCAGAAANIAaAAIAAAOIgaAAIAABegAsPA5IgbhYIgBAAIgbBYIgWAAIgdhsIARAAIAXBbIABAAIAbhbIAVAAIAcBbIABAAIAXhbIARAAIgeBsgAylA5IAAhsIARAAIAAAUQAEgJAGgFQAFgEAHgDIANgBIACAAIAAAQIgDAAQgHgBgGACQgHACgFAGQgFAFgEAKIAABGgA4WA5IAAhsIARAAIAAAUQAEgJAGgFQAFgEAHgDIANgBIACAAIAAAQIgDAAQgHgBgGACQgHACgFAGQgFAFgEAKIAABGgA6/A5IAAhEQAAgIgCgHQgCgFgEgEQgFgDgIABQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAiYIARAAIAAA7QAEgGAGgEQAFgEAHgCIANgBQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgA9YA5IAAh7IgpAAIAAgQIBkAAIAAAQIgpAAIAAB7gAIOgsIAGgRIAEgSIABgQIASAAQAAAHgDAJQgCAKgDAIIgIARg");
	this.shape.setTransform(232.275,32.2);

	this.instance_1 = new lib.KING_1_16_26042复制4();
	this.instance_1.setTransform(328.85,42.25,1,1,0,0,0,327.9,42.3);
	this.instance_1.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AGkBSQAKAAAGgDQAGgCAEgGQAEgFACgJIgrhsIATAAIAhBaIABAAIAghaIARAAIgnBoQgFAOgGAKQgGAKgJAFQgKAFgQAAgAjsBgIgMgBIAAgPIANACIANAAQASAAAJgHQAJgJAAgSIAAgMQgDALgJAEQgIAGgPAAQgSAAgKgHQgKgHgEgMQgEgMAAgSQAAgOAEgNQAEgMAKgIQAKgHASAAQAKAAAIADQAHADAEAFQAEAFACAHIAAgVIARAAIAABlQAAAWgNANQgMAMgcAAIgOgBgAjuggQgGAFgCAJQgCAKAAAJQAAAMACAJQACAJAGAGQAGAFANABQANAAAHgGQAIgEADgJQADgKgBgNQABgLgDgKQgDgJgIgFQgHgEgNAAQgNgBgGAHgAcEA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgAcMgjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgAYxA7QgRAAgLgIQgKgJgGgRIgBgJIgBgIIAAgFQAAgRAHgNQAHgMAOgIIALgFIAKgBIACAAQASAAANATIAAgEIARAAIAAA5IABAUIADATIgBAAIgQAAQgBAAAAAAQAAgBAAAAQAAgBgBgBQAAAAAAgCIgCgMIgDAFIgFAFQgFAEgGACQgGACgHAAgAYkgfQgJAGgFAMIgCAIIgBAIIAAAEQAAAKAFAJQAEAIAIAHIAHADIAHAAIAEAAQAfABAAgnIAAgGQAAgPgFgKQgGgJgLgDIgDAAIgDAAQgNAAgIAGgAU+A2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAGIAAAHIhKAEQAAAMADAHQADAIAIAEQAIADANAAQAJAAAJgBQAJgCAHgEIAAAQIgJADIgNADIgPABQgQAAgLgFgAVFgjQgHAFgCAIQgDAIAAALIA6gFQAAgHgCgIQgCgHgFgFQgGgDgMAAQgMAAgHADgANQA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQAQAAAMAFQALAFAGANQAFAMAAAVQAAAVgFAMQgGANgLAFQgMAFgQAAQgQAAgLgFgANYgjQgHAEgDAKQgDAIAAAQQAAAQADAIQADAJAHAFQAHADAMAAQAMAAAHgDQAHgFADgJQADgIAAgQQAAgQgDgIQgDgKgHgEQgHgDgMAAQgMAAgHADgAKnA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgAKvgjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgAFFA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAGIAAAHIhKAEQAAAMADAHQADAIAIAEQAIADANAAQAJAAAJgBQAJgCAHgEIAAAQIgJADIgNADIgPABQgQAAgLgFgAFMgjQgHAFgCAIQgDAIAAALIA6gFQAAgHgCgIQgCgHgFgFQgGgDgMAAQgMAAgHADgAlwA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQAQAAAMAFQALAFAGANQAFAMAAAVQAAAVgFAMQgGANgLAFQgMAFgQAAQgQAAgLgFgAlogjQgHAEgDAKQgDAIAAAQQAAAQADAIQADAJAHAFQAHADAMAAQAMAAAHgDQAHgFADgJQADgIAAgQQAAgQgDgIQgDgKgHgEQgHgDgMAAQgMAAgHADgAq0A2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQAMgFAQAAQAQAAALAFQALAFAGANQAGAMAAAVQAAAVgGAMQgGANgLAFQgLAFgQAAQgQAAgMgFgAqrgjQgHAEgDAKQgDAIAAAQQAAAQADAIQADAJAHAFQAHADAMAAQAMAAAHgDQAHgFADgJQADgIgBgQQABgQgDgIQgEgKgHgEQgHgDgLAAQgMAAgHADgAxIA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgAxAgjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgAz/A7QgRAAgLgIQgKgJgGgRIgBgJIgBgIIAAgFQAAgRAHgNQAHgMAOgIIALgFIAKgBIACAAQASAAANATIAAgEIARAAIAAA5IABAUIADATIgBAAIgQAAQAAAAgBAAQAAgBAAAAQAAgBgBgBQAAAAAAgCIgCgMIgDAFIgFAFQgFAEgGACQgGACgHAAgA0MgfQgJAGgFAMIgCAIIgBAIIAAAEQAAAKAFAJQAEAIAIAHIAHADIAHAAIAEAAQAfABAAgnIAAgGQAAgPgFgKQgGgJgLgDIgDAAIgDAAQgNAAgIAGgA25A2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgA2xgjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgA56A2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgA5ygjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgAd1A6QgFAAgDAAQgDgCgBgDQgBgCAAgGQAAgHADgDQADgDAHABQAHgBADADQADADAAAHQAAAGgCACQgBADgDACIgEAAIgDAAgAgXA6QgFAAgCAAQgDgCgBgDQgCgCAAgGQAAgHADgDQADgDAHABQAHgBADADQADADAAAHQAAAGgBACQgBADgDACIgFAAIgDAAgAR7A3QgHgCgDgIQgEgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIASAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQABAFAEACQADACAGgBIAHAAIAFAAIAAAOIgGABIgGAAIgDAAQgKAAgGgDgAuhA3QgHgCgDgIQgEgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIASAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQABAFAEACQADACAGgBIAHAAIAFAAIAAAOIgGABIgGAAIgDAAQgKAAgGgDgAXcA1QgGgGAAgMIAAiCIARAAIAAB+QAAAHADADQACADAGgBIAEAAIAEAAIAAAOIgFABIgHAAIgCAAQgKAAgGgFgAhrA6IgLAAIgMgBIgIgDIAAgOIAJACIALABIALABQANAAAGgDQAGgFAAgJQABgGgCgEQgCgDgFgCQgGgDgKgCQgMgDgHgEQgGgCgDgHQgDgGAAgIQABgOAJgIQAKgIAUAAIAPABIAMADIgBAOQgFgCgHAAQgHgCgHAAQgMAAgFADQgGAEAAAJQAAAGABADQACADAFABQAEACAJACQAMADAIADQAHAEADAGQAEAGAAAKQAAARgLAIQgKAHgSAAIgDAAgAbKA5IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAHAAIAlgsIAWAAIguAyIAxA6gAT4A5IAAhEQAAgIgCgHQgBgFgFgEQgEgDgJABQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAiYIARAAIAAA7QADgGAGgEQAGgEAGgCIAOgBQAOAAAIAFQAIAEADAIQAEAIgBAKIAABLgAQDA5IAAhEQAAgIgBgHQgCgFgEgEQgFgDgIABQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAhsIARAAIAAAPQAEgGAGgEQAFgEAHgCIANgBQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgAJKA5IAAhsIARAAIAAAUQAEgJAGgFQAFgEAHgDIANgBIACAAIAAAQIgDAAQgHgBgGACQgHACgFAGQgFAFgEAKIAABGgAD/A5IAAhEQAAgIgCgHQgBgFgFgEQgEgDgJABQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAiYIARAAIAAA7QADgGAGgEQAGgEAGgCIAOgBQAOAAAIAFQAIAEADAIQAEAIgBAKIAABLgABnA5IAAh7IgpAAIAAgQIBkAAIAAAQIgpAAIAAB7gAnNA5IAAhsIARAAIAAAUQADgJAGgFQAGgEAGgDIAOgBIACAAIgBAQIgCAAQgHgBgHACQgGACgGAGQgFAFgDAKIAABGgAoQA5IAAheIgSAAIAAgOIASAAIAAgBQAAgSAFgLQAEgJAIgDQAJgEALAAIAGABIAGABIAAANIgFAAIgHAAQgIgBgEADQgEADgCAHQgCAGAAANIAaAAIAAAOIgaAAIAABegAsPA5IgbhYIgBAAIgbBYIgWAAIgdhsIARAAIAXBbIABAAIAbhbIAVAAIAcBbIABAAIAXhbIARAAIgeBsgAylA5IAAhsIARAAIAAAUQAEgJAGgFQAFgEAHgDIANgBIACAAIAAAQIgDAAQgHgBgGACQgHACgFAGQgFAFgEAKIAABGgA4WA5IAAhsIARAAIAAAUQAEgJAGgFQAFgEAHgDIANgBIACAAIAAAQIgDAAQgHgBgGACQgHACgFAGQgFAFgEAKIAABGgA6/A5IAAhEQAAgIgCgHQgCgFgEgEQgFgDgIABQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAiYIARAAIAAA7QAEgGAGgEQAFgEAHgCIANgBQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgA9YA5IAAh7IgpAAIAAgQIBkAAIAAAQIgpAAIAAB7gAIOgsIAGgRIAEgSIABgQIASAAQAAAHgDAJQgCAKgDAIIgIARg");
	this.shape_1.setTransform(232.275,32.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.shape}]}).to({state:[{t:this.instance_1},{t:this.shape_1}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-6,-7.2,461,80);
p.frameBounds = [rect, rect];


(lib.KING_1_8_13991复制3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));

	// 图层_3
	this.instance = new lib.KING_1_13_34484();
	this.instance.setTransform(278.6,30,1.9572,1.0226,0,0,0,125.8,23.8);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.KING_1_13_34484(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AcvBgIgMgCIAAgOIANACIAOAAQASAAAJgIQAIgJAAgSIAAgLQgDAKgIAFQgIAFgQAAQgSABgKgIQgKgGgDgNQgEgMAAgRQAAgPAEgMQADgMAKgIQAKgHASAAQALAAAHACQAHAEAEAEQAEAFACAHIAAgVIASAAIAABlQAAAWgNANQgNANgcAAIgOgBgActghQgGAGgCAJQgCAKAAAJQAAAMACAIQACAKAHAGQAGAFAMAAQANAAAIgFQAHgEADgKQADgJAAgNQAAgLgDgKQgDgJgHgFQgIgFgNAAQgMAAgHAGgALlBSQAKAAAGgDQAGgCAEgGQAEgGACgJIgrhsIATAAIAhBaIABAAIAghaIARAAIgnBpQgFAOgGAJQgGALgJAEQgKAGgQAAgEAgFAA6QgQABgLgJQgLgJgFgQIgCgJIAAgIIAAgGQAAgQAHgNQAGgMAOgJIALgEIAKgBIACAAQATAAAMATIAAgFIASAAIAAA6IABATIACATIgBAAIgQAAQAAAAAAAAQAAAAgBgBQAAAAAAgBQgBgBAAgBIgBgNIgEAGIgEAEQgFAFgGABQgGACgHAAgAf4ggQgIAHgFALIgCAIIgBAIIAAAFQAAAKAEAJQAEAIAIAGIAHAEIAIAAIAEAAQAfAAAAgmIAAgGQAAgQgGgJQgFgJgLgDIgEAAIgDgBQgMAAgJAGgAZ/A2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIQACAIAAAIIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAaGgjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgASRA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQAQAAAMAEQALAGAGAMQAFANAAAUQAAAVgFANQgGAMgLAGQgMAEgQAAQgQAAgLgEgASZgjQgHAEgDAJQgDAJAAAPQAAAQADAJQADAJAHAEQAHAEAMAAQAMAAAHgEQAHgEADgJQADgJAAgQQAAgPgDgJQgDgJgHgEQgHgEgMAAQgMAAgHAEgAPoA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAPvgjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgAKGA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIQACAIAAAIIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAKNgjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgAggA1QgIgGgEgJIgCASIgPAAIAAiYIARAAIAABAQAEgKAIgGQAIgFAQAAQARgBAKAIQAKAHADANQAEAMAAAQQAAAQgEAMQgDANgKAHQgKAIgRAAQgQABgIgGgAgfgiQgHAFgDAKQgDAJAAAMQAAAMADAKQADAKAHAEQAIAFANABQALgBAHgFQAGgGACgKQACgJAAgLQAAgKgCgKQgCgJgHgGQgGgGgLAAQgNAAgIAFgAigA1QgIgGgEgJIgCASIgPAAIAAiYIARAAIAABAQAEgKAIgGQAIgFAQAAQASgBAKAIQAKAHADANQAEAMAAAQQAAAQgEAMQgDANgKAHQgKAIgSAAQgQABgIgGgAifgiQgHAFgDAKQgDAJAAAMQAAAMADAKQADAKAHAEQAIAFANABQAMgBAHgFQAGgGACgKQACgJAAgLQAAgKgCgKQgCgJgHgGQgGgGgMAAQgNAAgIAFgAkXA6QgRABgLgJQgKgJgGgQIgBgJIgBgIIAAgGQAAgQAHgNQAHgMAOgJIALgEIAKgBIACAAQASAAANATIAAgFIARAAIAAA6IABATIADATIgBAAIgQAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAgBAAgBIgCgNIgDAGIgFAEQgFAFgGABQgGACgHAAgAkkggQgJAHgFALIgCAIIgBAIIAAAFQAAAKAFAJQAEAIAIAGIAHAEIAHAAIAEAAQAfAAAAgmIAAgGQAAgQgFgJQgGgJgLgDIgDAAIgDgBQgNAAgIAGgAodA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIQACAIAAAIIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAoWgjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgAxsA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQAMgEAQAAQAQAAALAEQALAGAGAMQAGANAAAUQAAAVgGANQgGAMgLAGQgLAEgQAAQgQAAgMgEgAxjgjQgHAEgDAJQgDAJAAAPQAAAQADAJQADAJAHAEQAHAEAMAAQAMAAAHgEQAHgEADgJQADgJgBgQQABgPgDgJQgEgJgHgEQgHgEgLAAQgMAAgHAEgA4AA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIQABAIAAAIIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgA34gjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgA63A6QgRABgLgJQgKgJgGgQIgBgJIgBgIIAAgGQAAgQAHgNQAHgMAOgJIALgEIAKgBIACAAQASAAANATIAAgFIARAAIAAA6IABATIADATIgBAAIgQAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAgBAAgBIgCgNIgDAGIgFAEQgFAFgGABQgGACgHAAgA7EggQgJAHgFALIgCAIIgBAIIAAAFQAAAKAFAJQAEAIAIAGIAHAEIAHAAIAEAAQAfAAAAgmIAAgGQAAgQgFgJQgGgJgLgDIgDAAIgDgBQgNAAgIAGgA9xA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIQABAIAAAIIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgA9pgjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgEggyAA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIIABAQIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgEggqgAjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgEAktAA5QgFABgDgBQgDgBgBgDQgBgCAAgGQAAgIADgCQADgDAHAAQAHAAADADQADACAAAIQAAAGgCACQgBADgDABIgEABIgDgBgAEpA5QgFABgCgBQgDgBgBgDQgCgCAAgGQAAgIADgCQADgDAHAAQAHAAADADQADACAAAIQAAAGgBACQgBADgDABIgFABIgDgBgAW8A3QgHgCgDgIQgEgHAAgPIAAg8IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQABAFAEABQADADAGgBIAHAAIAFgBIAAAOIgGABIgGAAIgDABQgKAAgGgDgACGA3QgHgCgDgIQgDgHAAgPIAAg8IgQAAIAAgPIAQAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQACAFADABQADADAHgBIAGAAIAGgBIAAAOIgGABIgGAAIgEABQgJAAgHgDgApkA3QgHgCgDgIQgDgHAAgPIAAg8IgQAAIAAgPIAQAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQACAFADABQADADAHgBIAGAAIAGgBIAAAOIgGABIgGAAIgEABQgJAAgHgDgA1ZA3QgHgCgDgIQgEgHAAgPIAAg8IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQABAFAEABQADADAGgBIAHAAIAFgBIAAAOIgGABIgGAAIgDABQgKAAgGgDgEAjZAA5IgLAAIgMgBIgIgCIAAgPIAJACIALACIALABQANAAAGgEQAGgEAAgJQABgHgCgDQgCgEgFgCQgGgDgKgBQgMgDgHgEQgGgDgDgGQgDgGAAgJQABgOAJgHQAKgJAUABIAPABIAMACIgBAPQgFgCgHgBQgHgCgHAAQgMAAgFAEQgGADAAAJQAAAGABADQACADAFACQAEACAJABQAMADAIAEQAHADADAHQAEAGAAAKQAAAQgLAIQgKAIgSAAIgDgBgEAh5AA5IgMAAIgLgBIgJgCIAAgPIAKACIALACIALABQAMAAAGgEQAHgEAAgJQAAgHgCgDQgCgEgFgCQgFgDgKgBQgMgDgHgEQgHgDgCgGQgDgGAAgJQAAgOAKgHQAKgJATABIAQABIAMACIgCAPQgEgCgHgBQgHgCgIAAQgLAAgGAEQgGADAAAJQAAAGACADQACADAEACQAFACAIABQANADAHAEQAIADADAHQADAGAAAKQAAAQgKAIQgLAIgSAAIgCgBgADVA5IgLAAIgMgBIgIgCIAAgPIAJACIALACIALABQANAAAGgEQAGgEAAgJQABgHgCgDQgCgEgFgCQgGgDgKgBQgMgDgHgEQgGgDgDgGQgDgGAAgJQABgOAJgHQAKgJAUABIAPABIAMACIgBAPQgFgCgHgBQgHgCgHAAQgMAAgFAEQgGADAAAJQAAAGABADQACADAFACQAEACAJABQAMADAIAEQAHADADAHQAEAGAAAKQAAAQgLAIQgKAIgSAAIgDgBgAeYA4IAAhsIARAAIAAAUQADgIAGgFQAGgFAGgCIAOgBIACAAIgBAPIgCAAQgHAAgHACQgGACgGAGQgFAEgDAKIAABGgAY5A4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAiYIARAAIAAA8QADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAVEA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAhsIARAAIAAAQQADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAOLA4IAAhsIARAAIAAAUQAEgIAGgFQAFgFAHgCIANgBIACAAIAAAPIgDAAQgHAAgGACQgHACgFAGQgFAEgEAKIAABGgAJAA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAiYIARAAIAAA8QADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAGoA4IAAh7IgpAAIAAgPIBkAAIAAAPIgpAAIAAB7gABCA4IAAhsIARAAIAABsgAmFA4IAAhsIARAAIAAAUQAEgIAGgFQAFgFAHgCIANgBIACAAIAAAPIgDAAQgHAAgGACQgHACgFAGQgFAEgEAKIAABGgAqnA4IAAhsIARAAIAABsgArdA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAiYIARAAIAAA8QADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAtvA4IgbhYIgBAAIgbBYIgWAAIgdhsIARAAIAXBbIABAAIAbhbIAVAAIAcBbIABAAIAXhbIARAAIgeBsgAzHA4IgbhYIgBAAIgbBYIgWAAIgdhsIARAAIAXBbIABAAIAbhbIAVAAIAcBbIABAAIAXhbIARAAIgeBsgA5dA4IAAhsIARAAIAAAUQAEgIAGgFQAFgFAHgCIANgBIACAAIAAAPIgDAAQgHAAgGACQgHACgFAGQgFAEgEAKIAABGgA/OA4IAAhsIARAAIAAAUQAEgIAGgFQAFgFAHgCIANgBIACAAIAAAPIgDAAQgHAAgGACQgHACgFAGQgFAEgEAKIAABGgEgh3AA4IAAhEQAAgIgCgGQgCgFgEgEQgFgDgIAAQgHAAgHACQgGABgFAEQgFAGgEAJIAABIIgRAAIAAiYIARAAIAAA8QAEgHAGgDQAFgEAHgCIANgBQAPgBAIAFQAHAEAEAJQADAHAAALIAABKgEgkQAA4IAAh7IgpAAIAAgPIBkAAIAAAPIgpAAIAAB7gANPgsIAGgRIAEgSIABgRIASAAQAAAHgDAKQgCAJgDAJIgIARgABDhJQgDgDABgGQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAGgCADQgDACgFAAQgGAAgCgCgAqnhJQgCgDAAgGQAAgGACgCQADgCAFAAQAGAAACACQADACAAAGQAAAGgDADQgCACgGAAQgFAAgDgCg");
	this.shape.setTransform(277.275,32.25);

	this.instance_1 = new lib.KING_1_16_26042复制3();
	this.instance_1.setTransform(328.85,42.25,1,1,0,0,0,327.9,42.3);
	this.instance_1.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AcvBgIgMgCIAAgOIANACIAOAAQASAAAJgIQAIgJAAgSIAAgLQgDAKgIAFQgIAFgQAAQgSABgKgIQgKgGgDgNQgEgMAAgRQAAgPAEgMQADgMAKgIQAKgHASAAQALAAAHACQAHAEAEAEQAEAFACAHIAAgVIASAAIAABlQAAAWgNANQgNANgcAAIgOgBgActghQgGAGgCAJQgCAKAAAJQAAAMACAIQACAKAHAGQAGAFAMAAQANAAAIgFQAHgEADgKQADgJAAgNQAAgLgDgKQgDgJgHgFQgIgFgNAAQgMAAgHAGgALlBSQAKAAAGgDQAGgCAEgGQAEgGACgJIgrhsIATAAIAhBaIABAAIAghaIARAAIgnBpQgFAOgGAJQgGALgJAEQgKAGgQAAgEAgFAA6QgQABgLgJQgLgJgFgQIgCgJIAAgIIAAgGQAAgQAHgNQAGgMAOgJIALgEIAKgBIACAAQATAAAMATIAAgFIASAAIAAA6IABATIACATIgBAAIgQAAQAAAAAAAAQAAAAgBgBQAAAAAAgBQgBgBAAgBIgBgNIgEAGIgEAEQgFAFgGABQgGACgHAAgAf4ggQgIAHgFALIgCAIIgBAIIAAAFQAAAKAEAJQAEAIAIAGIAHAEIAIAAIAEAAQAfAAAAgmIAAgGQAAgQgGgJQgFgJgLgDIgEAAIgDgBQgMAAgJAGgAZ/A2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIQACAIAAAIIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAaGgjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgASRA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQAQAAAMAEQALAGAGAMQAFANAAAUQAAAVgFANQgGAMgLAGQgMAEgQAAQgQAAgLgEgASZgjQgHAEgDAJQgDAJAAAPQAAAQADAJQADAJAHAEQAHAEAMAAQAMAAAHgEQAHgEADgJQADgJAAgQQAAgPgDgJQgDgJgHgEQgHgEgMAAQgMAAgHAEgAPoA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAPvgjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgAKGA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIQACAIAAAIIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAKNgjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgAggA1QgIgGgEgJIgCASIgPAAIAAiYIARAAIAABAQAEgKAIgGQAIgFAQAAQARgBAKAIQAKAHADANQAEAMAAAQQAAAQgEAMQgDANgKAHQgKAIgRAAQgQABgIgGgAgfgiQgHAFgDAKQgDAJAAAMQAAAMADAKQADAKAHAEQAIAFANABQALgBAHgFQAGgGACgKQACgJAAgLQAAgKgCgKQgCgJgHgGQgGgGgLAAQgNAAgIAFgAigA1QgIgGgEgJIgCASIgPAAIAAiYIARAAIAABAQAEgKAIgGQAIgFAQAAQASgBAKAIQAKAHADANQAEAMAAAQQAAAQgEAMQgDANgKAHQgKAIgSAAQgQABgIgGgAifgiQgHAFgDAKQgDAJAAAMQAAAMADAKQADAKAHAEQAIAFANABQAMgBAHgFQAGgGACgKQACgJAAgLQAAgKgCgKQgCgJgHgGQgGgGgMAAQgNAAgIAFgAkXA6QgRABgLgJQgKgJgGgQIgBgJIgBgIIAAgGQAAgQAHgNQAHgMAOgJIALgEIAKgBIACAAQASAAANATIAAgFIARAAIAAA6IABATIADATIgBAAIgQAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAgBAAgBIgCgNIgDAGIgFAEQgFAFgGABQgGACgHAAgAkkggQgJAHgFALIgCAIIgBAIIAAAFQAAAKAFAJQAEAIAIAGIAHAEIAHAAIAEAAQAfAAAAgmIAAgGQAAgQgFgJQgGgJgLgDIgDAAIgDgBQgNAAgIAGgAodA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIQACAIAAAIIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAoWgjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgAxsA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQAMgEAQAAQAQAAALAEQALAGAGAMQAGANAAAUQAAAVgGANQgGAMgLAGQgLAEgQAAQgQAAgMgEgAxjgjQgHAEgDAJQgDAJAAAPQAAAQADAJQADAJAHAEQAHAEAMAAQAMAAAHgEQAHgEADgJQADgJgBgQQABgPgDgJQgEgJgHgEQgHgEgLAAQgMAAgHAEgA4AA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIQABAIAAAIIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgA34gjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgA63A6QgRABgLgJQgKgJgGgQIgBgJIgBgIIAAgGQAAgQAHgNQAHgMAOgJIALgEIAKgBIACAAQASAAANATIAAgFIARAAIAAA6IABATIADATIgBAAIgQAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAgBAAgBIgCgNIgDAGIgFAEQgFAFgGABQgGACgHAAgA7EggQgJAHgFALIgCAIIgBAIIAAAFQAAAKAFAJQAEAIAIAGIAHAEIAHAAIAEAAQAfAAAAgmIAAgGQAAgQgFgJQgGgJgLgDIgDAAIgDgBQgNAAgIAGgA9xA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIQABAIAAAIIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgA9pgjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgEggyAA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIIABAQIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgEggqgAjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgEAktAA5QgFABgDgBQgDgBgBgDQgBgCAAgGQAAgIADgCQADgDAHAAQAHAAADADQADACAAAIQAAAGgCACQgBADgDABIgEABIgDgBgAEpA5QgFABgCgBQgDgBgBgDQgCgCAAgGQAAgIADgCQADgDAHAAQAHAAADADQADACAAAIQAAAGgBACQgBADgDABIgFABIgDgBgAW8A3QgHgCgDgIQgEgHAAgPIAAg8IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQABAFAEABQADADAGgBIAHAAIAFgBIAAAOIgGABIgGAAIgDABQgKAAgGgDgACGA3QgHgCgDgIQgDgHAAgPIAAg8IgQAAIAAgPIAQAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQACAFADABQADADAHgBIAGAAIAGgBIAAAOIgGABIgGAAIgEABQgJAAgHgDgApkA3QgHgCgDgIQgDgHAAgPIAAg8IgQAAIAAgPIAQAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQACAFADABQADADAHgBIAGAAIAGgBIAAAOIgGABIgGAAIgEABQgJAAgHgDgA1ZA3QgHgCgDgIQgEgHAAgPIAAg8IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQABAFAEABQADADAGgBIAHAAIAFgBIAAAOIgGABIgGAAIgDABQgKAAgGgDgEAjZAA5IgLAAIgMgBIgIgCIAAgPIAJACIALACIALABQANAAAGgEQAGgEAAgJQABgHgCgDQgCgEgFgCQgGgDgKgBQgMgDgHgEQgGgDgDgGQgDgGAAgJQABgOAJgHQAKgJAUABIAPABIAMACIgBAPQgFgCgHgBQgHgCgHAAQgMAAgFAEQgGADAAAJQAAAGABADQACADAFACQAEACAJABQAMADAIAEQAHADADAHQAEAGAAAKQAAAQgLAIQgKAIgSAAIgDgBgEAh5AA5IgMAAIgLgBIgJgCIAAgPIAKACIALACIALABQAMAAAGgEQAHgEAAgJQAAgHgCgDQgCgEgFgCQgFgDgKgBQgMgDgHgEQgHgDgCgGQgDgGAAgJQAAgOAKgHQAKgJATABIAQABIAMACIgCAPQgEgCgHgBQgHgCgIAAQgLAAgGAEQgGADAAAJQAAAGACADQACADAEACQAFACAIABQANADAHAEQAIADADAHQADAGAAAKQAAAQgKAIQgLAIgSAAIgCgBgADVA5IgLAAIgMgBIgIgCIAAgPIAJACIALACIALABQANAAAGgEQAGgEAAgJQABgHgCgDQgCgEgFgCQgGgDgKgBQgMgDgHgEQgGgDgDgGQgDgGAAgJQABgOAJgHQAKgJAUABIAPABIAMACIgBAPQgFgCgHgBQgHgCgHAAQgMAAgFAEQgGADAAAJQAAAGABADQACADAFACQAEACAJABQAMADAIAEQAHADADAHQAEAGAAAKQAAAQgLAIQgKAIgSAAIgDgBgAeYA4IAAhsIARAAIAAAUQADgIAGgFQAGgFAGgCIAOgBIACAAIgBAPIgCAAQgHAAgHACQgGACgGAGQgFAEgDAKIAABGgAY5A4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAiYIARAAIAAA8QADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAVEA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAhsIARAAIAAAQQADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAOLA4IAAhsIARAAIAAAUQAEgIAGgFQAFgFAHgCIANgBIACAAIAAAPIgDAAQgHAAgGACQgHACgFAGQgFAEgEAKIAABGgAJAA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAiYIARAAIAAA8QADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAGoA4IAAh7IgpAAIAAgPIBkAAIAAAPIgpAAIAAB7gABCA4IAAhsIARAAIAABsgAmFA4IAAhsIARAAIAAAUQAEgIAGgFQAFgFAHgCIANgBIACAAIAAAPIgDAAQgHAAgGACQgHACgFAGQgFAEgEAKIAABGgAqnA4IAAhsIARAAIAABsgArdA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAiYIARAAIAAA8QADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAtvA4IgbhYIgBAAIgbBYIgWAAIgdhsIARAAIAXBbIABAAIAbhbIAVAAIAcBbIABAAIAXhbIARAAIgeBsgAzHA4IgbhYIgBAAIgbBYIgWAAIgdhsIARAAIAXBbIABAAIAbhbIAVAAIAcBbIABAAIAXhbIARAAIgeBsgA5dA4IAAhsIARAAIAAAUQAEgIAGgFQAFgFAHgCIANgBIACAAIAAAPIgDAAQgHAAgGACQgHACgFAGQgFAEgEAKIAABGgA/OA4IAAhsIARAAIAAAUQAEgIAGgFQAFgFAHgCIANgBIACAAIAAAPIgDAAQgHAAgGACQgHACgFAGQgFAEgEAKIAABGgEgh3AA4IAAhEQAAgIgCgGQgCgFgEgEQgFgDgIAAQgHAAgHACQgGABgFAEQgFAGgEAJIAABIIgRAAIAAiYIARAAIAAA8QAEgHAGgDQAFgEAHgCIANgBQAPgBAIAFQAHAEAEAJQADAHAAALIAABKgEgkQAA4IAAh7IgpAAIAAgPIBkAAIAAAPIgpAAIAAB7gANPgsIAGgRIAEgSIABgRIASAAQAAAHgDAKQgCAJgDAJIgIARgABDhJQgDgDABgGQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAGgCADQgDACgFAAQgGAAgCgCgAqnhJQgCgDAAgGQAAgGACgCQADgCAFAAQAGAAACACQADACAAAGQAAAGgDADQgCACgGAAQgFAAgDgCg");
	this.shape_1.setTransform(277.275,32.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.shape}]}).to({state:[{t:this.instance_1},{t:this.shape_1}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-6,-7.2,550,80);
p.frameBounds = [rect, rect];


(lib.KING_1_8_13991复制2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));

	// 图层_3
	this.instance = new lib.KING_1_13_34484();
	this.instance.setTransform(263.55,29.9,1.8058,1.0226,0,0,0,125.8,23.7);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.KING_1_13_34484(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Af1BSQAKAAAGgDQAGgCAEgGQAEgGACgJIgrhsIATAAIAhBaIABAAIAghaIARAAIgnBpQgFAOgGAJQgGALgJAEQgKAGgQAAgANGBSQAKAAAGgDQAGgCAEgGQAEgGACgJIgrhsIATAAIAhBaIABAAIAghaIARAAIgnBpQgFAOgGAJQgGALgJAEQgKAGgQAAgAsUBSQAJAAAGgDQAGgCAEgGQAEgGADgJIgshsIATAAIAhBaIACAAIAfhaIASAAIgnBpQgFAOgGAJQgGALgKAEQgJAGgQAAgAaZA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAaggjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgARJA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgARQgjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgALnA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgALugjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgACoA0QgKgIgDgNQgEgNAAgQQAAgOAEgNQADgMAKgIQAKgJASABQAQgBAIAGQAIAGADAJIAAg/IASAAIAACYIgPAAIgDgSQgDAKgJAFQgIAGgPgBQgSAAgKgGgACzghQgGAGgCAKQgCAJAAAKQAAALACAKQACAKAHAFQAGAFAMABQANgBAIgEQAHgGADgIQADgKAAgNQAAgLgDgKQgDgKgHgFQgIgFgNAAQgMAAgHAGgAhIA1QgIgGgEgJIgCASIgPAAIAAiYIARAAIAABAQAEgKAIgGQAIgFAQAAQASgBAKAIQAKAHADANQAEAMAAAQQAAAQgEAMQgDANgKAHQgKAIgSAAQgQABgIgGgAhHgiQgHAFgDAKQgDAJAAAMQAAAMADAKQADAKAHAEQAIAFANABQAMgBAHgFQAGgGACgKQACgJAAgLQAAgKgCgKQgCgJgHgGQgGgGgMAAQgNAAgIAFgAmsA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQAMgEAQAAQAQAAALAEQALAGAGAMQAGANAAAUQAAAVgGANQgGAMgLAGQgLAEgQAAQgQAAgMgEgAmjgjQgHAEgDAJQgDAJAAAPQAAAQADAJQADAJAHAEQAHAEAMAAQAMAAAHgEQAHgEADgJQADgJgBgQQABgPgDgJQgEgJgHgEQgHgEgLAAQgMAAgHAEgAqVA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIQABAIAAAIIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgAqNgjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgAuwA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQAMgEAQAAQAQAAALAEQALAGAGAMQAGANAAAUQAAAVgGANQgGAMgLAGQgLAEgQAAQgQAAgMgEgAungjQgHAEgDAJQgDAJAAAPQAAAQADAJQADAJAHAEQAHAEAMAAQAMAAAHgEQAHgEADgJQADgJgBgQQABgPgDgJQgEgJgHgEQgHgEgLAAQgMAAgHAEgA1EA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIIABAQIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgA08gjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgA37A6QgRABgLgJQgKgJgGgQIgBgJIgBgIIAAgGQAAgQAHgNQAHgMAOgJIALgEIAKgBIACAAQASAAANATIAAgFIARAAIAAA6IABATIADATIgBAAIgQAAQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAgBIgCgNIgDAGIgFAEQgFAFgGABQgGACgHAAgA4IggQgJAHgFALIgCAIIgBAIIAAAFQAAAKAFAJQAEAIAIAGIAHAEIAHAAIAEAAQAfAAAAgmIAAgGQAAgQgFgJQgGgJgLgDIgDAAIgDgBQgNAAgIAGgA61A2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIIABAQIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgA6tgjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgA92A2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIIABAQIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgA9ugjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgEAhxAA5QgFABgDgBQgDgBgBgDQgBgCAAgGQAAgIADgCQADgDAHAAQAHAAADADQADACAAAIQAAAGgCACQgBADgDABIgEABIgDgBgAGKA5QgFABgDgBQgDgBgBgDQgBgCAAgGQAAgIADgCQADgDAHAAQAHAAADADQADACAAAIQAAAGgCACQgBADgDABIgEABIgDgBgAXWA3QgHgCgDgIQgEgHAAgPIAAg8IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQABAFAEABQADADAGgBIAHAAIAFgBIAAAOIgGABIgGAAIgDABQgKAAgGgDgAydA3QgHgCgDgIQgEgHAAgPIAAg8IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQABAFAEABQADADAGgBIAHAAIAFgBIAAAOIgGABIgGAAIgDABQgKAAgGgDgAnwA1QgGgGAAgMIAAiDIARAAIAAB+QAAAIACACQADAEAFgBIAEAAIAEgBIAAAOIgFABIgGAAIgCABQgLAAgFgFgAoqA1QgGgGAAgMIAAiDIARAAIAAB+QAAAIACACQADAEAFgBIAEAAIAEgBIAAAOIgFABIgGAAIgCABQgLAAgFgFgAdKA5IgLAAIgMgBIgIgCIAAgPIAJACIALACIALABQANAAAGgEQAGgEAAgJQABgHgCgDQgCgEgFgCQgGgDgKgBQgMgDgHgEQgGgDgDgGQgDgGAAgJQABgOAJgHQAKgJAUABIAPABIAMACIgBAPQgFgCgHgBQgHgCgHAAQgMAAgFAEQgGADAAAJQAAAGABADQACADAFACQAEACAJABQAMADAIAEQAHADADAHQAEAGAAAKQAAAQgLAIQgKAIgSAAIgDgBgAE2A5IgLAAIgMgBIgIgCIAAgPIAJACIALACIALABQANAAAGgEQAGgEAAgJQABgHgCgDQgCgEgFgCQgGgDgKgBQgMgDgHgEQgGgDgDgGQgDgGAAgJQABgOAJgHQAKgJAUABIAPABIAMACIgBAPQgFgCgHgBQgHgCgHAAQgMAAgFAEQgGADAAAJQAAAGABADQACADAFACQAEACAJABQAMADAIAEQAHADADAHQAEAGAAAKQAAAQgLAIQgKAIgSAAIgDgBgAfRA4IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABZIAGAAIAmgtIAWAAIguAzIAwA5gAZTA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAiYIARAAIAAA8QADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAVeA4IAAhEQAAgIgBgGQgCgFgEgEQgFgDgIAAQgHAAgHACQgGABgFAEQgFAGgEAJIAABIIgRAAIAAhsIARAAIAAAQQAEgHAGgDQAFgEAHgCIANgBQAPgBAIAFQAHAEAEAJQADAHAAALIAABKgAThA4IAAhsIARAAIAABsgAPsA4IAAhsIARAAIAAAUQADgIAGgFQAGgFAGgCIAOgBIACAAIgBAPIgCAAQgHAAgHACQgGACgGAGQgFAEgDAKIAABGgAKhA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAiYIARAAIAAA8QADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAIJA4IAAh7IgpAAIAAgPIBjAAIAAAPIgoAAIAAB7gABRA4IAAhsIARAAIAAAUQADgIAGgFQAGgFAGgCIAOgBIACAAIgBAPIgCAAQgHAAgHACQgGACgGAGQgFAEgDAKIAABGgAAbA4IAAhsIARAAIAABsgAjjA4IgbhYIgBAAIgcBYIgVAAIgehsIASAAIAXBbIABAAIAbhbIAUAAIAcBbIABAAIAYhbIARAAIgfBsgAwLA4IgbhYIgBAAIgbBYIgWAAIgdhsIARAAIAXBbIABAAIAbhbIAVAAIAcBbIABAAIAXhbIARAAIgeBsgA2hA4IAAhsIARAAIAAAUQAEgIAGgFQAFgFAHgCIANgBIACAAIAAAPIgDAAQgHAAgGACQgHACgFAGQgFAEgEAKIAABGgA8SA4IAAhsIARAAIAAAUQAEgIAGgFQAFgFAHgCIANgBIACAAIAAAPIgDAAQgHAAgGACQgHACgFAGQgFAEgEAKIAABGgA+7A4IAAhEQAAgIgCgGQgCgFgEgEQgFgDgIAAQgHAAgHACQgGABgFAEQgFAGgEAJIAABIIgRAAIAAiYIARAAIAAA8QAEgHAGgDQAFgEAHgCIANgBQAPgBAIAFQAHAEAEAJQADAHAAALIAABKgEghUAA4IAAh7IgpAAIAAgPIBkAAIAAAPIgpAAIAAB7gAOwgsIAFgRIAEgSIACgRIARAAQAAAHgCAKQgCAJgEAJIgHARgATihJQgDgDABgGQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAGgCADQgDACgFAAQgGAAgCgCgAAbhJQgCgDAAgGQAAgGACgCQADgCAFAAQAGAAACACQADACAAAGQAAAGgDADQgCACgGAAQgFAAgDgCg");
	this.shape.setTransform(259.975,32.25);

	this.instance_1 = new lib.KING_1_16_26042复制2();
	this.instance_1.setTransform(328.85,42.25,1,1,0,0,0,327.9,42.3);
	this.instance_1.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("Af1BSQAKAAAGgDQAGgCAEgGQAEgGACgJIgrhsIATAAIAhBaIABAAIAghaIARAAIgnBpQgFAOgGAJQgGALgJAEQgKAGgQAAgANGBSQAKAAAGgDQAGgCAEgGQAEgGACgJIgrhsIATAAIAhBaIABAAIAghaIARAAIgnBpQgFAOgGAJQgGALgJAEQgKAGgQAAgAsUBSQAJAAAGgDQAGgCAEgGQAEgGADgJIgshsIATAAIAhBaIACAAIAfhaIASAAIgnBpQgFAOgGAJQgGALgKAEQgJAGgQAAgAaZA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAaggjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgARJA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgARQgjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgALnA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgALugjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgACoA0QgKgIgDgNQgEgNAAgQQAAgOAEgNQADgMAKgIQAKgJASABQAQgBAIAGQAIAGADAJIAAg/IASAAIAACYIgPAAIgDgSQgDAKgJAFQgIAGgPgBQgSAAgKgGgACzghQgGAGgCAKQgCAJAAAKQAAALACAKQACAKAHAFQAGAFAMABQANgBAIgEQAHgGADgIQADgKAAgNQAAgLgDgKQgDgKgHgFQgIgFgNAAQgMAAgHAGgAhIA1QgIgGgEgJIgCASIgPAAIAAiYIARAAIAABAQAEgKAIgGQAIgFAQAAQASgBAKAIQAKAHADANQAEAMAAAQQAAAQgEAMQgDANgKAHQgKAIgSAAQgQABgIgGgAhHgiQgHAFgDAKQgDAJAAAMQAAAMADAKQADAKAHAEQAIAFANABQAMgBAHgFQAGgGACgKQACgJAAgLQAAgKgCgKQgCgJgHgGQgGgGgMAAQgNAAgIAFgAmsA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQAMgEAQAAQAQAAALAEQALAGAGAMQAGANAAAUQAAAVgGANQgGAMgLAGQgLAEgQAAQgQAAgMgEgAmjgjQgHAEgDAJQgDAJAAAPQAAAQADAJQADAJAHAEQAHAEAMAAQAMAAAHgEQAHgEADgJQADgJgBgQQABgPgDgJQgEgJgHgEQgHgEgLAAQgMAAgHAEgAqVA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIQABAIAAAIIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgAqNgjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgAuwA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQAMgEAQAAQAQAAALAEQALAGAGAMQAGANAAAUQAAAVgGANQgGAMgLAGQgLAEgQAAQgQAAgMgEgAungjQgHAEgDAJQgDAJAAAPQAAAQADAJQADAJAHAEQAHAEAMAAQAMAAAHgEQAHgEADgJQADgJgBgQQABgPgDgJQgEgJgHgEQgHgEgLAAQgMAAgHAEgA1EA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIIABAQIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgA08gjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgA37A6QgRABgLgJQgKgJgGgQIgBgJIgBgIIAAgGQAAgQAHgNQAHgMAOgJIALgEIAKgBIACAAQASAAANATIAAgFIARAAIAAA6IABATIADATIgBAAIgQAAQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAgBIgCgNIgDAGIgFAEQgFAFgGABQgGACgHAAgA4IggQgJAHgFALIgCAIIgBAIIAAAFQAAAKAFAJQAEAIAIAGIAHAEIAHAAIAEAAQAfAAAAgmIAAgGQAAgQgFgJQgGgJgLgDIgDAAIgDgBQgNAAgIAGgA61A2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIIABAQIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgA6tgjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgA92A2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIIABAQIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgA9ugjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgEAhxAA5QgFABgDgBQgDgBgBgDQgBgCAAgGQAAgIADgCQADgDAHAAQAHAAADADQADACAAAIQAAAGgCACQgBADgDABIgEABIgDgBgAGKA5QgFABgDgBQgDgBgBgDQgBgCAAgGQAAgIADgCQADgDAHAAQAHAAADADQADACAAAIQAAAGgCACQgBADgDABIgEABIgDgBgAXWA3QgHgCgDgIQgEgHAAgPIAAg8IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQABAFAEABQADADAGgBIAHAAIAFgBIAAAOIgGABIgGAAIgDABQgKAAgGgDgAydA3QgHgCgDgIQgEgHAAgPIAAg8IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQABAFAEABQADADAGgBIAHAAIAFgBIAAAOIgGABIgGAAIgDABQgKAAgGgDgAnwA1QgGgGAAgMIAAiDIARAAIAAB+QAAAIACACQADAEAFgBIAEAAIAEgBIAAAOIgFABIgGAAIgCABQgLAAgFgFgAoqA1QgGgGAAgMIAAiDIARAAIAAB+QAAAIACACQADAEAFgBIAEAAIAEgBIAAAOIgFABIgGAAIgCABQgLAAgFgFgAdKA5IgLAAIgMgBIgIgCIAAgPIAJACIALACIALABQANAAAGgEQAGgEAAgJQABgHgCgDQgCgEgFgCQgGgDgKgBQgMgDgHgEQgGgDgDgGQgDgGAAgJQABgOAJgHQAKgJAUABIAPABIAMACIgBAPQgFgCgHgBQgHgCgHAAQgMAAgFAEQgGADAAAJQAAAGABADQACADAFACQAEACAJABQAMADAIAEQAHADADAHQAEAGAAAKQAAAQgLAIQgKAIgSAAIgDgBgAE2A5IgLAAIgMgBIgIgCIAAgPIAJACIALACIALABQANAAAGgEQAGgEAAgJQABgHgCgDQgCgEgFgCQgGgDgKgBQgMgDgHgEQgGgDgDgGQgDgGAAgJQABgOAJgHQAKgJAUABIAPABIAMACIgBAPQgFgCgHgBQgHgCgHAAQgMAAgFAEQgGADAAAJQAAAGABADQACADAFACQAEACAJABQAMADAIAEQAHADADAHQAEAGAAAKQAAAQgLAIQgKAIgSAAIgDgBgAfRA4IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABZIAGAAIAmgtIAWAAIguAzIAwA5gAZTA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAiYIARAAIAAA8QADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAVeA4IAAhEQAAgIgBgGQgCgFgEgEQgFgDgIAAQgHAAgHACQgGABgFAEQgFAGgEAJIAABIIgRAAIAAhsIARAAIAAAQQAEgHAGgDQAFgEAHgCIANgBQAPgBAIAFQAHAEAEAJQADAHAAALIAABKgAThA4IAAhsIARAAIAABsgAPsA4IAAhsIARAAIAAAUQADgIAGgFQAGgFAGgCIAOgBIACAAIgBAPIgCAAQgHAAgHACQgGACgGAGQgFAEgDAKIAABGgAKhA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAiYIARAAIAAA8QADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAIJA4IAAh7IgpAAIAAgPIBjAAIAAAPIgoAAIAAB7gABRA4IAAhsIARAAIAAAUQADgIAGgFQAGgFAGgCIAOgBIACAAIgBAPIgCAAQgHAAgHACQgGACgGAGQgFAEgDAKIAABGgAAbA4IAAhsIARAAIAABsgAjjA4IgbhYIgBAAIgcBYIgVAAIgehsIASAAIAXBbIABAAIAbhbIAUAAIAcBbIABAAIAYhbIARAAIgfBsgAwLA4IgbhYIgBAAIgbBYIgWAAIgdhsIARAAIAXBbIABAAIAbhbIAVAAIAcBbIABAAIAXhbIARAAIgeBsgA2hA4IAAhsIARAAIAAAUQAEgIAGgFQAFgFAHgCIANgBIACAAIAAAPIgDAAQgHAAgGACQgHACgFAGQgFAEgEAKIAABGgA8SA4IAAhsIARAAIAAAUQAEgIAGgFQAFgFAHgCIANgBIACAAIAAAPIgDAAQgHAAgGACQgHACgFAGQgFAEgEAKIAABGgA+7A4IAAhEQAAgIgCgGQgCgFgEgEQgFgDgIAAQgHAAgHACQgGABgFAEQgFAGgEAJIAABIIgRAAIAAiYIARAAIAAA8QAEgHAGgDQAFgEAHgCIANgBQAPgBAIAFQAHAEAEAJQADAHAAALIAABKgEghUAA4IAAh7IgpAAIAAgPIBkAAIAAAPIgpAAIAAB7gAOwgsIAFgRIAEgSIACgRIARAAQAAAHgCAKQgCAJgEAJIgHARgATihJQgDgDABgGQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAGgCADQgDACgFAAQgGAAgCgCgAAbhJQgCgDAAgGQAAgGACgCQADgCAFAAQAGAAACACQADACAAAGQAAAGgDADQgCACgGAAQgFAAgDgCg");
	this.shape_1.setTransform(259.975,32.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.shape}]}).to({state:[{t:this.instance_1},{t:this.shape_1}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-6,-7.2,515,80);
p.frameBounds = [rect, rect];


(lib.KING_1_4_12929 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		var _this=this;
		_this.stop();
		
		_this.addEventListener("click", fl_MouseClickHandler.bind(this));
		function fl_MouseClickHandler(e)
		{
			console.log(e.target.name);
			_this.gotoAndStop(parseInt(e.target.name.split("_")[1]) + 1);
			_this.parent.gotoPage(e.target.name.split("_")[1]);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4));

	// 图层_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF0000").ss(2,1,1).p("AIFAAQAACFiYBfQiXBejWAAQjVAAiYheQiXhfAAiFQAAiFCXheQCYheDVAAQDWAACXBeQCYBeAACFg");
	this.shape.setTransform(-51.6,58.75);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("rgba(254,134,89,0.8)").ss(4,1,1).p("ADGAAQAABTg6A5Qg5A6hSAAQhSAAg6g6Qg6g5AAhTQAAhSA6g6QA6g5BSAAQBSAAA5A5QA6A6AABSg");
	this.shape_1.setTransform(-250.7456,597.0852,1.0661,1.0661);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFF00").ss(2,1,1).p("AFyDsQCdhhgBiLQABiKidhiQiZhfjZAAQjYAAiaBfQicBiAACKQAACLCcBhQCaBgDYAAQDZAACZhgg");
	this.shape_2.setTransform(-51.6,58.75);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF0000").s().p("AAAFMQjYAAiahgQichhABiLQgBiKCchiQCahfDYAAQDZAACZBfQCdBiAACKQAACLidBhQiZBgjZAAIAAAAgAlnjaQiSBbAAB/QAACACSBbQCVBdDSAAQDTAACVhdQCShbAAiAQAAh/iShbQiVhdjTAAQjSAAiVBdg");
	this.shape_3.setTransform(-51.6,58.75);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FF0000").ss(2,1,1).p("AJKAAQAADHirCNQisCOjzAAQjyAAisiOQiriNAAjHQAAjGCriOQCsiNDyAAQDzAACsCNQCrCOAADGg");
	this.shape_4.setTransform(309.325,270.325);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#FFFF00").ss(2,1,1).p("AGlFcQCviQAAjMQAAjLiviRQiviPj2AAQj1AAivCPQivCRAADLQAADMCvCQQCvCQD1AAQD2AACviQg");
	this.shape_5.setTransform(309.325,270.325);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF0000").s().p("AmkFcQiviQAAjMQAAjLCviQQCviQD1AAQD2AACvCQQCvCQAADLQAADMivCQQivCQj2AAQj1AAiviQgAAAnXQjuAAipCLQioCKAADCQAADDCoCKQCpCLDuAAQDvAACpiLQCoiKAAjDQAAjCioiKQipiLjuAAIgBAAg");
	this.shape_6.setTransform(309.325,270.325);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#FFFF00").ss(1,1,1).p("AL5HKQBshmAAiPQAAiOhshlQhshkiYAAQiYAAhqBkQhtBkAACPQAACPBtBmQBqBkCYAAQCYAABshkgAASgfQCghagCiCQACiCighaQiWhWjVAAQjWAAiWBWQihBaACCCQgCCCChBaQCWBUDWAAQDVAACWhUg");
	this.shape_7.setTransform(-8.9761,315.575);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF0000").s().p("AOAJZIAAgGIACgBIAAAHgADVGeQhshlAAiPQAAiPBshkQBrhkCYAAQCYAABsBkQBrBkAACPQAACPhrBlQhsBkiYAAQiYAAhrhkgALOGQQBlhgAAiGQAAiGhlhfQhmhfiQABQiQgBhlBfQhmBfAACGQAACGBmBgQBlBfCQAAQCQAABmhfgAl3AKQjVAAiXhUQighbACiCQgCiBCghbQCXhVDVAAQDVAACXBVQCgBbgCCBQACCCigBbQiXBUjVAAIAAAAgArZnxQiUBTAAB3QAAB4CUBTQCTBTDPAAQDPAACThTQCUhTAAh4QAAh3iUhTQiThTjPAAQjPAAiTBTg");
	this.shape_8.setTransform(-6.0261,319.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1,p:{x:-250.7456,y:597.0852}},{t:this.shape}]},1).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_1,p:{x:-203.5456,y:597.4852}},{t:this.shape_4}]},1).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_1,p:{x:-156.2456,y:597.2852}}]},1).wait(1));

	// 图层_3
	this.pg_2 = new lib.KING_1_5_85426();
	this.pg_2.name = "pg_2";
	this.pg_2.setTransform(342.05,231.35,3.1227,1.9637,0,0,0,148.6,62.6);
	new cjs.ButtonHelper(this.pg_2, 0, 1, 2, false, new lib.KING_1_5_85426(), 3);

	this.pg_1 = new lib.KING_1_5_85426();
	this.pg_1.name = "pg_1";
	this.pg_1.setTransform(294.5,231.4,3.1227,1.9637,0,0,0,148.6,62.6);
	new cjs.ButtonHelper(this.pg_1, 0, 1, 2, false, new lib.KING_1_5_85426(), 3);

	this.pg_0 = new lib.KING_1_5_85426();
	this.pg_0.name = "pg_0";
	this.pg_0.setTransform(247.4,231.35,3.1227,1.9637,0,0,0,148.6,62.6);
	new cjs.ButtonHelper(this.pg_0, 0, 1, 2, false, new lib.KING_1_5_85426(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.pg_0},{t:this.pg_1},{t:this.pg_2}]}).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-270.3,577.3,134.2,39.6);
p.frameBounds = [rect, new cjs.Rectangle(-273.8,24.6,275.9,595.7), new cjs.Rectangle(-270.3,220.2,640.3,400.5), new cjs.Rectangle(-270.3,258.8,354.2,361.6)];


(lib.KING_1_11_36572复制4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag9AzQgagVAAgeQAAgdAagVQAagWAjAAQAkAAAaAWQAaAVAAAdQAAAegaAVQgaAVgkAAQgjAAgagVg");
	this.shape.setTransform(-83.25,39.3);

	this.instance = new lib.位图11();
	this.instance.setTransform(-91,35,0.3621,0.3621);

	this.instance_1 = new lib.KING_1_52_26957();
	this.instance_1.setTransform(-90,49,0.4194,0.4194);

	this.dia = new lib.KING_1_8_13991复制4();
	this.dia.name = "dia";
	this.dia.setTransform(121.5,95.1,1,1,0,0,0,122.4,20.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.dia},{t:this.instance_1},{t:this.instance},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.KING_1_11_36572复制4, rect = new cjs.Rectangle(-92,32.1,545.1,117), [rect]);


(lib.KING_1_11_36572复制3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag9AzQgagVAAgeQAAgdAagVQAagWAjAAQAkAAAaAWQAaAVAAAdQAAAegaAVQgaAVgkAAQgjAAgagVg");
	this.shape.setTransform(-83.25,39.3);

	this.instance = new lib.位图11();
	this.instance.setTransform(-91,35,0.3621,0.3621);

	this.dia = new lib.KING_1_8_13991复制3();
	this.dia.name = "dia";
	this.dia.setTransform(121.5,95.1,1,1,0,0,0,122.4,20.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.dia},{t:this.instance},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.KING_1_11_36572复制3, rect = new cjs.Rectangle(-92,32.1,634.1,117), [rect]);


(lib.KING_1_11_36572复制2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag9AzQgagVAAgeQAAgdAagVQAagWAjAAQAkAAAaAWQAaAVAAAdQAAAegaAVQgaAVgkAAQgjAAgagVg");
	this.shape.setTransform(-83.25,39.3);

	this.instance = new lib.位图11();
	this.instance.setTransform(-91,35,0.3621,0.3621);

	this.dia = new lib.KING_1_8_13991复制2();
	this.dia.name = "dia";
	this.dia.setTransform(121.5,95.1,1,1,0,0,0,122.4,20.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.dia},{t:this.instance},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.KING_1_11_36572复制2, rect = new cjs.Rectangle(-92,32.1,599.1,117), [rect]);


// stage content:
(lib.index = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		
		var _this = this;
		
		_this.pgId;
		_this.diaAry;
		_this.diaMcAry;
		_this.data;
		_this.curId = 0;
		_this.curPgDia; //存储当前页的所有对话mc
		_this.clickMode = false;
		_this.canClick = false;
		_this.start = false;
		_this.isEnded = false;
		//点击单词声音
		_this.audio;
		
		if (!this.isinit) {
			//console.log("第一次进入")
			this.isinit = true;
			init();
		}
		
		/*function playSoundBySrc(src) {
			audio.currentTime = 0;
			audio.pause();
			audio.src = src;
			console.log(audio.src);
			audio.play();
			_this.isEnded = false;
			_this._onp.setStu(false);
		}*/
		function playSoundBySrc(src) {
		    // 如果新源与当前源相同，不必重新设置
		    if (audio.src !== src) {
		        audio.pause(); // 暂停当前音频
		        audio.src = src; // 设置新音频源
		        audio.currentTime = 0; // 重置播放时间
		        
		        // 确保音频加载完成后再播放
		        audio.oncanplaythrough = function() {
		            audio.play().catch(function(error) {
		                console.error("播放错误:", error);
		            });
		            _this.isEnded = false;
		            _this._onp.setStu(false);
		            audio.oncanplaythrough = null; // 清除事件监听器
		        };
		        
		        // 触发加载
		        audio.load();
		    } else {
		        audio.currentTime = 0; // 如果源相同，重置播放时间并播放
		        audio.play().catch(function(error) {
		            console.error("播放错误:", error);
		        });
		        _this.isEnded = false;
		        _this._onp.setStu(false);
		    }
		}
		
		
		function init() {
			_this.pgId = 0;
			_this.diaAry = [2, 2, 2];
			_this.data = lesdata;
			hideDia();
		
			audio = new Audio();
			audio.addEventListener('play', function () {
				//console.log('被点击的单词开始播放');
			});
			audio.addEventListener('ended', function () {
				//播放结束事件。
				//console.log("播放结束。");
				_this.isEnded = true;
				resetDia();
				if (_this.clickMode) {
					_this._onp.setStu(true);
					//_this.clickMode=false;
					return;
				} //点读模式
				nextFun();
			});
		
		    //隐藏播放和清除按钮
		    _this._onp.visible=false;
		}
		
		_this.gotoPage = function (_pg) {
			if (_this.pgId == _pg && _this.start == true) {
				return;
			}
			//reset();
			_this.isEnded = true;
			_this.start = true;
			_this.pgId = _pg;
			_this.curId = 0;
			if(audio)audio.pause();
			_this.canClick = false;
			_this.clickMode = false;
			_this.gotoAndStop(_this.pgId);
			hideDia();
			updata();
		
			//reset();
			//console.log(_this.diaMcAry);
			//setTimeout(reset,1000);
		}
		
		function hideDia() {
			_this.curPgDia = [];
			//for(var i=1;i<=_this.diaAry[_this.pgId];i++){
			//console.log("##############################");
			//console.log(_this.data);
		    //console.log(_this.data[_this.pgId]);
			console.log(_this.data);
			for (var i = 1; i <= _this.data[_this.pgId].length; i++) {
				_this["dia_" + (parseInt(_this.pgId) + 1) + "_" + i].visible = false;
				_this["dia_" + (parseInt(_this.pgId) + 1) + "_" + i]["dia"].addEventListener("click", ondiamc);
				_this.curPgDia.push(_this["dia_" + (parseInt(_this.pgId) + 1) + "_" + i]);
				console.log("dia_" + (parseInt(_this.pgId) + 1) + "_" + i);
			}
		}
		function resetDia() {
			for (var v of _this.curPgDia) {
				v.dia.gotoAndStop(0);
			}
		}
		function updata() {
			_this.curPgDia[_this.curId].visible = true;
			_this._onp.visible=true;
			resetDia();
			_this.curPgDia[_this.curId].dia.gotoAndStop(1);
			playSoundBySrc(_this.data[_this.pgId][_this.curId].soundPath);
		}
		function nextFun() {
			//
			/*console.log("下一个");
			console.log(_this.curId);
			console.log(_this.curPgDia.length-1);*/
			if (_this.curId < _this.curPgDia.length - 1) {
				_this.curId += 1;
				updata();
			} else {
				_this.canClick = true;
				_this._onp.setStu(true);
				return;
			}
		}
		function prevFun() {
			//
			_this.curId += 1;
		}
		
		
		function ondiamc(e) {
			if (!_this.canClick) {
				return
			}
			_this.clickMode = true;
			for (var item of _this.curPgDia) {
				item.gotoAndStop(0);
			}
			e.currentTarget.gotoAndStop(1);
			const lastChar = e.currentTarget.parent.name.slice(-1);
			_this.curId = Number(lastChar) - 1; // 将 lastChar 转为数字并减去 1
			console.log(_this.curId);
			//点击对话框
			updata();
		}
		
		//子机控制父级
		_this.onPause = function () {
			if (!audio.paused && !audio.ended) {
				audio.pause();
			}
		};
		
		_this.onPlay = function () {
			//if (audio.paused || audio.ended) {
			if (_this.canClick && _this.isEnded) {
				_this.curId = 0;
				_this.clickMode = false;
				_this.canClick = false;
				hideDia();
				updata();
				return;
			} else if (audio.paused) {
				audio.play();
			}
		};
		_this.onClear = function () {
			if (!audio.paused && !audio.ended) {
				audio.pause();
			}
			_this.curId = 0;
			_this.clickMode = false;
			_this.canClick = true;
			_this.isEnded = true;
			hideDia();
			_this._onp.setStu(true);
			//updata();
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(3));

	// 跳转按钮
	this._onp = new lib.KING_1_12_80080();
	this._onp.name = "_onp";
	this._onp.setTransform(943.55,641.9,1,1,0,0,0,37.5,20.4);

	this.gotoBtnMc = new lib.KING_1_4_12929();
	this.gotoBtnMc.name = "gotoBtnMc";
	this.gotoBtnMc.setTransform(658.4,203.55,1,1,0,0,0,153.1,153.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.gotoBtnMc},{t:this._onp}]}).wait(3));

	// 标题
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AgSAbQgGgCgDgGQgBgHAAgMQAAgMABgGQADgGAGgDQAHgCALABQAMgBAGACQAHADACAGQACAGAAAMQAAAMgCAHQgCAGgHACQgGACgMAAQgLAAgHgCg");
	this.shape.setTransform(315.95,57.52);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231F20").s().p("AhGBRQAPAAAJgDQAJgDAGgGQAFgGACgIIhFiwIA1AAIApB+IACAAIAoh+IAzAAIg8CgQgIAZgJAPQgJARgLAIQgMAKgQAEQgQAEgXAAg");
	this.shape_1.setTransform(300.925,54.65);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#231F20").s().p("AgUBbQgYAAgQgMQgRgNgJgYQgDgJgBgLIgCgVIAAgHQAAgYAKgTQAKgSAUgOQAIgFAJgDQAIgBAJAAIAJAAQAQAAALAEQAKAGAHAKIAAABIABABIAAAAIABgFIABgBIAtAAIABAAIAAABIgCA6QAAAmACAYQADAYAFALIAAACIABAFIgBABIgtAAIgDgHIgGgSIgBAAQgHANgKAHQgLAGgPAAgAgdgtQgMAKgGAVIgCAKIAAAGQAAAUAHANQAHANANAFIAKACIAKABQANABAIgFQAJgEAEgKQAEgGACgLQABgJAAgNQAAgSgEgNQgGgMgIgGQgEgDgGgBQgFgBgHAAIgBAAQgQAAgLAKg");
	this.shape_2.setTransform(280.55,51.25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#231F20").s().p("AgHBcQgQAAgOgCIgbgEIAAgoQANAEAPACQAOACAMAAQAPABAHgEQAHgEAAgKQAAgIgDgEQgCgEgIgDQgGgDgOgDQgTgFgKgGQgLgFgEgJQgEgKABgPQgBgZAQgOQARgOAmAAQAOAAAOACQANACAHACIgBAlIgNgDIgQgDIgQgBQgPAAgHAEQgGAEABAJQgBAFADADQACADAIADIATAGQAUAFALAGQAKAGAEAKQAFAKAAAQQgBAfgSANQgTANgfAAIgDAAg");
	this.shape_3.setTransform(262.9,51.2759);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#231F20").s().p("Ag6B0QgQgMgGgUQgGgVABgcQgBgaAGgUQAGgVAQgMQAPgNAdAAQAXAAAMAHQANAHAFAMIAAhfIAvAAIAAD6IgrAAIgEgZQgFAMgMAIQgNAIgXAAQgdAAgPgLgAgXgNQgIAIgDALQgCANAAAQQAAAQACANQADAMAIAHQAIAIAPAAQAQAAAJgHQAJgGAEgNQADgMAAgSQAAgRgEgNQgDgMgJgHQgJgHgQAAQgPAAgIAIg");
	this.shape_4.setTransform(235.2731,47.875);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#231F20").s().p("AAiBbIAAhsQAAgSgGgIQgHgIgQAAQgPAAgJAGQgJAFgFAOIAAB1IgvAAIAAixIAvAAIAAAVQAIgNAPgGQANgGAUAAQAVAAANAHQANAHAGANQAFANAAAUIAAB5g");
	this.shape_5.setTransform(214.7,51.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#231F20").s().p("AgTBbQgZAAgRgMQgQgNgJgYQgDgJgBgLIgCgVIAAgHQAAgYAKgTQAKgSAUgOQAIgFAJgDQAIgBAJAAIAJAAQAPAAAMAEQAKAGAHAKIAAABIABABIAAAAIABgFIAAgBIAuAAIABAAIAAABIgCA6QAAAmACAYQADAYAEALIABACIABAFIgCABIgtAAIgCgHIgHgSIAAAAQgHANgKAHQgLAGgPAAgAgdgtQgMAKgGAVIgCAKIAAAGQAAAUAHANQAHANANAFIAKACIALABQAMABAIgFQAJgEAEgKQAEgGABgLQACgJAAgNQAAgSgEgNQgGgMgIgGQgEgDgGgBQgFgBgHAAIAAAAQgRAAgLAKg");
	this.shape_6.setTransform(193.35,51.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#231F20").s().p("AgGBqQgNgFgFgNQgGgNAAgXIAAhSIgXAAIAAgmIAXAAIAAgqIAvAAIAAAqIAlAAIAAAmIglAAIAABOQAAAPAEAGQAEAFAMAAIAIAAIAHgBIAAAlIgLABIgNAAIgDAAQgTAAgMgFg");
	this.shape_7.setTransform(169.35,49.3271);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#231F20").s().p("AAiBbIAAhsQAAgSgGgIQgHgIgQAAQgPAAgJAGQgJAFgFAOIAAB1IgwAAIAAixIAwAAIAAAVQAIgNAPgGQANgGAUAAQAVAAANAHQANAHAGANQAFANAAAUIAAB5g");
	this.shape_8.setTransform(153.05,51.175);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#231F20").s().p("AgXB/IAAixIAvAAIAACxgAgPhNQgGgBgDgGQgCgFAAgMQAAgLACgFQADgFAGgCQAFgCAKABQALgBAGACQAFACADAFQACAFAAALQAAAMgCAFQgDAGgFABQgGACgLAAQgKAAgFgCg");
	this.shape_9.setTransform(137.775,47.595);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#231F20").s().p("AAABcQgbABgTgIQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQATgJAbABQAcgBATAJQAUAIAKAUQAKAUAAAjQAAAkgKAUQgKAVgUAIQgSAHgaAAIgDAAgAgWgzQgIAGgEAMQgDANAAAUQAAAWADAMQAEAMAIAFQAJAFANAAQAPAAAIgFQAIgFAEgMQADgMAAgWQAAgUgDgNQgEgMgIgGQgJgFgOAAQgOAAgIAFg");
	this.shape_10.setTransform(122.825,51.3251);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#231F20").s().p("AhTByIAAjkIBOAAQAhAAAUAJQATAHAJASQAIARAAAcQAAAdgJARQgJARgUAJQgUAHgfAAIgcAAIAABGgAghADIAVAAQAYABALgIQAKgIAAgWQAAgXgKgJQgLgIgYAAIgVAAg");
	this.shape_11.setTransform(102.6514,48.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgVCZIhoAAIAAkxIBoAAQAhAAAbAGQAbAHAUAQQATAQALAfQALAeAAAuQgBA7gRAhQgTAhgiAOQggAOgqAAIgDAAgAg7BgIAjAAQAbAAASgJQASgIAKgVQAJgVAAglQAAgmgKgVQgJgVgTgIQgSgIgaABIgjAAg");
	this.shape_12.setTransform(48.35,48.5259);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#0D8075").s().p("AirCsQhHhHAAhlQAAhkBHhIQBHhGBkAAQBlAABHBGQBHBIAABkQAABlhHBHQhHBHhlAAQhkAAhHhHg");
	this.shape_13.setTransform(46.725,47.675);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(3));

	// 图层_2
	this.instance = new lib.位图5();
	this.instance.setTransform(336,70,0.49,0.49);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(3));

	// 对话内容
	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AglBYIgSgCIAAgfIASADIATABQAKAAAIgCQAIgCAFgFQAFgFABgKQgBgOgLgFQgKgFgUAAIgNAAIAAgbIANAAQASABAKgFQAKgFAAgNQAAgMgIgFQgHgEgPAAIgRACQgJABgIACIAAgdIARgEQALgBALAAQASAAAOAEQAOAFAIAKQAIALAAARQAAAOgHAJQgHAKgOAEIAAACQAQACAIALQAIALAAAQQAAAagSANQgTAMgjAAIgVgBg");
	this.shape_14.setTransform(349.125,646.925);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#D45D00").ss(2,1,1).p("AC6AAQAAArgRAjQgDAHgEAGQgMAVgTATQg2A2hNAAQhMAAg2g2Qg3g2AAhNQAAgZAHgXQAFgUAKgSQAMgYAVgVQA2g2BMAAQBNAAA2A2QA3A3AABMg");
	this.shape_15.setTransform(349.25,646.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#E67022").s().p("AiCCDQg2g2AAhNQAAgZAFgXQAGgUAJgSQANgYAVgVQA2g2BMAAQBNAAA2A2QA2A3AABMQAAArgRAjIgGANQgMAVgTATQg2A3hNgBQhMABg2g3gAhuhuQgRASgLAUQgIAPgEARQgFAUAAAVQAAAoARAhQALATARASQAuAtBAAAQAaAAAXgHQAigLAcgbQAPgQALgSIAFgLQAOgeAAgjQAAhAgtgvQgugthBAAQhAAAguAtg");
	this.shape_16.setTransform(349.25,646.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FC9D54").s().p("ABIAJQg7g5hSAAQgWAAgUAEQAhgTAqAAQA9AAAsAsQAkAjAHAwQgPgdgZgag");
	this.shape_17.setTransform(353,638.2375);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FA8F3C").s().p("AAJCZIgJABQg+AAgsgtIgEgFIgKgJIgSgTQgRghAAgoQAAgUAFgUQAEgRAIgQQALgUARgRQAugtBAAAQBBAAAuAtQAtAuAABAQAAAkgOAeIgFALQgLASgPAPQgcAcgiALQgOACgPAAIgLgBgABuhKQAZAZAOAeQgGgwglglQgsgsg+AAQgoAAgiATQAVgEAWAAQBSABA7A6g");
	this.shape_18.setTransform(349.25,646.65);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.rf(["#F27E32","#F58929"],[0,1],4.5,-11.5,0,4.5,-11.5,19.6).s().p("AhBgDQgRgSgLgTIARATIAKAJIAFAEQAsAsA+AAIAJAAIALAAQAPAAAOgCQgXAHgaAAQhAAAgugsg");
	this.shape_19.setTransform(344.775,658.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Ag8BYIAAghQAfgYARgQQARgPAHgLQAIgLgBgKQAAgOgIgGQgIgFgNAAIgSACIgVAEIAAgeQAKgDAMgBQAMgCAMAAQAcAAAQAMQAQAMAAAaQAAAKgDAJQgCAJgHAJQgGAKgMALQgMAMgSAOIgLAJIAAACIBLAAIAAAeg");
	this.shape_20.setTransform(301.775,646.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#D45D00").ss(2,1,1).p("AC6AAQAAArgRAjQgDAHgEAGQgMAVgTATQg2A2hNAAQhMAAg2g2Qg3g2AAhNQAAgZAHgXQAFgUAKgSQAMgYAVgVQA2g2BMAAQBNAAA2A2QA3A3AABMg");
	this.shape_21.setTransform(301.9,646.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#E67022").s().p("AiCCDQg2g2AAhNQAAgZAFgXQAGgUAJgSQANgYAVgVQA2g2BMAAQBNAAA2A2QA2A3AABMQAAArgRAjIgGANQgMAVgTATQg2A3hNgBQhMABg2g3gAhuhuQgRASgLAUQgIAPgEARQgFAUAAAVQAAAoARAhQALATARASQAuAtBAAAQAaAAAXgHQAigLAcgbQAPgQALgSIAFgLQAOgeAAgjQAAhAgtgvQgugthBAAQhAAAguAtg");
	this.shape_22.setTransform(301.9,646.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FC9D54").s().p("ABIAJQg7g5hSAAQgWAAgUAEQAhgTAqAAQA9AAAsAsQAkAjAHAwQgPgdgZgag");
	this.shape_23.setTransform(305.65,638.2375);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FA8F3C").s().p("AAJCZIgJABQg+AAgsgtIgEgFIgKgJIgSgTQgRghAAgoQAAgUAFgUQAEgRAIgQQALgUARgRQAugtBAAAQBBAAAuAtQAtAuAABAQAAAkgOAeIgFALQgLASgPAPQgcAcgiALQgOACgPAAIgLgBgABuhKQAZAZAOAeQgGgwglglQgsgsg+AAQgoAAgiATQAVgEAWAAQBSABA7A6g");
	this.shape_24.setTransform(301.9,646.65);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.rf(["#F27E32","#F58929"],[0,1],4.5,-11.5,0,4.5,-11.5,19.6).s().p("AhBgDQgRgSgLgTIARATIAKAJIAFAEQAsAsA+AAIAJAAIALAAQAPAAAOgCQgXAHgaAAQhAAAgugsg");
	this.shape_25.setTransform(297.425,658.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AADBXIAAiMIgqAIIAAgeIAzgLIAcAAIAACtg");
	this.shape_26.setTransform(253.475,646.925);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f().s("#D45D00").ss(2,1,1).p("AC6AAQAAArgRAjQgDAHgEAGQgMAVgTATQg2A2hNAAQhMAAg2g2Qg3g2AAhNQAAgZAHgXQAFgUAKgSQAMgYAVgVQA2g2BMAAQBNAAA2A2QA3A3AABMg");
	this.shape_27.setTransform(254.55,646.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#E67022").s().p("AiCCDQg2g2AAhNQAAgZAFgXQAGgUAJgSQANgYAVgVQA2g2BMAAQBNAAA2A2QA2A3AABMQAAArgRAjIgGANQgMAVgTATQg2A3hNgBQhMABg2g3gAhuhuQgRASgLAUQgIAPgEARQgFAUAAAVQAAAoARAhQALATARASQAuAtBAAAQAaAAAXgHQAigLAcgbQAPgQALgSIAFgLQAOgeAAgjQAAhAgtgvQgugthBAAQhAAAguAtg");
	this.shape_28.setTransform(254.55,646.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FC9D54").s().p("ABIAJQg7g5hSAAQgWAAgUAEQAhgTAqAAQA9AAAsAsQAkAjAHAwQgPgdgZgag");
	this.shape_29.setTransform(258.3,638.2375);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FA8F3C").s().p("AAJCZIgJABQg+AAgsgtIgEgFIgKgJIgSgTQgRghAAgoQAAgUAFgUQAEgRAIgQQALgUARgRQAugtBAAAQBBAAAuAtQAtAuAABAQAAAkgOAeIgFALQgLASgPAPQgcAcgiALQgOACgPAAIgLgBgABuhKQAZAZAOAeQgGgwglglQgsgsg+AAQgoAAgiATQAVgEAWAAQBSABA7A6g");
	this.shape_30.setTransform(254.55,646.65);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.rf(["#F27E32","#F58929"],[0,1],4.5,-11.5,0,4.5,-11.5,19.6).s().p("AhBgDQgRgSgLgTIARATIAKAJIAFAEQAsAsA+AAIAJAAIALAAQAPAAAOgCQgXAHgaAAQhAAAgugsg");
	this.shape_31.setTransform(250.075,658.4);

	this.dia_1_1 = new lib.KING_1_11_36572复制2();
	this.dia_1_1.name = "dia_1_1";
	this.dia_1_1.setTransform(463.35,480.45,1,1,0,0,0,159.4,40.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f().s("#FE8659").ss(8,1,1).p("EhHOAFpIAOwPQAHiYBghvQBph3CUAAMCDJAAAQCUAABpB3QBjBxAGCdQAAACAAABQAAADAAADIgPRFIAAArIgCCzQAACohoB4QhpB4iVAAMiDIAAAQiVAAhph4Qhoh4AAioIAEkZgEBHEAGvIAAArEhHPAF9IABgU");
	this.shape_32.setTransform(639.5,572.35);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("EhBsAQlQiVAAhoh4Qhph3AAiqIAFkYIgBgLIAOwOQAHiZBghvQBph3CVAAMCDIAAAQCUAABpB3QBiBxAHCdIAAAEIAAAFIgPRGIAAAqIAAgqIAAAAIAAAqIgCCyQAACqhoB3QhpB4iVAAgEhHOAFpIABALIgCAJg");
	this.shape_33.setTransform(639.5,572.35);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f().s("#FCE0CE").ss(18,1,1).p("EhHOAFpIAOwPQAHiYBghvQBph3CUAAMCDJAAAQCUAABpB3QBjBxAGCdQAAACAAABQAAADAAADIgPRFIAAArEBHEAGvIAAArIgCCzQAACohoB4QhpB4iVAAMiDIAAAQiVAAhph4Qhoh4AAioIAEkZIAAgLEhHPAF9IABgU");
	this.shape_34.setTransform(639.5,572.35);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("EhBsAQlQiVAAhoh4Qhph3AAiqIAFkYIgBgLIAOwOQAHiZBghvQBph3CVAAMCDIAAAQCUAABpB3QBiBxAHCdIAAAEIAAAFIgPRGIAAAqIgCCyQAACqhoB3QhpB4iVAAgEBHEAHagEBHEAGwIAAAAIAAAqgEhHOAFpIABALIgCAJg");
	this.shape_35.setTransform(639.5,572.35);

	this.dia_2_1 = new lib.KING_1_11_36572复制3();
	this.dia_2_1.name = "dia_2_1";
	this.dia_2_1.setTransform(463.35,480.45,1,1,0,0,0,159.4,40.5);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f().s("#FE8659").ss(8,1,1).p("EhHOAFpIAOwPQAHiYBghvQBph3CUAAMCDJAAAQCUAABpB3QBjBxAGCdQAAACAAABQAAADAAADIgPRFIAAArEBHEAGvIAAArIgCCzQAACohoB4QhpB4iVAAMiDIAAAQiVAAhph4Qhoh4AAioIAEkZIAAgLEhHPAF9IABgU");
	this.shape_36.setTransform(639.5,572.35);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f().s("#FCE0CE").ss(18,1,1).p("EhHOAFpIAOwPQAHiYBghvQBph3CUAAMCDJAAAQCUAABpB3QBjBxAGCdQAAACAAABQAAADAAADIgPRFIAAArIgCCzQAACohoB4QhpB4iVAAMiDIAAAQiVAAhph4Qhoh4AAioIAEkZgEBHEAGvIAAArEhHPAF9IABgU");
	this.shape_37.setTransform(639.5,572.35);

	this.dia_3_1 = new lib.KING_1_11_36572复制4();
	this.dia_3_1.name = "dia_3_1";
	this.dia_3_1.setTransform(463.35,480.45,1,1,0,0,0,159.4,40.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.dia_1_1},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14}]}).to({state:[{t:this.shape_33},{t:this.shape_37},{t:this.shape_35},{t:this.shape_36},{t:this.dia_2_1},{t:this.shape_28},{t:this.shape_30},{t:this.shape_29},{t:this.shape_31},{t:this.shape_27},{t:this.shape_26},{t:this.shape_22},{t:this.shape_24},{t:this.shape_23},{t:this.shape_25},{t:this.shape_21},{t:this.shape_20},{t:this.shape_16},{t:this.shape_18},{t:this.shape_17},{t:this.shape_19},{t:this.shape_15},{t:this.shape_14}]},1).to({state:[{t:this.shape_33},{t:this.shape_37},{t:this.shape_35},{t:this.shape_36},{t:this.dia_3_1},{t:this.shape_28},{t:this.shape_30},{t:this.shape_29},{t:this.shape_31},{t:this.shape_27},{t:this.shape_26},{t:this.shape_22},{t:this.shape_24},{t:this.shape_23},{t:this.shape_25},{t:this.shape_21},{t:this.shape_20},{t:this.shape_16},{t:this.shape_18},{t:this.shape_17},{t:this.shape_19},{t:this.shape_15},{t:this.shape_14}]},1).wait(1));

	// diban
	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("rgba(255,255,255,0.8)").s().p("EhkVAEsIAApXMDIrAAAIAAJXg");
	this.shape_38.setTransform(639.9,690.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_38).wait(3));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = rect = new cjs.Rectangle(637.7,369.5,1284.5,710.9);
p.frameBounds = [rect, rect, rect];
// library properties:
lib.properties = {
	id: 'E637B31863A9224E9952B4D82164A654',
	width: 1280,
	height: 720,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/index_atlas_1.png?1733366347653", id:"index_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['E637B31863A9224E9952B4D82164A654'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;