(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
var rect; // used to reference frame bounds
lib.ssMetadata = [
		{name:"index_atlas_1", frames: [[342,449,335,308],[591,0,232,315],[0,0,589,447],[0,449,340,321]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.位图10 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.位图11 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.位图7 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.位图8 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.元件32复制3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Eg3YAE3Qh0AAgEhxIAAhRQhYgkhIhQQgtgygmhEIAYAKQCEAzBXgBIAAiFQAAh4B4AAMBykAAAQB4AAAAB4IAAGEQgCA5geAcQgeAcg6AAg");
	this.shape.setTransform(390.775,31.075);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.元件32复制3, rect = new cjs.Rectangle(0,0,781.6,62.2), [rect]);


(lib.元件32复制2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Egi3AE3Qh0AAgEhxIAAhRQhYgkhHhQQgtgygnhEIAZAKQCDAzBXgBIAAiFQAAh4B4AAMBJhAAAQB5AAAAB4IAAGEQgDA5gdAcQgeAcg7AAg");
	this.shape.setTransform(259.45,31.075);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.元件32复制2, rect = new cjs.Rectangle(0,0,518.9,62.2), [rect]);


(lib.元件32复制 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgsoAE3Qh0AAgEhxIAAhRQhYgkhHhQQgtgygmhEIAYAKQCEAzBWgBIAAiFQAAh4B4AAMBdDAAAQB4AAAAB4IAAGEQgCA5geAcQgeAcg6AAg");
	this.shape.setTransform(321.925,31.075);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.元件32复制, rect = new cjs.Rectangle(0,0,643.9,62.2), [rect]);


(lib.元件23 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AzmDrIAAnVMAnNAAAIAAHVg");
	this.shape.setTransform(125.475,22.5);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = null;
p.frameBounds = [rect, rect, rect, new cjs.Rectangle(0,-1,251,47)];


(lib.KING_1_5_85426 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.149)").s().p("A3CU6QhkAAhGhGQhHhHAAhjMAAAgiTQAAhjBHhHQBGhGBkAAMAuMAAAQBfACBEBEQBGBHABBjMAAAAiTQgBBjhGBHQhEBEhfACg");
	this.shape.setTransform(-306.5,32.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFAED").s().p("A3CU6QhkAAhGhGQhHhHAAhjMAAAgiTQAAhjBHhHQBGhGBkAAMAuMAAAQBfACBEBEQBGBHABBjMAAAAiTQgBBjhGBHQhEBEhfACg");
	this.shape_1.setTransform(-306.5,32.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},4).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = null;
p.frameBounds = [rect, rect=new cjs.Rectangle(-478,-101,343.1,267.6), rect, rect, rect, rect, rect];


(lib.KING_1_3_43229 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#F99703").ss(0.5,1,1).p("AgMgKIAZAAQAFAAADADQADADAAAEIAAAAQAAAFgDADQgDADgFAAIgZAAQgFAAgDgDQgDgDAAgFIAAAAQAAgEADgDQADgDAFAAg");
	this.shape.setTransform(20.2734,10.9751,0.7179,0.7183,-1.0066);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F99703").s().p("AgMALQgFAAgDgDQgDgDAAgFIAAAAQAAgEADgDQADgDAFAAIAZAAQAFAAADADQADADAAAEIAAAAQAAAFgDADQgDADgFAAg");
	this.shape_1.setTransform(20.2734,10.9751,0.7179,0.7183,-1.0066);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAACsQgKABgIgJQgIgHAAgLIAAkjQAAgLAIgIQAIgHAKAAIAAAAQALAAAIAHQAIAIAAALIAAEjQAAALgIAHQgIAJgLgBg");
	this.shape_2.setTransform(22.5783,22.4041,0.3436,0.269);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAACsQgKABgIgJQgIgHAAgLIAAkjQAAgLAIgIQAIgHAKAAIAAAAQALAAAIAHQAIAIAAALIAAEjQAAALgIAHQgIAJgLgBg");
	this.shape_3.setTransform(18.0283,22.4041,0.3436,0.269);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F99703").s().p("Ai9BQQghAAgXgYQgYgXAAghQAAggAYgYQAXgXAhAAIF7AAQAhAAAYAXQAXAYAAAgQAAAhgXAXQgYAYghAAg");
	this.shape_4.setTransform(20.1509,14.1754,0.3437,0.344,-0.2262);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F99703").s().p("Ag2BgQglAAAAglIgNiYIgBgBIABgBIDQAAIACACIAAAAIgSCYQAAAlgmAAg");
	this.shape_5.setTransform(20.3762,23.3401,0.7179,0.7184);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#F99703").ss(3,1,1).p("AiQCQQg8g7AAhVQAAhUA8g8QA8g8BUAAQBUAAA8A8QAJAIAHAJQADAEAEAFQAmA0AABCQAABVg9A7Qg8A9hUAAQhUAAg8g9g");
	this.shape_6.setTransform(20.475,20.475);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AiQCQQg8g7AAhVQAAhUA8g8QA8g8BUAAQBUAAA8A8IAQARIAHAJQAmA0AABCQAABVg9A7Qg8A9hUAAQhUAAg8g9g");
	this.shape_7.setTransform(20.475,20.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-1.5,-1.5,44,44);
p.frameBounds = [rect, rect];


(lib.KING_1_2_47761 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#F69602").ss(6,1,1).p("AhBhxIAADjABChxIAADj");
	this.shape.setTransform(20.4957,20.4917,0.7181,0.7185);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#F69602").ss(3,1,1).p("AjJDIQhThSAAh2QAAh1BThUQBUhTB1AAQB2AABTBTQBUBUAAB1QAAB2hUBSQhTBVh2AAQh1AAhUhVg");
	this.shape_1.setTransform(20.4598,20.4917,0.7181,0.7185);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AjJDIQhThSAAh2QAAh1BThUQBUhTB1AAQB2AABTBTQBUBUAAB1QAAB2hUBSQhTBVh2AAQh1AAhUhVg");
	this.shape_2.setTransform(20.4598,20.4917,0.7181,0.7185);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-1.5,-1.5,44,44);
p.frameBounds = [rect, rect];


(lib.KING_1_1_84633 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F99703").s().p("Ah9CPQgHgHgBgIIgBj7QABgIAEgHIAEgEQAIgIAMAAQAFAAAFACIDcB/IABACQAFAEACAFQACAFAAAFQAAAGgCAEQgCAFgFAEIgEAFIjZB9QgFACgFAAQgMAAgIgIg");
	this.shape.setTransform(23.281,20.4775,0.684,0.6844);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#F99703").ss(3,1,1).p("AiKCKQg6g5AAhRQAAhQA6g6QA6g5BQAAQBRAAA6A5QA6A6AABQQAABRg6A5Qg6A6hRAAQhQAAg6g6g");
	this.shape_1.setTransform(20.4871,20.4731,1.0426,1.0432);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AiKCKQg5g5gBhRQABhQA5g6QA5g5BRAAQBRAAA5A5QA7A6AABQQAABRg7A5Qg5A6hRAAQhRAAg5g6g");
	this.shape_2.setTransform(20.4871,20.4731,1.0426,1.0432);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-1.5,-1.5,44,44);
p.frameBounds = [rect, rect];


(lib.元件2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A1tTJQi+AAAAi+MAAAggVQAAi+C+AAMArbAAAQC+AAAAC+MAAAAgVQAAC+i+AAg");
	mask.setTransform(296.025,207.525);

	// 图层_1
	this.instance = new lib.位图7();
	this.instance.setTransform(115,63.4,0.6299,0.6299,1.9503);

	this.instance_1 = new lib.位图8();
	this.instance_1.setTransform(127,47);

	this.instance_2 = new lib.位图10();
	this.instance_2.setTransform(125,57);

	var maskedShapeInstanceList = [this.instance,this.instance_1,this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},1).wait(1));

	// 图层_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCCCCC").ss(5,1,1).p("A1tzIMArbAAAQC+AAAAC+MAAAAgVQAAC+i+AAMgrbAAAQi+AAAAi+MAAAggVQAAi+C+AAg");
	this.shape.setTransform(296.0226,207.5487,1.05,1.05);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("A1tTJQi+AAAAi+MAAAggVQAAi+C+AAMArbAAAQC+AAAAC+MAAAAgVQAAC+i+AAg");
	this.shape_1.setTransform(296.0226,207.5487,1.05,1.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(3));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(127.7,76.5,336.8,262.2);
p.frameBounds = [rect, rect, rect];


(lib.KING_1_12_80080 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.isSingleFrame = false;
	// timeline functions:
	this.frame_0 = function() {
		if(this.isSingleFrame) {
			return;
		}
		if(this.totalFrames == 1) {
			this.isSingleFrame = true;
		}
		var _this = this;
		_this.stop();
		// 初始化状态
		function init(showPlay) {
		    _this.b_play.visible = showPlay;  // 根据参数控制播放按钮的显示
		    _this.b_pause.visible = !showPlay; // 根据参数控制暂停按钮的显示
		}
		_this.setStu=function(showPlay){
		    _this.b_play.visible = showPlay;  // 根据参数控制播放按钮的显示
		    _this.b_pause.visible = !showPlay; // 根据参数控制暂停按钮的显示
		}
		
		// 事件监听
		this.b_play.addEventListener("click", () => fl_MouseClickHandler_3(true));
		this.b_pause.addEventListener("click", () => fl_MouseClickHandler_3(false));
		
		function fl_MouseClickHandler_3(isPlay) { 
		    if (isPlay) {
		        _this.parent.onPlay();
		        _this.b_play.visible = false; 
		        _this.b_pause.visible = true;  
		    } else {
		        _this.parent.onPause();
		        _this.b_play.visible = true; 
		        _this.b_pause.visible = false;  
		    }
		    //_this.parent.isPlaying = !_this.parent.isPlaying; // 切换播放状态
		}
		
		// 调用初始化方法，初始状态为播放按钮显示
		init(true);
		
		
		this.b_clear.addEventListener("click", fl_MouseClickHandler_4.bind(this));
		
		function fl_MouseClickHandler_4()
		{
			_this.parent.onClear();
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// 图层_1
	this.b_clear = new lib.KING_1_3_43229();
	this.b_clear.name = "b_clear";
	this.b_clear.setTransform(76.2,20.4,1,1,0,0,0,20.4,20.4);
	new cjs.ButtonHelper(this.b_clear, 0, 1, 1);

	this.b_pause = new lib.KING_1_2_47761();
	this.b_pause.name = "b_pause";
	this.b_pause.setTransform(20.4,20.4,1,1,0,0,0,20.4,20.4);
	new cjs.ButtonHelper(this.b_pause, 0, 1, 1);

	this.b_play = new lib.KING_1_1_84633();
	this.b_play.name = "b_play";
	this.b_play.setTransform(20.4,20.4,1,1,0,0,0,20.4,20.4);
	new cjs.ButtonHelper(this.b_play, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.b_play},{t:this.b_pause},{t:this.b_clear}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.KING_1_12_80080, rect = new cjs.Rectangle(-1.5,-1.5,99.8,44), [rect]);


(lib.KING_1_4_12929 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		var _this=this;
		_this.stop();
		
		_this.addEventListener("click", fl_MouseClickHandler.bind(this));
		function fl_MouseClickHandler(e)
		{
			console.log(e.target.name);
			_this.gotoAndStop(parseInt(e.target.name.split("_")[1]) + 1);
			_this.parent.gotoPage(e.target.name.split("_")[1]);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4));

	// 图层_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#52A3DA").ss(5,1,1).p("A3C05MAuLAAAQBfACBFBEQBGBHAABjMAAAAiTQAABjhGBHQhFBEhfACMguLAAAQhkAAhGhGQhHhHAAhjMAAAgiTQAAhjBHhHQBGhGBkAAg");
	this.shape.setTransform(-207.45,199.05);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#52A3DA").ss(5,1,1).p("A3C05MAuLAAAQBfACBFBEQBHBHAABjMAAAAiTQAABjhHBHQhFBEhfACMguLAAAQhkAAhGhGQhHhHAAhjMAAAgiTQAAhjBHhHQBGhGBkAAg");
	this.shape_1.setTransform(140.05,200.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#52A3DA").ss(5,1,1).p("A3C05MAuMAAAQBfACBEBEQBHBHAABjMAAAAiTQAABjhHBHQhEBEhfACMguMAAAQhkAAhGhGQhHhHAAhjMAAAgiTQAAhjBHhHQBGhGBkAAg");
	this.shape_2.setTransform(487.05,202.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).wait(1));

	// 图层_3
	this.pg_2 = new lib.KING_1_5_85426();
	this.pg_2.name = "pg_2";
	this.pg_2.setTransform(479.55,213.35,1,1,0,0,0,-315.4,44.6);
	new cjs.ButtonHelper(this.pg_2, 0, 1, 2, false, new lib.KING_1_5_85426(), 3);

	this.pg_1 = new lib.KING_1_5_85426();
	this.pg_1.name = "pg_1";
	this.pg_1.setTransform(140.05,200.35,1,1,0,0,0,-306.4,32.6);
	new cjs.ButtonHelper(this.pg_1, 0, 1, 2, false, new lib.KING_1_5_85426(), 3);

	this.pg_0 = new lib.KING_1_5_85426();
	this.pg_0.name = "pg_0";
	this.pg_0.setTransform(-213.55,205.35,1,1,0,0,0,-313.4,36.6);
	new cjs.ButtonHelper(this.pg_0, 0, 1, 2, false, new lib.KING_1_5_85426(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.pg_0},{t:this.pg_1},{t:this.pg_2}]}).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-378.1,66.8,1038.2,268.6);
p.frameBounds = [rect, new cjs.Rectangle(-381.5,62.8,1041.5,272.6), new cjs.Rectangle(-378.1,63.8,1038.2,272.6), new cjs.Rectangle(-378.1,66.3,1039.3,272.6)];


(lib.元件21复制2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));

	// 图层_3
	this.instance = new lib.元件23();
	this.instance.setTransform(399.6,31.15,2.9649,1.3613,0,0,0,125.6,23.4);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.元件23(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AY0BTQAJAAAGgDQAGgDAEgFQAEgHACgIIgrhsIATAAIAhBaIABAAIAghaIASAAIgoBpQgEANgHAKQgFAKgKAFQgKAGgPAAgA4OBTQAKAAAGgDQAGgDAEgFQAEgHADgIIgshsIATAAIAhBaIACAAIAfhaIARAAIgmBpQgGANgFAKQgHAKgJAFQgJAGgRAAgEg17ABgIgMgBIAAgPIANACIANABQATAAAIgJQAJgIAAgTIAAgKQgDAKgIAEQgJAGgPAAQgSAAgKgHQgKgHgDgNQgFgMAAgQQAAgPAFgMQADgNAKgHQAKgIASAAQAKAAAIADQAHADAEAFQAEAFACAGIAAgUIARAAIAABkQABAXgNAMQgNANgcABIgOgCgEg19gAhQgGAGgCAKQgCAJAAAKQAAALACAJQACAJAHAGQAFAGANgBQANAAAIgEQAHgFADgKQADgIgBgNQABgMgDgKQgDgIgHgFQgIgFgNgBQgNABgGAFgEA1xAA0QgKgIgEgMQgDgNAAgRQAAgNADgNQAEgNAKgIQAJgIATAAQAQAAAHAFQAJAHADAJIAAg/IASAAIAACYIgPAAIgDgSQgDAJgJAGQgJAFgOAAQgTAAgJgHgEA18gAhQgGAHgCAJQgCAJAAAKQAAAMACAJQACAKAHAGQAFAFANABQANgBAHgFQAIgFADgJQADgKAAgNQAAgLgDgJQgDgKgIgFQgHgGgNAAQgNABgGAFgEAz6AA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQAMgFAPAAQARAAALAFQALAFAGAMQAFANABAUQgBAWgFANQgGAMgLAFQgLAFgRAAQgPAAgMgFgEA0CgAiQgHADgDAJQgCAKAAAOQAAAQACAKQADAIAHAEQAIAFALAAQAMAAAIgFQAGgEAEgIQACgKAAgQQAAgOgCgKQgEgJgHgDQgHgFgMAAQgLAAgIAFgEAx9AA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQALgFARAAQAPAAAMAFQALAFAGAMQAFANAAAUQAAAWgFANQgGAMgLAFQgMAFgPAAQgRAAgLgFgEAyFgAiQgGADgEAJQgCAKgBAOQABAQACAKQAEAIAGAEQAIAFAMAAQALAAAIgFQAHgEADgIQADgKgBgQQABgOgDgKQgEgJgHgDQgHgFgLAAQgMAAgIAFgEAuOAA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAFgMAMgFQALgFAQAAQANAAAJAEQAIAEAFAHQAEAGADAIIABARIAAAFIgBAGIhKAFQAAAMAEAIQACAHAIAEQAIAEANAAQAJgBAJgCQAJgCAHgCIAAAQIgJADIgMACIgQABQgPAAgMgFgEAuWgAiQgIAEgCAIQgCAIgBALIA6gEQAAgJgBgHQgDgHgFgEQgGgFgLAAQgNAAgGAFgEAq4AA2QgKgFgHgMQgFgNAAgWQAAgUAFgNQAGgMALgFQALgFAQAAQAOAAAJAEQAIAEAEAHQAFAGACAIIACARIgBAFIAAAGIhKAFQgBAMAEAIQADAHAIAEQAHAEAOAAQAIgBAKgCQAJgCAGgCIAAAQIgIADIgNACIgPABQgQAAgMgFgEArAgAiQgHAEgDAIQgCAIAAALIA5gEQABgJgCgHQgCgHgGgEQgFgFgMAAQgNAAgGAFgEAkhAA4QgLgDgIgIQgJgIgFgOQgEgOAAgVQAAgbAIgQQAIgPAPgIQAOgHAVABIAQABIAOADIAAARIgNgEIgRgBQgQAAgKAFQgLAGgFAMQgFAMAAAUQAAAWAFAMQAFAMAKAFQAKAFAQgBIARgBIAQgEIAAAQIgPAEQgJACgKAAQgPAAgMgDgEAhnAA2QgKgFgHgMQgFgNAAgWQAAgUAFgNQAGgMALgFQALgFAQAAQANAAAKAEQAIAEAEAHQAFAGACAIQACAJgBAIIAAAFIgBAGIhJAFQgBAMAEAIQADAHAIAEQAHAEAOAAQAJgBAJgCQAJgCAGgCIAAAQIgIADIgNACIgPABQgQAAgMgFgEAhvgAiQgHAEgDAIQgCAIAAALIA5gEQAAgJgBgHQgCgHgGgEQgFgFgMAAQgNAAgGAFgAXeA7QgRAAgLgJQgKgIgGgRIgBgIIgBgIIAAgHQAAgPAIgNQAGgNAOgJIALgDIAKgBIACAAQATgBAMAUIAAgGIARAAIAAA6IABAUIADASIgBABIgQAAQAAAAgBAAQAAgBAAAAQAAgBAAgBQgBAAAAgBIgCgOIgDAGIgFAFQgEAEgHACQgFACgHAAgAXRgfQgIAGgGAMIgCAIIAAAHIAAAFQAAAKAEAJQAEAIAIAHIAHADIAHABIAFAAQAeAAAAgnIAAgGQABgPgGgJQgFgKgLgDIgEAAIgDgBQgMAAgJAHgAOEA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAFgMALgFQAMgFAPAAQAOAAAJAEQAIAEAFAHQAFAGACAIIABARIgBAFIAAAGIhKAFQAAAMADAIQAEAHAHAEQAIAEANAAQAJgBAKgCQAIgCAHgCIAAAQIgJADIgNACIgPABQgPAAgMgFgAOLgiQgGAEgDAIQgDAIAAALIA6gEQAAgJgCgHQgCgHgFgEQgGgFgMAAQgMAAgHAFgAKyA0QgKgIgEgMQgEgNAAgRQAAgNAEgNQAEgNAKgIQAKgIARAAQAQAAAJAFQAIAHADAJIAAg/IASAAIAACYIgPAAIgDgSQgDAJgJAGQgJAFgPAAQgRAAgKgHgAK9ghQgGAHgCAJQgCAJAAAKQAAAMACAJQACAKAGAGQAHAFAMABQANgBAIgFQAHgFADgJQADgKgBgNQABgLgDgJQgDgKgHgFQgIgGgNAAQgNABgGAFgAFkA4QgMgDgIgIQgJgIgFgOQgEgOAAgVQAAgbAIgQQAIgPAPgIQAPgHAUABIARABIANADIAAARIgNgEIgRgBQgQAAgKAFQgLAGgFAMQgFAMAAAUQAAAWAFAMQAFAMAKAFQAKAFAQgBIARgBIAQgEIAAAQIgPAEQgIACgLAAQgOAAgMgDgAAlA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQAMgFAPAAQARAAALAFQALAFAGAMQAFANAAAUQAAAWgFANQgGAMgLAFQgLAFgRAAQgPAAgMgFgAAtgiQgHADgDAJQgCAKAAAOQAAAQACAKQADAIAHAEQAIAFALAAQAMAAAIgFQAGgEAEgIQACgKAAgQQAAgOgCgKQgEgJgHgDQgHgFgMAAQgLAAgIAFgAiTA0QgLgIgDgMQgEgNAAgRQAAgNAEgNQADgNALgIQAJgIASAAQAQAAAIAFQAJAHADAJIAAg/IARAAIAACYIgPAAIgCgSQgDAJgKAGQgIAFgPAAQgSAAgJgHgAiJghQgFAHgDAJQgBAJAAAKQAAAMABAJQACAKAHAGQAGAFAMABQANgBAIgFQAHgFAEgJQACgKAAgNQAAgLgCgJQgEgKgHgFQgIgGgNAAQgMABgHAFgAj5A7QgQAAgMgJQgKgIgFgRIgCgIIgBgIIAAgHQABgPAGgNQAHgNAOgJIALgDIAKgBIACAAQASgBANAUIAAgGIARAAIAAA6IACAUIACASIgBABIgQAAQAAAAgBAAQAAgBAAAAQAAgBgBgBQAAAAAAgBIgBgOIgEAGIgEAFQgGAEgGACQgFACgIAAgAkGgfQgJAGgEAMIgDAIIgBAHIAAAFQABAKAEAJQAEAIAIAHIAHADIAIABIADAAQAfAAABgnIAAgGQAAgPgGgJQgFgKgMgDIgDAAIgDgBQgNAAgIAHgAmPA0QgKgIgEgMQgDgNAAgRQAAgNADgNQAEgNAKgIQAKgIASAAQAPAAAJAFQAIAHADAJIAAg/IASAAIAACYIgPAAIgDgSQgDAJgJAGQgJAFgOAAQgSAAgKgHgAmEghQgGAHgCAJQgCAJAAAKQAAAMACAJQACAKAGAGQAHAFAMABQANgBAHgFQAIgFADgJQADgKAAgNQAAgLgDgJQgDgKgIgFQgHgGgNAAQgNABgGAFgApDA0QgLgIgDgMQgEgNAAgRQAAgNAEgNQADgNALgIQAJgIASAAQAQAAAIAFQAJAHADAJIAAg/IARAAIAACYIgPAAIgCgSQgDAJgKAGQgIAFgPAAQgSAAgJgHgAo4ghQgGAHgDAJQgBAJAAAKQAAAMABAJQACAKAHAGQAGAFAMABQANgBAIgFQAHgFAEgJQACgKAAgNQAAgLgCgJQgEgKgHgFQgIgGgNAAQgMABgGAFgAslA7QgRAAgLgJQgKgIgGgRIgBgIIgBgIIAAgHQAAgPAHgNQAGgNAPgJIALgDIAJgBIACAAQATgBANAUIAAgGIARAAIAAA6IABAUIADASIgBABIgRAAQAAAAAAAAQAAgBgBAAQAAgBAAgBQAAAAAAgBIgCgOIgEAGIgEAFQgFAEgGACQgGACgHAAgAszgfQgIAGgFAMIgCAIIgBAHIAAAFQAAAKAFAJQAEAIAHAHIAHADIAIABIAEAAQAfAAAAgnIAAgGQAAgPgGgJQgFgKgLgDIgDAAIgDgBQgNAAgJAHgAyjA3QgHgFgEgIQgDgIAAgLIAAhKIASAAIAABEQAAAJABAFQABAHAGACQAEADAIABQAHAAAGgCQAGgBAGgFQAEgFAEgJIAAhJIARAAIAABsIgPAAIgCgQQgEAHgFAFQgGADgGABQgHACgGAAQgOAAgJgEgEglnAA7QgRAAgKgJQgLgIgFgRIgCgIIAAgIIAAgHQAAgPAGgNQAHgNAOgJIALgDIAKgBIACAAQASgBANAUIAAgGIASAAIAAA6IABAUIACASIgBABIgQAAQAAAAAAAAQgBgBAAAAQAAgBAAgBQgBAAAAgBIgBgOIgEAGIgEAFQgFAEgGACQgHACgHAAgEgl0gAfQgJAGgEAMIgCAIIgCAHIAAAFQAAAKAFAJQAEAIAIAHIAHADIAIABIADAAQAgAAAAgnIAAgGQgBgPgFgJQgGgKgLgDIgDAAIgDgBQgNAAgIAHgEgnsAA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAFgMAMgFQALgFAQAAQANAAAJAEQAJAEAEAHQAEAGADAIIABARIAAAFIgBAGIhKAFQAAAMAEAIQACAHAIAEQAIAEANAAQAJgBAJgCQAJgCAHgCIAAAQIgJADIgMACIgQABQgPAAgMgFgEgnkgAiQgIAEgCAIQgCAIgBALIA6gEQAAgJgBgHQgCgHgGgEQgGgFgLAAQgNAAgGAFgEgqdAA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQAMgFAPAAQARAAALAFQALAFAGAMQAFANABAUQgBAWgFANQgGAMgLAFQgLAFgRAAQgPAAgMgFgEgqVgAiQgGADgEAJQgCAKAAAOQAAAQACAKQAEAIAGAEQAHAFAMAAQANAAAGgFQAHgEAEgIQACgKAAgQQAAgOgCgKQgEgJgHgDQgHgFgMAAQgMAAgHAFgEgvYAA3QgHgFgEgIQgDgIAAgLIAAhKIASAAIAABEQAAAJABAFQABAHAGACQAEADAIABQAIAAAFgCQAGgBAGgFQAEgFAEgJIAAhJIARAAIAABsIgPAAIgCgQQgDAHgGAFQgGADgGABQgHACgGAAQgOAAgJgEgEgxRAA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQAMgFAQAAQAQAAALAFQALAFAGAMQAGANgBAUQABAWgGANQgGAMgLAFQgLAFgQAAQgQAAgMgFgEgxIgAiQgIADgCAJQgEAKAAAOQAAAQAEAKQACAIAIAEQAGAFANAAQALAAAHgFQAIgEACgIQADgKAAgQQAAgOgDgKQgDgJgHgDQgHgFgLAAQgNAAgGAFgEg0CAA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQAMgFAPAAQAQAAAMAFQALAFAGAMQAFANABAUQgBAWgFANQgGAMgLAFQgMAFgQAAQgPAAgMgFgEgz6gAiQgGADgEAJQgCAKAAAOQAAAQACAKQAEAIAGAEQAIAFALAAQANAAAGgFQAIgEACgIQAEgKgBgQQABgOgEgKQgDgJgHgDQgHgFgMAAQgLAAgIAFgEA3yAA6QgFABgDgCQgCgBgBgCQgCgDAAgFQAAgJADgCQADgCAHAAQAHAAADACQADACAAAJQAAAFgCADQgBACgCABIgFABIgDAAgAavA6QgFABgCgCQgEgBgBgCQgBgDAAgFQAAgJADgCQADgCAHAAQAHAAADACQADACAAAJQAAAFgBADQgCACgDABIgEABIgDAAgA+pA4QgHgDgDgHQgEgIABgPIAAg7IgRAAIAAgPIARAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA6IABAOQACAEADACQADACAGAAIAHAAIAGgCIAAAPIgHABIgGAAIgDAAQgKAAgGgCgEgj/AA4QgHgDgDgHQgDgIAAgPIAAg7IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA6IABAOQABAEADACQAEACAGAAIAGAAIAGgCIAAAPIgGABIgGAAIgDAAQgKAAgHgCgEgrkAA4QgGgDgEgHQgDgIAAgPIAAg7IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA6IAAAOQACAEAEACQADACAGAAIAGAAIAGgCIAAAPIgGABIgGAAIgDAAQgKAAgHgCgEgtbAA4QgHgDgDgHQgEgIABgPIAAg7IgQAAIAAgPIAQAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA6IABAOQACAEADACQADACAGAAIAHAAIAGgCIAAAPIgHABIgGAAIgDAAQgKAAgGgCgAeFA1QgGgGAAgMIAAiCIARAAIAAB9QAAAJADACQACADAGAAIADAAIAEgCIAAAPIgEABIgHAAIgCAAQgLAAgFgFgAJzA1QgGgGAAgMIAAiCIARAAIAAB9QAAAJACACQADADAFAAIAFAAIADgCIAAAPIgEABIgHAAIgCAAQgKAAgGgFgEAs2AA6IgLgBIgMgBIgIgBIAAgPIAJACIALACIALAAQANAAAFgEQAHgEAAgIQAAgHgBgDQgDgFgEgCQgGgCgKgCQgMgCgHgEQgHgEgCgFQgDgHAAgJQABgNAJgIQAKgIATAAIAQABIAMACIgCAQQgEgCgHgCQgHgBgIAAQgLAAgGAEQgFADAAAJQAAAGABADQACACAFADQAEABAIACQANADAHADQAIAEADAGQADAHABAKQAAAQgLAHQgKAIgTAAIgCAAgAS0A6IgLgBIgLgBIgJgBIAAgPIAKACIALACIAKAAQANAAAGgEQAGgEABgIQAAgHgCgDQgCgFgFgCQgFgCgLgCQgLgCgIgEQgGgEgDgFQgCgHAAgJQAAgNAKgIQAKgIATAAIAQABIALACIgBAQQgFgCgGgCQgIgBgHAAQgMAAgFAEQgGADAAAJQAAAGACADQACACAEADQAEABAJACQAMADAIADQAHAEADAGQAEAHAAAKQAAAQgKAHQgLAIgSAAIgDAAgEAwqAA5IAAhdIgTAAIAAgPIATAAIAAgBQAAgTAFgJQAEgKAIgDQAIgDALAAIAHAAIAGABIAAAOIgGgBIgHgBQgHABgEADQgFACgBAHQgCAHAAAMIAaAAIAAAPIgaAAIAABdgEApyAA5IAAhEQAAgJgBgFQgCgGgEgDQgFgDgIgBQgHAAgGACQgHABgFAFQgFAFgEAKIAABIIgQAAIAAhsIAQAAIAAAQQAEgIAGgDQAFgEAHgBIANgCQAPAAAIAEQAHAFAEAIQAEAIgBALIAABKgEAn2AA5IAAhsIAQAAIAABsgEAnBAA5IAAhEQAAgJgDgFQgBgGgEgDQgFgDgJgBQgGAAgHACQgGABgFAFQgGAFgDAKIAABIIgRAAIAAiYIARAAIAAA8QADgIAHgDQAFgEAGgBIAOgCQAOAAAJAEQAHAFADAIQAEAIAAALIAABKgEAguAA5IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABZIAHAAIAlgtIAWAAIguAzIAwA5gAe5A5IAAhsIARAAIAABsgAcUA5IAAiLIATAAIAACLgAUwA5IAAiLIAoAAQAPAAANADQAMADAKAHQAIAHAFAOQAFAOAAAWQAAAagIAPQgJAQgPAGQgPAGgVAAgAVDApIAVAAQAPAAALgEQALgGAGgLQAGgMABgUQgBgXgGgLQgHgMgLgEQgLgFgOAAIgVAAgAQvA5IAAhEQAAgJgBgFQgBgGgFgDQgFgDgIgBQgHAAgGACQgHABgFAFQgFAFgEAKIAABIIgRAAIAAhsIARAAIAAAQQAEgIAGgDQAGgEAGgBIANgCQAPAAAIAEQAIAFADAIQAEAIgBALIAABKgAMnA5IAAhsIARAAIAAAUQAEgJAGgFQAFgEAGgCIAOgCIACAAIAAAPIgDAAQgHABgHACQgGACgFAFQgFAFgEAJIAABHgAI3A5IAAhsIARAAIAABsgAICA5IAAhEQAAgJgCgFQgCgGgEgDQgFgDgIgBQgHAAgGACQgHABgFAFQgFAFgEAKIAABIIgRAAIAAiYIARAAIAAA8QAEgIAGgDQAFgEAHgBIANgCQAPAAAIAEQAIAFADAIQAEAIgBALIAABKgADYA5IAAhEQAAgJgCgFQgBgGgFgDQgEgDgIgBQgIAAgGACQgGABgGAFQgEAFgEAKIAABIIgRAAIAAhsIARAAIAAAQQAEgIAFgDQAGgEAHgBIANgCQAOAAAJAEQAHAFAEAIQADAIgBALIAABKgAqEA5IAAhEQAAgJgCgFQgBgGgEgDQgFgDgJgBQgGAAgHACQgGABgFAFQgGAFgDAKIAABIIgRAAIAAhsIARAAIAAAQQADgIAHgDQAFgEAGgBIAOgCQAOAAAIAEQAIAFADAIQAEAIAAALIAABKgAuwA5IAAhEQABgMgFgIQgFgGgMgBQgGAAgFACQgHABgDAFQgFAEgCAIIAABLIgRAAIAAhEQAAgMgFgIQgDgGgMgBQgHAAgGACQgFABgFAEQgDAFgEAJIAABKIgQAAIAAhsIAQAAIAAAPQAGgKAIgEQAJgDAJAAQANAAAHAEQAJAGADAIQADgHAFgEQAGgEAHgBQAGgCAHAAQANAAAIAEQAHAFAEAIQAEAIgBALIAABKgAzlA5IAAhEQAAgMgFgIQgFgGgLgBQgHAAgFACQgGABgEAFQgEAEgDAIIAABLIgRAAIAAhEQAAgMgEgIQgEgGgMgBQgHAAgFACQgFABgFAEQgEAFgDAJIAABKIgRAAIAAhsIARAAIAAAPQAFgKAJgEQAIgDAKAAQANAAAHAEQAIAGADAIQADgHAGgEQAFgEAHgBQAGgCAIAAQAMAAAIAEQAIAFADAIQAEAIAAALIAABKgA4+A5IAAhEQAAgMgEgIQgFgGgMgBQgGAAgGACQgFABgEAFQgEAEgDAIIAABLIgSAAIAAhEQABgMgEgIQgFgGgMgBQgGAAgFACQgGABgEAEQgFAFgCAJIAABKIgRAAIAAhsIARAAIAAAPQAFgKAIgEQAIgDAKAAQANAAAIAEQAHAGAEAIQADgHAGgEQAFgEAGgBQAHgCAHAAQAMAAAJAEQAHAFAEAIQAEAIAAALIAABKgA8sA5IAAhEQAAgJgCgFQgBgGgFgDQgEgDgIgBQgIAAgGACQgHABgFAFQgEAFgEAKIAABIIgRAAIAAiYIARAAIAAA8QAEgIAFgDQAGgEAHgBIANgCQAPAAAIAEQAHAFAEAIQADAIgBALIAABKgA/tA5IAAhsIARAAIAABsgEgg4AA5IgbhZIgBAAIgcBZIgVAAIgdhsIARAAIAXBaIABAAIAbhaIAUAAIAdBaIABAAIAXhaIARAAIgeBsgEg3+AA5IAAiLIASAAIAACLgARggrIAFgRIAEgSIACgRIARAAQAAAHgCAJQgDAJgDAKIgIARgEAn2gBJQgCgCAAgGQAAgHACgCQADgCAFAAQAFAAADACQADACAAAHQAAAGgDACQgDACgFAAQgFAAgDgCgAe5hJQgCgCABgGQgBgHACgCQADgCAGAAQAFAAADACQACACAAAHQAAAGgCACQgDACgFAAQgGAAgDgCgAI3hJQgCgCAAgGQAAgHACgCQADgCAFAAQAGAAACACQADACAAAHQAAAGgDACQgCACgGAAQgFAAgDgCgA/shJQgDgCABgGQgBgHADgCQACgCAGAAQAFAAADACQACACAAAHQAAAGgCACQgDACgFAAQgGAAgCgCg");
	this.shape.setTransform(404.8,32.15);

	this.instance_1 = new lib.元件32复制3();
	this.instance_1.setTransform(328.85,42.25,1,1,0,0,0,327.9,42.3);
	this.instance_1.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AY0BTQAJAAAGgDQAGgDAEgFQAEgHACgIIgrhsIATAAIAhBaIABAAIAghaIASAAIgoBpQgEANgHAKQgFAKgKAFQgKAGgPAAgA4OBTQAKAAAGgDQAGgDAEgFQAEgHADgIIgshsIATAAIAhBaIACAAIAfhaIARAAIgmBpQgGANgFAKQgHAKgJAFQgJAGgRAAgEg17ABgIgMgBIAAgPIANACIANABQATAAAIgJQAJgIAAgTIAAgKQgDAKgIAEQgJAGgPAAQgSAAgKgHQgKgHgDgNQgFgMAAgQQAAgPAFgMQADgNAKgHQAKgIASAAQAKAAAIADQAHADAEAFQAEAFACAGIAAgUIARAAIAABkQABAXgNAMQgNANgcABIgOgCgEg19gAhQgGAGgCAKQgCAJAAAKQAAALACAJQACAJAHAGQAFAGANgBQANAAAIgEQAHgFADgKQADgIgBgNQABgMgDgKQgDgIgHgFQgIgFgNgBQgNABgGAFgEA1xAA0QgKgIgEgMQgDgNAAgRQAAgNADgNQAEgNAKgIQAJgIATAAQAQAAAHAFQAJAHADAJIAAg/IASAAIAACYIgPAAIgDgSQgDAJgJAGQgJAFgOAAQgTAAgJgHgEA18gAhQgGAHgCAJQgCAJAAAKQAAAMACAJQACAKAHAGQAFAFANABQANgBAHgFQAIgFADgJQADgKAAgNQAAgLgDgJQgDgKgIgFQgHgGgNAAQgNABgGAFgEAz6AA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQAMgFAPAAQARAAALAFQALAFAGAMQAFANABAUQgBAWgFANQgGAMgLAFQgLAFgRAAQgPAAgMgFgEA0CgAiQgHADgDAJQgCAKAAAOQAAAQACAKQADAIAHAEQAIAFALAAQAMAAAIgFQAGgEAEgIQACgKAAgQQAAgOgCgKQgEgJgHgDQgHgFgMAAQgLAAgIAFgEAx9AA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQALgFARAAQAPAAAMAFQALAFAGAMQAFANAAAUQAAAWgFANQgGAMgLAFQgMAFgPAAQgRAAgLgFgEAyFgAiQgGADgEAJQgCAKgBAOQABAQACAKQAEAIAGAEQAIAFAMAAQALAAAIgFQAHgEADgIQADgKgBgQQABgOgDgKQgEgJgHgDQgHgFgLAAQgMAAgIAFgEAuOAA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAFgMAMgFQALgFAQAAQANAAAJAEQAIAEAFAHQAEAGADAIIABARIAAAFIgBAGIhKAFQAAAMAEAIQACAHAIAEQAIAEANAAQAJgBAJgCQAJgCAHgCIAAAQIgJADIgMACIgQABQgPAAgMgFgEAuWgAiQgIAEgCAIQgCAIgBALIA6gEQAAgJgBgHQgDgHgFgEQgGgFgLAAQgNAAgGAFgEAq4AA2QgKgFgHgMQgFgNAAgWQAAgUAFgNQAGgMALgFQALgFAQAAQAOAAAJAEQAIAEAEAHQAFAGACAIIACARIgBAFIAAAGIhKAFQgBAMAEAIQADAHAIAEQAHAEAOAAQAIgBAKgCQAJgCAGgCIAAAQIgIADIgNACIgPABQgQAAgMgFgEArAgAiQgHAEgDAIQgCAIAAALIA5gEQABgJgCgHQgCgHgGgEQgFgFgMAAQgNAAgGAFgEAkhAA4QgLgDgIgIQgJgIgFgOQgEgOAAgVQAAgbAIgQQAIgPAPgIQAOgHAVABIAQABIAOADIAAARIgNgEIgRgBQgQAAgKAFQgLAGgFAMQgFAMAAAUQAAAWAFAMQAFAMAKAFQAKAFAQgBIARgBIAQgEIAAAQIgPAEQgJACgKAAQgPAAgMgDgEAhnAA2QgKgFgHgMQgFgNAAgWQAAgUAFgNQAGgMALgFQALgFAQAAQANAAAKAEQAIAEAEAHQAFAGACAIQACAJgBAIIAAAFIgBAGIhJAFQgBAMAEAIQADAHAIAEQAHAEAOAAQAJgBAJgCQAJgCAGgCIAAAQIgIADIgNACIgPABQgQAAgMgFgEAhvgAiQgHAEgDAIQgCAIAAALIA5gEQAAgJgBgHQgCgHgGgEQgFgFgMAAQgNAAgGAFgAXeA7QgRAAgLgJQgKgIgGgRIgBgIIgBgIIAAgHQAAgPAIgNQAGgNAOgJIALgDIAKgBIACAAQATgBAMAUIAAgGIARAAIAAA6IABAUIADASIgBABIgQAAQAAAAgBAAQAAgBAAAAQAAgBAAgBQgBAAAAgBIgCgOIgDAGIgFAFQgEAEgHACQgFACgHAAgAXRgfQgIAGgGAMIgCAIIAAAHIAAAFQAAAKAEAJQAEAIAIAHIAHADIAHABIAFAAQAeAAAAgnIAAgGQABgPgGgJQgFgKgLgDIgEAAIgDgBQgMAAgJAHgAOEA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAFgMALgFQAMgFAPAAQAOAAAJAEQAIAEAFAHQAFAGACAIIABARIgBAFIAAAGIhKAFQAAAMADAIQAEAHAHAEQAIAEANAAQAJgBAKgCQAIgCAHgCIAAAQIgJADIgNACIgPABQgPAAgMgFgAOLgiQgGAEgDAIQgDAIAAALIA6gEQAAgJgCgHQgCgHgFgEQgGgFgMAAQgMAAgHAFgAKyA0QgKgIgEgMQgEgNAAgRQAAgNAEgNQAEgNAKgIQAKgIARAAQAQAAAJAFQAIAHADAJIAAg/IASAAIAACYIgPAAIgDgSQgDAJgJAGQgJAFgPAAQgRAAgKgHgAK9ghQgGAHgCAJQgCAJAAAKQAAAMACAJQACAKAGAGQAHAFAMABQANgBAIgFQAHgFADgJQADgKgBgNQABgLgDgJQgDgKgHgFQgIgGgNAAQgNABgGAFgAFkA4QgMgDgIgIQgJgIgFgOQgEgOAAgVQAAgbAIgQQAIgPAPgIQAPgHAUABIARABIANADIAAARIgNgEIgRgBQgQAAgKAFQgLAGgFAMQgFAMAAAUQAAAWAFAMQAFAMAKAFQAKAFAQgBIARgBIAQgEIAAAQIgPAEQgIACgLAAQgOAAgMgDgAAlA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQAMgFAPAAQARAAALAFQALAFAGAMQAFANAAAUQAAAWgFANQgGAMgLAFQgLAFgRAAQgPAAgMgFgAAtgiQgHADgDAJQgCAKAAAOQAAAQACAKQADAIAHAEQAIAFALAAQAMAAAIgFQAGgEAEgIQACgKAAgQQAAgOgCgKQgEgJgHgDQgHgFgMAAQgLAAgIAFgAiTA0QgLgIgDgMQgEgNAAgRQAAgNAEgNQADgNALgIQAJgIASAAQAQAAAIAFQAJAHADAJIAAg/IARAAIAACYIgPAAIgCgSQgDAJgKAGQgIAFgPAAQgSAAgJgHgAiJghQgFAHgDAJQgBAJAAAKQAAAMABAJQACAKAHAGQAGAFAMABQANgBAIgFQAHgFAEgJQACgKAAgNQAAgLgCgJQgEgKgHgFQgIgGgNAAQgMABgHAFgAj5A7QgQAAgMgJQgKgIgFgRIgCgIIgBgIIAAgHQABgPAGgNQAHgNAOgJIALgDIAKgBIACAAQASgBANAUIAAgGIARAAIAAA6IACAUIACASIgBABIgQAAQAAAAgBAAQAAgBAAAAQAAgBgBgBQAAAAAAgBIgBgOIgEAGIgEAFQgGAEgGACQgFACgIAAgAkGgfQgJAGgEAMIgDAIIgBAHIAAAFQABAKAEAJQAEAIAIAHIAHADIAIABIADAAQAfAAABgnIAAgGQAAgPgGgJQgFgKgMgDIgDAAIgDgBQgNAAgIAHgAmPA0QgKgIgEgMQgDgNAAgRQAAgNADgNQAEgNAKgIQAKgIASAAQAPAAAJAFQAIAHADAJIAAg/IASAAIAACYIgPAAIgDgSQgDAJgJAGQgJAFgOAAQgSAAgKgHgAmEghQgGAHgCAJQgCAJAAAKQAAAMACAJQACAKAGAGQAHAFAMABQANgBAHgFQAIgFADgJQADgKAAgNQAAgLgDgJQgDgKgIgFQgHgGgNAAQgNABgGAFgApDA0QgLgIgDgMQgEgNAAgRQAAgNAEgNQADgNALgIQAJgIASAAQAQAAAIAFQAJAHADAJIAAg/IARAAIAACYIgPAAIgCgSQgDAJgKAGQgIAFgPAAQgSAAgJgHgAo4ghQgGAHgDAJQgBAJAAAKQAAAMABAJQACAKAHAGQAGAFAMABQANgBAIgFQAHgFAEgJQACgKAAgNQAAgLgCgJQgEgKgHgFQgIgGgNAAQgMABgGAFgAslA7QgRAAgLgJQgKgIgGgRIgBgIIgBgIIAAgHQAAgPAHgNQAGgNAPgJIALgDIAJgBIACAAQATgBANAUIAAgGIARAAIAAA6IABAUIADASIgBABIgRAAQAAAAAAAAQAAgBgBAAQAAgBAAgBQAAAAAAgBIgCgOIgEAGIgEAFQgFAEgGACQgGACgHAAgAszgfQgIAGgFAMIgCAIIgBAHIAAAFQAAAKAFAJQAEAIAHAHIAHADIAIABIAEAAQAfAAAAgnIAAgGQAAgPgGgJQgFgKgLgDIgDAAIgDgBQgNAAgJAHgAyjA3QgHgFgEgIQgDgIAAgLIAAhKIASAAIAABEQAAAJABAFQABAHAGACQAEADAIABQAHAAAGgCQAGgBAGgFQAEgFAEgJIAAhJIARAAIAABsIgPAAIgCgQQgEAHgFAFQgGADgGABQgHACgGAAQgOAAgJgEgEglnAA7QgRAAgKgJQgLgIgFgRIgCgIIAAgIIAAgHQAAgPAGgNQAHgNAOgJIALgDIAKgBIACAAQASgBANAUIAAgGIASAAIAAA6IABAUIACASIgBABIgQAAQAAAAAAAAQgBgBAAAAQAAgBAAgBQgBAAAAgBIgBgOIgEAGIgEAFQgFAEgGACQgHACgHAAgEgl0gAfQgJAGgEAMIgCAIIgCAHIAAAFQAAAKAFAJQAEAIAIAHIAHADIAIABIADAAQAgAAAAgnIAAgGQgBgPgFgJQgGgKgLgDIgDAAIgDgBQgNAAgIAHgEgnsAA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAFgMAMgFQALgFAQAAQANAAAJAEQAJAEAEAHQAEAGADAIIABARIAAAFIgBAGIhKAFQAAAMAEAIQACAHAIAEQAIAEANAAQAJgBAJgCQAJgCAHgCIAAAQIgJADIgMACIgQABQgPAAgMgFgEgnkgAiQgIAEgCAIQgCAIgBALIA6gEQAAgJgBgHQgCgHgGgEQgGgFgLAAQgNAAgGAFgEgqdAA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQAMgFAPAAQARAAALAFQALAFAGAMQAFANABAUQgBAWgFANQgGAMgLAFQgLAFgRAAQgPAAgMgFgEgqVgAiQgGADgEAJQgCAKAAAOQAAAQACAKQAEAIAGAEQAHAFAMAAQANAAAGgFQAHgEAEgIQACgKAAgQQAAgOgCgKQgEgJgHgDQgHgFgMAAQgMAAgHAFgEgvYAA3QgHgFgEgIQgDgIAAgLIAAhKIASAAIAABEQAAAJABAFQABAHAGACQAEADAIABQAIAAAFgCQAGgBAGgFQAEgFAEgJIAAhJIARAAIAABsIgPAAIgCgQQgDAHgGAFQgGADgGABQgHACgGAAQgOAAgJgEgEgxRAA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQAMgFAQAAQAQAAALAFQALAFAGAMQAGANgBAUQABAWgGANQgGAMgLAFQgLAFgQAAQgQAAgMgFgEgxIgAiQgIADgCAJQgEAKAAAOQAAAQAEAKQACAIAIAEQAGAFANAAQALAAAHgFQAIgEACgIQADgKAAgQQAAgOgDgKQgDgJgHgDQgHgFgLAAQgNAAgGAFgEg0CAA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQAMgFAPAAQAQAAAMAFQALAFAGAMQAFANABAUQgBAWgFANQgGAMgLAFQgMAFgQAAQgPAAgMgFgEgz6gAiQgGADgEAJQgCAKAAAOQAAAQACAKQAEAIAGAEQAIAFALAAQANAAAGgFQAIgEACgIQAEgKgBgQQABgOgEgKQgDgJgHgDQgHgFgMAAQgLAAgIAFgEA3yAA6QgFABgDgCQgCgBgBgCQgCgDAAgFQAAgJADgCQADgCAHAAQAHAAADACQADACAAAJQAAAFgCADQgBACgCABIgFABIgDAAgAavA6QgFABgCgCQgEgBgBgCQgBgDAAgFQAAgJADgCQADgCAHAAQAHAAADACQADACAAAJQAAAFgBADQgCACgDABIgEABIgDAAgA+pA4QgHgDgDgHQgEgIABgPIAAg7IgRAAIAAgPIARAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA6IABAOQACAEADACQADACAGAAIAHAAIAGgCIAAAPIgHABIgGAAIgDAAQgKAAgGgCgEgj/AA4QgHgDgDgHQgDgIAAgPIAAg7IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA6IABAOQABAEADACQAEACAGAAIAGAAIAGgCIAAAPIgGABIgGAAIgDAAQgKAAgHgCgEgrkAA4QgGgDgEgHQgDgIAAgPIAAg7IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA6IAAAOQACAEAEACQADACAGAAIAGAAIAGgCIAAAPIgGABIgGAAIgDAAQgKAAgHgCgEgtbAA4QgHgDgDgHQgEgIABgPIAAg7IgQAAIAAgPIAQAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA6IABAOQACAEADACQADACAGAAIAHAAIAGgCIAAAPIgHABIgGAAIgDAAQgKAAgGgCgAeFA1QgGgGAAgMIAAiCIARAAIAAB9QAAAJADACQACADAGAAIADAAIAEgCIAAAPIgEABIgHAAIgCAAQgLAAgFgFgAJzA1QgGgGAAgMIAAiCIARAAIAAB9QAAAJACACQADADAFAAIAFAAIADgCIAAAPIgEABIgHAAIgCAAQgKAAgGgFgEAs2AA6IgLgBIgMgBIgIgBIAAgPIAJACIALACIALAAQANAAAFgEQAHgEAAgIQAAgHgBgDQgDgFgEgCQgGgCgKgCQgMgCgHgEQgHgEgCgFQgDgHAAgJQABgNAJgIQAKgIATAAIAQABIAMACIgCAQQgEgCgHgCQgHgBgIAAQgLAAgGAEQgFADAAAJQAAAGABADQACACAFADQAEABAIACQANADAHADQAIAEADAGQADAHABAKQAAAQgLAHQgKAIgTAAIgCAAgAS0A6IgLgBIgLgBIgJgBIAAgPIAKACIALACIAKAAQANAAAGgEQAGgEABgIQAAgHgCgDQgCgFgFgCQgFgCgLgCQgLgCgIgEQgGgEgDgFQgCgHAAgJQAAgNAKgIQAKgIATAAIAQABIALACIgBAQQgFgCgGgCQgIgBgHAAQgMAAgFAEQgGADAAAJQAAAGACADQACACAEADQAEABAJACQAMADAIADQAHAEADAGQAEAHAAAKQAAAQgKAHQgLAIgSAAIgDAAgEAwqAA5IAAhdIgTAAIAAgPIATAAIAAgBQAAgTAFgJQAEgKAIgDQAIgDALAAIAHAAIAGABIAAAOIgGgBIgHgBQgHABgEADQgFACgBAHQgCAHAAAMIAaAAIAAAPIgaAAIAABdgEApyAA5IAAhEQAAgJgBgFQgCgGgEgDQgFgDgIgBQgHAAgGACQgHABgFAFQgFAFgEAKIAABIIgQAAIAAhsIAQAAIAAAQQAEgIAGgDQAFgEAHgBIANgCQAPAAAIAEQAHAFAEAIQAEAIgBALIAABKgEAn2AA5IAAhsIAQAAIAABsgEAnBAA5IAAhEQAAgJgDgFQgBgGgEgDQgFgDgJgBQgGAAgHACQgGABgFAFQgGAFgDAKIAABIIgRAAIAAiYIARAAIAAA8QADgIAHgDQAFgEAGgBIAOgCQAOAAAJAEQAHAFADAIQAEAIAAALIAABKgEAguAA5IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABZIAHAAIAlgtIAWAAIguAzIAwA5gAe5A5IAAhsIARAAIAABsgAcUA5IAAiLIATAAIAACLgAUwA5IAAiLIAoAAQAPAAANADQAMADAKAHQAIAHAFAOQAFAOAAAWQAAAagIAPQgJAQgPAGQgPAGgVAAgAVDApIAVAAQAPAAALgEQALgGAGgLQAGgMABgUQgBgXgGgLQgHgMgLgEQgLgFgOAAIgVAAgAQvA5IAAhEQAAgJgBgFQgBgGgFgDQgFgDgIgBQgHAAgGACQgHABgFAFQgFAFgEAKIAABIIgRAAIAAhsIARAAIAAAQQAEgIAGgDQAGgEAGgBIANgCQAPAAAIAEQAIAFADAIQAEAIgBALIAABKgAMnA5IAAhsIARAAIAAAUQAEgJAGgFQAFgEAGgCIAOgCIACAAIAAAPIgDAAQgHABgHACQgGACgFAFQgFAFgEAJIAABHgAI3A5IAAhsIARAAIAABsgAICA5IAAhEQAAgJgCgFQgCgGgEgDQgFgDgIgBQgHAAgGACQgHABgFAFQgFAFgEAKIAABIIgRAAIAAiYIARAAIAAA8QAEgIAGgDQAFgEAHgBIANgCQAPAAAIAEQAIAFADAIQAEAIgBALIAABKgADYA5IAAhEQAAgJgCgFQgBgGgFgDQgEgDgIgBQgIAAgGACQgGABgGAFQgEAFgEAKIAABIIgRAAIAAhsIARAAIAAAQQAEgIAFgDQAGgEAHgBIANgCQAOAAAJAEQAHAFAEAIQADAIgBALIAABKgAqEA5IAAhEQAAgJgCgFQgBgGgEgDQgFgDgJgBQgGAAgHACQgGABgFAFQgGAFgDAKIAABIIgRAAIAAhsIARAAIAAAQQADgIAHgDQAFgEAGgBIAOgCQAOAAAIAEQAIAFADAIQAEAIAAALIAABKgAuwA5IAAhEQABgMgFgIQgFgGgMgBQgGAAgFACQgHABgDAFQgFAEgCAIIAABLIgRAAIAAhEQAAgMgFgIQgDgGgMgBQgHAAgGACQgFABgFAEQgDAFgEAJIAABKIgQAAIAAhsIAQAAIAAAPQAGgKAIgEQAJgDAJAAQANAAAHAEQAJAGADAIQADgHAFgEQAGgEAHgBQAGgCAHAAQANAAAIAEQAHAFAEAIQAEAIgBALIAABKgAzlA5IAAhEQAAgMgFgIQgFgGgLgBQgHAAgFACQgGABgEAFQgEAEgDAIIAABLIgRAAIAAhEQAAgMgEgIQgEgGgMgBQgHAAgFACQgFABgFAEQgEAFgDAJIAABKIgRAAIAAhsIARAAIAAAPQAFgKAJgEQAIgDAKAAQANAAAHAEQAIAGADAIQADgHAGgEQAFgEAHgBQAGgCAIAAQAMAAAIAEQAIAFADAIQAEAIAAALIAABKgA4+A5IAAhEQAAgMgEgIQgFgGgMgBQgGAAgGACQgFABgEAFQgEAEgDAIIAABLIgSAAIAAhEQABgMgEgIQgFgGgMgBQgGAAgFACQgGABgEAEQgFAFgCAJIAABKIgRAAIAAhsIARAAIAAAPQAFgKAIgEQAIgDAKAAQANAAAIAEQAHAGAEAIQADgHAGgEQAFgEAGgBQAHgCAHAAQAMAAAJAEQAHAFAEAIQAEAIAAALIAABKgA8sA5IAAhEQAAgJgCgFQgBgGgFgDQgEgDgIgBQgIAAgGACQgHABgFAFQgEAFgEAKIAABIIgRAAIAAiYIARAAIAAA8QAEgIAFgDQAGgEAHgBIANgCQAPAAAIAEQAHAFAEAIQADAIgBALIAABKgA/tA5IAAhsIARAAIAABsgEgg4AA5IgbhZIgBAAIgcBZIgVAAIgdhsIARAAIAXBaIABAAIAbhaIAUAAIAdBaIABAAIAXhaIARAAIgeBsgEg3+AA5IAAiLIASAAIAACLgARggrIAFgRIAEgSIACgRIARAAQAAAHgCAJQgDAJgDAKIgIARgEAn2gBJQgCgCAAgGQAAgHACgCQADgCAFAAQAFAAADACQADACAAAHQAAAGgDACQgDACgFAAQgFAAgDgCgAe5hJQgCgCABgGQgBgHACgCQADgCAGAAQAFAAADACQACACAAAHQAAAGgCACQgDACgFAAQgGAAgDgCgAI3hJQgCgCAAgGQAAgHACgCQADgCAFAAQAGAAACACQADACAAAHQAAAGgDACQgCACgGAAQgFAAgDgCgA/shJQgDgCABgGQgBgHADgCQACgCAGAAQAFAAADACQACACAAAHQAAAGgCACQgDACgFAAQgGAAgCgCg");
	this.shape_1.setTransform(404.8,32.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.shape}]}).to({state:[{t:this.instance_1},{t:this.shape_1}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-6,-7,799,80);
p.frameBounds = [rect, rect];


(lib.元件21复制 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));

	// 图层_3
	this.instance = new lib.元件23();
	this.instance.setTransform(272.2,31.15,1.9508,1.3613,0,0,0,125.6,23.4);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.元件23(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EAhOABgIgMgBIAAgQIANACIAOABQASAAAJgIQAJgJAAgSIAAgLQgDAKgJAFQgIAGgPAAQgSgBgKgGQgLgIgDgMQgEgMAAgRQAAgOAEgNQADgNALgHQAKgIASAAQAKAAAHAEQAIADADAEQAFAGACAGIAAgVIARAAIAABlQAAAXgNAMQgMANgcAAIgPgBgEAhMgAhQgFAFgDAKQgCAJAAAKQAAAMACAJQACAJAHAFQAGAGAMAAQANAAAIgFQAHgEAEgKQACgJAAgNQAAgLgCgKQgEgJgHgFQgIgFgNAAQgMAAgHAGgAL7BSQAJAAAGgDQAGgDAEgFQAEgGACgIIgrhtIATAAIAhBaIABAAIAghaIASAAIgnBpQgFAOgHAKQgFAKgKAEQgKAGgPAAgAcPAzQgKgHgEgMQgDgOAAgQQAAgOADgNQAEgMAKgJQAKgHASgBQAPABAJAFQAIAGADAKIAAhAIASAAIAACZIgPAAIgDgSQgDAIgJAGQgJAFgOABQgSAAgKgIgAcaghQgGAGgCAJQgCAKAAAKQAAAMACAJQACAKAGAFQAHAFAMABQANgBAHgEQAIgFADgKQADgJAAgNQAAgMgDgJQgDgJgIgGQgHgFgNAAQgNAAgGAGgAaqA7QgRAAgLgJQgKgIgGgSIgBgIIgBgIIAAgGQAAgQAHgNQAGgMAPgJIALgEIAKgBIABAAQATAAANATIAAgFIARAAIAAA5IABAVIADASIgBABIgQAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgBAAgBIgCgNIgEAFIgEAGQgFADgGADQgGACgHAAgAacgfQgIAFgFANIgCAIIgBAHIAAAEQAAALAFAIQADAJAIAHIAIACIAHABIAEAAQAfAAAAgmIAAgGQAAgPgFgKQgGgKgLgCIgDAAIgEgBQgMAAgJAHgAYkA1QgLgEgGgNQgGgMAAgWQAAgVAGgMQAGgNALgEQAKgGARAAQANAAAJAFQAIADAFAIQAEAGACAIIACAQIgBAGIAAAGIhKAEQAAAMAEAIQACAHAJAFQAHADANAAQAJAAAJgCQAKgCAGgDIAAAQIgIADIgOADIgOABQgQAAgMgGgAYsgjQgIAEgCAJQgCAHgBAMIA6gFQAAgIgCgHQgCgIgFgEQgGgEgLAAQgNAAgGAEgAUvA1QgLgEgGgNQgGgMAAgWQAAgVAGgMQAGgNAKgEQALgGAQAAQAOAAAJAFQAJADAEAIQAEAGACAIIACAQIgBAGIAAAGIhKAEQAAAMADAIQAEAHAIAFQAHADANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgOADIgOABQgRAAgLgGgAU2gjQgGAEgDAJQgDAHAAAMIA6gFQAAgIgCgHQgCgIgFgEQgGgEgMAAQgMAAgHAEgAKlA7QgQAAgMgJQgKgIgGgSIgBgIIgBgIIAAgGQAAgQAHgNQAHgMAOgJIALgEIAKgBIACAAQATAAAMATIAAgFIARAAIAAA5IABAVIADASIgBABIgQAAQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAgBAAgBIgCgNIgDAFIgFAGQgEADgHADQgGACgGAAgAKYgfQgIAFgGANIgCAIIgBAHIAAAEQABALAEAIQAEAJAIAHIAHACIAHABIAFAAQAeAAAAgmIAAgGQABgPgGgKQgFgKgLgCIgEAAIgDgBQgMAAgJAHgABLA1QgLgEgGgNQgGgMAAgWQAAgVAGgMQAFgNALgEQALgGAQAAQAOAAAJAFQAIADAFAIQAEAGACAIIACAQIgBAGIAAAGIhKAEQAAAMADAIQADAHAIAFQAIADANAAQAJAAAKgCQAIgCAHgDIAAAQIgIADIgOADIgPABQgPAAgMgGgABSgjQgGAEgDAJQgDAHAAAMIA6gFQAAgIgCgHQgCgIgFgEQgGgEgMAAQgMAAgHAEgAiGAzQgKgHgDgMQgFgOAAgQQAAgOAFgNQADgMAKgJQAJgHASgBQAQABAJAFQAIAGADAKIAAhAIASAAIAACZIgPAAIgDgSQgDAIgJAGQgIAFgQABQgSAAgJgIgAh7ghQgGAGgCAJQgCAKAAAKQAAAMACAJQACAKAGAFQAHAFAMABQANgBAIgEQAHgFADgKQADgJgBgNQABgMgDgJQgDgJgHgGQgIgFgNAAQgNAAgGAGgAnUA3QgMgCgIgJQgJgHgFgOQgEgPAAgUQAAgcAIgQQAIgPAPgHQAOgHAVABIARABIANACIAAARIgNgDIgRgBQgQgBgKAFQgLAGgFAMQgFAMAAAVQAAAVAFANQAFALAKAFQAKAGAQgBIARgBIAQgFIAAAQIgPAFQgIABgLABQgOAAgMgEgAsTA1QgLgEgGgNQgGgMAAgWQAAgVAGgMQAGgNALgEQALgGARAAQAPAAAMAGQALAEAGANQAFAMAAAVQAAAWgFAMQgGANgLAEQgMAGgPAAQgRAAgLgGgAsLgjQgGAEgEAJQgDAJAAAPQAAAQADAJQAEAJAGAEQAIAEAMAAQALAAAIgEQAHgEADgJQADgJgBgQQABgPgDgJQgEgJgHgEQgHgEgLAAQgMAAgIAEgAu8A1QgLgEgGgNQgGgMAAgWQAAgVAGgMQAGgNALgEQAKgGARAAQANAAAJAFQAIADAFAIQAEAGACAIIACAQIgBAGIAAAGIhKAEQAAAMAEAIQACAHAJAFQAHADANAAQAJAAAJgCQAKgCAGgDIAAAQIgIADIgOADIgOABQgQAAgMgGgAu0gjQgIAEgCAJQgCAHgBAMIA6gFQAAgIgCgHQgBgIgGgEQgGgEgLAAQgNAAgGAEgAzzA1QgLgEgGgNQgFgMAAgWQAAgVAFgMQAGgNALgEQAMgGAQAAQAQAAALAGQAMAEAFANQAGAMAAAVQAAAWgGAMQgFANgMAEQgLAGgQAAQgQAAgMgGgAzqgjQgHAEgDAJQgDAJAAAPQAAAQADAJQADAJAHAEQAHAEAMAAQAMAAAHgEQAHgEADgJQADgJAAgQQAAgPgDgJQgDgJgIgEQgGgEgMAAQgMAAgHAEgA5SA7QgRAAgLgJQgKgIgGgSIgBgIIgBgIIAAgGQAAgQAIgNQAGgMAOgJIALgEIAKgBIACAAQATAAAMATIAAgFIARAAIAAA5IABAVIADASIgBABIgQAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBgBAAgBIgCgNIgDAFIgFAGQgEADgHADQgFACgHAAgA5fgfQgIAFgGANIgCAIIAAAHIAAAEQAAALAEAIQAEAJAIAHIAHACIAHABIAFAAQAeAAAAgmIAAgGQABgPgGgKQgFgKgLgCIgEAAIgDgBQgMAAgJAHgA8cAzQgKgHgEgMQgDgOAAgQQAAgOADgNQAEgMAKgJQAJgHATgBQAQABAHAFQAJAGADAKIAAhAIASAAIAACZIgPAAIgDgSQgDAIgJAGQgJAFgOABQgTAAgJgIgA8RghQgGAGgCAJQgCAKAAAKQAAAMACAJQACAKAGAFQAGAFANABQANgBAHgEQAIgFADgKQADgJAAgNQAAgMgDgJQgDgJgIgGQgHgFgNAAQgMAAgHAGgA+CA7QgQAAgLgJQgKgIgGgSIgCgIIAAgIIAAgGQAAgQAHgNQAGgMAOgJIAMgEIAKgBIABAAQATAAAMATIAAgFIASAAIAAA5IABAVIADASIgBABIgQAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgBAAgBIgCgNIgEAFIgEAGQgFADgGADQgGACgHAAgA+OgfQgJAFgFANIgCAIIgBAHIAAAEQAAALAFAIQADAJAJAHIAHACIAHABIAEAAQAfAAAAgmIAAgGQAAgPgFgKQgGgKgLgCIgDAAIgEgBQgMAAgIAHgEggHAA1QgLgEgGgNQgGgMAAgWQAAgVAGgMQAGgNALgEQAKgGARAAQANAAAJAFQAIADAFAIQAEAGACAIIACAQIgBAGIAAAGIhKAEQAAAMADAIQAEAHAIAFQAHADANAAQAJAAAJgCQAKgCAGgDIAAAQIgIADIgOADIgOABQgRAAgLgGgEggAgAjQgGAEgDAJQgCAHgBAMIA6gFQAAgIgCgHQgCgIgFgEQgGgEgLAAQgNAAgHAEgEAjDAA6QgFAAgDgBQgDgBAAgDQgCgDAAgFQAAgIADgDQADgCAHABQAHgBADACQADADAAAIQAAAFgBADQgCADgDABIgEABIgDAAgAN2A6QgFAAgCgBQgEgBgBgDQgBgDAAgFQAAgIADgDQADgCAHABQAHgBADACQADADAAAIQAAAFgBADQgBADgEABIgEABIgDAAgA3pA3QgIgDgCgHQgEgIAAgOIAAg8IgQAAIAAgPIAQAAIAAgZIARAAIAAAZIAbAAIAAAPIgbAAIAAA7IABANQACAFAEACQADACAGgBIAHAAIAFgBIAAAPIgGABIgGAAIgDAAQgKAAgGgDgARMA0QgGgFAAgNIAAiCIARAAIAAB+QAAAIADADQACADAGgBIADAAIAFgBIAAAPIgGABIgGAAIgCAAQgLAAgFgGgAjFA0QgGgFAAgNIAAiCIARAAIAAB+QAAAIADADQACADAFgBIAFAAIADgBIAAAPIgEABIgHAAIgCAAQgKAAgGgGgAF7A6IgLgBIgLgBIgJgCIAAgOIAKACIAKABIALAAQANAAAGgDQAGgEAAgJQABgHgCgDQgCgEgFgCQgGgCgKgDQgMgCgHgEQgGgDgDgGQgCgGAAgJQAAgNAJgJQAKgHAUgBIAPABIAMADIgBAPQgFgCgGgBQgIgCgHABQgMgBgFAEQgGADAAAKQAAAFACADQACADAEACQAEACAJABQAMADAIAEQAHADADAGQAEAHAAAKQAAARgKAHQgLAIgSAAIgDAAgEAgBAA5IAAhEQAAgJgBgGQgCgGgEgDQgFgDgJAAQgGAAgHABQgGACgFAFQgGAEgDAKIAABJIgRAAIAAhtIARAAIAAAQQADgHAHgEQAFgDAGgCIAOgCQAOABAIAEQAIAFADAHQAEAJAAAKIAABLgAeEA5IAAhtIARAAIAABtgAXHA5IAAhtIARAAIAAAVQAEgKAFgFQAGgEAHgCIANgCIACAAIgBAQIgCAAQgHAAgGACQgHACgGAFQgEAFgEAKIAABHgAT1A5IgogzIgGAAIAAAzIgRAAIAAiZIARAAIAABZIAHAAIAlgtIAWAAIguAzIAxA6gASAA5IAAhtIARAAIAABtgAPbA5IAAiLIATAAIAACLgAH3A5IAAiLIAoAAQAQgBAMADQAMADAKAHQAJAIAEAOQAFANAAAXQAAAZgJAPQgIAQgPAHQgPAFgVABgAIKApIAVAAQAPgBALgEQALgFAGgMQAGgMABgTQgBgXgGgMQgHgMgLgEQgLgEgOAAIgVAAgAD2A5IAAhEQAAgJgBgGQgCgGgEgDQgFgDgIAAQgHAAgGABQgHACgFAFQgFAEgEAKIAABJIgQAAIAAhtIAQAAIAAAQQAEgHAGgEQAFgDAHgCIANgCQAPABAIAEQAHAFAEAHQAEAJgBAKIAABLgAgRA5IAAhtIARAAIAAAVQADgKAFgFQAGgEAGgCIAOgCIACAAIAAAQIgDAAQgHAAgHACQgGACgFAFQgFAFgDAKIAABHgAkBA5IAAhtIARAAIAABtgAk2A5IAAhEQAAgJgCgGQgCgGgEgDQgFgDgIAAQgHAAgGABQgHACgFAFQgFAEgEAKIAABJIgQAAIAAiZIAQAAIAAA8QAEgHAGgEQAFgDAHgCIANgCQAPABAIAEQAHAFAEAHQAEAJgBAKIAABLgApgA5IAAhEQAAgJgCgGQgBgGgEgDQgFgDgJAAQgGAAgHABQgGACgGAFQgFAEgDAKIAABJIgRAAIAAhtIARAAIAAAQQADgHAGgEQAGgDAHgCIANgCQAOABAJAEQAHAFAEAHQADAJgBAKIAABLgAwCA5IAAhEQAAgNgEgHQgFgHgMAAQgGAAgGABQgFACgFAFQgEADgCAIIAABMIgRAAIAAhEQAAgNgFgHQgDgHgNAAQgGAAgGABQgFACgEAEQgEAFgEAIIAABLIgRAAIAAhtIARAAIAAAPQAGgKAIgDQAIgDAKgBQANABAIAEQAHAFAEAIQADgGAFgFQAGgDAGgCQAHgBAHgBQANABAHAEQAJAFADAHQADAJABAKIAABLgA04A5IAAhEQAAgJgCgGQgCgGgEgDQgFgDgIAAQgHAAgGABQgHACgFAFQgFAEgEAKIAABJIgQAAIAAiZIAQAAIAAA8QAEgHAGgEQAFgDAHgCIANgCQAPABAIAEQAHAFAEAHQAEAJgBAKIAABLgEghkAA5IAAhtIARAAIAAAVQAEgKAFgFQAGgEAHgCIANgCIACAAIgBAQIgCAAQgHAAgHACQgGACgGAFQgEAFgEAKIAABHgEgjPAA5IAAiLIASAAIAACLgAEngsIAFgRIAEgSIACgRIARAAQAAAIgCAIQgCAKgEAJIgIARgAeFhKQgDgCABgGQgBgHADgCQACgCAGABQAFgBADACQACACAAAHQAAAGgCACQgDACgFAAQgGAAgCgCgASAhKQgCgCABgGQgBgHACgCQADgCAGABQAFgBADACQACACAAAHQAAAGgCACQgDACgFAAQgGAAgDgCgAkBhKQgCgCAAgGQAAgHACgCQADgCAFABQAGgBACACQADACAAAHQAAAGgDACQgCACgGAAQgFAAgDgCg");
	this.shape.setTransform(273.2,32.2);

	this.instance_1 = new lib.元件32复制2();
	this.instance_1.setTransform(328.85,42.25,1,1,0,0,0,327.9,42.3);
	this.instance_1.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("EAhOABgIgMgBIAAgQIANACIAOABQASAAAJgIQAJgJAAgSIAAgLQgDAKgJAFQgIAGgPAAQgSgBgKgGQgLgIgDgMQgEgMAAgRQAAgOAEgNQADgNALgHQAKgIASAAQAKAAAHAEQAIADADAEQAFAGACAGIAAgVIARAAIAABlQAAAXgNAMQgMANgcAAIgPgBgEAhMgAhQgFAFgDAKQgCAJAAAKQAAAMACAJQACAJAHAFQAGAGAMAAQANAAAIgFQAHgEAEgKQACgJAAgNQAAgLgCgKQgEgJgHgFQgIgFgNAAQgMAAgHAGgAL7BSQAJAAAGgDQAGgDAEgFQAEgGACgIIgrhtIATAAIAhBaIABAAIAghaIASAAIgnBpQgFAOgHAKQgFAKgKAEQgKAGgPAAgAcPAzQgKgHgEgMQgDgOAAgQQAAgOADgNQAEgMAKgJQAKgHASgBQAPABAJAFQAIAGADAKIAAhAIASAAIAACZIgPAAIgDgSQgDAIgJAGQgJAFgOABQgSAAgKgIgAcaghQgGAGgCAJQgCAKAAAKQAAAMACAJQACAKAGAFQAHAFAMABQANgBAHgEQAIgFADgKQADgJAAgNQAAgMgDgJQgDgJgIgGQgHgFgNAAQgNAAgGAGgAaqA7QgRAAgLgJQgKgIgGgSIgBgIIgBgIIAAgGQAAgQAHgNQAGgMAPgJIALgEIAKgBIABAAQATAAANATIAAgFIARAAIAAA5IABAVIADASIgBABIgQAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgBAAgBIgCgNIgEAFIgEAGQgFADgGADQgGACgHAAgAacgfQgIAFgFANIgCAIIgBAHIAAAEQAAALAFAIQADAJAIAHIAIACIAHABIAEAAQAfAAAAgmIAAgGQAAgPgFgKQgGgKgLgCIgDAAIgEgBQgMAAgJAHgAYkA1QgLgEgGgNQgGgMAAgWQAAgVAGgMQAGgNALgEQAKgGARAAQANAAAJAFQAIADAFAIQAEAGACAIIACAQIgBAGIAAAGIhKAEQAAAMAEAIQACAHAJAFQAHADANAAQAJAAAJgCQAKgCAGgDIAAAQIgIADIgOADIgOABQgQAAgMgGgAYsgjQgIAEgCAJQgCAHgBAMIA6gFQAAgIgCgHQgCgIgFgEQgGgEgLAAQgNAAgGAEgAUvA1QgLgEgGgNQgGgMAAgWQAAgVAGgMQAGgNAKgEQALgGAQAAQAOAAAJAFQAJADAEAIQAEAGACAIIACAQIgBAGIAAAGIhKAEQAAAMADAIQAEAHAIAFQAHADANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgOADIgOABQgRAAgLgGgAU2gjQgGAEgDAJQgDAHAAAMIA6gFQAAgIgCgHQgCgIgFgEQgGgEgMAAQgMAAgHAEgAKlA7QgQAAgMgJQgKgIgGgSIgBgIIgBgIIAAgGQAAgQAHgNQAHgMAOgJIALgEIAKgBIACAAQATAAAMATIAAgFIARAAIAAA5IABAVIADASIgBABIgQAAQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAgBAAgBIgCgNIgDAFIgFAGQgEADgHADQgGACgGAAgAKYgfQgIAFgGANIgCAIIgBAHIAAAEQABALAEAIQAEAJAIAHIAHACIAHABIAFAAQAeAAAAgmIAAgGQABgPgGgKQgFgKgLgCIgEAAIgDgBQgMAAgJAHgABLA1QgLgEgGgNQgGgMAAgWQAAgVAGgMQAFgNALgEQALgGAQAAQAOAAAJAFQAIADAFAIQAEAGACAIIACAQIgBAGIAAAGIhKAEQAAAMADAIQADAHAIAFQAIADANAAQAJAAAKgCQAIgCAHgDIAAAQIgIADIgOADIgPABQgPAAgMgGgABSgjQgGAEgDAJQgDAHAAAMIA6gFQAAgIgCgHQgCgIgFgEQgGgEgMAAQgMAAgHAEgAiGAzQgKgHgDgMQgFgOAAgQQAAgOAFgNQADgMAKgJQAJgHASgBQAQABAJAFQAIAGADAKIAAhAIASAAIAACZIgPAAIgDgSQgDAIgJAGQgIAFgQABQgSAAgJgIgAh7ghQgGAGgCAJQgCAKAAAKQAAAMACAJQACAKAGAFQAHAFAMABQANgBAIgEQAHgFADgKQADgJgBgNQABgMgDgJQgDgJgHgGQgIgFgNAAQgNAAgGAGgAnUA3QgMgCgIgJQgJgHgFgOQgEgPAAgUQAAgcAIgQQAIgPAPgHQAOgHAVABIARABIANACIAAARIgNgDIgRgBQgQgBgKAFQgLAGgFAMQgFAMAAAVQAAAVAFANQAFALAKAFQAKAGAQgBIARgBIAQgFIAAAQIgPAFQgIABgLABQgOAAgMgEgAsTA1QgLgEgGgNQgGgMAAgWQAAgVAGgMQAGgNALgEQALgGARAAQAPAAAMAGQALAEAGANQAFAMAAAVQAAAWgFAMQgGANgLAEQgMAGgPAAQgRAAgLgGgAsLgjQgGAEgEAJQgDAJAAAPQAAAQADAJQAEAJAGAEQAIAEAMAAQALAAAIgEQAHgEADgJQADgJgBgQQABgPgDgJQgEgJgHgEQgHgEgLAAQgMAAgIAEgAu8A1QgLgEgGgNQgGgMAAgWQAAgVAGgMQAGgNALgEQAKgGARAAQANAAAJAFQAIADAFAIQAEAGACAIIACAQIgBAGIAAAGIhKAEQAAAMAEAIQACAHAJAFQAHADANAAQAJAAAJgCQAKgCAGgDIAAAQIgIADIgOADIgOABQgQAAgMgGgAu0gjQgIAEgCAJQgCAHgBAMIA6gFQAAgIgCgHQgBgIgGgEQgGgEgLAAQgNAAgGAEgAzzA1QgLgEgGgNQgFgMAAgWQAAgVAFgMQAGgNALgEQAMgGAQAAQAQAAALAGQAMAEAFANQAGAMAAAVQAAAWgGAMQgFANgMAEQgLAGgQAAQgQAAgMgGgAzqgjQgHAEgDAJQgDAJAAAPQAAAQADAJQADAJAHAEQAHAEAMAAQAMAAAHgEQAHgEADgJQADgJAAgQQAAgPgDgJQgDgJgIgEQgGgEgMAAQgMAAgHAEgA5SA7QgRAAgLgJQgKgIgGgSIgBgIIgBgIIAAgGQAAgQAIgNQAGgMAOgJIALgEIAKgBIACAAQATAAAMATIAAgFIARAAIAAA5IABAVIADASIgBABIgQAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBgBAAgBIgCgNIgDAFIgFAGQgEADgHADQgFACgHAAgA5fgfQgIAFgGANIgCAIIAAAHIAAAEQAAALAEAIQAEAJAIAHIAHACIAHABIAFAAQAeAAAAgmIAAgGQABgPgGgKQgFgKgLgCIgEAAIgDgBQgMAAgJAHgA8cAzQgKgHgEgMQgDgOAAgQQAAgOADgNQAEgMAKgJQAJgHATgBQAQABAHAFQAJAGADAKIAAhAIASAAIAACZIgPAAIgDgSQgDAIgJAGQgJAFgOABQgTAAgJgIgA8RghQgGAGgCAJQgCAKAAAKQAAAMACAJQACAKAGAFQAGAFANABQANgBAHgEQAIgFADgKQADgJAAgNQAAgMgDgJQgDgJgIgGQgHgFgNAAQgMAAgHAGgA+CA7QgQAAgLgJQgKgIgGgSIgCgIIAAgIIAAgGQAAgQAHgNQAGgMAOgJIAMgEIAKgBIABAAQATAAAMATIAAgFIASAAIAAA5IABAVIADASIgBABIgQAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgBAAgBIgCgNIgEAFIgEAGQgFADgGADQgGACgHAAgA+OgfQgJAFgFANIgCAIIgBAHIAAAEQAAALAFAIQADAJAJAHIAHACIAHABIAEAAQAfAAAAgmIAAgGQAAgPgFgKQgGgKgLgCIgDAAIgEgBQgMAAgIAHgEggHAA1QgLgEgGgNQgGgMAAgWQAAgVAGgMQAGgNALgEQAKgGARAAQANAAAJAFQAIADAFAIQAEAGACAIIACAQIgBAGIAAAGIhKAEQAAAMADAIQAEAHAIAFQAHADANAAQAJAAAJgCQAKgCAGgDIAAAQIgIADIgOADIgOABQgRAAgLgGgEggAgAjQgGAEgDAJQgCAHgBAMIA6gFQAAgIgCgHQgCgIgFgEQgGgEgLAAQgNAAgHAEgEAjDAA6QgFAAgDgBQgDgBAAgDQgCgDAAgFQAAgIADgDQADgCAHABQAHgBADACQADADAAAIQAAAFgBADQgCADgDABIgEABIgDAAgAN2A6QgFAAgCgBQgEgBgBgDQgBgDAAgFQAAgIADgDQADgCAHABQAHgBADACQADADAAAIQAAAFgBADQgBADgEABIgEABIgDAAgA3pA3QgIgDgCgHQgEgIAAgOIAAg8IgQAAIAAgPIAQAAIAAgZIARAAIAAAZIAbAAIAAAPIgbAAIAAA7IABANQACAFAEACQADACAGgBIAHAAIAFgBIAAAPIgGABIgGAAIgDAAQgKAAgGgDgARMA0QgGgFAAgNIAAiCIARAAIAAB+QAAAIADADQACADAGgBIADAAIAFgBIAAAPIgGABIgGAAIgCAAQgLAAgFgGgAjFA0QgGgFAAgNIAAiCIARAAIAAB+QAAAIADADQACADAFgBIAFAAIADgBIAAAPIgEABIgHAAIgCAAQgKAAgGgGgAF7A6IgLgBIgLgBIgJgCIAAgOIAKACIAKABIALAAQANAAAGgDQAGgEAAgJQABgHgCgDQgCgEgFgCQgGgCgKgDQgMgCgHgEQgGgDgDgGQgCgGAAgJQAAgNAJgJQAKgHAUgBIAPABIAMADIgBAPQgFgCgGgBQgIgCgHABQgMgBgFAEQgGADAAAKQAAAFACADQACADAEACQAEACAJABQAMADAIAEQAHADADAGQAEAHAAAKQAAARgKAHQgLAIgSAAIgDAAgEAgBAA5IAAhEQAAgJgBgGQgCgGgEgDQgFgDgJAAQgGAAgHABQgGACgFAFQgGAEgDAKIAABJIgRAAIAAhtIARAAIAAAQQADgHAHgEQAFgDAGgCIAOgCQAOABAIAEQAIAFADAHQAEAJAAAKIAABLgAeEA5IAAhtIARAAIAABtgAXHA5IAAhtIARAAIAAAVQAEgKAFgFQAGgEAHgCIANgCIACAAIgBAQIgCAAQgHAAgGACQgHACgGAFQgEAFgEAKIAABHgAT1A5IgogzIgGAAIAAAzIgRAAIAAiZIARAAIAABZIAHAAIAlgtIAWAAIguAzIAxA6gASAA5IAAhtIARAAIAABtgAPbA5IAAiLIATAAIAACLgAH3A5IAAiLIAoAAQAQgBAMADQAMADAKAHQAJAIAEAOQAFANAAAXQAAAZgJAPQgIAQgPAHQgPAFgVABgAIKApIAVAAQAPgBALgEQALgFAGgMQAGgMABgTQgBgXgGgMQgHgMgLgEQgLgEgOAAIgVAAgAD2A5IAAhEQAAgJgBgGQgCgGgEgDQgFgDgIAAQgHAAgGABQgHACgFAFQgFAEgEAKIAABJIgQAAIAAhtIAQAAIAAAQQAEgHAGgEQAFgDAHgCIANgCQAPABAIAEQAHAFAEAHQAEAJgBAKIAABLgAgRA5IAAhtIARAAIAAAVQADgKAFgFQAGgEAGgCIAOgCIACAAIAAAQIgDAAQgHAAgHACQgGACgFAFQgFAFgDAKIAABHgAkBA5IAAhtIARAAIAABtgAk2A5IAAhEQAAgJgCgGQgCgGgEgDQgFgDgIAAQgHAAgGABQgHACgFAFQgFAEgEAKIAABJIgQAAIAAiZIAQAAIAAA8QAEgHAGgEQAFgDAHgCIANgCQAPABAIAEQAHAFAEAHQAEAJgBAKIAABLgApgA5IAAhEQAAgJgCgGQgBgGgEgDQgFgDgJAAQgGAAgHABQgGACgGAFQgFAEgDAKIAABJIgRAAIAAhtIARAAIAAAQQADgHAGgEQAGgDAHgCIANgCQAOABAJAEQAHAFAEAHQADAJgBAKIAABLgAwCA5IAAhEQAAgNgEgHQgFgHgMAAQgGAAgGABQgFACgFAFQgEADgCAIIAABMIgRAAIAAhEQAAgNgFgHQgDgHgNAAQgGAAgGABQgFACgEAEQgEAFgEAIIAABLIgRAAIAAhtIARAAIAAAPQAGgKAIgDQAIgDAKgBQANABAIAEQAHAFAEAIQADgGAFgFQAGgDAGgCQAHgBAHgBQANABAHAEQAJAFADAHQADAJABAKIAABLgA04A5IAAhEQAAgJgCgGQgCgGgEgDQgFgDgIAAQgHAAgGABQgHACgFAFQgFAEgEAKIAABJIgQAAIAAiZIAQAAIAAA8QAEgHAGgEQAFgDAHgCIANgCQAPABAIAEQAHAFAEAHQAEAJgBAKIAABLgEghkAA5IAAhtIARAAIAAAVQAEgKAFgFQAGgEAHgCIANgCIACAAIgBAQIgCAAQgHAAgHACQgGACgGAFQgEAFgEAKIAABHgEgjPAA5IAAiLIASAAIAACLgAEngsIAFgRIAEgSIACgRIARAAQAAAIgCAIQgCAKgEAJIgIARgAeFhKQgDgCABgGQgBgHADgCQACgCAGABQAFgBADACQACACAAAHQAAAGgCACQgDACgFAAQgGAAgCgCgASAhKQgCgCABgGQgBgHACgCQADgCAGABQAFgBADACQACACAAAHQAAAGgCACQgDACgFAAQgGAAgDgCgAkBhKQgCgCAAgGQAAgHACgCQADgCAFABQAGgBACACQADACAAAHQAAAGgDACQgCACgGAAQgFAAgDgCg");
	this.shape_1.setTransform(273.2,32.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.shape}]}).to({state:[{t:this.instance_1},{t:this.shape_1}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-6,-7,536,80);
p.frameBounds = [rect, rect];


(lib.元件21 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));

	// 图层_3
	this.instance = new lib.元件23();
	this.instance.setTransform(330.3,31.15,2.4152,1.3613,0,0,0,125.5,23.4);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.元件23(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// 图层_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AfFBTQAJAAAGgDQAGgDAEgFQAEgHADgIIgshsIATAAIAhBaIACAAIAfhaIASAAIgnBpQgFANgGAKQgGAKgKAFQgJAGgQAAgAnMBTQAKAAAGgDQAGgDAEgFQAEgHACgIIgrhsIATAAIAhBaIABAAIAghaIARAAIgnBpQgFANgGAKQgGAKgJAFQgKAGgQAAgEgq/ABgIgMgBIAAgPIANACIAOABQASAAAJgJQAIgIAAgTIAAgKQgDAKgIAEQgIAGgQAAQgSAAgKgHQgKgHgDgNQgEgMAAgQQAAgPAEgMQADgNAKgHQAKgIASAAQALAAAHADQAHADAEAFQAEAFACAGIAAgUIASAAIAABkQAAAXgNAMQgNANgcABIgOgCgEgrBgAhQgGAGgCAKQgCAJAAAKQAAALACAJQACAJAHAGQAGAGAMgBQANAAAIgEQAHgFADgKQADgIAAgNQAAgMgDgKQgDgIgHgFQgIgFgNgBQgMABgHAFgEAo/AA3QgIgFgDgIQgDgIAAgLIAAhKIARAAIAABEQAAAJACAFQABAHAFACQAFADAIABQAHAAAGgCQAGgBAFgFQAFgFADgJIAAhJIASAAIAABsIgPAAIgCgQQgEAHgFAFQgGADgGABQgHACgHAAQgOAAgIgEgAdvA7QgQAAgLgJQgLgIgFgRIgCgIIAAgIIAAgHQAAgPAHgNQAGgNAOgJIALgDIAKgBIACAAQATgBAMAUIAAgGIASAAIAAA6IABAUIACASIgBABIgQAAQAAAAAAAAQgBgBAAAAQAAgBAAgBQAAAAgBgBIgBgOIgEAGIgEAFQgFAEgGACQgGACgHAAgAdigfQgIAGgFAMIgCAIIgBAHIAAAFQAAAKAEAJQAEAIAIAHIAHADIAIABIAEAAQAfAAAAgnIAAgGQAAgPgGgJQgFgKgLgDIgEAAIgDgBQgMAAgJAHgAUVA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAGACAIIABARIAAAFIgBAGIhKAFQAAAMAEAIQADAHAIAEQAHAEANAAQAJgBAKgCQAJgCAGgCIAAAQIgIADIgNACIgPABQgQAAgMgFgAUdgiQgHAEgDAIQgCAIgBALIA6gEQAAgJgBgHQgCgHgGgEQgGgFgLAAQgNAAgGAFgARDA0QgKgIgDgMQgEgNAAgRQAAgNAEgNQADgNAKgIQAKgIASAAQAQAAAIAFQAIAHADAJIAAg/IASAAIAACYIgPAAIgDgSQgDAJgJAGQgIAFgPAAQgSAAgKgHgAROghQgGAHgCAJQgCAJAAAKQAAAMACAJQACAKAHAGQAGAFAMABQANgBAIgFQAHgFADgJQADgKAAgNQAAgLgDgJQgDgKgHgFQgIgGgNAAQgMABgHAFgAL1A4QgMgDgIgIQgJgIgEgOQgFgOAAgVQAAgbAIgQQAIgPAPgIQAPgHAUABIARABIANADIAAARIgNgEIgRgBQgPAAgLAFQgKAGgGAMQgFAMAAAUQAAAWAFAMQAFAMAKAFQAKAFAQgBIARgBIAQgEIAAAQIgPAEQgIACgLAAQgOAAgMgDgAG2A2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQAMgFAQAAQAQAAALAFQALAFAGAMQAGANAAAUQAAAWgGANQgGAMgLAFQgLAFgQAAQgQAAgMgFgAG/giQgHADgDAJQgDAKAAAOQAAAQADAKQADAIAHAEQAHAFAMAAQAMAAAHgFQAHgEADgIQADgKgBgQQABgOgDgKQgEgJgHgDQgHgFgLAAQgMAAgHAFgACcA0QgKgIgDgMQgEgNAAgRQAAgNAEgNQADgNAKgIQAKgIASAAQAQAAAIAFQAIAHADAJIAAg/IASAAIAACYIgPAAIgDgSQgDAJgJAGQgIAFgPAAQgSAAgKgHgACnghQgGAHgCAJQgCAJAAAKQAAAMACAJQACAKAHAGQAGAFAMABQANgBAIgFQAHgFADgJQADgKAAgNQAAgLgDgJQgDgKgHgFQgIgGgNAAQgMABgHAFgAhPA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAGACAIQABAJAAAIIAAAFIgBAGIhKAFQAAAMAEAIQADAHAIAEQAHAEANAAQAJgBAKgCQAJgCAGgCIAAAQIgIADIgNACIgPABQgQAAgMgFgAhHgiQgHAEgDAIQgCAIgBALIA6gEQAAgJgBgHQgCgHgGgEQgGgFgLAAQgNAAgGAFgAzhA7QgQAAgLgJQgLgIgFgRIgCgIIAAgIIAAgHQAAgPAHgNQAGgNAOgJIALgDIAKgBIACAAQATgBAMAUIAAgGIASAAIAAA6IABAUIACASIgBABIgQAAQAAAAAAAAQAAgBgBAAQAAgBAAgBQAAAAgBgBIgBgOIgEAGIgEAFQgFAEgGACQgGACgHAAgAzugfQgIAGgFAMIgCAIIgBAHIAAAFQAAAKAEAJQAEAIAIAHIAHADIAIABIAEAAQAfAAAAgnIAAgGQAAgPgGgJQgFgKgLgDIgEAAIgDgBQgMAAgJAHgA4gA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAFgMALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAGACAIQACAJAAAIIgBAFIAAAGIhKAFQAAAMADAIQADAHAIAEQAIAEANAAQAJgBAJgCQAJgCAHgCIAAAQIgJADIgNACIgPABQgQAAgLgFgA4ZgiQgHAEgCAIQgDAIAAALIA6gEQAAgJgCgHQgCgHgFgEQgGgFgMAAQgMAAgHAFgA83A2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQAMgFAQAAIAQABIAMADIAAAQQgGgCgHgBQgHgCgIAAQgMAAgHAEQgHAEgDAIQgDAKAAAOQAAAQADAKQADAIAHAEQAHAEAMAAIAPgCQAIgBAGgCIAAAQIgIACIgLABIgKABQgQAAgMgFgA/gA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAGACAIIABARIAAAFIgBAGIhKAFQAAAMAEAIQADAHAIAEQAHAEANAAQAJgBAKgCQAJgCAGgCIAAAQIgIADIgNACIgPABQgQAAgMgFgA/YgiQgHAEgDAIQgCAIgBALIA6gEQAAgJgBgHQgCgHgGgEQgGgFgLAAQgNAAgGAFgEglRAA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQALgFAQAAQAQAAAMAFQALAFAGAMQAFANAAAUQAAAWgFANQgGAMgLAFQgMAFgQAAQgQAAgLgFgEglJgAiQgHADgDAJQgDAKAAAOQAAAQADAKQADAIAHAEQAHAFAMAAQAMAAAHgFQAHgEADgIQADgKAAgQQAAgOgDgKQgDgJgHgDQgHgFgMAAQgMAAgHAFgEgpGAA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQAMgFAQAAQAQAAALAFQALAFAGAMQAGANAAAUQAAAWgGANQgGAMgLAFQgLAFgQAAQgQAAgMgFgEgo9gAiQgHADgDAJQgDAKAAAOQAAAQADAKQADAIAHAEQAHAFAMAAQAMAAAHgFQAHgEADgIQADgKgBgQQABgOgDgKQgEgJgHgDQgHgFgLAAQgMAAgHAFgEAs2AA6QgFABgDgCQgDgBgBgCQgBgDAAgFQAAgJADgCQADgCAHAAQAHAAADACQADACAAAJQAAAFgCADQgBACgDABIgEABIgDAAgEAhAAA6QgFABgCgCQgDgBgBgCQgCgDAAgFQAAgJADgCQADgCAHAAQAHAAADACQADACAAAJQAAAFgBADQgBACgDABIgFABIgDAAgEAjqAA4QgHgDgDgHQgDgIAAgPIAAg7IgQAAIAAgPIAQAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA6IABAOQACAEADACQADACAHAAIAGAAIAGgCIAAAPIgGABIgGAAIgEAAQgJAAgHgCgAtnA4QgHgDgDgHQgEgIAAgPIAAg7IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA6IABAOQABAEAEACQADACAGAAIAHAAIAFgCIAAAPIgGABIgGAAIgDAAQgKAAgGgCgEgijAA4QgHgDgDgHQgDgIAAgPIAAg7IgQAAIAAgPIAQAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA6IABAOQACAEADACQADACAHAAIAGAAIAGgCIAAAPIgGABIgGAAIgEAAQgJAAgHgCgEgmXAA4QgHgDgDgHQgEgIAAgPIAAg7IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA6IABAOQABAEAEACQADACAGAAIAHAAIAFgCIAAAPIgGABIgGAAIgDAAQgKAAgGgCgAQEA1QgGgGAAgMIAAiCIARAAIAAB9QAAAJADACQACADAGAAIAEAAIAEgCIAAAPIgFABIgHAAIgCAAQgKAAgGgFgEAlwAA6IgMgBIgLgBIgJgBIAAgPIAKACIALACIALAAQAMAAAGgEQAHgEAAgIQAAgHgCgDQgCgFgFgCQgFgCgKgCQgMgCgHgEQgHgEgCgFQgDgHAAgJQAAgNAKgIQAKgIATAAIAQABIAMACIgCAQQgEgCgHgCQgHgBgIAAQgLAAgGAEQgGADAAAJQAAAGACADQACACAEADQAFABAIACQANADAHADQAIAEADAGQADAHAAAKQAAAQgKAHQgLAIgSAAIgCAAgAZGA6IgMgBIgLgBIgJgBIAAgPIAKACIALACIALAAQAMAAAGgEQAHgEAAgIQAAgHgCgDQgCgFgFgCQgFgCgKgCQgMgCgHgEQgHgEgCgFQgDgHAAgJQAAgNAKgIQAKgIATAAIAQABIAMACIgCAQQgEgCgHgCQgHgBgIAAQgLAAgGAEQgGADAAAJQAAAGACADQACACAEADQAFABAIACQANADAHADQAIAEADAGQADAHAAAKQAAAQgKAHQgLAIgSAAIgCAAgAEqA6IgLgBIgMgBIgIgBIAAgPIAJACIALACIALAAQANAAAGgEQAGgEAAgIQABgHgCgDQgCgFgFgCQgGgCgKgCQgMgCgHgEQgGgEgDgFQgDgHAAgJQABgNAJgIQAKgIAUAAIAPABIAMACIgBAQQgFgCgHgCQgHgBgHAAQgMAAgFAEQgGADAAAJQAAAGABADQACACAFADQAEABAJACQAMADAIADQAHAEADAGQAEAHAAAKQAAAQgLAHQgKAIgSAAIgDAAgEAr0AA5IAAhEQAAgJgBgFQgCgGgEgDQgFgDgIgBQgHAAgHACQgGABgFAFQgFAFgEAKIAABIIgRAAIAAhsIARAAIAAAQQAEgIAGgDQAFgEAHgBIANgCQAPAAAIAEQAHAFAEAIQADAIAAALIAABKgEAnvAA5IAAhdIgTAAIAAgPIATAAIAAgBQAAgTAEgJQAFgKAIgDQAIgDALAAIAGAAIAGABIAAAOIgFgBIgHgBQgHABgEADQgFACgBAHQgCAHAAAMIAaAAIAAAPIgaAAIAABdgEAilAA5IAAiLIATAAIAACLgAbBA5IAAiLIApAAQAPAAAMADQANADAJAHQAJAHAEAOQAFAOAAAWQAAAagIAPQgJAQgPAGQgPAGgUAAgAbUApIAVAAQAPAAALgEQALgGAGgLQAGgMABgUQgBgXgGgLQgGgMgLgEQgLgFgPAAIgVAAgAXBA5IAAhEQAAgJgCgFQgBgGgFgDQgEgDgJgBQgHAAgGACQgHABgFAFQgFAFgDAKIAABIIgRAAIAAhsIARAAIAAAQQADgIAGgDQAGgEAGgBIAOgCQAOAAAIAEQAIAFADAIQAEAIgBALIAABKgAS4A5IAAhsIARAAIAAAUQAEgJAGgFQAFgEAHgCIANgCIACAAIAAAPIgDAAQgHABgGACQgHACgFAFQgFAFgEAJIAABHgAPIA5IAAhsIARAAIAABsgAOTA5IAAhEQAAgJgCgFQgBgGgFgDQgEgDgJgBQgHAAgGACQgHABgFAFQgFAFgDAKIAABIIgRAAIAAiYIARAAIAAA8QADgIAGgDQAGgEAGgBIAOgCQAOAAAIAEQAIAFADAIQAEAIgBALIAABKgAJpA5IAAhEQAAgJgBgFQgCgGgEgDQgFgDgIgBQgHAAgHACQgGABgFAFQgFAFgEAKIAABIIgRAAIAAhsIARAAIAAAQQAEgIAGgDQAFgEAHgBIANgCQAPAAAIAEQAHAFAEAIQADAIAAALIAABKgABbA5IAAhEQAAgJgBgFQgCgGgEgDQgFgDgIgBQgHAAgHACQgGABgFAFQgFAFgEAKIAABIIgRAAIAAhsIARAAIAAAQQAEgIAGgDQAFgEAHgBIANgCQAPAAAIAEQAHAFAEAIQADAIAAALIAABKgAiVA5IAAhsIARAAIAABsgAjiA5IAAhsIARAAIAAAUQAEgJAGgFQAFgEAHgCIANgCIACAAIAAAPIgDAAQgHABgGACQgHACgFAFQgFAFgEAJIAABHgAklA5IAAhdIgSAAIAAgPIASAAIAAgBQAAgTAFgJQAEgKAIgDQAJgDALAAIAGAAIAGABIAAAOIgFgBIgHgBQgIABgEADQgEACgCAHQgCAHAAAMIAaAAIAAAPIgaAAIAABdgAn8A5IAAhEQAAgMgEgIQgFgGgMgBQgGAAgGACQgGABgEAFQgEAEgCAIIAABLIgSAAIAAhEQABgMgFgIQgEgGgMgBQgGAAgGACQgFABgFAEQgEAFgDAJIAABKIgRAAIAAhsIARAAIAAAPQAGgKAIgEQAIgDAKAAQANAAAHAEQAIAGAEAIQADgHAFgEQAGgEAGgBQAHgCAHAAQAMAAAIAEQAIAFAEAIQADAIAAALIAABKgArqA5IAAhEQAAgJgCgFQgBgGgFgDQgEgDgJgBQgHAAgGACQgHABgFAFQgFAFgDAKIAABIIgRAAIAAiYIARAAIAAA8QADgIAGgDQAGgEAGgBIAOgCQAOAAAIAEQAIAFADAIQAEAIgBALIAABKgAurA5IAAhsIARAAIAABsgAv2A5IgbhZIgBAAIgbBZIgWAAIgdhsIARAAIAXBaIABAAIAbhaIAVAAIAcBaIABAAIAXhaIARAAIgeBsgA03A5IAAhEQAAgMgEgIQgFgGgMgBQgGAAgGACQgGABgEAFQgEAEgCAIIAABLIgSAAIAAhEQABgMgFgIQgEgGgMgBQgGAAgGACQgFABgFAEQgEAFgDAJIAABKIgRAAIAAhsIARAAIAAAPQAGgKAIgEQAIgDAKAAQANAAAHAEQAIAGAEAIQADgHAFgEQAGgEAGgBQAHgCAHAAQAMAAAIAEQAIAFAEAIQADAIAAALIAABKgA5mA5IAAhEQAAgJgCgFQgBgGgFgDQgEgDgJgBQgHAAgGACQgHABgFAFQgFAFgDAKIAABIIgRAAIAAhsIARAAIAAAQQADgIAGgDQAGgEAGgBIAOgCQAOAAAIAEQAIAFADAIQAEAIgBALIAABKgA7jA5IAAhsIARAAIAABsgEgglAA5IAAhEQAAgJgCgFQgCgGgEgDQgFgDgIgBQgHAAgHACQgGABgFAFQgFAFgEAKIAABIIgRAAIAAiYIARAAIAAA8QAEgIAGgDQAFgEAHgBIANgCQAPAAAIAEQAHAFAEAIQADAIAAALIAABKgEgtCAA5IAAiLIATAAIAACLgEAkbgArIAFgRIAEgSIACgRIARAAQAAAHgCAJQgCAJgEAKIgHARgAXxgrIAFgRIAEgSIACgRIARAAQAAAHgCAJQgCAJgEAKIgHARgAPJhJQgDgCABgGQgBgHADgCQACgCAGAAQAFAAADACQACACAAAHQAAAGgCACQgDACgFAAQgGAAgCgCgAiVhJQgCgCAAgGQAAgHACgCQADgCAFAAQAGAAACACQADACAAAHQAAAGgDACQgCACgGAAQgFAAgDgCgAurhJQgCgCAAgGQAAgHACgCQADgCAFAAQAGAAACACQADACAAAHQAAAGgDACQgCACgGAAQgFAAgDgCgA7jhJQgCgCAAgGQAAgHACgCQADgCAFAAQAGAAACACQADACAAAHQAAAGgDACQgCACgGAAQgFAAgDgCg");
	this.shape.setTransform(335.875,32.15);

	this.instance_1 = new lib.元件32复制();
	this.instance_1.setTransform(328.85,42.25,1,1,0,0,0,327.9,42.3);
	this.instance_1.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AfFBTQAJAAAGgDQAGgDAEgFQAEgHADgIIgshsIATAAIAhBaIACAAIAfhaIASAAIgnBpQgFANgGAKQgGAKgKAFQgJAGgQAAgAnMBTQAKAAAGgDQAGgDAEgFQAEgHACgIIgrhsIATAAIAhBaIABAAIAghaIARAAIgnBpQgFANgGAKQgGAKgJAFQgKAGgQAAgEgq/ABgIgMgBIAAgPIANACIAOABQASAAAJgJQAIgIAAgTIAAgKQgDAKgIAEQgIAGgQAAQgSAAgKgHQgKgHgDgNQgEgMAAgQQAAgPAEgMQADgNAKgHQAKgIASAAQALAAAHADQAHADAEAFQAEAFACAGIAAgUIASAAIAABkQAAAXgNAMQgNANgcABIgOgCgEgrBgAhQgGAGgCAKQgCAJAAAKQAAALACAJQACAJAHAGQAGAGAMgBQANAAAIgEQAHgFADgKQADgIAAgNQAAgMgDgKQgDgIgHgFQgIgFgNgBQgMABgHAFgEAo/AA3QgIgFgDgIQgDgIAAgLIAAhKIARAAIAABEQAAAJACAFQABAHAFACQAFADAIABQAHAAAGgCQAGgBAFgFQAFgFADgJIAAhJIASAAIAABsIgPAAIgCgQQgEAHgFAFQgGADgGABQgHACgHAAQgOAAgIgEgAdvA7QgQAAgLgJQgLgIgFgRIgCgIIAAgIIAAgHQAAgPAHgNQAGgNAOgJIALgDIAKgBIACAAQATgBAMAUIAAgGIASAAIAAA6IABAUIACASIgBABIgQAAQAAAAAAAAQgBgBAAAAQAAgBAAgBQAAAAgBgBIgBgOIgEAGIgEAFQgFAEgGACQgGACgHAAgAdigfQgIAGgFAMIgCAIIgBAHIAAAFQAAAKAEAJQAEAIAIAHIAHADIAIABIAEAAQAfAAAAgnIAAgGQAAgPgGgJQgFgKgLgDIgEAAIgDgBQgMAAgJAHgAUVA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAGACAIIABARIAAAFIgBAGIhKAFQAAAMAEAIQADAHAIAEQAHAEANAAQAJgBAKgCQAJgCAGgCIAAAQIgIADIgNACIgPABQgQAAgMgFgAUdgiQgHAEgDAIQgCAIgBALIA6gEQAAgJgBgHQgCgHgGgEQgGgFgLAAQgNAAgGAFgARDA0QgKgIgDgMQgEgNAAgRQAAgNAEgNQADgNAKgIQAKgIASAAQAQAAAIAFQAIAHADAJIAAg/IASAAIAACYIgPAAIgDgSQgDAJgJAGQgIAFgPAAQgSAAgKgHgAROghQgGAHgCAJQgCAJAAAKQAAAMACAJQACAKAHAGQAGAFAMABQANgBAIgFQAHgFADgJQADgKAAgNQAAgLgDgJQgDgKgHgFQgIgGgNAAQgMABgHAFgAL1A4QgMgDgIgIQgJgIgEgOQgFgOAAgVQAAgbAIgQQAIgPAPgIQAPgHAUABIARABIANADIAAARIgNgEIgRgBQgPAAgLAFQgKAGgGAMQgFAMAAAUQAAAWAFAMQAFAMAKAFQAKAFAQgBIARgBIAQgEIAAAQIgPAEQgIACgLAAQgOAAgMgDgAG2A2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQAMgFAQAAQAQAAALAFQALAFAGAMQAGANAAAUQAAAWgGANQgGAMgLAFQgLAFgQAAQgQAAgMgFgAG/giQgHADgDAJQgDAKAAAOQAAAQADAKQADAIAHAEQAHAFAMAAQAMAAAHgFQAHgEADgIQADgKgBgQQABgOgDgKQgEgJgHgDQgHgFgLAAQgMAAgHAFgACcA0QgKgIgDgMQgEgNAAgRQAAgNAEgNQADgNAKgIQAKgIASAAQAQAAAIAFQAIAHADAJIAAg/IASAAIAACYIgPAAIgDgSQgDAJgJAGQgIAFgPAAQgSAAgKgHgACnghQgGAHgCAJQgCAJAAAKQAAAMACAJQACAKAHAGQAGAFAMABQANgBAIgFQAHgFADgJQADgKAAgNQAAgLgDgJQgDgKgHgFQgIgGgNAAQgMABgHAFgAhPA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAGACAIQABAJAAAIIAAAFIgBAGIhKAFQAAAMAEAIQADAHAIAEQAHAEANAAQAJgBAKgCQAJgCAGgCIAAAQIgIADIgNACIgPABQgQAAgMgFgAhHgiQgHAEgDAIQgCAIgBALIA6gEQAAgJgBgHQgCgHgGgEQgGgFgLAAQgNAAgGAFgAzhA7QgQAAgLgJQgLgIgFgRIgCgIIAAgIIAAgHQAAgPAHgNQAGgNAOgJIALgDIAKgBIACAAQATgBAMAUIAAgGIASAAIAAA6IABAUIACASIgBABIgQAAQAAAAAAAAQAAgBgBAAQAAgBAAgBQAAAAgBgBIgBgOIgEAGIgEAFQgFAEgGACQgGACgHAAgAzugfQgIAGgFAMIgCAIIgBAHIAAAFQAAAKAEAJQAEAIAIAHIAHADIAIABIAEAAQAfAAAAgnIAAgGQAAgPgGgJQgFgKgLgDIgEAAIgDgBQgMAAgJAHgA4gA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAFgMALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAGACAIQACAJAAAIIgBAFIAAAGIhKAFQAAAMADAIQADAHAIAEQAIAEANAAQAJgBAJgCQAJgCAHgCIAAAQIgJADIgNACIgPABQgQAAgLgFgA4ZgiQgHAEgCAIQgDAIAAALIA6gEQAAgJgCgHQgCgHgFgEQgGgFgMAAQgMAAgHAFgA83A2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQAMgFAQAAIAQABIAMADIAAAQQgGgCgHgBQgHgCgIAAQgMAAgHAEQgHAEgDAIQgDAKAAAOQAAAQADAKQADAIAHAEQAHAEAMAAIAPgCQAIgBAGgCIAAAQIgIACIgLABIgKABQgQAAgMgFgA/gA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAGACAIIABARIAAAFIgBAGIhKAFQAAAMAEAIQADAHAIAEQAHAEANAAQAJgBAKgCQAJgCAGgCIAAAQIgIADIgNACIgPABQgQAAgMgFgA/YgiQgHAEgDAIQgCAIgBALIA6gEQAAgJgBgHQgCgHgGgEQgGgFgLAAQgNAAgGAFgEglRAA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQALgFAQAAQAQAAAMAFQALAFAGAMQAFANAAAUQAAAWgFANQgGAMgLAFQgMAFgQAAQgQAAgLgFgEglJgAiQgHADgDAJQgDAKAAAOQAAAQADAKQADAIAHAEQAHAFAMAAQAMAAAHgFQAHgEADgIQADgKAAgQQAAgOgDgKQgDgJgHgDQgHgFgMAAQgMAAgHAFgEgpGAA2QgLgFgGgMQgGgNAAgWQAAgUAGgNQAGgMALgFQAMgFAQAAQAQAAALAFQALAFAGAMQAGANAAAUQAAAWgGANQgGAMgLAFQgLAFgQAAQgQAAgMgFgEgo9gAiQgHADgDAJQgDAKAAAOQAAAQADAKQADAIAHAEQAHAFAMAAQAMAAAHgFQAHgEADgIQADgKgBgQQABgOgDgKQgEgJgHgDQgHgFgLAAQgMAAgHAFgEAs2AA6QgFABgDgCQgDgBgBgCQgBgDAAgFQAAgJADgCQADgCAHAAQAHAAADACQADACAAAJQAAAFgCADQgBACgDABIgEABIgDAAgEAhAAA6QgFABgCgCQgDgBgBgCQgCgDAAgFQAAgJADgCQADgCAHAAQAHAAADACQADACAAAJQAAAFgBADQgBACgDABIgFABIgDAAgEAjqAA4QgHgDgDgHQgDgIAAgPIAAg7IgQAAIAAgPIAQAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA6IABAOQACAEADACQADACAHAAIAGAAIAGgCIAAAPIgGABIgGAAIgEAAQgJAAgHgCgAtnA4QgHgDgDgHQgEgIAAgPIAAg7IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA6IABAOQABAEAEACQADACAGAAIAHAAIAFgCIAAAPIgGABIgGAAIgDAAQgKAAgGgCgEgijAA4QgHgDgDgHQgDgIAAgPIAAg7IgQAAIAAgPIAQAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA6IABAOQACAEADACQADACAHAAIAGAAIAGgCIAAAPIgGABIgGAAIgEAAQgJAAgHgCgEgmXAA4QgHgDgDgHQgEgIAAgPIAAg7IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA6IABAOQABAEAEACQADACAGAAIAHAAIAFgCIAAAPIgGABIgGAAIgDAAQgKAAgGgCgAQEA1QgGgGAAgMIAAiCIARAAIAAB9QAAAJADACQACADAGAAIAEAAIAEgCIAAAPIgFABIgHAAIgCAAQgKAAgGgFgEAlwAA6IgMgBIgLgBIgJgBIAAgPIAKACIALACIALAAQAMAAAGgEQAHgEAAgIQAAgHgCgDQgCgFgFgCQgFgCgKgCQgMgCgHgEQgHgEgCgFQgDgHAAgJQAAgNAKgIQAKgIATAAIAQABIAMACIgCAQQgEgCgHgCQgHgBgIAAQgLAAgGAEQgGADAAAJQAAAGACADQACACAEADQAFABAIACQANADAHADQAIAEADAGQADAHAAAKQAAAQgKAHQgLAIgSAAIgCAAgAZGA6IgMgBIgLgBIgJgBIAAgPIAKACIALACIALAAQAMAAAGgEQAHgEAAgIQAAgHgCgDQgCgFgFgCQgFgCgKgCQgMgCgHgEQgHgEgCgFQgDgHAAgJQAAgNAKgIQAKgIATAAIAQABIAMACIgCAQQgEgCgHgCQgHgBgIAAQgLAAgGAEQgGADAAAJQAAAGACADQACACAEADQAFABAIACQANADAHADQAIAEADAGQADAHAAAKQAAAQgKAHQgLAIgSAAIgCAAgAEqA6IgLgBIgMgBIgIgBIAAgPIAJACIALACIALAAQANAAAGgEQAGgEAAgIQABgHgCgDQgCgFgFgCQgGgCgKgCQgMgCgHgEQgGgEgDgFQgDgHAAgJQABgNAJgIQAKgIAUAAIAPABIAMACIgBAQQgFgCgHgCQgHgBgHAAQgMAAgFAEQgGADAAAJQAAAGABADQACACAFADQAEABAJACQAMADAIADQAHAEADAGQAEAHAAAKQAAAQgLAHQgKAIgSAAIgDAAgEAr0AA5IAAhEQAAgJgBgFQgCgGgEgDQgFgDgIgBQgHAAgHACQgGABgFAFQgFAFgEAKIAABIIgRAAIAAhsIARAAIAAAQQAEgIAGgDQAFgEAHgBIANgCQAPAAAIAEQAHAFAEAIQADAIAAALIAABKgEAnvAA5IAAhdIgTAAIAAgPIATAAIAAgBQAAgTAEgJQAFgKAIgDQAIgDALAAIAGAAIAGABIAAAOIgFgBIgHgBQgHABgEADQgFACgBAHQgCAHAAAMIAaAAIAAAPIgaAAIAABdgEAilAA5IAAiLIATAAIAACLgAbBA5IAAiLIApAAQAPAAAMADQANADAJAHQAJAHAEAOQAFAOAAAWQAAAagIAPQgJAQgPAGQgPAGgUAAgAbUApIAVAAQAPAAALgEQALgGAGgLQAGgMABgUQgBgXgGgLQgGgMgLgEQgLgFgPAAIgVAAgAXBA5IAAhEQAAgJgCgFQgBgGgFgDQgEgDgJgBQgHAAgGACQgHABgFAFQgFAFgDAKIAABIIgRAAIAAhsIARAAIAAAQQADgIAGgDQAGgEAGgBIAOgCQAOAAAIAEQAIAFADAIQAEAIgBALIAABKgAS4A5IAAhsIARAAIAAAUQAEgJAGgFQAFgEAHgCIANgCIACAAIAAAPIgDAAQgHABgGACQgHACgFAFQgFAFgEAJIAABHgAPIA5IAAhsIARAAIAABsgAOTA5IAAhEQAAgJgCgFQgBgGgFgDQgEgDgJgBQgHAAgGACQgHABgFAFQgFAFgDAKIAABIIgRAAIAAiYIARAAIAAA8QADgIAGgDQAGgEAGgBIAOgCQAOAAAIAEQAIAFADAIQAEAIgBALIAABKgAJpA5IAAhEQAAgJgBgFQgCgGgEgDQgFgDgIgBQgHAAgHACQgGABgFAFQgFAFgEAKIAABIIgRAAIAAhsIARAAIAAAQQAEgIAGgDQAFgEAHgBIANgCQAPAAAIAEQAHAFAEAIQADAIAAALIAABKgABbA5IAAhEQAAgJgBgFQgCgGgEgDQgFgDgIgBQgHAAgHACQgGABgFAFQgFAFgEAKIAABIIgRAAIAAhsIARAAIAAAQQAEgIAGgDQAFgEAHgBIANgCQAPAAAIAEQAHAFAEAIQADAIAAALIAABKgAiVA5IAAhsIARAAIAABsgAjiA5IAAhsIARAAIAAAUQAEgJAGgFQAFgEAHgCIANgCIACAAIAAAPIgDAAQgHABgGACQgHACgFAFQgFAFgEAJIAABHgAklA5IAAhdIgSAAIAAgPIASAAIAAgBQAAgTAFgJQAEgKAIgDQAJgDALAAIAGAAIAGABIAAAOIgFgBIgHgBQgIABgEADQgEACgCAHQgCAHAAAMIAaAAIAAAPIgaAAIAABdgAn8A5IAAhEQAAgMgEgIQgFgGgMgBQgGAAgGACQgGABgEAFQgEAEgCAIIAABLIgSAAIAAhEQABgMgFgIQgEgGgMgBQgGAAgGACQgFABgFAEQgEAFgDAJIAABKIgRAAIAAhsIARAAIAAAPQAGgKAIgEQAIgDAKAAQANAAAHAEQAIAGAEAIQADgHAFgEQAGgEAGgBQAHgCAHAAQAMAAAIAEQAIAFAEAIQADAIAAALIAABKgArqA5IAAhEQAAgJgCgFQgBgGgFgDQgEgDgJgBQgHAAgGACQgHABgFAFQgFAFgDAKIAABIIgRAAIAAiYIARAAIAAA8QADgIAGgDQAGgEAGgBIAOgCQAOAAAIAEQAIAFADAIQAEAIgBALIAABKgAurA5IAAhsIARAAIAABsgAv2A5IgbhZIgBAAIgbBZIgWAAIgdhsIARAAIAXBaIABAAIAbhaIAVAAIAcBaIABAAIAXhaIARAAIgeBsgA03A5IAAhEQAAgMgEgIQgFgGgMgBQgGAAgGACQgGABgEAFQgEAEgCAIIAABLIgSAAIAAhEQABgMgFgIQgEgGgMgBQgGAAgGACQgFABgFAEQgEAFgDAJIAABKIgRAAIAAhsIARAAIAAAPQAGgKAIgEQAIgDAKAAQANAAAHAEQAIAGAEAIQADgHAFgEQAGgEAGgBQAHgCAHAAQAMAAAIAEQAIAFAEAIQADAIAAALIAABKgA5mA5IAAhEQAAgJgCgFQgBgGgFgDQgEgDgJgBQgHAAgGACQgHABgFAFQgFAFgDAKIAABIIgRAAIAAhsIARAAIAAAQQADgIAGgDQAGgEAGgBIAOgCQAOAAAIAEQAIAFADAIQAEAIgBALIAABKgA7jA5IAAhsIARAAIAABsgEgglAA5IAAhEQAAgJgCgFQgCgGgEgDQgFgDgIgBQgHAAgHACQgGABgFAFQgFAFgEAKIAABIIgRAAIAAiYIARAAIAAA8QAEgIAGgDQAFgEAHgBIANgCQAPAAAIAEQAHAFAEAIQADAIAAALIAABKgEgtCAA5IAAiLIATAAIAACLgEAkbgArIAFgRIAEgSIACgRIARAAQAAAHgCAJQgCAJgEAKIgHARgAXxgrIAFgRIAEgSIACgRIARAAQAAAHgCAJQgCAJgEAKIgHARgAPJhJQgDgCABgGQgBgHADgCQACgCAGAAQAFAAADACQACACAAAHQAAAGgCACQgDACgFAAQgGAAgCgCgAiVhJQgCgCAAgGQAAgHACgCQADgCAFAAQAGAAACACQADACAAAHQAAAGgDACQgCACgGAAQgFAAgDgCgAurhJQgCgCAAgGQAAgHACgCQADgCAFAAQAGAAACACQADACAAAHQAAAGgDACQgCACgGAAQgFAAgDgCgA7jhJQgCgCAAgGQAAgHACgCQADgCAFAAQAGAAACACQADACAAAHQAAAGgDACQgCACgGAAQgFAAgDgCg");
	this.shape_1.setTransform(335.875,32.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.shape}]}).to({state:[{t:this.instance_1},{t:this.shape_1}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-6,-7,661,80);
p.frameBounds = [rect, rect];


(lib.元件1复制2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.dia = new lib.元件21复制2();
	this.dia.name = "dia";
	this.dia.setTransform(213.05,64.3,1,1,0,0,0,122.4,20.9);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag9AzQgagVAAgeQAAgdAagVQAagWAjAAQAkAAAaAWQAaAVAAAdQAAAegaAVQgaAVgkAAQgjAAgagVg");
	this.shape.setTransform(8.75,7.25);

	this.instance = new lib.位图11();
	this.instance.setTransform(1,2.95,0.3621,0.3621);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape},{t:this.dia}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.元件1复制2, rect = new cjs.Rectangle(0,0,884.6,117), [rect]);


(lib.元件1复制 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.dia = new lib.元件21复制();
	this.dia.name = "dia";
	this.dia.setTransform(213.05,64.3,1,1,0,0,0,122.4,20.9);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag9AzQgagVAAgeQAAgdAagVQAagWAjAAQAkAAAaAWQAaAVAAAdQAAAegaAVQgaAVgkAAQgjAAgagVg");
	this.shape.setTransform(8.75,7.25);

	this.instance = new lib.位图11();
	this.instance.setTransform(1,2.95,0.3621,0.3621);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape},{t:this.dia}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.元件1复制, rect = new cjs.Rectangle(0,0,621.6,117), [rect]);


(lib.元件1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.dia = new lib.元件21();
	this.dia.name = "dia";
	this.dia.setTransform(213.05,64.3,1,1,0,0,0,122.4,20.9);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag9AzQgagVAAgeQAAgdAagVQAagWAjAAQAkAAAaAWQAaAVAAAdQAAAegaAVQgaAVgkAAQgjAAgagVg");
	this.shape.setTransform(8.75,7.25);

	this.instance = new lib.位图11();
	this.instance.setTransform(1,2.95,0.3621,0.3621);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape},{t:this.dia}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.元件1, rect = new cjs.Rectangle(0,0,746.6,117), [rect]);


// stage content:
(lib.index = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		
		var _this = this;
		
		_this.pgId;
		_this.diaAry;
		_this.diaMcAry;
		_this.data;
		_this.curId = 0;
		_this.curPgDia; //存储当前页的所有对话mc
		_this.clickMode = false;
		_this.canClick = false;
		_this.start = false;
		_this.isEnded = false;
		//点击单词声音
		_this.audio;
		
		if (!this.isinit) {
			//console.log("第一次进入")
			this.isinit = true;
			init();
		}
		
		/*function playSoundBySrc(src) {
			audio.currentTime = 0;
			audio.pause();
			audio.src = src;
			console.log(audio.src);
			audio.play();
			_this.isEnded = false;
			_this._onp.setStu(false);
		}*/
		function playSoundBySrc(src) {
		    // 如果新源与当前源相同，不必重新设置
		    if (audio.src !== src) {
		        audio.pause(); // 暂停当前音频
		        audio.src = src; // 设置新音频源
		        audio.currentTime = 0; // 重置播放时间
		        
		        // 确保音频加载完成后再播放
		        audio.oncanplaythrough = function() {
		            audio.play().catch(function(error) {
		                console.error("播放错误:", error);
		            });
		            _this.isEnded = false;
		            _this._onp.setStu(false);
		            audio.oncanplaythrough = null; // 清除事件监听器
		        };
		        
		        // 触发加载
		        audio.load();
		    } else {
		        audio.currentTime = 0; // 如果源相同，重置播放时间并播放
		        audio.play().catch(function(error) {
		            console.error("播放错误:", error);
		        });
		        _this.isEnded = false;
		        _this._onp.setStu(false);
		    }
		}
		
		
		function init() {
			_this.pgId = 0;
			_this.diaAry = [2, 2, 2];
			_this.data = lesdata;
			hideDia();
		
			audio = new Audio();
			audio.addEventListener('play', function () {
				//console.log('被点击的单词开始播放');
			});
			audio.addEventListener('ended', function () {
				//播放结束事件。
				//console.log("播放结束。");
				_this.isEnded = true;
				resetDia();
				if (_this.clickMode) {
					_this._onp.setStu(true);
					//_this.clickMode=false;
					return;
				} //点读模式
				nextFun();
			});
		
		    //隐藏播放和清除按钮
		    _this._onp.visible=false;
		}
		
		_this.gotoPage = function (_pg) {
			if (_this.pgId == _pg && _this.start == true) {
				return;
			}
			//reset();
			_this.isEnded = true;
			_this.start = true;
			_this.pgId = _pg;
			_this.curId = 0;
			if(audio)audio.pause();
			_this.canClick = false;
			_this.clickMode = false;
			_this.gotoAndStop(_this.pgId);
			hideDia();
			updata();
		
			//reset();
			//console.log(_this.diaMcAry);
			//setTimeout(reset,1000);
		}
		
		function hideDia() {
			_this.curPgDia = [];
			//for(var i=1;i<=_this.diaAry[_this.pgId];i++){
			//console.log("##############################");
			//console.log(_this.data);
		    //console.log(_this.data[_this.pgId]);
			console.log(_this.data);
			for (var i = 1; i <= _this.data[_this.pgId].length; i++) {
				_this["dia_" + (parseInt(_this.pgId) + 1) + "_" + i].visible = false;
				_this["dia_" + (parseInt(_this.pgId) + 1) + "_" + i]["dia"].addEventListener("click", ondiamc);
				_this.curPgDia.push(_this["dia_" + (parseInt(_this.pgId) + 1) + "_" + i]);
				console.log("dia_" + (parseInt(_this.pgId) + 1) + "_" + i);
			}
		}
		function resetDia() {
			for (var v of _this.curPgDia) {
				v.dia.gotoAndStop(0);
			}
		}
		function updata() {
			_this.curPgDia[_this.curId].visible = true;
			_this._onp.visible=true;
			resetDia();
			_this.curPgDia[_this.curId].dia.gotoAndStop(1);
			playSoundBySrc(_this.data[_this.pgId][_this.curId].soundPath);
		}
		function nextFun() {
			//
			/*console.log("下一个");
			console.log(_this.curId);
			console.log(_this.curPgDia.length-1);*/
			if (_this.curId < _this.curPgDia.length - 1) {
				_this.curId += 1;
				updata();
			} else {
				_this.canClick = true;
				_this._onp.setStu(true);
				return;
			}
		}
		function prevFun() {
			//
			_this.curId += 1;
		}
		
		
		function ondiamc(e) {
			if (!_this.canClick) {
				return
			}
			_this.clickMode = true;
			for (var item of _this.curPgDia) {
				item.gotoAndStop(0);
			}
			e.currentTarget.gotoAndStop(1);
			const lastChar = e.currentTarget.parent.name.slice(-1);
			_this.curId = Number(lastChar) - 1; // 将 lastChar 转为数字并减去 1
			console.log(_this.curId);
			//点击对话框
			updata();
		}
		
		//子机控制父级
		_this.onPause = function () {
			if (!audio.paused && !audio.ended) {
				audio.pause();
			}
		};
		
		_this.onPlay = function () {
			//if (audio.paused || audio.ended) {
			if (_this.canClick && _this.isEnded) {
				_this.curId = 0;
				_this.clickMode = false;
				_this.canClick = false;
				hideDia();
				updata();
				return;
			} else if (audio.paused) {
				audio.play();
			}
		};
		_this.onClear = function () {
			if (!audio.paused && !audio.ended) {
				audio.pause();
			}
			_this.curId = 0;
			_this.clickMode = false;
			_this.canClick = true;
			_this.isEnded = true;
			hideDia();
			_this._onp.setStu(true);
			//updata();
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(3));

	// 跳转按钮
	this._onp = new lib.KING_1_12_80080();
	this._onp.name = "_onp";
	this._onp.setTransform(943.55,641.9,1,1,0,0,0,37.5,20.4);

	this.gotoBtnMc = new lib.KING_1_4_12929();
	this.gotoBtnMc.name = "gotoBtnMc";
	this.gotoBtnMc.setTransform(658.4,203.55,1,1,0,0,0,153.1,153.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.gotoBtnMc},{t:this._onp}]}).wait(3));

	// 标题
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AgSAbQgGgCgCgGQgCgHAAgMQAAgMACgGQACgGAGgDQAHgCALABQAMgBAHACQAGADACAGQACAGAAAMQAAAMgCAHQgCAGgGACQgHACgMAAQgLAAgHgCg");
	this.shape.setTransform(460.65,57.52);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231F20").s().p("AhGBRQAPAAAJgDQAJgDAGgGQAFgGACgIIhFiwIA1AAIApB+IACAAIAoh+IAzAAIg8CgQgIAZgJAPQgJARgLAIQgMAKgQAEQgQAEgXAAg");
	this.shape_1.setTransform(445.625,54.65);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#231F20").s().p("AgUBbQgYAAgQgMQgRgNgJgYQgDgJgCgLIgBgVIAAgHQABgYAJgTQAKgSAUgOQAIgFAIgDQAJgBAJAAIAIAAQARAAAKAEQAMAGAFAKIABABIAAABIABAAIABgFIABgBIAtAAIABAAIAAABIgCA6QAAAmADAYQACAYAFALIAAACIABAFIgBABIgtAAIgEgHIgFgSIgBAAQgHANgKAHQgLAGgPAAgAgdgtQgMAKgGAVIgCAKIAAAGQAAAUAHANQAHANANAFIAKACIAKABQAMABAJgFQAJgEAEgKQAEgGACgLQABgJAAgNQAAgSgFgNQgEgMgJgGQgEgDgFgBQgHgBgGAAIgBAAQgQAAgLAKg");
	this.shape_2.setTransform(425.25,51.25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#231F20").s().p("AgHBcQgPAAgPgCIgbgEIAAgoQAOAEAOACQAOACAMAAQAPABAHgEQAHgEAAgKQAAgIgDgEQgCgEgIgDQgGgDgOgDQgTgFgLgGQgJgFgFgJQgEgKAAgPQAAgZAQgOQARgOAmAAQAPAAANACQANACAIACIgCAlIgNgDIgQgDIgQgBQgQAAgGAEQgGAEAAAJQAAAFADADQACADAIADIATAGQAUAFAKAGQALAGAEAKQAEAKABAQQAAAfgUANQgSANgfAAIgDAAg");
	this.shape_3.setTransform(407.6,51.2759);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#231F20").s().p("Ag6B0QgQgMgGgUQgGgVABgcQgBgaAGgUQAGgVAQgMQAPgNAdAAQAXAAAMAHQANAHAFAMIAAhfIAvAAIAAD6IgrAAIgEgZQgFAMgMAIQgNAIgXAAQgdAAgPgLgAgXgNQgIAIgDALQgCANAAAQQAAAQACANQADAMAIAHQAIAIAPAAQAQAAAJgHQAJgGAEgNQADgMAAgSQAAgRgEgNQgDgMgJgHQgJgHgQAAQgPAAgIAIg");
	this.shape_4.setTransform(379.9731,47.875);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#231F20").s().p("AAiBbIAAhsQAAgSgGgIQgGgIgSAAQgNAAgKAGQgKAFgEAOIAAB1IgvAAIAAixIAvAAIAAAVQAIgNAPgGQANgGATAAQAWAAANAHQANAHAGANQAFANABAUIAAB5g");
	this.shape_5.setTransform(359.4,51.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#231F20").s().p("AgUBbQgYAAgQgMQgRgNgJgYQgDgJgCgLIgBgVIAAgHQAAgYAKgTQAKgSAUgOQAIgFAJgDQAIgBAJAAIAIAAQARAAALAEQAKAGAGAKIABABIABABIAAAAIABgFIABgBIAtAAIABAAIAAABIgCA6QAAAmACAYQADAYAFALIAAACIABAFIgBABIgtAAIgEgHIgFgSIgBAAQgHANgKAHQgLAGgPAAgAgdgtQgMAKgGAVIgCAKIAAAGQAAAUAHANQAHANANAFIAKACIAKABQANABAIgFQAJgEAEgKQADgGADgLQABgJAAgNQAAgSgFgNQgEgMgJgGQgEgDgFgBQgHgBgGAAIgBAAQgQAAgLAKg");
	this.shape_6.setTransform(338.05,51.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#231F20").s().p("AgpBVQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQAUgJAbABQAeAAARAKQARAKAGARQAGASAAAXIgBANIgBALIhyAHQACATALAJQAMAJAXAAQALAAALgCQAMgCAJgDQAKgCAGgEIAAAmQgJAFgSAEQgSADgYAAIgDAAQgYAAgSgHgAgYgtQgJAJgBAWIBIgGQABgKgDgIQgCgIgHgEQgHgFgOAAQgVAAgJAKg");
	this.shape_7.setTransform(310.3018,51.3251);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#231F20").s().p("AgHBcQgPAAgPgCIgagEIAAgoQAMAEAPACQAOACANAAQANABAIgEQAHgEAAgKQAAgIgCgEQgEgEgGgDQgHgDgPgDQgSgFgLgGQgKgFgEgJQgDgKgBgPQAAgZARgOQAQgOAmAAQAPAAANACQANACAHACIgCAlIgMgDIgQgDIgRgBQgPAAgFAEQgHAEAAAJQAAAFACADQADADAHADIAVAGQASAFALAGQALAGAFAKQADAKAAAQQABAfgUANQgSANgfAAIgDAAg");
	this.shape_8.setTransform(292.55,51.2759);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#231F20").s().p("AAABcQgbABgTgIQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQATgJAbABQAcgBATAJQAUAIAKAUQAKAUAAAjQAAAkgKAUQgKAVgUAIQgSAHgaAAIgDAAgAgWgzQgIAGgEAMQgDANAAAUQAAAWADAMQAEAMAIAFQAJAFANAAQAPAAAIgFQAIgFAEgMQADgMAAgWQAAgUgDgNQgEgMgIgGQgJgFgOAAQgOAAgIAFg");
	this.shape_9.setTransform(274.225,51.3251);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#231F20").s().p("AAABcQgbABgTgIQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQATgJAbABQAcgBATAJQAUAIAKAUQAKAUAAAjQAAAkgKAUQgKAVgUAIQgSAHgaAAIgDAAgAgWgzQgIAGgEAMQgDANAAAUQAAAWADAMQAEAMAIAFQAJAFANAAQAPAAAIgFQAIgFAEgMQADgMAAgWQAAgUgDgNQgEgMgIgGQgJgFgOAAQgOAAgIAFg");
	this.shape_10.setTransform(253.775,51.3251);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#231F20").s().p("AAhB9IAAhtQAAgRgFgIQgHgIgQABQgPgBgJAGQgKAGgDANIAAB1IgxAAIAAj5IAxAAIAABeQAHgNAOgGQAOgGATAAQAWAAANAHQANAGAGAOQAGANAAASIAAB6g");
	this.shape_11.setTransform(233.1,47.725);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#231F20").s().p("AgaBVQgUgIgKgVQgLgUAAgkQAAgjALgUQAKgUAUgIQATgJAbABQAOAAAMABQAMACAIACIAAApQgJgEgKgBQgJgCgMAAQgPAAgKAEQgJAFgFAMQgFAMAAATQAAAVAFALQAFAMAJAEQAKAFAQAAIAVgCQAKgBAKgEIAAAoIgNADIgRADIgSAAIgDAAQgZAAgSgHg");
	this.shape_12.setTransform(214.375,51.3251);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#231F20").s().p("AglAxQAIgOAHgRQAGgSAEgQQAFgRAAgPIAtAAQAAALgEANQgDANgFANIgMAaQgHAMgGAJg");
	this.shape_13.setTransform(191.475,59.85);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#231F20").s().p("AAhBbIAAhsQABgSgGgIQgGgIgRAAQgPAAgJAGQgKAFgDAOIAAB1IgxAAIAAixIAxAAIAAAVQAHgNAOgGQAOgGAUAAQAVAAANAHQANAHAGANQAGANgBAUIAAB5g");
	this.shape_14.setTransform(176.3,51.175);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#231F20").s().p("AgpBVQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQAUgJAbABQAeAAARAKQARAKAGARQAGASAAAXIgBANIgBALIhyAHQACATALAJQAMAJAXAAQALAAALgCQAMgCAJgDQAKgCAGgEIAAAmQgJAFgSAEQgSADgYAAIgDAAQgYAAgSgHgAgYgtQgJAJgBAWIBIgGQABgKgDgIQgCgIgHgEQgHgFgOAAQgVAAgJAKg");
	this.shape_15.setTransform(156.1018,51.3251);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#231F20").s().p("AgFBqQgNgFgGgNQgGgNAAgXIAAhSIgXAAIAAgmIAXAAIAAgqIAvAAIAAAqIAlAAIAAAmIglAAIAABOQAAAPAEAGQAFAFAMAAIAHAAIAGgBIAAAlIgLABIgLAAIgEAAQgTAAgLgFg");
	this.shape_16.setTransform(140.5,49.3271);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#231F20").s().p("AgHBcQgPAAgPgCIgagEIAAgoQAMAEAPACQAOACANAAQANABAIgEQAHgEAAgKQAAgIgDgEQgDgEgGgDQgHgDgPgDQgSgFgLgGQgKgFgEgJQgDgKgBgPQAAgZAQgOQARgOAmAAQAPAAANACQANACAIACIgDAlIgMgDIgQgDIgRgBQgPAAgFAEQgHAEAAAJQAAAFACADQADADAIADIAUAGQASAFALAGQALAGAFAKQADAKAAAQQABAfgUANQgSANgfAAIgDAAg");
	this.shape_17.setTransform(126.6,51.2759);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#231F20").s().p("AgXB/IAAixIAvAAIAACxgAgPhNQgGgBgDgGQgCgFAAgMQAAgLACgFQADgFAGgCQAFgCAKABQALgBAGACQAFACADAFQACAFAAALQAAAMgCAFQgDAGgFABQgGACgLAAQgKAAgFgCg");
	this.shape_18.setTransform(113.775,47.595);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#231F20").s().p("AhGByIAAjkIAzAAIAAC5IBaAAIAAArg");
	this.shape_19.setTransform(101.3,48.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgXCXQgbgHgUgRQgTgSgKgfQgLgeAAgwQAAg5ATgjQARgjAhgOQAhgPAsAAQAWAAASADQASACAOAFIAAA6QgPgFgQgDQgRgDgTAAQgcAAgQAJQgSAKgIAWQgIAVAAAlQAAAnAIAWQAIAVASAJQAQAIAbAAQASAAASgDQASgDARgGIAAA5QgNAGgUAEQgTADgWAAQgiAAgagGg");
	this.shape_20.setTransform(45.95,48.525);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#0D8075").s().p("AirCsQhHhHAAhlQAAhkBHhIQBHhGBkAAQBlAABHBGQBHBIAABkQAABlhHBHQhHBHhlAAQhkAAhHhHg");
	this.shape_21.setTransform(46.725,47.675);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(3));

	// 对话内容
	this.dia_1_1 = new lib.元件1();
	this.dia_1_1.name = "dia_1_1";
	this.dia_1_1.setTransform(529.65,501.8,1,1,0,0,0,367.7,58.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f().s("#FE8659").ss(8,1,1).p("EhPHAJCIAO3AQAHiYBghvQBph3CUAAMCS7AAAQCUAABpB3QBjBxAGCdQAAACAAABQAAADAAADIgHIRIgBAKIgHPbIAAAYEBPFgFdIAAAKEBO9AKIIAAAYIgCDFQAACphoB3QhpB4iVAAMiS6AAAQiVAAhph4Qhoh3AAipIAEkZIAAgKEhPIAJWIABgU");
	this.shape_22.setTransform(640,550.725);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("EhJlAT9QiVAAhoh4Qhph3AAipIAFkZIgBgKIAO3AQAHiYBghvQBph3CVAAMCS6AAAQCUAABpB3QBiBxAGCdIAAADIAAAGIgGIRIgBAKIABgKIgBAKIAAAAIgHPbIAAAYIAAgYIABAAIgBAYIgCDFQAACphoB3QhpB4iUAAgEhPHAJCIABAKIgCAKgEhPGAJMg");
	this.shape_23.setTransform(640,550.725);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f().s("#FCE0CE").ss(18,1,1).p("EhPHAJCIAO3AQAHiYBghvQBph3CUAAMCS7AAAQCUAABpB3QBjBxAGCdQAAACAAABQAAADAAADIgHIRIAAAKEBPFgFdIgBAKIgHPbIAAAYIgCDFQAACphoB3QhpB4iVAAMiS6AAAQiVAAhph4Qhoh3AAipIAEkZIAAgKEBO9AKIIAAAYEhPIAJWIABgU");
	this.shape_24.setTransform(640,550.725);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("EhJlAT9QiVAAhoh4Qhph3AAipIAFkZIgBgKIAO3AQAHiYBghvQBph3CVAAMCS6AAAQCUAABpB3QBiBxAGCdIAAADIAAAGIgGIRIgBAKIgHPbIAAAYIgCDFQAACphoB3QhpB4iUAAgEBO9AKggEBO9AKIIABAAIgBAYgEhPHAJCIABAKIgCAKgEBPEgFTIABgKIgBAKgEBPFgFdg");
	this.shape_25.setTransform(640,550.725);

	this.dia_2_1 = new lib.元件1复制();
	this.dia_2_1.name = "dia_2_1";
	this.dia_2_1.setTransform(529.65,501.8,1,1,0,0,0,367.7,58.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("#FE8659").ss(8,1,1).p("EhPHAJCIAO3AQAHiYBghvQBph3CUAAMCS7AAAQCUAABpB3QBjBxAGCdQAAACAAABQAAADAAADIgHIRIAAAKEBPFgFdIgBAKIgHPbIAAAYIgCDFQAACphoB3QhpB4iVAAMiS6AAAQiVAAhph4Qhoh3AAipIAEkZIAAgKEBO9AKIIAAAYEhPIAJWIABgU");
	this.shape_26.setTransform(640,550.725);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f().s("#FCE0CE").ss(18,1,1).p("EhPHAJCIAO3AQAHiYBghvQBph3CUAAMCS7AAAQCUAABpB3QBjBxAGCdQAAACAAABQAAADAAADIgHIRIgBAKIgHPbIAAAYEBPFgFdIAAAKEBO9AKIIAAAYIgCDFQAACphoB3QhpB4iVAAMiS6AAAQiVAAhph4Qhoh3AAipIAEkZIAAgKEhPIAJWIABgU");
	this.shape_27.setTransform(640,550.725);

	this.dia_3_1 = new lib.元件1复制2();
	this.dia_3_1.name = "dia_3_1";
	this.dia_3_1.setTransform(529.65,501.8,1,1,0,0,0,367.7,58.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.dia_1_1}]}).to({state:[{t:this.shape_23},{t:this.shape_27},{t:this.shape_25},{t:this.shape_26},{t:this.dia_2_1}]},1).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.dia_3_1}]},1).wait(1));

	// 图
	this.instance = new lib.元件2("single",2);
	this.instance.setTransform(992.35,267,1.0157,1.0157,0,0,0,294.6,223.6);

	this.instance_1 = new lib.元件2("single",1);
	this.instance_1.setTransform(644.7,267,1.0157,1.0157,0,0,0,294.5,223.6);

	this.instance_2 = new lib.元件2("single",0);
	this.instance_2.setTransform(297.05,267,1.0157,1.0157,0,0,0,294.4,223.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(3));

	// diban
	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("rgba(255,255,255,0.8)").s().p("EhkVAEsIAApXMDIrAAAIAAJXg");
	this.shape_28.setTransform(639.9,690.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_28).wait(3));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = rect = new cjs.Rectangle(637.7,369.5,1302.6,710.9);
p.frameBounds = [rect, rect, rect];
// library properties:
lib.properties = {
	id: 'E637B31863A9224E9952B4D82164A654',
	width: 1280,
	height: 720,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/index_atlas_1.png", id:"index_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['E637B31863A9224E9952B4D82164A654'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;