(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
var rect; // used to reference frame bounds
lib.ssMetadata = [
		{name:"index_atlas_1", frames: [[0,0,1446,527],[1448,0,242,327]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.位图5 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.位图61 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.元件32复制2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EAv6AE3IAAAAMhgaAAAQh0AAgEhxIAAhSQhYgjhHhRQgtgxgnhEIAZAKQCDAyBXAAIAAiFQAAh4B4AAMBkvAAAIAAABIAEAAQB5AAAAB4IAAGDQgDA5geAcQgeAcg6AAg");
	this.shape.setTransform(346.75,31.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.元件32复制2, rect = new cjs.Rectangle(0,0,693.5,62.2), [rect]);


(lib.元件32复制 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AaWE3IAAAAMg1SAAAQh0AAgEhxIAAhSQhYgjhHhRQgtgxgnhEIAZAKQCDAyBXAAIAAiFQAAh4B4AAMA1/AAAIAAABIDtAAQB3AAABB4IAAGDQgCA5gfAcQgeAcg5AAg");
	this.shape.setTransform(208.75,31.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.元件32复制, rect = new cjs.Rectangle(0,0,417.5,62.2), [rect]);


(lib.元件23 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AzmDrIAAnVMAnNAAAIAAHVg");
	this.shape.setTransform(125.475,22.5);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = null;
p.frameBounds = [rect, rect, rect, new cjs.Rectangle(0,-1,251,47)];


(lib.元件20复制 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AAAAAIAAAAIAAABg");
	this.shape.setTransform(54.375,76.7125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.149)").s().p("AkPIXQgOgKgPgQQgogrgEhXQgDhWAHhDIAKhgQAMiTgChsIAAgKIAAAAIgEhrQgChIADgwQAFhWAigvQAhguA1AAIAUABQAeAUA5AQQAdAIAYAEQAWAEAQAAIAKAAIASAAQA8gBA/gRIAEgCQAPgFASgFQBYggAWAaQAPAJAKAYQAQAoADBEQACAlgDBRIgFB4IgBAAIAAAPQgFBagBAwQgCBDALCTQAFBCAAA0IAAAFIABAEQAKB8gsAmIgJAHQgKAIgNACQgxALgmgHIg3gKIgggHQgIgCgFgDIgjgDQAFgSAAgWIAAgHQgCgngQgcQgMgVgQgGQgHgCgHAAQgXAAgSAfQgRAfAAArQAAASADAQIAAABQglgBglARIgEACQg9AUgnAAQgYAAgPgHg");
	this.shape_1.setTransform(48.7877,25.8532);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFAED").s().p("AkPIXQgOgKgPgQQgogrgEhXQgDhWAHhDIAKhgQAMiTgChsIAAgKIAAAAIgEhrQgChIADgwQAFhWAigvQAhguA1AAIAUABQAeAUA5AQQA4AQAjAAIBTAAQAeABAZgNQAagNAmgIQAmgIARgCQAQgCAQAEQAWAHAMAfQAQAoADBEQACAlgDBRIgFB4IgBAAIAAAPQgFBagBAwQgCBDALCTQAFBCAAA0IAAAFIABAEQAKB8gsAmIgJAHQgKAIgNACQgxALgmgHIg3gKIgggHQgIgCgFgDIgjgDQAFgSAAgWIAAgHQgCgngQgcQgMgVgQgGQgHgCgHAAQgXAAgSAfQgRAfAAArQAAASADAQIAAABQglgBglARIgEACQg9AUgnAAQgYAAgPgHg");
	this.shape_2.setTransform(48.7877,25.8532);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_2}]},4).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = null;
p.frameBounds = [rect, rect=new cjs.Rectangle(14.3,-28.3,69.1,108.5), rect, rect, rect, rect, rect];


(lib.元件18 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#F99703").ss(0.5,1,1).p("AgMgKIAZAAQAFAAADADQADADAAAEIAAAAQAAAFgDADQgDADgFAAIgZAAQgFAAgDgDQgDgDAAgFIAAAAQAAgEADgDQADgDAFAAg");
	this.shape.setTransform(20.2868,10.9643,0.7179,0.7184,-1.0078);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F99703").s().p("AgMALQgFAAgDgDQgDgDAAgFIAAAAQAAgEADgDQADgDAFAAIAZAAQAFAAADADQADADAAAEIAAAAQAAAFgDADQgDADgFAAg");
	this.shape_1.setTransform(20.2868,10.9643,0.7179,0.7184,-1.0078);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAACsQgKABgIgJQgIgHAAgLIAAkjQAAgLAIgIQAIgHAKAAIAAAAQALAAAIAHQAIAIAAALIAAEjQAAALgIAHQgIAJgLgBg");
	this.shape_2.setTransform(22.5995,22.3228,0.3437,0.2691);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAACsQgKABgIgJQgIgHAAgLIAAkjQAAgLAIgIQAIgHAKAAIAAAAQALAAAIAHQAIAIAAALIAAEjQAAALgIAHQgIAJgLgBg");
	this.shape_3.setTransform(18.0495,22.3228,0.3437,0.2691);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F99703").s().p("Ai9BQQghAAgXgYQgYgXAAghQAAggAYgYQAXgXAhAAIF7AAQAhAAAYAXQAXAYAAAgQAAAhgXAXQgYAYghAAg");
	this.shape_4.setTransform(20.1713,14.1731,0.3437,0.344,-0.2288);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F99703").s().p("Ag2BgQglAAAAglIgNiYIgBgBIABgBIDQAAIACACIAAAAIgSCYQAAAlgmAAg");
	this.shape_5.setTransform(20.4003,23.3432,0.718,0.7184);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#F99703").ss(3,1,1).p("AiQCQQg8g7AAhVQAAhUA8g8QA8g8BUAAQBUAAA8A8QAJAIAHAJQADAEAEAFQAmA0AABCQAABVg9A7Qg8A9hUAAQhUAAg8g9g");
	this.shape_6.setTransform(20.475,20.475);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AiQCQQg8g7AAhVQAAhUA8g8QA8g8BUAAQBUAAA8A8IAQARIAHAJQAmA0AABCQAABVg9A7Qg8A9hUAAQhUAAg8g9g");
	this.shape_7.setTransform(20.475,20.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-1.5,-1.5,44,44);
p.frameBounds = [rect, rect];


(lib.元件17 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#F69602").ss(6,1,1).p("ABChxIAADjAhBhxIAADj");
	this.shape.setTransform(20.4957,20.4917,0.7181,0.7185);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#F69602").ss(3,1,1).p("AjJDIQhThSAAh2QAAh1BThUQBUhTB1AAQB2AABTBTQBUBUAAB1QAAB2hUBSQhTBVh2AAQh1AAhUhVg");
	this.shape_1.setTransform(20.4598,20.4917,0.7181,0.7185);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AjJDIQhThSAAh2QAAh1BThUQBUhTB1AAQB2AABTBTQBUBUAAB1QAAB2hUBSQhTBVh2AAQh1AAhUhVg");
	this.shape_2.setTransform(20.4598,20.4917,0.7181,0.7185);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-1.5,-1.5,44,44);
p.frameBounds = [rect, rect];


(lib.元件10 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F99703").s().p("Ah9CPQgHgHgBgIIgBj7QABgIAEgHIAEgEQAIgIAMAAQAFAAAFACIDcB/IABACQAFAEACAFQACAFAAAFQAAAGgCAEQgCAFgFAEIgEAFIjZB9QgFACgFAAQgMAAgIgIg");
	this.shape.setTransform(23.281,20.4775,0.684,0.6844);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#F99703").ss(3,1,1).p("AiKCKQg6g5AAhRQAAhQA6g6QA6g5BQAAQBRAAA6A5QA6A6AABQQAABRg6A5Qg6A6hRAAQhQAAg6g6g");
	this.shape_1.setTransform(20.4871,20.4731,1.0426,1.0432);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AiKCKQg5g5gBhRQABhQA5g6QA5g5BRAAQBRAAA5A5QA7A6AABQQAABRg7A5Qg5A6hRAAQhRAAg5g6g");
	this.shape_2.setTransform(20.4871,20.4731,1.0426,1.0432);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-1.5,-1.5,44,44);
p.frameBounds = [rect, rect];


(lib.暂停播放组 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.isSingleFrame = false;
	// timeline functions:
	this.frame_0 = function() {
		if(this.isSingleFrame) {
			return;
		}
		if(this.totalFrames == 1) {
			this.isSingleFrame = true;
		}
		var _this = this;
		_this.stop();
		// 初始化状态
		function init(showPlay) {
		    _this.b_play.visible = showPlay;  // 根据参数控制播放按钮的显示
		    _this.b_pause.visible = !showPlay; // 根据参数控制暂停按钮的显示
		}
		_this.setStu=function(showPlay){
		    _this.b_play.visible = showPlay;  // 根据参数控制播放按钮的显示
		    _this.b_pause.visible = !showPlay; // 根据参数控制暂停按钮的显示
		}
		
		// 事件监听
		this.b_play.addEventListener("click", () => fl_MouseClickHandler_3(true));
		this.b_pause.addEventListener("click", () => fl_MouseClickHandler_3(false));
		
		function fl_MouseClickHandler_3(isPlay) { 
		    if (isPlay) {
		        _this.parent.onPlay();
		        _this.b_play.visible = false; 
		        _this.b_pause.visible = true;  
		    } else {
		        _this.parent.onPause();
		        _this.b_play.visible = true; 
		        _this.b_pause.visible = false;  
		    }
		    //_this.parent.isPlaying = !_this.parent.isPlaying; // 切换播放状态
		}
		
		// 调用初始化方法，初始状态为播放按钮显示
		init(true);
		
		
		this.b_clear.addEventListener("click", fl_MouseClickHandler_4.bind(this));
		
		function fl_MouseClickHandler_4()
		{
			_this.parent.onClear();
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// 图层_1
	this.b_clear = new lib.元件18();
	this.b_clear.name = "b_clear";
	this.b_clear.setTransform(76.2,20.4,1,1,0,0,0,20.4,20.4);
	new cjs.ButtonHelper(this.b_clear, 0, 1, 1);

	this.b_pause = new lib.元件17();
	this.b_pause.name = "b_pause";
	this.b_pause.setTransform(20.4,20.4,1,1,0,0,0,20.4,20.4);
	new cjs.ButtonHelper(this.b_pause, 0, 1, 1);

	this.b_play = new lib.元件10();
	this.b_play.name = "b_play";
	this.b_play.setTransform(20.4,20.4,1,1,0,0,0,20.4,20.4);
	new cjs.ButtonHelper(this.b_play, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.b_play},{t:this.b_pause},{t:this.b_clear}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.暂停播放组, rect = new cjs.Rectangle(-1.5,-1.5,99.8,44), [rect]);


(lib.元件21复制2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));

	// 图层_3
	this.instance = new lib.元件23();
	this.instance.setTransform(363.3,29.8,2.6051,1.0226,0,0,0,125.5,23.6);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.元件23(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EAnOABgIgMgCIAAgOIANACIAOAAQASAAAJgIQAIgJAAgSIAAgLQgDAKgIAFQgIAFgQAAQgSABgKgIQgKgGgDgNQgEgMAAgRQAAgPAEgMQADgMAKgIQAKgHASAAQALAAAHACQAHAEAEAEQAEAFACAHIAAgVIASAAIAABlQAAAWgNANQgNANgcAAIgOgBgEAnMgAhQgGAGgCAJQgCAKAAAJQAAAMACAIQACAKAHAGQAGAFAMAAQANAAAIgFQAHgEADgKQADgJAAgNQAAgLgDgKQgDgJgHgFQgIgFgNAAQgMAAgHAGgAbJBgIgMgCIAAgOIANACIAOAAQASAAAJgIQAIgJAAgSIAAgLQgDAKgIAFQgIAFgQAAQgSABgKgIQgKgGgDgNQgEgMAAgRQAAgPAEgMQADgMAKgIQAKgHASAAQALAAAHACQAHAEAEAEQAEAFACAHIAAgVIASAAIAABlQAAAWgNANQgNANgcAAIgOgBgAbHghQgGAGgCAJQgCAKAAAJQAAAMACAIQACAKAHAGQAGAFAMAAQANAAAIgFQAHgEADgKQADgJAAgNQAAgLgDgKQgDgJgHgFQgIgFgNAAQgMAAgHAGgAWQBSQAJAAAGgDQAGgCAEgGQAEgGADgJIgshsIATAAIAhBaIACAAIAfhaIASAAIgnBpQgFAOgGAJQgGALgKAEQgJAGgQAAgARfBhIAAiVIARAAIAAAUQAEgKAIgGQAIgFAQAAQASgBAKAIQAKAHADANQAEAMAAAQQAAAQgEAMQgDANgKAHQgKAIgSAAQgQABgIgGQgIgGgEgJIAAA7gAR9giQgHAFgDAKQgDAJAAAMQAAAMADAKQADAKAHAEQAIAFANABQAMgBAHgFQAGgGACgKQACgJAAgLQAAgKgCgKQgCgJgHgGQgGgGgMAAQgNAAgIAFgAifBgIgMgCIAAgOIANACIANAAQASAAAJgIQAJgJAAgSIAAgLQgDAKgJAFQgIAFgPAAQgSABgKgIQgKgGgEgNQgEgMAAgRQAAgPAEgMQAEgMAKgIQAKgHASAAQAKAAAIACQAHAEAEAEQAEAFACAHIAAgVIARAAIAABlQAAAWgNANQgMANgcAAIgOgBgAihghQgGAGgCAJQgCAKAAAJQAAAMACAIQACAKAGAGQAGAFANAAQANAAAHgFQAIgEADgKQADgJgBgNQABgLgDgKQgDgJgIgFQgHgFgNAAQgNAAgGAGgEgksABhIAAiVIARAAIAAAUQAEgKAIgGQAIgFAQAAQASgBAKAIQAKAHADANQAEAMAAAQQAAAQgEAMQgDANgKAHQgKAIgSAAQgQABgIgGQgIgGgEgJIAAA7gEgkOgAiQgHAFgDAKQgDAJAAAMQAAAMADAKQADAKAHAEQAIAFANABQAMgBAHgFQAGgGACgKQACgJAAgLQAAgKgCgKQgCgJgHgGQgGgGgMAAQgNAAgIAFgEAuPAA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIIABAQIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgEAuXgAjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgEAsKAA0QgKgIgEgNQgEgNAAgQQAAgOAEgNQAEgMAKgIQAJgJASABQAQgBAIAGQAJAGADAJIAAg/IARAAIAACYIgOAAIgDgSQgDAKgJAFQgJAGgPgBQgSAAgJgGgEAsVgAhQgGAGgCAKQgCAJAAAKQAAALACAKQACAKAGAFQAGAFANABQANgBAHgEQAIgGADgIQADgKgBgNQABgLgDgKQgDgKgIgFQgHgFgNAAQgNAAgGAGgEApYAA6QgRABgLgJQgKgJgGgQIgBgJIgBgIIAAgGQAAgQAHgNQAHgMAOgJIALgEIAKgBIACAAQASAAANATIAAgFIARAAIAAA6IABATIADATIgBAAIgQAAQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAgBAAgBIgCgNIgDAGIgFAEQgFAFgGABQgGACgHAAgEApLgAgQgJAHgFALIgCAIIgBAIIAAAFQAAAKAFAJQAEAIAIAGIAHAEIAHAAIAEAAQAfAAAAgmIAAgGQAAgQgFgJQgGgJgLgDIgDAAIgDgBQgNAAgIAGgEAkeAA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgEAklgAjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgAU6A6QgQABgLgJQgLgJgFgQIgCgJIAAgIIAAgGQAAgQAHgNQAGgMAOgJIALgEIAKgBIACAAQATAAAMATIAAgFIASAAIAAA6IABATIACATIgBAAIgQAAQAAAAAAAAQgBAAAAgBQAAAAAAgBQgBgBAAgBIgBgNIgEAGIgEAEQgFAFgGABQgGACgHAAgAUtggQgIAHgFALIgCAIIgBAIIAAAFQAAAKAEAJQAEAIAIAGIAHAEIAIAAIAEAAQAfAAAAgmIAAgGQAAgQgGgJQgFgJgLgDIgEAAIgDgBQgMAAgJAGgAPHA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAPOgjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgAEhA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAEogjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgACbA0QgKgIgDgNQgEgNAAgQQAAgOAEgNQADgMAKgIQAKgJASABQAQgBAIAGQAIAGADAJIAAg/IASAAIAACYIgPAAIgDgSQgDAKgJAFQgIAGgPgBQgSAAgKgGgACmghQgGAGgCAKQgCAJAAAKQAAALACAKQACAKAHAFQAGAFAMABQANgBAIgEQAHgGADgIQADgKAAgNQAAgLgDgKQgDgKgHgFQgIgFgNAAQgMAAgHAGgAgWA6QgQABgLgJQgLgJgFgQIgCgJIAAgIIAAgGQAAgQAHgNQAGgMAOgJIALgEIAKgBIACAAQASAAAMATIAAgFIASAAIAAA6IABATIACATIgBAAIgQAAQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAgBgBgBIgBgNIgEAGIgEAEQgFAFgFABQgGACgHAAgAgjggQgIAHgFALIgCAIIgBAIIAAAFQAAAKAEAJQAEAIAIAGIAHAEIAIAAIAEAAQAeAAAAgmIAAgGQAAgQgGgJQgFgJgKgDIgEAAIgDgBQgMAAgJAGgAlGA6QgQABgLgJQgLgJgFgQIgCgJIAAgIIAAgGQAAgQAHgNQAGgMAOgJIALgEIAKgBIACAAQATAAAMATIAAgFIASAAIAAA6IABATIACATIgBAAIgQAAQAAAAAAAAQgBAAAAgBQAAAAAAgBQgBgBAAgBIgBgNIgEAGIgEAEQgFAFgGABQgGACgHAAgAlTggQgIAHgFALIgCAIIgBAIIAAAFQAAAKAEAJQAEAIAIAGIAHAEIAIAAIAEAAQAfAAAAgmIAAgGQAAgQgGgJQgFgJgLgDIgEAAIgDgBQgMAAgJAGgAqWA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAqPgjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgAtXA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAtQgjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgA0lA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIIABAQIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgA0dgjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgA5bA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQAQAAAMAEQALAGAGAMQAFANAAAUQAAAVgFANQgGAMgLAGQgMAEgQAAQgQAAgLgEgA5TgjQgHAEgDAJQgDAJAAAPQAAAQADAJQADAJAHAEQAHAEAMAAQAMAAAHgEQAHgEADgJQADgJAAgQQAAgPgDgJQgDgJgHgEQgHgEgMAAQgMAAgHAEgEgiKAA6QgRABgLgJQgKgJgGgQIgBgJIgBgIIAAgGQAAgQAHgNQAHgMAOgJIALgEIAKgBIACAAQASAAANATIAAgFIARAAIAAA6IABATIADATIgBAAIgQAAQgBAAAAAAQAAAAAAgBQAAAAgBgBQAAgBAAgBIgCgNIgDAGIgFAEQgFAFgGABQgGACgHAAgEgiXgAgQgJAHgFALIgCAIIgBAIIAAAFQAAAKAFAJQAEAIAIAGIAHAEIAHAAIAEAAQAfAAAAgmIAAgGQAAgQgFgJQgGgJgLgDIgDAAIgDgBQgNAAgIAGgEgoDAA6QgQABgLgJQgLgJgFgQIgCgJIAAgIIAAgGQAAgQAHgNQAGgMAOgJIALgEIAKgBIACAAQATAAAMATIAAgFIASAAIAAA6IABATIACATIgBAAIgQAAQAAAAAAAAQAAAAgBgBQAAAAAAgBQAAgBgBgBIgBgNIgEAGIgEAEQgFAFgGABQgGACgHAAgEgoQgAgQgIAHgFALIgCAIIgBAIIAAAFQAAAKAEAJQAEAIAIAGIAHAEIAIAAIAEAAQAfAAAAgmIAAgGQAAgQgGgJQgFgJgLgDIgEAAIgDgBQgMAAgJAGgEgs0AA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgEgstgAjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgEAx8AA5QgFABgCgBQgDgBgBgDQgCgCAAgGQAAgIADgCQADgDAHAAQAHAAADADQADACAAAIQAAAGgBACQgBADgDABIgFABIgDgBgAIOA5QgFABgDgBQgDgBgBgDQgBgCAAgGQAAgIADgCQADgDAHAAQAHAAADADQADACAAAIQAAAGgCACQgBADgDABIgEABIgDgBgAy0A5QgFABgDgBQgDgBgBgDQgBgCAAgGQAAgIADgCQADgDAHAAQAHAAADADQADACAAAIQAAAGgCACQgBADgDABIgEABIgDgBgEAhbAA3QgHgCgDgIQgEgHAAgPIAAg8IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQABAFAEABQADADAGgBIAHAAIAFgBIAAAOIgGABIgGAAIgDABQgKAAgGgDgATlA1QgGgGAAgMIAAiDIARAAIAAB+QAAAIADACQACAEAGgBIAEAAIAEgBIAAAOIgFABIgHAAIgCABQgKAAgGgFgALkA1QgGgGAAgMIAAiDIARAAIAAB+QAAAIACACQADAEAFgBIAEAAIAEgBIAAAOIgFABIgGAAIgCABQgLAAgFgFgEgwXAA1QgGgGAAgMIAAiDIARAAIAAB+QAAAIACACQADAEAFgBIAEAAIAEgBIAAAOIgFABIgGAAIgCABQgLAAgFgFgAniA5IgMAAIgLgBIgJgCIAAgPIAKACIALACIALABQAMAAAGgEQAHgEAAgJQAAgHgCgDQgCgEgFgCQgFgDgKgBQgMgDgHgEQgHgDgCgGQgDgGAAgJQAAgOAKgHQAKgJATABIAQABIAMACIgCAPQgEgCgHgBQgHgCgIAAQgLAAgGAEQgGADAAAJQAAAGACADQACADAEACQAFACAIABQANADAHAEQAIADADAHQADAGAAAKQAAAQgKAIQgLAIgSAAIgCgBgA9kA5IgLAAIgMgBIgIgCIAAgPIAJACIALACIALABQANAAAGgEQAGgEAAgJQABgHgCgDQgCgEgFgCQgGgDgKgBQgMgDgHgEQgGgDgDgGQgDgGAAgJQABgOAJgHQAKgJAUABIAPABIAMACIgBAPQgFgCgHgBQgHgCgHAAQgMAAgFAEQgGADAAAJQAAAGABADQACADAFACQAEACAJABQAMADAIAEQAHADADAHQAEAGAAAKQAAAQgLAIQgKAIgSAAIgDgBgEAw6AA4IAAhEQAAgIgBgGQgCgFgEgEQgFgDgIAAQgHAAgHACQgGABgFAEQgFAGgEAJIAABIIgRAAIAAhsIARAAIAAAQQAEgHAGgDQAFgEAHgCIANgBQAPgBAIAFQAHAEAEAJQADAHAAALIAABKgEAqyAA4IAAhsIARAAIAAAUQAEgIAGgFQAFgFAHgCIANgBIACAAIAAAPIgDAAQgHAAgGACQgHACgFAGQgFAEgEAKIAABGgEAjYAA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAiYIARAAIAAA8QADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAfjA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAhsIARAAIAAAQQADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAdmA4IAAhsIARAAIAABsgAZ8A4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAhsIARAAIAAAQQADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAX/A4IAAhsIARAAIAABsgAONA4IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABZIAGAAIAmgtIAWAAIguAzIAwA5gAMYA4IAAhsIARAAIAABsgAJzA4IAAiKIASAAIAACKgAHMA4IAAhEQAAgIgBgGQgCgFgEgEQgFgDgIAAQgHAAgHACQgGABgFAEQgFAGgEAJIAABIIgRAAIAAhsIARAAIAAAQQAEgHAGgDQAFgEAHgCIANgBQAPgBAIAFQAHAEAEAJQADAHAAALIAABKgABEA4IAAhsIARAAIAAAUQADgIAGgFQAGgFAGgCIAOgBIACAAIgBAPIgCAAQgHAAgHACQgGACgGAGQgFAEgDAKIAABGgArzA4IAAhsIARAAIAAAUQADgIAGgFQAGgFAGgCIAOgBIACAAIgBAPIgCAAQgHAAgHACQgGACgGAGQgFAEgDAKIAABGgAudA4IAAhEQAAgIgCgGQgCgFgEgEQgFgDgIAAQgHAAgHACQgGABgFAEQgFAGgEAJIAABIIgRAAIAAiYIARAAIAAA8QAEgHAGgDQAFgEAHgCIANgBQAPgBAIAFQAHAEAEAJQADAHAAALIAABKgAw1A4IAAh7IgpAAIAAgPIBjAAIAAAPIgoAAIAAB7gA1rA4IAAhEQABgMgFgHQgFgHgMAAQgGAAgFACQgGABgEAEQgEAFgDAHIAABLIgRAAIAAhEQAAgMgEgHQgEgHgMAAQgHAAgFACQgGABgEAEQgEAFgDAIIAABKIgRAAIAAhsIARAAIAAAPQAFgKAIgDQAJgEAJABQANgBAIAFQAIAFADAJQADgIAGgDQAFgEAHgCQAGgCAHABQANgBAIAFQAIAEADAJQAEAHAAALIAABKgA6hA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAiYIARAAIAAA8QADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgA/pA4IAAhEQAAgIgBgGQgCgFgEgEQgFgDgIAAQgHAAgHACQgGABgFAEQgFAGgEAJIAABIIgRAAIAAhsIARAAIAAAQQAEgHAGgDQAFgEAHgCIANgBQAPgBAIAFQAHAEAEAJQADAHAAALIAABKgEglhAA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAhsIARAAIAAAQQADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgEgqcAA4IAAiKIAnAAQAUgBALAFQALAFAFAKQAFAJAAAQQAAAZgMAKQgNAKgbAAIgUAAIAAAxgEgqJgAHIATAAQANAAAHgDQAIgDADgGQADgHAAgMQAAgKgDgHQgDgGgIgDQgHgDgNAAIgTAAgEgtuAA4IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABZIAGAAIAmgtIAWAAIguAzIAwA5gEgvjAA4IAAhsIARAAIAABsgEgyIAA4IAAiKIASAAIAACKgAo3gsIAFgRIAEgSIACgRIARAAQAAAHgCAKQgCAJgEAJIgHARgA+5gsIAGgRIAEgSIABgRIASAAQAAAHgDAKQgCAJgDAJIgIARgAdnhJQgDgDABgGQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAGgCADQgDACgFAAQgGAAgCgCgAX/hJQgCgDAAgGQAAgGACgCQADgCAFAAQAGAAACACQADACAAAGQAAAGgDADQgCACgGAAQgFAAgDgCgAMYhJQgCgDAAgGQAAgGACgCQADgCAFAAQAGAAACACQADACAAAGQAAAGgDADQgCACgGAAQgFAAgDgCgEgvjgBJQgCgDAAgGQAAgGACgCQADgCAFAAQAGAAACACQADACAAAGQAAAGgDADQgCACgGAAQgFAAgDgCg");
	this.shape.setTransform(361.525,32.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("EAnOABgIgMgCIAAgOIANACIAOAAQASAAAJgIQAIgJAAgSIAAgLQgDAKgIAFQgIAFgQAAQgSABgKgIQgKgGgDgNQgEgMAAgRQAAgPAEgMQADgMAKgIQAKgHASAAQALAAAHACQAHAEAEAEQAEAFACAHIAAgVIASAAIAABlQAAAWgNANQgNANgcAAIgOgBgEAnMgAhQgGAGgCAJQgCAKAAAJQAAAMACAIQACAKAHAGQAGAFAMAAQANAAAIgFQAHgEADgKQADgJAAgNQAAgLgDgKQgDgJgHgFQgIgFgNAAQgMAAgHAGgAbJBgIgMgCIAAgOIANACIAOAAQASAAAJgIQAIgJAAgSIAAgLQgDAKgIAFQgIAFgQAAQgSABgKgIQgKgGgDgNQgEgMAAgRQAAgPAEgMQADgMAKgIQAKgHASAAQALAAAHACQAHAEAEAEQAEAFACAHIAAgVIASAAIAABlQAAAWgNANQgNANgcAAIgOgBgAbHghQgGAGgCAJQgCAKAAAJQAAAMACAIQACAKAHAGQAGAFAMAAQANAAAIgFQAHgEADgKQADgJAAgNQAAgLgDgKQgDgJgHgFQgIgFgNAAQgMAAgHAGgAWQBSQAJAAAGgDQAGgCAEgGQAEgGADgJIgshsIATAAIAhBaIACAAIAfhaIASAAIgnBpQgFAOgGAJQgGALgKAEQgJAGgQAAgARfBhIAAiVIARAAIAAAUQAEgKAIgGQAIgFAQAAQASgBAKAIQAKAHADANQAEAMAAAQQAAAQgEAMQgDANgKAHQgKAIgSAAQgQABgIgGQgIgGgEgJIAAA7gAR9giQgHAFgDAKQgDAJAAAMQAAAMADAKQADAKAHAEQAIAFANABQAMgBAHgFQAGgGACgKQACgJAAgLQAAgKgCgKQgCgJgHgGQgGgGgMAAQgNAAgIAFgAifBgIgMgCIAAgOIANACIANAAQASAAAJgIQAJgJAAgSIAAgLQgDAKgJAFQgIAFgPAAQgSABgKgIQgKgGgEgNQgEgMAAgRQAAgPAEgMQAEgMAKgIQAKgHASAAQAKAAAIACQAHAEAEAEQAEAFACAHIAAgVIARAAIAABlQAAAWgNANQgMANgcAAIgOgBgAihghQgGAGgCAJQgCAKAAAJQAAAMACAIQACAKAGAGQAGAFANAAQANAAAHgFQAIgEADgKQADgJgBgNQABgLgDgKQgDgJgIgFQgHgFgNAAQgNAAgGAGgEgksABhIAAiVIARAAIAAAUQAEgKAIgGQAIgFAQAAQASgBAKAIQAKAHADANQAEAMAAAQQAAAQgEAMQgDANgKAHQgKAIgSAAQgQABgIgGQgIgGgEgJIAAA7gEgkOgAiQgHAFgDAKQgDAJAAAMQAAAMADAKQADAKAHAEQAIAFANABQAMgBAHgFQAGgGACgKQACgJAAgLQAAgKgCgKQgCgJgHgGQgGgGgMAAQgNAAgIAFgEAuPAA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIIABAQIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgEAuXgAjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgEAsKAA0QgKgIgEgNQgEgNAAgQQAAgOAEgNQAEgMAKgIQAJgJASABQAQgBAIAGQAJAGADAJIAAg/IARAAIAACYIgOAAIgDgSQgDAKgJAFQgJAGgPgBQgSAAgJgGgEAsVgAhQgGAGgCAKQgCAJAAAKQAAALACAKQACAKAGAFQAGAFANABQANgBAHgEQAIgGADgIQADgKgBgNQABgLgDgKQgDgKgIgFQgHgFgNAAQgNAAgGAGgEApYAA6QgRABgLgJQgKgJgGgQIgBgJIgBgIIAAgGQAAgQAHgNQAHgMAOgJIALgEIAKgBIACAAQASAAANATIAAgFIARAAIAAA6IABATIADATIgBAAIgQAAQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAgBAAgBIgCgNIgDAGIgFAEQgFAFgGABQgGACgHAAgEApLgAgQgJAHgFALIgCAIIgBAIIAAAFQAAAKAFAJQAEAIAIAGIAHAEIAHAAIAEAAQAfAAAAgmIAAgGQAAgQgFgJQgGgJgLgDIgDAAIgDgBQgNAAgIAGgEAkeAA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgEAklgAjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgAU6A6QgQABgLgJQgLgJgFgQIgCgJIAAgIIAAgGQAAgQAHgNQAGgMAOgJIALgEIAKgBIACAAQATAAAMATIAAgFIASAAIAAA6IABATIACATIgBAAIgQAAQAAAAAAAAQgBAAAAgBQAAAAAAgBQgBgBAAgBIgBgNIgEAGIgEAEQgFAFgGABQgGACgHAAgAUtggQgIAHgFALIgCAIIgBAIIAAAFQAAAKAEAJQAEAIAIAGIAHAEIAIAAIAEAAQAfAAAAgmIAAgGQAAgQgGgJQgFgJgLgDIgEAAIgDgBQgMAAgJAGgAPHA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAPOgjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgAEhA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAEogjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgACbA0QgKgIgDgNQgEgNAAgQQAAgOAEgNQADgMAKgIQAKgJASABQAQgBAIAGQAIAGADAJIAAg/IASAAIAACYIgPAAIgDgSQgDAKgJAFQgIAGgPgBQgSAAgKgGgACmghQgGAGgCAKQgCAJAAAKQAAALACAKQACAKAHAFQAGAFAMABQANgBAIgEQAHgGADgIQADgKAAgNQAAgLgDgKQgDgKgHgFQgIgFgNAAQgMAAgHAGgAgWA6QgQABgLgJQgLgJgFgQIgCgJIAAgIIAAgGQAAgQAHgNQAGgMAOgJIALgEIAKgBIACAAQASAAAMATIAAgFIASAAIAAA6IABATIACATIgBAAIgQAAQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAgBgBgBIgBgNIgEAGIgEAEQgFAFgFABQgGACgHAAgAgjggQgIAHgFALIgCAIIgBAIIAAAFQAAAKAEAJQAEAIAIAGIAHAEIAIAAIAEAAQAeAAAAgmIAAgGQAAgQgGgJQgFgJgKgDIgEAAIgDgBQgMAAgJAGgAlGA6QgQABgLgJQgLgJgFgQIgCgJIAAgIIAAgGQAAgQAHgNQAGgMAOgJIALgEIAKgBIACAAQATAAAMATIAAgFIASAAIAAA6IABATIACATIgBAAIgQAAQAAAAAAAAQgBAAAAgBQAAAAAAgBQgBgBAAgBIgBgNIgEAGIgEAEQgFAFgGABQgGACgHAAgAlTggQgIAHgFALIgCAIIgBAIIAAAFQAAAKAEAJQAEAIAIAGIAHAEIAIAAIAEAAQAfAAAAgmIAAgGQAAgQgGgJQgFgJgLgDIgEAAIgDgBQgMAAgJAGgAqWA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAqPgjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgAtXA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgAtQgjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgA0lA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQANAAAJADQAJAFAEAGQAFAHACAIIABAQIAAAFIgBAHIhKAFQAAAMAEAHQADAIAIADQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgEgA0dgjQgHAFgDAHQgCAJgBAKIA6gEQAAgIgBgIQgCgGgGgFQgGgEgLAAQgNAAgGAEgA5bA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAGgMALgGQALgEAQAAQAQAAAMAEQALAGAGAMQAFANAAAUQAAAVgFANQgGAMgLAGQgMAEgQAAQgQAAgLgEgA5TgjQgHAEgDAJQgDAJAAAPQAAAQADAJQADAJAHAEQAHAEAMAAQAMAAAHgEQAHgEADgJQADgJAAgQQAAgPgDgJQgDgJgHgEQgHgEgMAAQgMAAgHAEgEgiKAA6QgRABgLgJQgKgJgGgQIgBgJIgBgIIAAgGQAAgQAHgNQAHgMAOgJIALgEIAKgBIACAAQASAAANATIAAgFIARAAIAAA6IABATIADATIgBAAIgQAAQgBAAAAAAQAAAAAAgBQAAAAgBgBQAAgBAAgBIgCgNIgDAGIgFAEQgFAFgGABQgGACgHAAgEgiXgAgQgJAHgFALIgCAIIgBAIIAAAFQAAAKAFAJQAEAIAIAGIAHAEIAHAAIAEAAQAfAAAAgmIAAgGQAAgQgFgJQgGgJgLgDIgDAAIgDgBQgNAAgIAGgEgoDAA6QgQABgLgJQgLgJgFgQIgCgJIAAgIIAAgGQAAgQAHgNQAGgMAOgJIALgEIAKgBIACAAQATAAAMATIAAgFIASAAIAAA6IABATIACATIgBAAIgQAAQAAAAAAAAQAAAAgBgBQAAAAAAgBQAAgBgBgBIgBgNIgEAGIgEAEQgFAFgGABQgGACgHAAgEgoQgAgQgIAHgFALIgCAIIgBAIIAAAFQAAAKAEAJQAEAIAIAGIAHAEIAIAAIAEAAQAfAAAAgmIAAgGQAAgQgGgJQgFgJgLgDIgEAAIgDgBQgMAAgJAGgEgs0AA2QgLgGgGgMQgGgNAAgVQAAgUAGgNQAFgMALgGQALgEAQAAQAOAAAJADQAIAFAFAGQAEAHACAIIACAQIgBAFIAAAHIhKAFQAAAMADAHQADAIAIADQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgEgEgstgAjQgHAFgCAHQgDAJAAAKIA6gEQAAgIgCgIQgCgGgFgFQgGgEgMAAQgMAAgHAEgEAx8AA5QgFABgCgBQgDgBgBgDQgCgCAAgGQAAgIADgCQADgDAHAAQAHAAADADQADACAAAIQAAAGgBACQgBADgDABIgFABIgDgBgAIOA5QgFABgDgBQgDgBgBgDQgBgCAAgGQAAgIADgCQADgDAHAAQAHAAADADQADACAAAIQAAAGgCACQgBADgDABIgEABIgDgBgAy0A5QgFABgDgBQgDgBgBgDQgBgCAAgGQAAgIADgCQADgDAHAAQAHAAADADQADACAAAIQAAAGgCACQgBADgDABIgEABIgDgBgEAhbAA3QgHgCgDgIQgEgHAAgPIAAg8IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQABAFAEABQADADAGgBIAHAAIAFgBIAAAOIgGABIgGAAIgDABQgKAAgGgDgATlA1QgGgGAAgMIAAiDIARAAIAAB+QAAAIADACQACAEAGgBIAEAAIAEgBIAAAOIgFABIgHAAIgCABQgKAAgGgFgALkA1QgGgGAAgMIAAiDIARAAIAAB+QAAAIACACQADAEAFgBIAEAAIAEgBIAAAOIgFABIgGAAIgCABQgLAAgFgFgEgwXAA1QgGgGAAgMIAAiDIARAAIAAB+QAAAIACACQADAEAFgBIAEAAIAEgBIAAAOIgFABIgGAAIgCABQgLAAgFgFgAniA5IgMAAIgLgBIgJgCIAAgPIAKACIALACIALABQAMAAAGgEQAHgEAAgJQAAgHgCgDQgCgEgFgCQgFgDgKgBQgMgDgHgEQgHgDgCgGQgDgGAAgJQAAgOAKgHQAKgJATABIAQABIAMACIgCAPQgEgCgHgBQgHgCgIAAQgLAAgGAEQgGADAAAJQAAAGACADQACADAEACQAFACAIABQANADAHAEQAIADADAHQADAGAAAKQAAAQgKAIQgLAIgSAAIgCgBgA9kA5IgLAAIgMgBIgIgCIAAgPIAJACIALACIALABQANAAAGgEQAGgEAAgJQABgHgCgDQgCgEgFgCQgGgDgKgBQgMgDgHgEQgGgDgDgGQgDgGAAgJQABgOAJgHQAKgJAUABIAPABIAMACIgBAPQgFgCgHgBQgHgCgHAAQgMAAgFAEQgGADAAAJQAAAGABADQACADAFACQAEACAJABQAMADAIAEQAHADADAHQAEAGAAAKQAAAQgLAIQgKAIgSAAIgDgBgEAw6AA4IAAhEQAAgIgBgGQgCgFgEgEQgFgDgIAAQgHAAgHACQgGABgFAEQgFAGgEAJIAABIIgRAAIAAhsIARAAIAAAQQAEgHAGgDQAFgEAHgCIANgBQAPgBAIAFQAHAEAEAJQADAHAAALIAABKgEAqyAA4IAAhsIARAAIAAAUQAEgIAGgFQAFgFAHgCIANgBIACAAIAAAPIgDAAQgHAAgGACQgHACgFAGQgFAEgEAKIAABGgEAjYAA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAiYIARAAIAAA8QADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAfjA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAhsIARAAIAAAQQADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAdmA4IAAhsIARAAIAABsgAZ8A4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAhsIARAAIAAAQQADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgAX/A4IAAhsIARAAIAABsgAONA4IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABZIAGAAIAmgtIAWAAIguAzIAwA5gAMYA4IAAhsIARAAIAABsgAJzA4IAAiKIASAAIAACKgAHMA4IAAhEQAAgIgBgGQgCgFgEgEQgFgDgIAAQgHAAgHACQgGABgFAEQgFAGgEAJIAABIIgRAAIAAhsIARAAIAAAQQAEgHAGgDQAFgEAHgCIANgBQAPgBAIAFQAHAEAEAJQADAHAAALIAABKgABEA4IAAhsIARAAIAAAUQADgIAGgFQAGgFAGgCIAOgBIACAAIgBAPIgCAAQgHAAgHACQgGACgGAGQgFAEgDAKIAABGgArzA4IAAhsIARAAIAAAUQADgIAGgFQAGgFAGgCIAOgBIACAAIgBAPIgCAAQgHAAgHACQgGACgGAGQgFAEgDAKIAABGgAudA4IAAhEQAAgIgCgGQgCgFgEgEQgFgDgIAAQgHAAgHACQgGABgFAEQgFAGgEAJIAABIIgRAAIAAiYIARAAIAAA8QAEgHAGgDQAFgEAHgCIANgBQAPgBAIAFQAHAEAEAJQADAHAAALIAABKgAw1A4IAAh7IgpAAIAAgPIBjAAIAAAPIgoAAIAAB7gA1rA4IAAhEQABgMgFgHQgFgHgMAAQgGAAgFACQgGABgEAEQgEAFgDAHIAABLIgRAAIAAhEQAAgMgEgHQgEgHgMAAQgHAAgFACQgGABgEAEQgEAFgDAIIAABKIgRAAIAAhsIARAAIAAAPQAFgKAIgDQAJgEAJABQANgBAIAFQAIAFADAJQADgIAGgDQAFgEAHgCQAGgCAHABQANgBAIAFQAIAEADAJQAEAHAAALIAABKgA6hA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAiYIARAAIAAA8QADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgA/pA4IAAhEQAAgIgBgGQgCgFgEgEQgFgDgIAAQgHAAgHACQgGABgFAEQgFAGgEAJIAABIIgRAAIAAhsIARAAIAAAQQAEgHAGgDQAFgEAHgCIANgBQAPgBAIAFQAHAEAEAJQADAHAAALIAABKgEglhAA4IAAhEQAAgIgCgGQgBgFgFgEQgEgDgJAAQgHAAgGACQgHABgFAEQgFAGgDAJIAABIIgRAAIAAhsIARAAIAAAQQADgHAGgDQAGgEAGgCIAOgBQAOgBAIAFQAIAEADAJQAEAHgBALIAABKgEgqcAA4IAAiKIAnAAQAUgBALAFQALAFAFAKQAFAJAAAQQAAAZgMAKQgNAKgbAAIgUAAIAAAxgEgqJgAHIATAAQANAAAHgDQAIgDADgGQADgHAAgMQAAgKgDgHQgDgGgIgDQgHgDgNAAIgTAAgEgtuAA4IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABZIAGAAIAmgtIAWAAIguAzIAwA5gEgvjAA4IAAhsIARAAIAABsgEgyIAA4IAAiKIASAAIAACKgAo3gsIAFgRIAEgSIACgRIARAAQAAAHgCAKQgCAJgEAJIgHARgA+5gsIAGgRIAEgSIABgRIASAAQAAAHgDAKQgCAJgDAJIgIARgAdnhJQgDgDABgGQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAGgCADQgDACgFAAQgGAAgCgCgAX/hJQgCgDAAgGQAAgGACgCQADgCAFAAQAGAAACACQADACAAAGQAAAGgDADQgCACgGAAQgFAAgDgCgAMYhJQgCgDAAgGQAAgGACgCQADgCAFAAQAGAAACACQADACAAAGQAAAGgDADQgCACgGAAQgFAAgDgCgEgvjgBJQgCgDAAgGQAAgGACgCQADgCAFAAQAGAAACACQADACAAAGQAAAGgDADQgCACgGAAQgFAAgDgCg");
	this.shape_1.setTransform(361.525,32.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).wait(1));

	// 图层_5
	this.instance_1 = new lib.元件32复制2();
	this.instance_1.setTransform(328.85,42.25,1,1,0,0,0,327.9,42.3);
	this.instance_1.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-6,-7,711,80);
p.frameBounds = [rect, rect];


(lib.元件21复制 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));

	// 图层_3
	this.instance = new lib.元件23();
	this.instance.setTransform(224.75,29.7,1.5014,1.0226,0,0,0,125.5,23.5);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.元件23(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AX1BKQgJgFgDgIQgDgIAAgKIAAhLIARAAIAABEQABAJABAGQACAGAFADQAEADAIAAQAHAAAHgCQAFgBAFgFQAFgEAEgKIAAhJIARAAIAABsIgPAAIgCgQQgEAIgFAEQgFADgHACQgGABgIAAQgOAAgHgEgANLBOQgRAAgKgIQgLgJgGgRIgBgIIgBgIIAAgGQAAgRAIgMQAGgNAOgIIALgEIAKgBIACAAQASAAANATIAAgFIARAAIAAA5IABAUIADATIgBAAIgQAAQAAAAAAAAQgBAAAAgBQAAAAAAgBQgBgBAAgBIgCgNIgDAFIgFAFQgFAEgFACQgGACgHAAgAM+gMQgJAGgFALIgBAIIgBAJIAAAEQgBALAFAIQAEAJAIAGIAHADIAHABIAFAAQAeAAAAgmIAAgHQAAgQgFgIQgGgKgKgDIgEAAIgDAAQgMAAgJAGgAK+BJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAGgNALgFQAMgFAPAAQARAAALAFQALAFAGANQAFALAAAWQAAAVgFANQgGAMgLAFQgLAFgRAAQgPAAgMgFgALGgPQgHADgDAKQgCAIAAAQQAAAQACAJQADAJAHAEQAIAEALAAQAMAAAIgEQAGgEAEgJQACgJAAgQQAAgQgCgIQgEgKgHgDQgHgEgMAAQgLAAgIAEgAJKBJQgIgGgEgKIgCATIgPAAIAAiYIARAAIAABAQAEgKAIgGQAJgGAPAAQASAAAKAHQAKAIAEAMQADAMAAARQAAAPgDANQgEANgKAHQgKAIgSAAQgPAAgJgFgAJMgOQgIAFgDAJQgDAJAAANQAAAMADAKQADAJAIAFQAHAFANABQAMgBAHgGQAGgFACgKQACgKAAgKQAAgMgCgJQgCgJgHgFQgFgGgNAAQgNAAgHAFgAGfBOQgQAAgMgIQgKgJgFgRIgCgIIgBgIIAAgGQABgRAGgMQAHgNAOgIIALgEIAKgBIACAAQASAAANATIAAgFIARAAIAAA5IACAUIACATIgBAAIgQAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAgBAAgBIgBgNIgEAFIgEAFQgGAEgGACQgFACgIAAgAGSgMQgJAGgEALIgDAIIgBAJIAAAEQABALAEAIQAEAJAIAGIAHADIAIABIADAAQAfAAABgmIAAgHQAAgQgGgIQgFgKgMgDIgDAAIgDAAQgNAAgIAGgAicBJQgMgFgGgMQgFgNgBgVQABgWAFgLQAGgNALgFQALgFAQAAQAOAAAIAEQAJAEAFAHQAEAHACAIIACAPIgBAFIAAAIIhLAEQAAAMAEAIQADAHAIAEQAHAEANAAQAKAAAJgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgLgFgAiVgPQgHAEgCAIQgDAHgBALIA7gEQgBgIgBgHQgCgHgFgEQgHgEgLAAQgMAAgHAEgAnTBJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAGgNALgFQAMgFAPAAQARAAALAFQALAFAGANQAFALAAAWQAAAVgFANQgGAMgLAFQgLAFgRAAQgPAAgMgFgAnLgPQgHADgDAKQgCAIAAAQQAAAQACAJQADAJAHAEQAIAEALAAQAMAAAIgEQAGgEAEgJQACgJAAgQQAAgQgCgIQgEgKgHgDQgHgEgMAAQgLAAgIAEgAuPBJQgLgFgHgMQgFgNgBgVQABgWAFgLQAGgNALgFQALgFAQAAQAOAAAIAEQAJAEAFAHQAEAHACAIIACAPIgBAFIAAAIIhLAEQAAAMAEAIQADAHAIAEQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgLgFgAuIgPQgHAEgCAIQgDAHgBALIA7gEQgBgIgBgHQgCgHgFgEQgHgEgLAAQgMAAgHAEgAyUBJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAGgNALgFQALgFAQAAQAQAAAMAFQALAFAGANQAGALAAAWQAAAVgGANQgGAMgLAFQgMAFgQAAQgQAAgLgFgAyMgPQgHADgCAKQgDAIAAAQQAAAQADAJQACAJAHAEQAIAEALAAQANAAAGgEQAIgEACgJQAEgJgBgQQABgQgEgIQgDgKgHgDQgHgEgMAAQgLAAgIAEgA2jBJQgMgFgFgMQgGgNgBgVQABgWAGgLQAFgNALgFQALgFAQAAQAOAAAIAEQAJAEAFAHQAEAHACAIIACAPIgBAFIAAAIIhLAEQAAAMAEAIQADAHAIAEQAHAEANAAQAKAAAJgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgLgFgA2cgPQgHAEgCAIQgDAHgBALIA7gEQgBgIgBgHQgCgHgFgEQgHgEgLAAQgMAAgHAEgAbrBNQgEABgDgBQgDgBgBgDQgCgDABgFQAAgIACgDQAEgCAGAAQAIAAACACQAEADAAAIQAAAFgCADQgBADgDABIgFAAIgDAAgAP1BNQgEABgDgBQgDgBgBgDQgBgDAAgFQAAgIADgDQACgCAHAAQAIAAACACQADADAAAIQAAAFgBADQgBADgDABIgFAAIgDAAgAgtBNQgFABgCgBQgDgBgBgDQgCgDABgFQAAgIACgDQADgCAHAAQAIAAACACQAEADAAAIQgBAFgBADQgBADgDABIgFAAIgDAAgASgBLQgIgDgCgHQgEgIAAgOIAAg8IgQAAIAAgPIAQAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQACAEADACQADACAHAAIAHAAIAFgBIAAAOIgGABIgGAAIgDAAQgKAAgGgCgAO0BLQgIgDgCgHQgEgIAAgOIAAg8IgQAAIAAgPIAQAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQACAEAEACQADACAGAAIAHAAIAFgBIAAAOIgGABIgGAAIgDAAQgKAAgGgCgAB9BLQgHgDgDgHQgEgIABgOIAAg8IgRAAIAAgPIARAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQACAEADACQADACAGAAIAHAAIAGgBIAAAOIgHABIgGAAIgDAAQgKAAgGgCgAvWBLQgHgDgDgHQgEgIABgOIAAg8IgQAAIAAgPIAQAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQACAEADACQADACAGAAIAHAAIAGgBIAAAOIgHABIgGAAIgDAAQgKAAgGgCgAwaBLQgHgDgDgHQgDgIgBgOIAAg8IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQACAEADACQADACAHAAIAGAAIAFgBIAAAOIgGABIgFAAIgEAAQgKAAgGgCgA6GBIQgHgGAAgMIAAiCIASAAIAAB+QgBAIADACQACADAGAAIAEAAIAEgBIAAAOIgFABIgGAAIgCAAQgLAAgFgFgAUlBNIgMAAIgLgBIgJgCIAAgPIAKACIALACIALAAQAMAAAHgDQAGgEAAgJQAAgHgCgDQgCgEgEgCQgGgDgKgCQgMgCgHgEQgHgEgCgGQgDgGAAgIQAAgOAKgIQAKgIAUAAIAPABIAMADIgBAPQgFgCgHgBQgHgCgHAAQgMAAgFAEQgHADAAAJQABAFABADQACADAEACQAFACAJABQAMADAIAEQAHAEADAGQAEAHgBAKQAAAQgKAIQgKAHgTAAIgCAAgAECBNIgLAAIgMgBIgIgCIAAgPIAJACIALACIALAAQAMAAAGgDQAHgEAAgJQAAgHgBgDQgCgEgFgCQgGgDgKgCQgMgCgHgEQgHgEgCgGQgDgGAAgIQABgOAJgIQAKgIATAAIAQABIAMADIgCAPQgEgCgHgBQgHgCgIAAQgLAAgGAEQgFADAAAJQAAAFABADQACADAEACQAFACAJABQAMADAHAEQAIAEADAGQAEAHAAAKQAAAQgLAIQgKAHgTAAIgCAAgArcBNIgLAAIgMgBIgJgCIAAgPIAKACIALACIALAAQANAAAFgDQAHgEAAgJQAAgHgBgDQgDgEgEgCQgGgDgKgCQgMgCgHgEQgGgEgDgGQgDgGAAgIQABgOAJgIQAKgIATAAIAQABIAMADIgBAPQgFgCgHgBQgHgCgIAAQgLAAgGAEQgFADgBAJQAAAFACADQACADAEACQAFACAJABQAMADAHAEQAIAEADAGQAEAHAAAKQAAAQgLAIQgKAHgTAAIgCAAgAaqBMIAAhFQgBgHgBgGQgCgGgEgDQgFgDgIAAQgHAAgHABQgGACgFAEQgFAFgDAJIAABJIgRAAIAAhsIARAAIAAAQQADgHAGgEQAFgEAHgBIAOgCQAOAAAIAFQAHAEAEAIQADAIAAAKIAABLgAWkBMIAAhdIgSAAIAAgPIASAAIAAgBQAAgSAEgKQAFgKAIgDQAJgDALAAIAGAAIAFABIAAAOIgEgBIgHAAQgIAAgEADQgEACgCAHQgCAHAAAMIAaAAIAAAPIgaAAIAABdgARaBMIAAiLIATAAIAACLgAA4BMIAAiLIASAAIAACLgAjjBMIAAhFQABgLgEgHQgGgHgLAAQgHAAgFABQgGACgEAEQgEAEgCAHIAABMIgSAAIAAhFQAAgLgEgHQgEgHgMAAQgGAAgGABQgGACgEAEQgEAEgDAIIAABLIgRAAIAAhsIARAAIAAAPQAFgKAJgDQAIgEAKAAQANAAAHAFQAIAFADAIQAEgHAFgEQAGgEAGgBQAHgCAGAAQANAAAIAFQAIAEAEAIQADAIAAAKIAABLgAoZBMIAAhFQAAgHgCgGQgBgGgFgDQgFgDgIAAQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAiYIARAAIAAA8QADgHAGgEQAGgEAGgBIANgCQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgA0LBMIAAiLIATAAIAAB7IA8AAIAAAQgA3eBMIgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAHAAIAlgsIAXAAIguAyIAwA6gA5TBMIAAhsIARAAIAABsgA74BMIAAiLIATAAIAACLgATQgYIAGgRIADgSIACgRIARAAQAAAHgCAJQgCAKgDAJIgIARgACugYIAFgRIAEgSIACgRIARAAQAAAHgCAJQgDAKgDAJIgIARgAsxgYIAFgRIAFgSIABgRIASAAQAAAHgDAJQgCAKgDAJIgIARgA5Sg2QgCgCAAgGQAAgHACgCQACgCAGABQAFgBADACQADACAAAHQAAAGgDACQgDACgFAAQgGAAgCgCg");
	this.shape.setTransform(219.05,30.275);

	this.instance_1 = new lib.元件32复制();
	this.instance_1.setTransform(328.85,42.25,1,1,0,0,0,327.9,42.3);
	this.instance_1.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AX1BKQgJgFgDgIQgDgIAAgKIAAhLIARAAIAABEQABAJABAGQACAGAFADQAEADAIAAQAHAAAHgCQAFgBAFgFQAFgEAEgKIAAhJIARAAIAABsIgPAAIgCgQQgEAIgFAEQgFADgHACQgGABgIAAQgOAAgHgEgANLBOQgRAAgKgIQgLgJgGgRIgBgIIgBgIIAAgGQAAgRAIgMQAGgNAOgIIALgEIAKgBIACAAQASAAANATIAAgFIARAAIAAA5IABAUIADATIgBAAIgQAAQAAAAAAAAQgBAAAAgBQAAAAAAgBQgBgBAAgBIgCgNIgDAFIgFAFQgFAEgFACQgGACgHAAgAM+gMQgJAGgFALIgBAIIgBAJIAAAEQgBALAFAIQAEAJAIAGIAHADIAHABIAFAAQAeAAAAgmIAAgHQAAgQgFgIQgGgKgKgDIgEAAIgDAAQgMAAgJAGgAK+BJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAGgNALgFQAMgFAPAAQARAAALAFQALAFAGANQAFALAAAWQAAAVgFANQgGAMgLAFQgLAFgRAAQgPAAgMgFgALGgPQgHADgDAKQgCAIAAAQQAAAQACAJQADAJAHAEQAIAEALAAQAMAAAIgEQAGgEAEgJQACgJAAgQQAAgQgCgIQgEgKgHgDQgHgEgMAAQgLAAgIAEgAJKBJQgIgGgEgKIgCATIgPAAIAAiYIARAAIAABAQAEgKAIgGQAJgGAPAAQASAAAKAHQAKAIAEAMQADAMAAARQAAAPgDANQgEANgKAHQgKAIgSAAQgPAAgJgFgAJMgOQgIAFgDAJQgDAJAAANQAAAMADAKQADAJAIAFQAHAFANABQAMgBAHgGQAGgFACgKQACgKAAgKQAAgMgCgJQgCgJgHgFQgFgGgNAAQgNAAgHAFgAGfBOQgQAAgMgIQgKgJgFgRIgCgIIgBgIIAAgGQABgRAGgMQAHgNAOgIIALgEIAKgBIACAAQASAAANATIAAgFIARAAIAAA5IACAUIACATIgBAAIgQAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAgBAAgBIgBgNIgEAFIgEAFQgGAEgGACQgFACgIAAgAGSgMQgJAGgEALIgDAIIgBAJIAAAEQABALAEAIQAEAJAIAGIAHADIAIABIADAAQAfAAABgmIAAgHQAAgQgGgIQgFgKgMgDIgDAAIgDAAQgNAAgIAGgAicBJQgMgFgGgMQgFgNgBgVQABgWAFgLQAGgNALgFQALgFAQAAQAOAAAIAEQAJAEAFAHQAEAHACAIIACAPIgBAFIAAAIIhLAEQAAAMAEAIQADAHAIAEQAHAEANAAQAKAAAJgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgLgFgAiVgPQgHAEgCAIQgDAHgBALIA7gEQgBgIgBgHQgCgHgFgEQgHgEgLAAQgMAAgHAEgAnTBJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAGgNALgFQAMgFAPAAQARAAALAFQALAFAGANQAFALAAAWQAAAVgFANQgGAMgLAFQgLAFgRAAQgPAAgMgFgAnLgPQgHADgDAKQgCAIAAAQQAAAQACAJQADAJAHAEQAIAEALAAQAMAAAIgEQAGgEAEgJQACgJAAgQQAAgQgCgIQgEgKgHgDQgHgEgMAAQgLAAgIAEgAuPBJQgLgFgHgMQgFgNgBgVQABgWAFgLQAGgNALgFQALgFAQAAQAOAAAIAEQAJAEAFAHQAEAHACAIIACAPIgBAFIAAAIIhLAEQAAAMAEAIQADAHAIAEQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgLgFgAuIgPQgHAEgCAIQgDAHgBALIA7gEQgBgIgBgHQgCgHgFgEQgHgEgLAAQgMAAgHAEgAyUBJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAGgNALgFQALgFAQAAQAQAAAMAFQALAFAGANQAGALAAAWQAAAVgGANQgGAMgLAFQgMAFgQAAQgQAAgLgFgAyMgPQgHADgCAKQgDAIAAAQQAAAQADAJQACAJAHAEQAIAEALAAQANAAAGgEQAIgEACgJQAEgJgBgQQABgQgEgIQgDgKgHgDQgHgEgMAAQgLAAgIAEgA2jBJQgMgFgFgMQgGgNgBgVQABgWAGgLQAFgNALgFQALgFAQAAQAOAAAIAEQAJAEAFAHQAEAHACAIIACAPIgBAFIAAAIIhLAEQAAAMAEAIQADAHAIAEQAHAEANAAQAKAAAJgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgLgFgA2cgPQgHAEgCAIQgDAHgBALIA7gEQgBgIgBgHQgCgHgFgEQgHgEgLAAQgMAAgHAEgAbrBNQgEABgDgBQgDgBgBgDQgCgDABgFQAAgIACgDQAEgCAGAAQAIAAACACQAEADAAAIQAAAFgCADQgBADgDABIgFAAIgDAAgAP1BNQgEABgDgBQgDgBgBgDQgBgDAAgFQAAgIADgDQACgCAHAAQAIAAACACQADADAAAIQAAAFgBADQgBADgDABIgFAAIgDAAgAgtBNQgFABgCgBQgDgBgBgDQgCgDABgFQAAgIACgDQADgCAHAAQAIAAACACQAEADAAAIQgBAFgBADQgBADgDABIgFAAIgDAAgASgBLQgIgDgCgHQgEgIAAgOIAAg8IgQAAIAAgPIAQAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQACAEADACQADACAHAAIAHAAIAFgBIAAAOIgGABIgGAAIgDAAQgKAAgGgCgAO0BLQgIgDgCgHQgEgIAAgOIAAg8IgQAAIAAgPIAQAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQACAEAEACQADACAGAAIAHAAIAFgBIAAAOIgGABIgGAAIgDAAQgKAAgGgCgAB9BLQgHgDgDgHQgEgIABgOIAAg8IgRAAIAAgPIARAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQACAEADACQADACAGAAIAHAAIAGgBIAAAOIgHABIgGAAIgDAAQgKAAgGgCgAvWBLQgHgDgDgHQgEgIABgOIAAg8IgQAAIAAgPIAQAAIAAgaIARAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQACAEADACQADACAGAAIAHAAIAGgBIAAAOIgHABIgGAAIgDAAQgKAAgGgCgAwaBLQgHgDgDgHQgDgIgBgOIAAg8IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQACAEADACQADACAHAAIAGAAIAFgBIAAAOIgGABIgFAAIgEAAQgKAAgGgCgA6GBIQgHgGAAgMIAAiCIASAAIAAB+QgBAIADACQACADAGAAIAEAAIAEgBIAAAOIgFABIgGAAIgCAAQgLAAgFgFgAUlBNIgMAAIgLgBIgJgCIAAgPIAKACIALACIALAAQAMAAAHgDQAGgEAAgJQAAgHgCgDQgCgEgEgCQgGgDgKgCQgMgCgHgEQgHgEgCgGQgDgGAAgIQAAgOAKgIQAKgIAUAAIAPABIAMADIgBAPQgFgCgHgBQgHgCgHAAQgMAAgFAEQgHADAAAJQABAFABADQACADAEACQAFACAJABQAMADAIAEQAHAEADAGQAEAHgBAKQAAAQgKAIQgKAHgTAAIgCAAgAECBNIgLAAIgMgBIgIgCIAAgPIAJACIALACIALAAQAMAAAGgDQAHgEAAgJQAAgHgBgDQgCgEgFgCQgGgDgKgCQgMgCgHgEQgHgEgCgGQgDgGAAgIQABgOAJgIQAKgIATAAIAQABIAMADIgCAPQgEgCgHgBQgHgCgIAAQgLAAgGAEQgFADAAAJQAAAFABADQACADAEACQAFACAJABQAMADAHAEQAIAEADAGQAEAHAAAKQAAAQgLAIQgKAHgTAAIgCAAgArcBNIgLAAIgMgBIgJgCIAAgPIAKACIALACIALAAQANAAAFgDQAHgEAAgJQAAgHgBgDQgDgEgEgCQgGgDgKgCQgMgCgHgEQgGgEgDgGQgDgGAAgIQABgOAJgIQAKgIATAAIAQABIAMADIgBAPQgFgCgHgBQgHgCgIAAQgLAAgGAEQgFADgBAJQAAAFACADQACADAEACQAFACAJABQAMADAHAEQAIAEADAGQAEAHAAAKQAAAQgLAIQgKAHgTAAIgCAAgAaqBMIAAhFQgBgHgBgGQgCgGgEgDQgFgDgIAAQgHAAgHABQgGACgFAEQgFAFgDAJIAABJIgRAAIAAhsIARAAIAAAQQADgHAGgEQAFgEAHgBIAOgCQAOAAAIAFQAHAEAEAIQADAIAAAKIAABLgAWkBMIAAhdIgSAAIAAgPIASAAIAAgBQAAgSAEgKQAFgKAIgDQAJgDALAAIAGAAIAFABIAAAOIgEgBIgHAAQgIAAgEADQgEACgCAHQgCAHAAAMIAaAAIAAAPIgaAAIAABdgARaBMIAAiLIATAAIAACLgAA4BMIAAiLIASAAIAACLgAjjBMIAAhFQABgLgEgHQgGgHgLAAQgHAAgFABQgGACgEAEQgEAEgCAHIAABMIgSAAIAAhFQAAgLgEgHQgEgHgMAAQgGAAgGABQgGACgEAEQgEAEgDAIIAABLIgRAAIAAhsIARAAIAAAPQAFgKAJgDQAIgEAKAAQANAAAHAFQAIAFADAIQAEgHAFgEQAGgEAGgBQAHgCAGAAQANAAAIAFQAIAEAEAIQADAIAAAKIAABLgAoZBMIAAhFQAAgHgCgGQgBgGgFgDQgFgDgIAAQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAiYIARAAIAAA8QADgHAGgEQAGgEAGgBIANgCQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgA0LBMIAAiLIATAAIAAB7IA8AAIAAAQgA3eBMIgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAHAAIAlgsIAXAAIguAyIAwA6gA5TBMIAAhsIARAAIAABsgA74BMIAAiLIATAAIAACLgATQgYIAGgRIADgSIACgRIARAAQAAAHgCAJQgCAKgDAJIgIARgACugYIAFgRIAEgSIACgRIARAAQAAAHgCAJQgDAKgDAJIgIARgAsxgYIAFgRIAFgSIABgRIASAAQAAAHgDAJQgCAKgDAJIgIARgA5Sg2QgCgCAAgGQAAgHACgCQACgCAGABQAFgBADACQADACAAAHQAAAGgDACQgDACgFAAQgGAAgCgCg");
	this.shape_1.setTransform(219.05,30.275);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.shape}]}).to({state:[{t:this.instance_1},{t:this.shape_1}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-6,-7,435,80);
p.frameBounds = [rect, rect];


(lib.元件19 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		var _this=this;
		_this.stop();
		
		_this.addEventListener("click", fl_MouseClickHandler.bind(this));
		function fl_MouseClickHandler(e)
		{
			console.log(e.target.name);
			_this.gotoAndStop(parseInt(e.target.name.split("_")[1]) + 1);
			_this.parent.gotoPage(e.target.name.split("_")[1]);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(3));

	// 图层_5
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AhUCYIDmkUYAJgKgBgQgLgJYgKgIgPABgJAJIj5ECYgPAPAAAYAPAPYAQAPAYgBAOgPYABgBAAAAABgB");
	this.shape.setTransform(-91.6322,252.8846,0.8,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AhPgsIBWBwYAPATAbAEATgPYATgOAEgcgPgSYgCgDgDgDgDgCIhvhXYgLgJgQACgJALYgHAKAAAMAHAJ");
	this.shape_1.setTransform(-104.2812,259.0462,0.8,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1,p:{x:-104.2812,y:259.0462}},{t:this.shape,p:{x:-91.6322,y:252.8846}}]},1).to({state:[{t:this.shape_1,p:{x:357.9188,y:259.0962}},{t:this.shape,p:{x:370.5678,y:252.9346}}]},1).wait(1));

	// 图层_4
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("rgba(52,198,194,0.8)").ss(4,1,1).p("AVgsFQABhBgDgpQgMiZhChdQgwhGhXgRQg+gLhBAFQhCAEiXARQhjALhNAQQgrAJgkAJQhnAch3gBQjFgCiOgBQiMgDjjgmQjkgmh/gfIhIgJQjYgMiFBnQiJBqgWDFQgGA3gBBDQAAABAAAAQAABFAFBSQAGBUAICkIACAAQAAALAAALQAGD6gxFXQAAAMgoDRQgGAigDAjQgOCDALCfQAMDMCjBmQA7AkA4AYQCqAwGLhJQAGgCAIgBQCXgnB0gEAD2SWIB3AUQBPAJAUACQATACA0AGQAzAFA3AHQA2AGBMAJQCZASDDgWQAygGAqgSQAUgGARgJQCuhagqkhQAAgEAAgFQAAgGAAgHQgChkgNh6QgDgagEgcQgslUAIicQAEhxASjOQACgTACgRQAOi9AGhZQACgoAFh4");
	this.shape_2.setTransform(-95.075,143.4528);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("rgba(52,198,194,0.8)").ss(4,1,1).p("AD3SdIB6ALQAQAGAjAFQA0AIBNAKQBAAGCbASQCbASDGgWQAygGArgRQAUgGASgKQCvhZgqkdQAAgEAAgFQAAgGAAgHQgCh4gUiZQgtlUAIicQAFhwASjPQACgSACgSQAOi8AGhaQAMi7gGhWQgMichDheQgwhHhZgSQg+gLhDAFQhCAEiZASQicARhmAcQhnAch3gBQjFgCiNgBQiNgCjjgnQhRgOhEgPQgmgIgmgKQgjgJghgKQgcgJgdgFQgngIgpgBQgbAAgbABQgoACglAHQgkAGgjALQgZAJgYAJQg0AXgrAiQiJBsgWDIQgMBvAKCmQAGBVAICkIACAAQAAAKAAAMQAGD6gxFWQAAANgoDRQgaCZAODJQAMDKCjBlQA7AkA4AYQCqAuGLhHQAGgDAIAAQCXgnB4gB");
	this.shape_3.setTransform(366.7829,143.0329);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

	// 图层_3
	this.pg_0 = new lib.元件20复制();
	this.pg_0.name = "pg_0";
	this.pg_0.setTransform(-292,81.8,4.0305,2.3267,0,0,0.5072);
	new cjs.ButtonHelper(this.pg_0, 0, 1, 2, false, new lib.元件20复制(), 3);

	this.pg_1 = new lib.元件20复制();
	this.pg_1.name = "pg_1";
	this.pg_1.setTransform(170.15,82.6,4.0392,2.3235,0,0,0.5071,0,0.1);
	new cjs.ButtonHelper(this.pg_1, 0, 1, 2, false, new lib.元件20复制(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.pg_1},{t:this.pg_0}]}).wait(3));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-234.6,16.9,741.5,252.4);
p.frameBounds = [rect, new cjs.Rectangle(-235.8,16.4,742.7,255.1), new cjs.Rectangle(-234.6,15.7,742.8,255.8)];


(lib.d1_1复制2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.instance = new lib.位图61();
	this.instance.setTransform(-96,-121,0.3488,0.3488);

	this.dia = new lib.元件21复制();
	this.dia.name = "dia";
	this.dia.setTransform(122,-59.35,1,1,0,0,0,122.4,20.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.dia},{t:this.instance}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.d1_1复制2, rect = new cjs.Rectangle(-96,-121,524.6,114.1), [rect]);


(lib.d1_1复制 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.instance = new lib.位图61();
	this.instance.setTransform(-96,-121,0.3488,0.3488);

	this.dia = new lib.元件21复制2();
	this.dia.name = "dia";
	this.dia.setTransform(122,-59.35,1,1,0,0,0,122.4,20.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.dia},{t:this.instance}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.d1_1复制, rect = new cjs.Rectangle(-96,-121,800.6,114.1), [rect]);


// stage content:
(lib.index = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		
		var _this = this;
		
		_this.pgId;
		_this.diaAry;
		_this.diaMcAry;
		_this.data;
		_this.curId = 0;
		_this.curPgDia; //存储当前页的所有对话mc
		_this.clickMode = false;
		_this.canClick = false;
		_this.start = false;
		_this.isEnded = false;
		//点击单词声音
		_this.audio;
		
		if (!this.isinit) {
			//console.log("第一次进入")
			this.isinit = true;
			init();
		}
		
		/*function playSoundBySrc(src) {
			audio.currentTime = 0;
			audio.pause();
			audio.src = src;
			console.log(audio.src);
			audio.play();
			_this.isEnded = false;
			_this._onp.setStu(false);
		}*/
		function playSoundBySrc(src) {
		    // 如果新源与当前源相同，不必重新设置
		    if (audio.src !== src) {
		        audio.pause(); // 暂停当前音频
		        audio.src = src; // 设置新音频源
		        audio.currentTime = 0; // 重置播放时间
		        
		        // 确保音频加载完成后再播放
		        audio.oncanplaythrough = function() {
		            audio.play().catch(function(error) {
		                console.error("播放错误:", error);
		            });
		            _this.isEnded = false;
		            _this._onp.setStu(false);
		            audio.oncanplaythrough = null; // 清除事件监听器
		        };
		        
		        // 触发加载
		        audio.load();
		    } else {
		        audio.currentTime = 0; // 如果源相同，重置播放时间并播放
		        audio.play().catch(function(error) {
		            console.error("播放错误:", error);
		        });
		        _this.isEnded = false;
		        _this._onp.setStu(false);
		    }
		}
		
		
		function init() {
			_this.pgId = 0;
			_this.diaAry = [2, 2, 2];
			_this.data = lesdata;
			hideDia();
		
			audio = new Audio();
			audio.addEventListener('play', function () {
				//console.log('被点击的单词开始播放');
			});
			audio.addEventListener('ended', function () {
				//播放结束事件。
				//console.log("播放结束。");
				_this.isEnded = true;
				resetDia();
				if (_this.clickMode) {
					_this._onp.setStu(true);
					//_this.clickMode=false;
					return;
				} //点读模式
				nextFun();
			});
		
		    //隐藏播放和清除按钮
		    _this._onp.visible=false;
		}
		
		_this.gotoPage = function (_pg) {
			if (_this.pgId == _pg && _this.start == true) {
				return;
			}
			//reset();
			_this.isEnded = true;
			_this.start = true;
			_this.pgId = _pg;
			_this.curId = 0;
			if(audio)audio.pause();
			_this.canClick = false;
			_this.clickMode = false;
			_this.gotoAndStop(_this.pgId);
			hideDia();
			updata();
		
			//reset();
			//console.log(_this.diaMcAry);
			//setTimeout(reset,1000);
		}
		
		function hideDia() {
			_this.curPgDia = [];
			//for(var i=1;i<=_this.diaAry[_this.pgId];i++){
			//console.log("##############################");
			//console.log(_this.data);
		    //console.log(_this.data[_this.pgId]);
			console.log(_this.data);
			for (var i = 1; i <= _this.data[_this.pgId].length; i++) {
				_this["dia_" + (parseInt(_this.pgId) + 1) + "_" + i].visible = false;
				_this["dia_" + (parseInt(_this.pgId) + 1) + "_" + i]["dia"].addEventListener("click", ondiamc);
				_this.curPgDia.push(_this["dia_" + (parseInt(_this.pgId) + 1) + "_" + i]);
				console.log("dia_" + (parseInt(_this.pgId) + 1) + "_" + i);
			}
		}
		function resetDia() {
			for (var v of _this.curPgDia) {
				v.dia.gotoAndStop(0);
			}
		}
		function updata() {
			_this.curPgDia[_this.curId].visible = true;
			_this._onp.visible=true;
			resetDia();
			_this.curPgDia[_this.curId].dia.gotoAndStop(1);
			playSoundBySrc(_this.data[_this.pgId][_this.curId].soundPath);
		}
		function nextFun() {
			//
			/*console.log("下一个");
			console.log(_this.curId);
			console.log(_this.curPgDia.length-1);*/
			if (_this.curId < _this.curPgDia.length - 1) {
				_this.curId += 1;
				updata();
			} else {
				_this.canClick = true;
				_this._onp.setStu(true);
				return;
			}
		}
		function prevFun() {
			//
			_this.curId += 1;
		}
		
		
		function ondiamc(e) {
			if (!_this.canClick) {
				return
			}
			_this.clickMode = true;
			for (var item of _this.curPgDia) {
				item.gotoAndStop(0);
			}
			e.currentTarget.gotoAndStop(1);
			const lastChar = e.currentTarget.parent.name.slice(-1);
			_this.curId = Number(lastChar) - 1; // 将 lastChar 转为数字并减去 1
			console.log(_this.curId);
			//点击对话框
			updata();
		}
		
		//子机控制父级
		_this.onPause = function () {
			if (!audio.paused && !audio.ended) {
				audio.pause();
			}
		};
		
		_this.onPlay = function () {
			//if (audio.paused || audio.ended) {
			if (_this.canClick && _this.isEnded) {
				_this.curId = 0;
				_this.clickMode = false;
				_this.canClick = false;
				hideDia();
				updata();
				return;
			} else if (audio.paused) {
				audio.play();
			}
		};
		_this.onClear = function () {
			if (!audio.paused && !audio.ended) {
				audio.pause();
			}
			_this.curId = 0;
			_this.clickMode = false;
			_this.canClick = true;
			_this.isEnded = true;
			hideDia();
			_this._onp.setStu(true);
			//updata();
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));

	// 跳转按钮
	this._onp = new lib.暂停播放组();
	this._onp.name = "_onp";
	this._onp.setTransform(943.55,641.9,1,1,0,0,0,37.5,20.4);

	this.gotoBtnMc = new lib.元件19();
	this.gotoBtnMc.name = "gotoBtnMc";
	this.gotoBtnMc.setTransform(661.55,244.4,1.1598,1.1598,0,0,0,153.1,153.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.gotoBtnMc},{t:this._onp}]}).wait(2));

	// 标题
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AgSAbQgGgCgDgGQgBgHAAgMQAAgMABgGQADgGAGgDQAHgCALABQAMgBAGACQAHADACAGQACAGAAAMQAAAMgCAHQgCAGgHACQgGACgMAAQgLAAgHgCg");
	this.shape.setTransform(712.4,57.52);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231F20").s().p("AhGBRQAPAAAJgDQAJgDAGgGQAFgGACgIIhFiwIA1AAIApB+IACAAIAoh+IAzAAIg8CgQgIAZgJAPQgJARgLAIQgMAKgQAEQgQAEgXAAg");
	this.shape_1.setTransform(697.375,54.65);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#231F20").s().p("AgUBbQgYAAgQgMQgRgNgJgYQgDgJgBgLIgCgVIAAgHQAAgYAKgTQAKgSAUgOQAIgFAJgDQAIgBAJAAIAJAAQAQAAALAEQAKAGAHAKIAAABIABABIAAAAIABgFIABgBIAtAAIABAAIAAABIgCA6QAAAmACAYQADAYAFALIAAACIABAFIgBABIgtAAIgDgHIgGgSIgBAAQgHANgKAHQgLAGgPAAgAgdgtQgMAKgGAVIgCAKIAAAGQAAAUAHANQAHANANAFIAKACIAKABQANABAIgFQAJgEAEgKQAEgGACgLQABgJAAgNQAAgSgEgNQgGgMgIgGQgEgDgGgBQgFgBgHAAIgBAAQgQAAgLAKg");
	this.shape_2.setTransform(677,51.25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#231F20").s().p("AgHBcQgQAAgOgCIgbgEIAAgoQANAEAPACQAOACAMAAQAPABAHgEQAHgEAAgKQAAgIgDgEQgCgEgIgDQgGgDgOgDQgTgFgKgGQgLgFgEgJQgEgKABgPQgBgZAQgOQARgOAmAAQAOAAAOACQANACAHACIgBAlIgNgDIgQgDIgQgBQgPAAgHAEQgGAEABAJQgBAFADADQACADAHADIAUAGQAUAFALAGQAKAGAEAKQAFAKAAAQQgBAfgSANQgTANgfAAIgDAAg");
	this.shape_3.setTransform(659.35,51.2759);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#231F20").s().p("Ag6B0QgQgMgGgUQgGgVABgcQgBgaAGgUQAGgVAQgMQAPgNAdAAQAXAAAMAHQANAHAFAMIAAhfIAvAAIAAD6IgrAAIgEgZQgFAMgMAIQgNAIgXAAQgdAAgPgLgAgXgNQgIAIgDALQgCANAAAQQAAAQACANQADAMAIAHQAIAIAPAAQAQAAAJgHQAJgGAEgNQADgMAAgSQAAgRgEgNQgDgMgJgHQgJgHgQAAQgPAAgIAIg");
	this.shape_4.setTransform(631.7231,47.875);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#231F20").s().p("AAiBbIAAhsQAAgSgGgIQgHgIgQAAQgPAAgJAGQgJAFgFAOIAAB1IgvAAIAAixIAvAAIAAAVQAIgNAPgGQANgGAUAAQAVAAANAHQANAHAGANQAFANAAAUIAAB5g");
	this.shape_5.setTransform(611.15,51.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#231F20").s().p("AgTBbQgZAAgRgMQgQgNgJgYQgDgJgBgLIgCgVIAAgHQAAgYAKgTQAKgSAUgOQAIgFAJgDQAIgBAJAAIAJAAQAPAAAMAEQAKAGAHAKIAAABIABABIAAAAIABgFIAAgBIAuAAIABAAIAAABIgCA6QAAAmACAYQADAYAFALIAAACIABAFIgBABIgtAAIgDgHIgHgSIAAAAQgHANgKAHQgLAGgPAAgAgdgtQgMAKgGAVIgCAKIAAAGQAAAUAHANQAHANANAFIAKACIALABQAMABAIgFQAJgEAEgKQAEgGABgLQACgJAAgNQAAgSgEgNQgGgMgIgGQgEgDgGgBQgFgBgHAAIAAAAQgRAAgLAKg");
	this.shape_6.setTransform(589.8,51.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#231F20").s().p("AAXB9IgwhMIgIAAIAABMIgwAAIAAj5IAwAAIAACJIAKAAIAuhBIA4AAIg/BSIBBBfg");
	this.shape_7.setTransform(563.45,47.725);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#231F20").s().p("AgaBVQgUgIgKgVQgLgUAAgkQAAgjALgUQAKgUAUgIQATgJAbABQAOAAAMABQAMACAIACIAAApQgJgEgKgBQgJgCgMAAQgPAAgKAEQgJAFgFAMQgFAMAAATQAAAVAFALQAFAMAJAEQAKAFAQAAIAVgCQAKgBAKgEIAAAoIgNADIgRADIgSAAIgDAAQgZAAgSgHg");
	this.shape_8.setTransform(544.725,51.3251);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#231F20").s().p("AgXB/IAAixIAvAAIAACxgAgPhNQgGgBgDgGQgCgFAAgMQAAgLACgFQADgFAGgCQAFgCAKABQALgBAGACQAFACADAFQACAFAAALQAAAMgCAFQgDAGgFABQgGACgLAAQgKAAgFgCg");
	this.shape_9.setTransform(531.725,47.595);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#231F20").s().p("AgYByIAAi3Ig8AAIAAgtICpAAIAAAtIg8AAIAAC3g");
	this.shape_10.setTransform(517.9,48.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#231F20").s().p("AgbBzQgGgCgCgFQgDgHAAgLQAAgMADgFQACgHAGgBQAGgDAMABQAKgBAGADQAGABADAHQACAFAAAMQAAALgCAHQgDAFgGACQgGADgKAAQgMAAgGgDgAgeAoIAAgPQAAgJACgHQADgHAFgHQAGgHAKgIIAJgKQAEgFACgFQABgEAAgHQAAgPgIgEQgGgGgUABIgVABQgLACgIADIAAgqQAJgCANgBQANgCAPAAQAaAAARAEQARAFAHANQAIANAAAXQAAAPgDAKQgCAKgHAJQgHAHgLAIIgOAMQgGAFgCAEQgCAFAAAFIAAAIg");
	this.shape_11.setTransform(493.075,48.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#231F20").s().p("AgpBVQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQAUgJAbABQAeAAARAKQARAKAGARQAGASAAAXIgBANIgBALIhyAHQACATALAJQAMAJAXAAQALAAALgCQAMgCAJgDQAKgCAGgEIAAAmQgJAFgSAEQgSADgYAAIgDAAQgYAAgSgHgAgYgtQgJAJgBAWIBIgGQABgKgDgIQgCgIgHgEQgHgFgOAAQgVAAgJAKg");
	this.shape_12.setTransform(475.8518,51.3251);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#231F20").s().p("AAXB9IgwhMIgHAAIAABMIgxAAIAAj5IAxAAIAACJIAKAAIAthBIA4AAIhABSIBCBfg");
	this.shape_13.setTransform(457.9,47.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#231F20").s().p("AgXB/IAAixIAvAAIAACxgAgPhNQgGgBgDgGQgCgFAAgMQAAgLACgFQADgFAGgCQAFgCAKABQALgBAGACQAFACADAFQACAFAAALQAAAMgCAFQgDAGgFABQgGACgLAAQgKAAgFgCg");
	this.shape_14.setTransform(442.625,47.595);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#231F20").s().p("AgOB5QgMgFgEgKQgFgKAAgQIAAjNIAvAAIAADBQAAAMADAEQAEAEAIAAIAEAAIAFgBIAAAlIgJACIgLAAQgTAAgLgFg");
	this.shape_15.setTransform(433.825,47.825);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#231F20").s().p("AgUBaQgWAAgNgGQgNgHgGgNQgGgNAAgUIAAh5IAwAAIAABsQAAASAGAIQAGAIARAAQANAAAKgGQAJgFAEgOIAAh1IAwAAIAACxIgrAAIgEgVQgHANgOAGQgNAGgRAAIgDgBg");
	this.shape_16.setTransform(408.875,51.5019);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#231F20").s().p("AAABcQgbABgTgIQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQATgJAbABQAcgBATAJQAUAIAKAUQAKAUAAAjQAAAkgKAUQgKAVgUAIQgSAHgaAAIgDAAgAgWgzQgIAGgEAMQgDANAAAUQAAAWADAMQAEAMAIAFQAJAFANAAQAPAAAIgFQAIgFAEgMQADgMAAgWQAAgUgDgNQgEgMgIgGQgJgFgOAAQgOAAgIAFg");
	this.shape_17.setTransform(388.325,51.3251);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#231F20").s().p("AhGBRQAPAAAJgDQAJgDAGgGQAFgGACgIIhFiwIA1AAIApB+IACAAIAoh+IAzAAIg8CgQgIAZgJAPQgJARgLAIQgMAKgQAEQgQAEgXAAg");
	this.shape_18.setTransform(368.525,54.65);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#231F20").s().p("AAABcQgbABgTgIQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQATgJAbABQAcgBATAJQAUAIAKAUQAKAUAAAjQAAAkgKAUQgKAVgUAIQgSAHgaAAIgDAAgAgWgzQgIAGgEAMQgDANAAAUQAAAWADAMQAEAMAIAFQAJAFANAAQAPAAAIgFQAIgFAEgMQADgMAAgWQAAgUgDgNQgEgMgIgGQgJgFgOAAQgOAAgIAFg");
	this.shape_19.setTransform(340.225,51.3251);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#231F20").s().p("Ag6B0QgQgMgGgUQgGgVABgcQgBgaAGgUQAGgVAQgMQAPgNAdAAQAXAAAMAHQANAHAFAMIAAhfIAvAAIAAD6IgrAAIgEgZQgFAMgMAIQgNAIgXAAQgdAAgPgLgAgXgNQgIAIgDALQgCANAAAQQAAAQACANQADAMAIAHQAIAIAPAAQAQAAAJgHQAJgGAEgNQADgMAAgSQAAgRgEgNQgDgMgJgHQgJgHgQAAQgPAAgIAIg");
	this.shape_20.setTransform(318.9731,47.875);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#231F20").s().p("AgpBVQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQAUgJAbABQAeAAARAKQARAKAGARQAGASAAAXIgBANIgBALIhyAHQACATALAJQAMAJAXAAQALAAALgCQAMgCAJgDQAKgCAGgEIAAAmQgJAFgSAEQgSADgYAAIgDAAQgYAAgSgHgAgYgtQgJAJgBAWIBIgGQABgKgDgIQgCgIgHgEQgHgFgOAAQgVAAgJAKg");
	this.shape_21.setTransform(290.7018,51.3251);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#231F20").s().p("ABUBbIAAhsQABgSgHgIQgGgIgPAAQgOAAgJAGQgHAGgEAOIAAB0IguAAIAAhsQAAgSgHgIQgGgIgOAAQgPAAgHAGQgIAFgDANIAAB2IgwAAIAAixIAwAAIAAAUQAHgMAMgGQANgGASAAQAUAAAMAHQAMAGAGAMQAHgNAPgGQAOgGAUAAQAdAAAQAPQAOAQAAAhIAAB1g");
	this.shape_22.setTransform(265.5,51.1742);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#231F20").s().p("AAABcQgbABgTgIQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQATgJAbABQAcgBATAJQAUAIAKAUQAKAUAAAjQAAAkgKAUQgKAVgUAIQgSAHgaAAIgDAAgAgWgzQgIAGgEAMQgDANAAAUQAAAWADAMQAEAMAIAFQAJAFANAAQAPAAAIgFQAIgFAEgMQADgMAAgWQAAgUgDgNQgEgMgIgGQgJgFgOAAQgOAAgIAFg");
	this.shape_23.setTransform(239.675,51.3251);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#231F20").s().p("AAiB9IAAhtQgBgRgFgIQgGgIgSABQgNgBgKAGQgKAGgEANIAAB1IgvAAIAAj5IAvAAIAABeQAIgNAOgGQAOgGATAAQAWAAANAHQANAGAGAOQAFANABASIAAB6g");
	this.shape_24.setTransform(219,47.725);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#231F20").s().p("AgpBVQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQAUgJAbABQAeAAARAKQARAKAGARQAGASAAAXIgBANIgBALIhyAHQACATALAJQAMAJAXAAQALAAALgCQAMgCAJgDQAKgCAGgEIAAAmQgJAFgSAEQgSADgYAAIgDAAQgYAAgSgHgAgYgtQgJAJgBAWIBIgGQABgKgDgIQgCgIgHgEQgHgFgOAAQgVAAgJAKg");
	this.shape_25.setTransform(190.3018,51.3251);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#231F20").s().p("AgHBcQgQAAgOgCIgagEIAAgoQANAEAOACQAOACANAAQAOABAHgEQAHgEAAgKQAAgIgCgEQgEgEgHgDQgGgDgPgDQgSgFgKgGQgLgFgEgJQgEgKABgPQgBgZARgOQAQgOAmAAQAOAAAOACQANACAHACIgBAlIgNgDIgQgDIgQgBQgPAAgHAEQgGAEABAJQgBAFACADQADADAHADIAUAGQAUAFALAGQAKAGAEAKQAFAKAAAQQgBAfgSANQgTANgfAAIgDAAg");
	this.shape_26.setTransform(172.55,51.2759);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#231F20").s().p("AAABcQgbABgTgIQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQATgJAbABQAcgBATAJQAUAIAKAUQAKAUAAAjQAAAkgKAUQgKAVgUAIQgSAHgaAAIgDAAgAgWgzQgIAGgEAMQgDANAAAUQAAAWADAMQAEAMAIAFQAJAFANAAQAPAAAIgFQAIgFAEgMQADgMAAgWQAAgUgDgNQgEgMgIgGQgJgFgOAAQgOAAgIAFg");
	this.shape_27.setTransform(154.225,51.3251);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#231F20").s().p("AAhB9IAAhtQABgRgHgIQgGgIgQABQgPgBgJAGQgKAGgDANIAAB1IgxAAIAAj5IAxAAIAABeQAHgNAOgGQANgGAVAAQAVAAANAHQANAGAGAOQAGANgBASIAAB6g");
	this.shape_28.setTransform(133.55,47.725);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#231F20").s().p("AAjByIgjiQIgBAAIgkCQIg/AAIgxjkIA0AAIAhCpIACAAIAjiTIA5AAIAhCTIACAAIAhipIA1AAIg1Dkg");
	this.shape_29.setTransform(107.35,48.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("ABYCZIgahMIh7AAIgbBMIhFAAIBykxIBYAAIBxExgAAqAWIgnhzIgFAAIgoBzIBUAAg");
	this.shape_30.setTransform(46.625,45.175);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#0D8075").s().p("AirCsQhHhHAAhlQAAhkBHhIQBHhGBkAAQBlAABHBGQBHBIAABkQAABlhHBHQhHBHhlAAQhkAAhHhHg");
	this.shape_31.setTransform(46.725,47.675);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(2));

	// 图层_2
	this.instance = new lib.位图5();
	this.instance.setTransform(192,70,0.62,0.62);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#333333").s().p("EgxGACQIAAjdIAaAAIAAAdQAGgOALgJQANgJAXAAQAbAAAPALQAOAKAGATQAFATAAAYQAAAWgFAUQgGASgOAMQgPAMgbAAQgXAAgNgIQgMgJgFgPIAABZgEgwZgAzQgKAHgFAPQgFANAAATQAAASAFAPQAFAOAKAHQALAIAUAAQATAAAJgJQAKgJACgOQADgOAAgQQAAgRgDgNQgDgPgJgIQgKgJgSAAQgUAAgLAIgEA4CABQQgQgIgKgSQgJgTAAggQAAgfAJgSQAJgTARgHQAQgIAXAAQAVAAAMAGQAOAGAGAKQAHAKACAMQADAMAAALIgBAJIgBAKIhuAGQAAASAGAMQAEALAMAFQALAGAUAAQANAAAOgDQANgDALgEIAAAYQgGACgIACIgTADQgKACgNAAQgXAAgRgHgEA4NgA0QgKAGgEAMQgEAMgBAQIBXgGQAAgNgDgKQgDgKgIgHQgIgHgSAAQgSABgKAGgEAw0ABQQgRgIgIgSQgKgTABggQgBgfAKgSQAIgTARgHQARgIAXAAQAYAAASAIQAQAHAIATQAJASAAAfQAAAggJATQgIASgQAIQgSAHgYAAQgXAAgRgHgEAx5AA8QALgGAEgOQAEgNAAgYQAAgWgEgOQgFgOgLgFQgKgGgSgBQgRABgLAGQgKAFgFAOQgEAOABAWQAAAYAEANQAEAOAKAGQAMAGAQgBQATABAKgGgEAmfABQQgQgIgJgSQgJgTAAggQAAgfAJgSQAIgTARgHQAQgIAYAAQAVAAAMAGQANAGAHAKQAGAKADAMQACAMABALIgBAJIgBAKIhuAGQAAASAFAMQAFALAMAFQALAGATAAQAOAAANgDQAOgDAKgEIAAAYQgFACgJACIgTADQgKACgMAAQgYAAgRgHgEAmqgA0QgJAGgEAMQgEAMgBAQIBWgGQAAgNgCgKQgDgKgJgHQgIgHgRAAQgSABgLAGgEAgcABQQgRgIgJgSQgIgTgBggQABgfAIgSQAJgTARgHQARgIAYAAQAXAAARAIQARAHAJATQAJASgBAfQABAggJATQgJASgRAIQgRAHgXAAQgYAAgRgHgEAhiAA8QAKgGAEgOQAEgNAAgYQAAgWgFgOQgEgOgKgFQgLgGgRgBQgTABgJAGQgLAFgEAOQgFAOAAAWQAAAYAFANQAFAOAKAGQAKAGASgBQASABALgGgA5IBQQgQgIgJgSQgKgTABggQgBgfAKgSQAIgTARgHQAQgIAXAAQAVAAANAGQAMAGAIAKQAGAKACAMQADAMAAALIgBAJIgBAKIhtAGQAAASAEAMQAGALALAFQALAGAUAAQAOAAANgDQAOgDAJgEIAAAYQgEACgJACIgTADQgLACgMAAQgXAAgRgHgA49g0QgKAGgEAMQgEAMAAAQIBVgGQABgNgDgKQgDgKgIgHQgJgHgRAAQgSABgKAGgEggWABQQgRgIgIgSQgJgTAAggQAAgfAJgSQAIgTARgHQARgIAYAAQAYAAAQAIQARAHAIATQAKASgBAfQABAggKATQgIASgRAIQgQAHgYAAQgYAAgRgHgA/RA8QALgGAEgOQAEgNAAgYQAAgWgEgOQgFgOgLgFQgKgGgRgBQgTABgJAGQgLAFgFAOQgEAOABAWQgBAYAFANQAEAOALAGQALAGARgBQASABAKgGgEgtWABXQgYAAgQgNQgQgNgIgYIgCgNIgBgMIAAgKQAAgYAKgSQAKgTAVgNIAQgGQAIgCAIAAIACAAQAbABATAcIAAgHIAAgBIABAAIAYAAIABAAIABABIAABVIABAeIADAbIgBABIgYAAQgCAAgBgGIgDgTIgFAHIgGAIQgHAGgJADQgJADgKAAgEgtpgAvQgMAIgIATIgDAMIgBAKIAAAHQAAAQAGANQAHANAMAKIAKADIALABIAGAAQAtABAAg5IAAgJQABgXgJgOQgHgPgRgEIgFAAIgEAAIgBAAQgSAAgNAJgEg2FABXQgYAAgRgNQgQgNgHgYIgDgNIgBgMIAAgKQABgYAJgSQALgTAVgNIAQgGQAHgCAIAAIADAAQAbABATAcIAAgHIAAgBIABAAIAYAAIABAAIAAABIAABVIABAeIAEAbIgCABIgYAAQgBAAgBgGIgDgTIgGAHIgFAIQgIAGgJADQgIADgLAAgEg2YgAvQgNAIgIATIgDAMIgBAKIAAAHQAAAQAHANQAGANAMAKIALADIAKABIAGAAQAuABAAg5IAAgJQAAgXgIgOQgIgPgQgEIgFAAIgFAAIgBAAQgRAAgNAJgEAqZABVIgRgCIgMgCIAAgXIANAEIARACIARABQASAAAJgFQAKgGAAgOQAAgJgCgGQgDgFgIgDQgIgEgPgEQgSgDgKgGQgKgFgEgJQgEgIAAgOQAAgUAPgMQAPgMAcAAQAMAAAMABQALACAGADIgBAWQgHgDgKgCQgLgCgLAAQgRAAgIAFQgJAFAAAOQAAAHACAFQADAEAHADQAGADAMADQATAEALAGQAMAFAEAJQAGAKAAAPQgBAYgQALQgPAMgeAAIgSgBgEAk3ABSQgLgEgEgMQgFgKAAgVIAAhaIgYAAIAAgWIAYAAIAAgnIAaAAIAAAnIAoAAIAAAWIgoAAIAABYQAAAMABAIQACAGAFADQAGADAJgBIAKAAIAIgBIAAAVIgJABIgJABQgSAAgLgEgEAjSABSQgLgEgEgMQgFgKAAgVIAAhaIgYAAIAAgWIAYAAIAAgnIAaAAIAAAnIAoAAIAAAWIgoAAIAABYQgBAMACAIQACAGAGADQAEADAKgBIAKAAIAIgBIAAAVIgJABIgJABQgSAAgLgEgEgmwABVIgRgCIgOgCIAAgXIAOAEIASACIAQABQASAAAKgFQAJgGAAgOQAAgJgCgGQgEgFgHgDQgIgEgPgEQgSgDgKgGQgKgFgEgJQgEgIABgOQAAgUAOgMQAPgMAcAAQAMAAAMABQALACAHADIgCAWQgIgDgJgCQgLgCgLAAQgRAAgJAFQgIAFgBAOQAAAHADAFQACAEAIADQAGADANADQASAEALAGQAMAFAEAJQAFAKABAPQgBAYgPALQgQAMgeAAIgRgBgEA2aABUIAAhlQABgUgHgJQgHgLgSAAQgJAAgJADQgIACgGAGQgHAGgDAMIAABwIgaAAIAAhlQABgUgHgJQgGgLgSAAQgJAAgJADQgIACgGAGQgGAGgFANIAABvIgaAAIAAihIAaAAIAAAVQAIgOANgFQALgFAQAAQATAAALAHQALAHAGANQAFgLAHgGQAJgGAJgCQAKgCAKAAQASAAANAHQALAHAGAMQAFAMAAAPIAABvgEAvMABUIAAhlQAAgNgCgJQgDgJgGgEQgHgFgNAAQgKAAgKACQgJACgIAIQgIAGgFAOIAABtIgaAAIAAjjIAaAAIAABZQAFgKAJgGQAJgGAKgCQAJgCALAAQAUAAANAHQALAHAFAMQAFAMAAAPIAABvgAdsBUIAAjPIAbAAIAAC3IBaAAIAAAYgA6wBUIAAhlQAAgUgGgJQgHgLgSAAQgJAAgIADQgJACgGAGQgHAGgDAMIAABwIgaAAIAAhlQAAgUgGgJQgGgLgRAAQgLAAgHADQgJACgGAGQgHAGgEANIAABvIgaAAIAAihIAaAAIAAAVQAIgOAMgFQAMgFAPAAQAUAAALAHQALAHAGANQAEgLAIgGQAJgGAJgCQAKgCAKAAQATAAAMAHQALAHAFAMQAGAMAAAPIAABvgEgh+ABUIAAhlQAAgNgCgJQgDgJgGgEQgIgFgNAAQgJAAgKACQgKACgHAIQgIAGgEAOIAABtIgaAAIAAjjIAaAAIAABZQAEgKAJgGQAJgGAJgCQAKgCALAAQAUAAAMAHQAMAHAFAMQAFAMAAAPIAABvgEgplABUIAAhlQAAgNgDgJQgCgJgHgEQgHgFgNAAQgKAAgJACQgKACgHAIQgIAGgEAOIAABtIgaAAIAAihIAaAAIAAAXQAEgKAJgGQAJgGAJgCQALgCAKAAQAUAAAMAHQAMAHAFAMQAFAMAAAPIAABvgEgyVABUIAAhlQAAgNgCgJQgCgJgIgEQgGgFgNAAQgKAAgJACQgKACgIAIQgIAGgEAOIAABtIgaAAIAAihIAaAAIAAAXQAFgKAIgGQAJgGAKgCQAKgCAKAAQAVAAAMAHQALAHAGAMQAEAMAAAPIAABvgEg5pABUIAAjPIA6AAQAdgBARAIQAQAHAIAOQAGAPAAAYQABAjgTAQQgSAQgogBIgfAAIAABKgEg5OgALIAdAAQATAAALgEQALgFAFgJQAFgKgBgRQABgRgFgJQgFgJgLgFQgLgEgTAAIgdAAgEAotgBCIAIgZQADgNACgOQADgOAAgLIAaAAQAAALgEAOQgDANgGAOQgFANgGAMgEgodgBCIAIgZQADgNACgOQADgOAAgLIAZAAQABALgEAOQgDANgGAOQgEANgGAMg");
	this.shape_32.setTransform(636.75,411.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_32},{t:this.instance}]}).wait(2));

	// 对话内容
	this.dia_1_1 = new lib.d1_1复制();
	this.dia_1_1.name = "dia_1_1";
	this.dia_1_1.setTransform(467.6,633.5,1,1,0,0,0,159.4,40.5);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f().s("#FE8659").ss(8,1,1).p("EhHTAHIIABgNIAXywQAAgIABgIQALiPBbhoQBph4CUAAMCDJAAAQCUAABpB4QBjBwAGCdQAAACAAACQAAACAAADIgbXCQAACphoB3QhpB4iVAAMiDIAAAQiVAAhph4Qhoh3AAipIAEkUIABgN");
	this.shape_33.setTransform(640,564.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("EhBxAR0QiVAAhoh3Qhph4AAipIAFkUIAAgMIAAAMIAAgMIAAAAIAXyxIABgQQALiPBbhoQBph3CVAAMCDIAAAQCUAABpB3QBiBwAGCdIAAAEIAAAFIgaXCQAACphoB4QhpB3iVAAg");
	this.shape_34.setTransform(640,564.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f().s("#FCE0CE").ss(18,1,1).p("EhHTAHIIABgNIAXywQAAgIABgIQALiPBbhoQBph4CUAAMCDJAAAQCUAABpB4QBjBwAGCdQAAACAAACQAAACAAADIgbXCQAACphoB3QhpB4iVAAMiDIAAAQiVAAhph4Qhoh3AAipIAEkUIABgN");
	this.shape_35.setTransform(640,564.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("EhBxAR0QiVAAhoh3Qhph4AAipIAFkUIAAgMIAXyxIABgQQALiPBbhoQBph3CVAAMCDIAAAQCUAABpB3QBiBwAGCdIAAAEIAAAFIgaXCQAACphoB4QhpB3iVAAgEhHSAG8IAAAAIAAAMgEhHSAG8g");
	this.shape_36.setTransform(640,564.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f().s("#FE8659").ss(8,1,1).p("Eg4LgRLMBwXAAAQCVAABoB3QBpB4AACqIAAVlQAACphpB4QhoB4iVAAMhwXAAAQiVAAhph4Qhnh4AAipIAA1lQAAiqBnh4QBph3CVAAg");
	this.shape_37.setTransform(578.6,568.45);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("Eg4LARMQiVAAhoh4Qhoh3AAiqIAA1lQAAipBoh4QBoh4CVAAMBwXAAAQCVAABoB4QBpB4AACpIAAVlQAACqhpB3QhoB4iVAAg");
	this.shape_38.setTransform(578.6,568.45);

	this.dia_2_1 = new lib.d1_1复制2();
	this.dia_2_1.name = "dia_2_1";
	this.dia_2_1.setTransform(467.6,633.5,1,1,0,0,0,159.4,40.5);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f().s("#FE8659").ss(8,1,1).p("EhHCgC2IACiXIAFmoQAAgIABgIQALiPBbhoQBph4CUAAMCDJAAAQCUAABpB4QBjBwAGCdQAAACAAACQAAACAAADIgIJrEBHNgB7IAAAcEBHNgC2IAAA7IgBAcIgBC/EBHAAHWIgDEGQAACphoB3QhpB4iVAAMiDIAAAQiVAAhph4Qhoh3AAipIAJpKEBHBAGWIAAAtIAAAGIgBANEBHBAHDIgBAMIAAAHEBHJABgIgDE2EhHKADiIABhQIABjDIAAgiEhHKADiIAAhQEhHIgAxIABgiIABj6EhHKAGWIAAhiEhHOAGWIAEhiIAAhS");
	this.shape_39.setTransform(640,564.4);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("EhBxAR0QiVAAhoh3Qhph4AAipIAJpKIAEAAIABAAIAABQIAAhQIABjDIABgiIABj6IAGAAIgCCXIACiXIAFmoIABgQQALiPBbhoQBph3CVAAMCDIAAAQCUAABpB3QBiBwAGCdIAAAEIAAAFIgHJrIgDAAIAAg7IAAA7IgBAcIgBC/IgCAAIgDE2IgFAAIgBAuIAAALIAAgGIAAAOIAAgIIAAAIIgDEFQAACphoB4QhpB3iVAAgEhHKAGWIABhiIAAhSIgBhQIABBQIAABSIgFBiIAFhigEhHIgBTIABAAIgBAigEBHMgBfIABgcIAAAcgEhHAgFNg");
	this.shape_40.setTransform(640,564.4);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f().s("#FCE0CE").ss(18,1,1).p("EhHCgC2IACiXIAFmoQAAgIABgIQALiPBbhoQBph4CUAAMCDJAAAQCUAABpB4QBjBwAGCdQAAACAAACQAAACAAADIgIJrEBHNgB7IgBAcIgBC/EBHNgC2IAAA7IAAAcEBHBAHDIgBAMIAAAHIgDEGQAACphoB3QhpB4iVAAMiDIAAAQiVAAhph4Qhoh3AAipIAJpKEBHBAHDIAAAGIgBANEBHBAGWIAAAtEBHJABgIgDE2EhHIgAxIABgiIABj6EhHIgAxIAAgiEhHKADiIAAhQEhHKADiIABhQIABjDEhHOAGWIAEhiEhHKAGWIAAhiIAAhS");
	this.shape_41.setTransform(640,564.4);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("EhBxAR0QiVAAhoh3Qhph4AAipIAJpKIAEAAIABAAIAABQIAAhQIABjDIABgiIABj6IAGAAIgCCXIACiXIAFmoIABgQQALiPBbhoQBph3CVAAMCDIAAAQCUAABpB3QBiBwAGCdIAAAEIAAAFIgHJrIgDAAIAAg7IAAA7IgBAcIgBC/IgCAAIgDE2IgFAAIgBAuIAAALIAAAIIAAgIIAAgGIAAAOIgDEFQAACphoB4QhpB3iVAAgEhHJAE0IgBBiIABhiIAAhSgEhHOAGWIAFhigEhHJADiIgBhQgEhHIgBTIABAAIgBAigEhHHgBTgEBHMgBfIABgcIAAAcgEhHAgFNg");
	this.shape_42.setTransform(640,564.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.dia_1_1}]}).to({state:[{t:this.shape_38},{t:this.shape_37},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.dia_2_1}]},1).wait(1));

	// diban
	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("rgba(255,255,255,0.8)").s().p("EhkVAEsIAApXMDIrAAAIAAJXg");
	this.shape_43.setTransform(639.9,690.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_43).wait(2));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = rect = new cjs.Rectangle(637.7,366.2,1284.5,714.3);
p.frameBounds = [rect, rect];
// library properties:
lib.properties = {
	id: 'E637B31863A9224E9952B4D82164A654',
	width: 1280,
	height: 720,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/index_atlas_1.png?1734506930718", id:"index_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['E637B31863A9224E9952B4D82164A654'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;