(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
var rect; // used to reference frame bounds
lib.ssMetadata = [
		{name:"index_atlas_1", frames: [[0,0,1726,500],[1728,0,143,199]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.位图18 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.位图19 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.元件32复制5 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Egi4AE3Qh0AAgEhwIAAhSQhYgkhHhQQgtgygmhEIAYAKQCEAzBWgBIAAiFQAAh4B4AAMBG/AAAIAAAAIBVAAIAAAAIBPAAQB4AAAAB4IAAGFQgCA4geAcQgeAcg6AAg");
	this.shape.setTransform(259.525,31.05);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.元件32复制5, rect = new cjs.Rectangle(0,0,519.1,62.2), [rect]);


(lib.元件32复制4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A+CE3Qh0AAgEhwIAAhSQhYgkhHhQQgtgygmhEIAYAKQCEAzBWgBIAAiFQAAh4B4AAMA9TAAAIAAAAIBVAAIAAAAIBPAAQB4AAAAB4IAAGFQgCA4geAcQgeAcg6AAg");
	this.shape.setTransform(228.525,31.05);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.元件32复制4, rect = new cjs.Rectangle(0,0,457.1,62.2), [rect]);


(lib.元件32复制 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EghyAE3Qh0AAgEhwIAAhSQhYgkhHhQQgtgygmhEIAYAKQCEAzBWgBIAAiFQAAh4B4AAMBEzAAAIAAAAIBVAAIAAAAIBPAAQB4AAAAB4IAAGFQgCA4geAcQgeAcg6AAg");
	this.shape.setTransform(252.525,31.05);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.元件32复制, rect = new cjs.Rectangle(0,0,505.1,62.2), [rect]);


(lib.元件23 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AzmDrIAAnVMAnNAAAIAAHVg");
	this.shape.setTransform(125.475,22.5);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = null;
p.frameBounds = [rect, rect, rect, new cjs.Rectangle(0,-1,251,47)];


(lib.元件20 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.149)").s().p("AELIiQgdgCgwgKQg5gMgWgCIgwgGIAAgGQAAgrgUgeQgTgegbAAQgbAAgUAeQgUAeAAArIAAAEQg5AFg0AOQg3APgcAAQgvgCgjghQgxguADiDQABgsAGhCIAKhgQAMiTgBhsIgEh4QgDhIADgwQAGhWAigvQAhguA1AAIAUABQAdAFA4ASQA5ASAdAEQBLANBigLQAagDArgMIBFgSQAggHAVAEQAdAHAQAfQAWAoAEBEQACAlgEBRIgICKQgGBagBAwQgDBDAPCTQAOCLgGBKQgJByhhAAIgQgBg");
	this.shape.setTransform(53.3189,25.9092);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFAED").s().p("AELIiQgdgCgwgKQg5gMgWgCIgwgGIAAgGQAAgrgUgeQgTgegbAAQgbAAgUAeQgUAeAAArIAAAEQg5AFg0AOQg3APgcAAQgvgCgjghQgxguADiDQABgsAGhCIAKhgQAMiTgBhsIgEh4QgDhIADgwQAGhWAigvQAhguA1AAIAUABQAdAFA4ASQA5ASAdAEQBLANBigLQAagDArgMIBFgSQAggHAVAEQAdAHAQAfQAWAoAEBEQACAlgEBRIgICKQgGBagBAwQgDBDAPCTQAOCLgGBKQgJByhhAAIgQgBg");
	this.shape_1.setTransform(53.3189,25.9092);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},4).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = null;
p.frameBounds = [rect, rect=new cjs.Rectangle(14.3,-28.8,78.2,109.4), rect, rect, rect, rect, rect];


(lib.元件18 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#F99703").ss(0.5,1,1).p("AgMgKIAZAAQAFAAADADQADADAAAEIAAAAQAAAFgDADQgDADgFAAIgZAAQgFAAgDgDQgDgDAAgFIAAAAQAAgEADgDQADgDAFAAg");
	this.shape.setTransform(20.2734,10.9751,0.7179,0.7183,-1.0066);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F99703").s().p("AgMALQgFAAgDgDQgDgDAAgFIAAAAQAAgEADgDQADgDAFAAIAZAAQAFAAADADQADADAAAEIAAAAQAAAFgDADQgDADgFAAg");
	this.shape_1.setTransform(20.2734,10.9751,0.7179,0.7183,-1.0066);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAACsQgKABgIgJQgIgHAAgLIAAkjQAAgLAIgIQAIgHAKAAIAAAAQALAAAIAHQAIAIAAALIAAEjQAAALgIAHQgIAJgLgBg");
	this.shape_2.setTransform(22.5783,22.4041,0.3436,0.269);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAACsQgKABgIgJQgIgHAAgLIAAkjQAAgLAIgIQAIgHAKAAIAAAAQALAAAIAHQAIAIAAALIAAEjQAAALgIAHQgIAJgLgBg");
	this.shape_3.setTransform(18.0283,22.4041,0.3436,0.269);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F99703").s().p("Ai9BQQghAAgXgYQgYgXAAghQAAggAYgYQAXgXAhAAIF7AAQAhAAAYAXQAXAYAAAgQAAAhgXAXQgYAYghAAg");
	this.shape_4.setTransform(20.1509,14.1754,0.3437,0.344,-0.2262);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F99703").s().p("Ag2BgQglAAAAglIgNiYIgBgBIABgBIDQAAIACACIAAAAIgSCYQAAAlgmAAg");
	this.shape_5.setTransform(20.3762,23.3401,0.7179,0.7184);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#F99703").ss(3,1,1).p("AiQCQQg8g7AAhVQAAhUA8g8QA8g8BUAAQBUAAA8A8QAJAIAHAJQADAEAEAFQAmA0AABCQAABVg9A7Qg8A9hUAAQhUAAg8g9g");
	this.shape_6.setTransform(20.475,20.475);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AiQCQQg8g7AAhVQAAhUA8g8QA8g8BUAAQBUAAA8A8IAQARIAHAJQAmA0AABCQAABVg9A7Qg8A9hUAAQhUAAg8g9g");
	this.shape_7.setTransform(20.475,20.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-1.5,-1.5,44,44);
p.frameBounds = [rect, rect];


(lib.元件17 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#F69602").ss(6,1,1).p("AhBhxIAADjABChxIAADj");
	this.shape.setTransform(20.4957,20.4917,0.7181,0.7185);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#F69602").ss(3,1,1).p("AjJDIQhThSAAh2QAAh1BThUQBUhTB1AAQB2AABTBTQBUBUAAB1QAAB2hUBSQhTBVh2AAQh1AAhUhVg");
	this.shape_1.setTransform(20.4598,20.4917,0.7181,0.7185);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AjJDIQhThSAAh2QAAh1BThUQBUhTB1AAQB2AABTBTQBUBUAAB1QAAB2hUBSQhTBVh2AAQh1AAhUhVg");
	this.shape_2.setTransform(20.4598,20.4917,0.7181,0.7185);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-1.5,-1.5,44,44);
p.frameBounds = [rect, rect];


(lib.元件10 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F99703").s().p("Ah9CPQgHgHgBgIIgBj7QABgIAEgHIAEgEQAIgIAMAAQAFAAAFACIDcB/IABACQAFAEACAFQACAFAAAFQAAAGgCAEQgCAFgFAEIgEAFIjZB9QgFACgFAAQgMAAgIgIg");
	this.shape.setTransform(23.281,20.4775,0.684,0.6844);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#F99703").ss(3,1,1).p("AiKCKQg6g5AAhRQAAhQA6g6QA6g5BQAAQBRAAA6A5QA6A6AABQQAABRg6A5Qg6A6hRAAQhQAAg6g6g");
	this.shape_1.setTransform(20.4871,20.4731,1.0426,1.0432);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AiKCKQg5g5gBhRQABhQA5g6QA5g5BRAAQBRAAA5A5QA7A6AABQQAABRg7A5Qg5A6hRAAQhRAAg5g6g");
	this.shape_2.setTransform(20.4871,20.4731,1.0426,1.0432);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-1.5,-1.5,44,44);
p.frameBounds = [rect, rect];


(lib.暂停播放组 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.isSingleFrame = false;
	// timeline functions:
	this.frame_0 = function() {
		if(this.isSingleFrame) {
			return;
		}
		if(this.totalFrames == 1) {
			this.isSingleFrame = true;
		}
		var _this = this;
		_this.stop();
		// 初始化状态
		function init(showPlay) {
		    _this.b_play.visible = showPlay;  // 根据参数控制播放按钮的显示
		    _this.b_pause.visible = !showPlay; // 根据参数控制暂停按钮的显示
		}
		_this.setStu=function(showPlay){
		    _this.b_play.visible = showPlay;  // 根据参数控制播放按钮的显示
		    _this.b_pause.visible = !showPlay; // 根据参数控制暂停按钮的显示
		}
		
		// 事件监听
		this.b_play.addEventListener("click", () => fl_MouseClickHandler_3(true));
		this.b_pause.addEventListener("click", () => fl_MouseClickHandler_3(false));
		
		function fl_MouseClickHandler_3(isPlay) { 
		    if (isPlay) {
		        _this.parent.onPlay();
		        _this.b_play.visible = false; 
		        _this.b_pause.visible = true;  
		    } else {
		        _this.parent.onPause();
		        _this.b_play.visible = true; 
		        _this.b_pause.visible = false;  
		    }
		    //_this.parent.isPlaying = !_this.parent.isPlaying; // 切换播放状态
		}
		
		// 调用初始化方法，初始状态为播放按钮显示
		init(true);
		
		
		this.b_clear.addEventListener("click", fl_MouseClickHandler_4.bind(this));
		
		function fl_MouseClickHandler_4()
		{
			_this.parent.onClear();
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// 图层_1
	this.b_clear = new lib.元件18();
	this.b_clear.name = "b_clear";
	this.b_clear.setTransform(76.2,20.4,1,1,0,0,0,20.4,20.4);
	new cjs.ButtonHelper(this.b_clear, 0, 1, 1);

	this.b_pause = new lib.元件17();
	this.b_pause.name = "b_pause";
	this.b_pause.setTransform(20.4,20.4,1,1,0,0,0,20.4,20.4);
	new cjs.ButtonHelper(this.b_pause, 0, 1, 1);

	this.b_play = new lib.元件10();
	this.b_play.name = "b_play";
	this.b_play.setTransform(20.4,20.4,1,1,0,0,0,20.4,20.4);
	new cjs.ButtonHelper(this.b_play, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.b_play},{t:this.b_pause},{t:this.b_clear}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.暂停播放组, rect = new cjs.Rectangle(-1.5,-1.5,99.8,44), [rect]);


(lib.元件21复制4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));

	// 图层_3
	this.instance = new lib.元件23();
	this.instance.setTransform(242.45,29.8,1.6391,1.0226,0,0,0,125.7,23.6);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.元件23(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AaBBOQgQAAgLgIQgLgJgFgRIgCgIIAAgIIAAgGQAAgRAHgMQAGgNAOgIIALgEIAKgBIACAAQATAAAMATIAAgFIASAAIAAA5IABAUIACATIgBAAIgQAAQAAAAAAAAQgBAAAAgBQAAAAAAgBQgBgBAAgBIgBgNIgEAFIgEAFQgFAEgGACQgGACgHAAgAZ0gMQgIAGgFALIgCAIIgBAJIAAAEQAAALAEAIQAEAJAIAGIAHADIAIABIAEAAQAfAAAAgmIAAgHQAAgQgGgIQgFgKgLgDIgEAAIgDAAQgMAAgJAGgAUtBJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAGgNALgFQAMgFAQAAQAQAAALAFQALAFAGANQAGALAAAWQAAAVgGANQgGAMgLAFQgLAFgQAAQgQAAgMgFgAU2gPQgHADgDAKQgDAIAAAQQAAAQADAJQADAJAHAEQAHAEAMAAQAMAAAHgEQAHgEADgJQADgJgBgQQABgQgDgIQgEgKgHgDQgHgEgLAAQgMAAgHAEgAR0BHQgKgHgEgNQgEgNAAgQQAAgPAEgMQAEgNAKgIQAJgIASAAQAQAAAIAGQAJAGADAJIAAg/IARAAIAACYIgOAAIgDgSQgDAJgJAGQgJAFgPAAQgSAAgJgHgAR/gNQgGAGgCAIQgCAKAAALQAAALACAKQACAJAGAGQAGAFANABQANgBAHgEQAIgGADgJQADgJgBgNQABgNgDgJQgDgJgIgFQgHgFgNAAQgNAAgGAGgAN+BKQgIgFgEgIQgDgIAAgKIAAhLIASAAIAABEQAAAJABAGQACAGAFADQAEADAJAAQAHAAAGgCQAGgBAFgFQAFgEADgKIAAhJIARAAIAABsIgPAAIgCgQQgDAIgGAEQgFADgHACQgGABgHAAQgOAAgIgEgAMEBJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAGgNALgFQAMgFAQAAQAQAAALAFQALAFAGANQAGALAAAWQAAAVgGANQgGAMgLAFQgLAFgQAAQgQAAgMgFgAMNgPQgHADgDAKQgDAIAAAQQAAAQADAJQADAJAHAEQAHAEAMAAQAMAAAHgEQAHgEADgJQADgJgBgQQABgQgDgIQgEgKgHgDQgHgEgLAAQgMAAgHAEgAH7BJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAFIAAAIIhKAEQAAAMADAIQADAHAIAEQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgFgAICgPQgHAEgCAIQgDAHAAALIA6gEQAAgIgCgHQgCgHgFgEQgGgEgMAAQgMAAgHAEgACRBJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAFIgBAIIhKAEQAAAMAEAIQADAHAIAEQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgFgACZgPQgHAEgDAIQgCAHgBALIA6gEQAAgIgBgHQgCgHgGgEQgGgEgLAAQgNAAgGAEgAqeBOQgRAAgLgIQgKgJgGgRIgBgIIgBgIIAAgGQAAgRAHgMQAHgNAOgIIALgEIAKgBIACAAQASAAANATIAAgFIARAAIAAA5IABAUIADATIgBAAIgQAAQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAgBAAgBIgCgNIgDAFIgFAFQgFAEgGACQgGACgHAAgAqrgMQgJAGgFALIgCAIIgBAJIAAAEQAAALAFAIQAEAJAIAGIAHADIAHABIAEAAQAfAAAAgmIAAgHQAAgQgFgIQgGgKgLgDIgDAAIgDAAQgNAAgIAGgAukBJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAFIgBAIIhKAEQAAAMAEAIQADAHAIAEQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgFgAucgPQgHAEgDAIQgCAHgBALIA6gEQAAgIgBgHQgCgHgGgEQgGgEgLAAQgNAAgGAEgA5SBJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAFIAAAIIhKAEQAAAMADAIQADAHAIAEQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgFgA5LgPQgHAEgCAIQgDAHAAALIA6gEQAAgIgCgHQgCgHgFgEQgGgEgMAAQgMAAgHAEgAeaBNQgFABgCgBQgDgBgBgDQgCgDAAgFQAAgIADgDQADgCAHAAQAHAAADACQADADAAAIQAAAFgBADQgBADgDABIgFAAIgDAAgAknBNQgFABgCgBQgDgBgBgDQgCgDAAgFQAAgIADgDQADgCAHAAQAHAAADACQADADAAAIQAAAFgBADQgBADgDABIgFAAIgDAAgAE4BLQgHgDgDgHQgEgIAAgOIAAg8IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQABAEAEACQADACAGAAIAHAAIAFgBIAAAOIgGABIgGAAIgDAAQgKAAgGgCgAxnBLQgHgDgDgHQgEgIAAgOIAAg8IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQABAEAEACQADACAGAAIAHAAIAFgBIAAAOIgGABIgGAAIgDAAQgKAAgGgCgAhRBIQgGgGAAgMIAAiCIARAAIAAB+QAAAIADACQACADAGAAIAEAAIAEgBIAAAOIgFABIgHAAIgCAAQgKAAgGgFgA81BIQgGgGAAgMIAAiCIARAAIAAB+QAAAIACACQADADAFAAIAEAAIAEgBIAAAOIgFABIgGAAIgCAAQgLAAgFgFgAKsBNIgMAAIgLgBIgJgCIAAgPIAKACIALACIALAAQAMAAAGgDQAHgEAAgJQAAgHgCgDQgCgEgFgCQgFgDgKgCQgMgCgHgEQgHgEgCgGQgDgGAAgIQAAgOAKgIQAKgIATAAIAQABIAMADIgCAPQgEgCgHgBQgHgCgIAAQgLAAgGAEQgGADAAAJQAAAFACADQACADAEACQAFACAIABQANADAHAEQAIAEADAGQADAHAAAKQAAAQgKAIQgLAHgSAAIgCAAgAdZBMIAAhFQAAgHgCgGQgBgGgFgDQgEgDgJAAQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAhsIARAAIAAAQQADgHAGgEQAGgEAGgBIAOgCQAOAAAIAFQAIAEADAIQAEAIgBAKIAABLgAbcBMIAAhsIARAAIAABsgAYUBMIAAhsIARAAIAAAUQADgJAGgFQAGgEAGgCIAOgCIACAAIgBAQIgCAAQgHAAgHACQgGACgGAFQgFAFgDAJIAABHgAWdBMIAAhdIgTAAIAAgPIATAAIAAgBQAAgSAEgKQAFgKAIgDQAIgDALAAIAGAAIAGABIAAAOIgFgBIgHAAQgHAAgEADQgFACgBAHQgCAHAAAMIAaAAIAAAPIgaAAIAABdgAQzBMIAAhFQAAgHgBgGQgCgGgEgDQgFgDgIAAQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAhsIARAAIAAAQQAEgHAGgEQAFgEAHgBIANgCQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgAG1BMIAAhFQAAgHgCgGQgCgGgEgDQgFgDgIAAQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAiYIARAAIAAA8QAEgHAGgEQAFgEAHgBIANgCQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgABXBMIgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAHAAIAlgsIAWAAIguAyIAxA6gAgdBMIAAhsIARAAIAABsgAjCBMIAAiLIATAAIAACLgAnHBMIAAhFQAAgHgBgGQgCgGgEgDQgFgDgIAAQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAhsIARAAIAAAQQAEgHAGgEQAFgEAHgBIANgCQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgApEBMIAAhsIARAAIAABsgAsMBMIAAhsIARAAIAAAUQAEgJAGgFQAFgEAHgCIANgCIACAAIAAAQIgDAAQgHAAgGACQgHACgFAFQgFAFgEAJIAABHgAvqBMIAAhFQAAgHgCgGQgBgGgFgDQgEgDgJAAQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAiYIARAAIAAA8QADgHAGgEQAGgEAGgBIAOgCQAOAAAIAFQAIAEADAIQAEAIgBAKIAABLgAzfBMIAAhFQAAgHgBgGQgCgGgEgDQgFgDgIAAQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAhsIARAAIAAAQQAEgHAGgEQAFgEAHgBIANgCQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgA1cBMIAAhsIARAAIAABsgA6MBMIgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAGAAIAmgsIAWAAIguAyIAwA6gA8BBMIAAhsIARAAIAABsgA+mBMIAAiLIASAAIAACLgAlugYIAFgRIAEgSIACgRIARAAQAAAHgDAJQgCAKgDAJIgIARgAmXgYIAGgRIAEgSIABgRIASAAQAAAHgDAJQgCAKgDAJIgIARgA2XgYQAAgIACgJIAGgSIAHgRIANAAIgFARIgEASIgCARgA2/gYQAAgIACgJIAGgSIAHgRIANAAIgFARIgEASIgCARgAbcg2QgCgCAAgGQAAgHACgCQADgCAFABQAGgBACACQADACAAAHQAAAGgDACQgCACgGAAQgFAAgDgCgAgcg2QgDgCABgGQgBgHADgCQACgCAGABQAFgBADACQACACAAAHQAAAGgCACQgDACgFAAQgGAAgCgCgApDg2QgDgCABgGQgBgHADgCQACgCAGABQAFgBADACQACACAAAHQAAAGgCACQgDACgFAAQgGAAgCgCgA1bg2QgDgCABgGQgBgHADgCQACgCAGABQAFgBADACQACACAAAHQAAAGgCACQgDACgFAAQgGAAgCgCgA8Bg2QgCgCAAgGQAAgHACgCQADgCAFABQAGgBACACQADACAAAHQAAAGgDACQgCACgGAAQgFAAgDgCg");
	this.shape.setTransform(241.525,30.275);

	this.instance_1 = new lib.元件32复制4();
	this.instance_1.setTransform(328.85,42.25,1,1,0,0,0,327.9,42.3);
	this.instance_1.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AaBBOQgQAAgLgIQgLgJgFgRIgCgIIAAgIIAAgGQAAgRAHgMQAGgNAOgIIALgEIAKgBIACAAQATAAAMATIAAgFIASAAIAAA5IABAUIACATIgBAAIgQAAQAAAAAAAAQgBAAAAgBQAAAAAAgBQgBgBAAgBIgBgNIgEAFIgEAFQgFAEgGACQgGACgHAAgAZ0gMQgIAGgFALIgCAIIgBAJIAAAEQAAALAEAIQAEAJAIAGIAHADIAIABIAEAAQAfAAAAgmIAAgHQAAgQgGgIQgFgKgLgDIgEAAIgDAAQgMAAgJAGgAUtBJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAGgNALgFQAMgFAQAAQAQAAALAFQALAFAGANQAGALAAAWQAAAVgGANQgGAMgLAFQgLAFgQAAQgQAAgMgFgAU2gPQgHADgDAKQgDAIAAAQQAAAQADAJQADAJAHAEQAHAEAMAAQAMAAAHgEQAHgEADgJQADgJgBgQQABgQgDgIQgEgKgHgDQgHgEgLAAQgMAAgHAEgAR0BHQgKgHgEgNQgEgNAAgQQAAgPAEgMQAEgNAKgIQAJgIASAAQAQAAAIAGQAJAGADAJIAAg/IARAAIAACYIgOAAIgDgSQgDAJgJAGQgJAFgPAAQgSAAgJgHgAR/gNQgGAGgCAIQgCAKAAALQAAALACAKQACAJAGAGQAGAFANABQANgBAHgEQAIgGADgJQADgJgBgNQABgNgDgJQgDgJgIgFQgHgFgNAAQgNAAgGAGgAN+BKQgIgFgEgIQgDgIAAgKIAAhLIASAAIAABEQAAAJABAGQACAGAFADQAEADAJAAQAHAAAGgCQAGgBAFgFQAFgEADgKIAAhJIARAAIAABsIgPAAIgCgQQgDAIgGAEQgFADgHACQgGABgHAAQgOAAgIgEgAMEBJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAGgNALgFQAMgFAQAAQAQAAALAFQALAFAGANQAGALAAAWQAAAVgGANQgGAMgLAFQgLAFgQAAQgQAAgMgFgAMNgPQgHADgDAKQgDAIAAAQQAAAQADAJQADAJAHAEQAHAEAMAAQAMAAAHgEQAHgEADgJQADgJgBgQQABgQgDgIQgEgKgHgDQgHgEgLAAQgMAAgHAEgAH7BJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAFIAAAIIhKAEQAAAMADAIQADAHAIAEQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgFgAICgPQgHAEgCAIQgDAHAAALIA6gEQAAgIgCgHQgCgHgFgEQgGgEgMAAQgMAAgHAEgACRBJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAFIgBAIIhKAEQAAAMAEAIQADAHAIAEQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgFgACZgPQgHAEgDAIQgCAHgBALIA6gEQAAgIgBgHQgCgHgGgEQgGgEgLAAQgNAAgGAEgAqeBOQgRAAgLgIQgKgJgGgRIgBgIIgBgIIAAgGQAAgRAHgMQAHgNAOgIIALgEIAKgBIACAAQASAAANATIAAgFIARAAIAAA5IABAUIADATIgBAAIgQAAQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAgBAAgBIgCgNIgDAFIgFAFQgFAEgGACQgGACgHAAgAqrgMQgJAGgFALIgCAIIgBAJIAAAEQAAALAFAIQAEAJAIAGIAHADIAHABIAEAAQAfAAAAgmIAAgHQAAgQgFgIQgGgKgLgDIgDAAIgDAAQgNAAgIAGgAukBJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAFIgBAIIhKAEQAAAMAEAIQADAHAIAEQAHAEANAAQAJAAAKgCQAJgCAGgDIAAAQIgIADIgNACIgPABQgQAAgMgFgAucgPQgHAEgDAIQgCAHgBALIA6gEQAAgIgBgHQgCgHgGgEQgGgEgLAAQgNAAgGAEgA5SBJQgLgFgGgMQgGgNAAgVQAAgWAGgLQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAFIAAAIIhKAEQAAAMADAIQADAHAIAEQAIAEANAAQAJAAAJgCQAJgCAHgDIAAAQIgJADIgNACIgPABQgQAAgLgFgA5LgPQgHAEgCAIQgDAHAAALIA6gEQAAgIgCgHQgCgHgFgEQgGgEgMAAQgMAAgHAEgAeaBNQgFABgCgBQgDgBgBgDQgCgDAAgFQAAgIADgDQADgCAHAAQAHAAADACQADADAAAIQAAAFgBADQgBADgDABIgFAAIgDAAgAknBNQgFABgCgBQgDgBgBgDQgCgDAAgFQAAgIADgDQADgCAHAAQAHAAADACQADADAAAIQAAAFgBADQgBADgDABIgFAAIgDAAgAE4BLQgHgDgDgHQgEgIAAgOIAAg8IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQABAEAEACQADACAGAAIAHAAIAFgBIAAAOIgGABIgGAAIgDAAQgKAAgGgCgAxnBLQgHgDgDgHQgEgIAAgOIAAg8IgQAAIAAgPIAQAAIAAgaIASAAIAAAaIAbAAIAAAPIgbAAIAAA7IABANQABAEAEACQADACAGAAIAHAAIAFgBIAAAOIgGABIgGAAIgDAAQgKAAgGgCgAhRBIQgGgGAAgMIAAiCIARAAIAAB+QAAAIADACQACADAGAAIAEAAIAEgBIAAAOIgFABIgHAAIgCAAQgKAAgGgFgA81BIQgGgGAAgMIAAiCIARAAIAAB+QAAAIACACQADADAFAAIAEAAIAEgBIAAAOIgFABIgGAAIgCAAQgLAAgFgFgAKsBNIgMAAIgLgBIgJgCIAAgPIAKACIALACIALAAQAMAAAGgDQAHgEAAgJQAAgHgCgDQgCgEgFgCQgFgDgKgCQgMgCgHgEQgHgEgCgGQgDgGAAgIQAAgOAKgIQAKgIATAAIAQABIAMADIgCAPQgEgCgHgBQgHgCgIAAQgLAAgGAEQgGADAAAJQAAAFACADQACADAEACQAFACAIABQANADAHAEQAIAEADAGQADAHAAAKQAAAQgKAIQgLAHgSAAIgCAAgAdZBMIAAhFQAAgHgCgGQgBgGgFgDQgEgDgJAAQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAhsIARAAIAAAQQADgHAGgEQAGgEAGgBIAOgCQAOAAAIAFQAIAEADAIQAEAIgBAKIAABLgAbcBMIAAhsIARAAIAABsgAYUBMIAAhsIARAAIAAAUQADgJAGgFQAGgEAGgCIAOgCIACAAIgBAQIgCAAQgHAAgHACQgGACgGAFQgFAFgDAJIAABHgAWdBMIAAhdIgTAAIAAgPIATAAIAAgBQAAgSAEgKQAFgKAIgDQAIgDALAAIAGAAIAGABIAAAOIgFgBIgHAAQgHAAgEADQgFACgBAHQgCAHAAAMIAaAAIAAAPIgaAAIAABdgAQzBMIAAhFQAAgHgBgGQgCgGgEgDQgFgDgIAAQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAhsIARAAIAAAQQAEgHAGgEQAFgEAHgBIANgCQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgAG1BMIAAhFQAAgHgCgGQgCgGgEgDQgFgDgIAAQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAiYIARAAIAAA8QAEgHAGgEQAFgEAHgBIANgCQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgABXBMIgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAHAAIAlgsIAWAAIguAyIAxA6gAgdBMIAAhsIARAAIAABsgAjCBMIAAiLIATAAIAACLgAnHBMIAAhFQAAgHgBgGQgCgGgEgDQgFgDgIAAQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAhsIARAAIAAAQQAEgHAGgEQAFgEAHgBIANgCQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgApEBMIAAhsIARAAIAABsgAsMBMIAAhsIARAAIAAAUQAEgJAGgFQAFgEAHgCIANgCIACAAIAAAQIgDAAQgHAAgGACQgHACgFAFQgFAFgEAJIAABHgAvqBMIAAhFQAAgHgCgGQgBgGgFgDQgEgDgJAAQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAiYIARAAIAAA8QADgHAGgEQAGgEAGgBIAOgCQAOAAAIAFQAIAEADAIQAEAIgBAKIAABLgAzfBMIAAhFQAAgHgBgGQgCgGgEgDQgFgDgIAAQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAhsIARAAIAAAQQAEgHAGgEQAFgEAHgBIANgCQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgA1cBMIAAhsIARAAIAABsgA6MBMIgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAGAAIAmgsIAWAAIguAyIAwA6gA8BBMIAAhsIARAAIAABsgA+mBMIAAiLIASAAIAACLgAlugYIAFgRIAEgSIACgRIARAAQAAAHgDAJQgCAKgDAJIgIARgAmXgYIAGgRIAEgSIABgRIASAAQAAAHgDAJQgCAKgDAJIgIARgA2XgYQAAgIACgJIAGgSIAHgRIANAAIgFARIgEASIgCARgA2/gYQAAgIACgJIAGgSIAHgRIANAAIgFARIgEASIgCARgAbcg2QgCgCAAgGQAAgHACgCQADgCAFABQAGgBACACQADACAAAHQAAAGgDACQgCACgGAAQgFAAgDgCgAgcg2QgDgCABgGQgBgHADgCQACgCAGABQAFgBADACQACACAAAHQAAAGgCACQgDACgFAAQgGAAgCgCgApDg2QgDgCABgGQgBgHADgCQACgCAGABQAFgBADACQACACAAAHQAAAGgCACQgDACgFAAQgGAAgCgCgA1bg2QgDgCABgGQgBgHADgCQACgCAGABQAFgBADACQACACAAAHQAAAGgCACQgDACgFAAQgGAAgCgCgA8Bg2QgCgCAAgGQAAgHACgCQADgCAFABQAGgBACACQADACAAAHQAAAGgDACQgCACgGAAQgFAAgDgCg");
	this.shape_1.setTransform(241.525,30.275);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.shape}]}).to({state:[{t:this.instance_1},{t:this.shape_1}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-6,-7.1,475,80);
p.frameBounds = [rect, rect];


(lib.元件21复制3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));

	// 图层_3
	this.instance = new lib.元件23();
	this.instance.setTransform(273.25,29.8,1.8863,1.0226,0,0,0,125.6,23.6);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.元件23(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A3yBSQAJAAAGgDQAGgCAEgGQAEgFADgJIgshsIATAAIAhBaIACAAIAfhaIASAAIgnBoQgFAOgGAKQgGAKgKAFQgJAFgQAAgAfkA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAIARABIAMADIAAAQQgGgCgHgCQgHgBgJAAQgMAAgHADQgHAFgDAJQgDAJAAAPQAAAQADAIQADAKAHADQAIAEAMgBIAPAAQAHgCAGgCIAAAQIgIACIgKACIgLAAQgQAAgLgFgAdlA2QgIgEgEgIQgDgIAAgKIAAhLIASAAIAABEQAAAIABAHQACAGAFADQAEACAJAAQAHABAGgCQAGgCAFgEQAFgFADgJIAAhJIARAAIAABsIgPAAIgCgQQgDAIgGADQgFAEgHACQgGABgHAAQgOAAgIgFgAbiA0QgKgIgDgMQgEgNAAgQQAAgPAEgNQADgMAKgIQAKgIASAAQAQAAAIAGQAIAFADAKIAAg/IASAAIAACYIgPAAIgDgSQgDAJgJAFQgIAGgPAAQgSAAgKgHgAbtggQgGAFgCAKQgCAJAAALQAAALACAKQACAJAHAGQAGAFAMAAQANAAAIgEQAHgGADgJQADgJAAgNQAAgMgDgKQgDgJgHgFQgIgFgNAAQgMgBgHAHgAY/A2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAGIAAAHIhKAEQAAAMADAHQADAIAIAEQAIADANAAQAJAAAJgBQAJgCAHgEIAAAQIgJADIgNADIgPABQgQAAgLgFgAZGgjQgHAFgCAIQgDAIAAALIA6gFQAAgHgCgIQgCgHgFgFQgGgDgMAAQgMAAgHADgASHA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQAMgFAQAAQAQAAALAFQALAFAGANQAGAMAAAVQAAAVgGAMQgGANgLAFQgLAFgQAAQgQAAgMgFgASQgjQgHAEgDAKQgDAIAAAQQAAAQADAIQADAJAHAFQAHADAMAAQAMAAAHgDQAHgFADgJQADgIgBgQQABgQgDgIQgEgKgHgEQgHgDgLAAQgMAAgHADgAPOA0QgKgIgEgMQgEgNAAgQQAAgPAEgNQAEgMAKgIQAJgIASAAQAQAAAIAGQAJAFADAKIAAg/IARAAIAACYIgOAAIgDgSQgDAJgJAFQgJAGgPAAQgSAAgJgHgAPZggQgGAFgCAKQgCAJAAALQAAALACAKQACAJAGAGQAGAFANAAQANAAAHgEQAIgGADgJQADgJgBgNQABgMgDgKQgDgJgIgFQgHgFgNAAQgNgBgGAHgALYA2QgIgEgEgIQgDgIAAgKIAAhLIASAAIAABEQAAAIABAHQACAGAFADQAEACAJAAQAHABAGgCQAGgCAFgEQAFgFADgJIAAhJIARAAIAABsIgPAAIgCgQQgDAIgGADQgFAEgHACQgGABgHAAQgOAAgIgFgAJeA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQAMgFAQAAQAQAAALAFQALAFAGANQAGAMAAAVQAAAVgGAMQgGANgLAFQgLAFgQAAQgQAAgMgFgAJngjQgHAEgDAKQgDAIAAAQQAAAQADAIQADAJAHAFQAHADAMAAQAMAAAHgDQAHgFADgJQADgIgBgQQABgQgDgIQgEgKgHgEQgHgDgLAAQgMAAgHADgAFVA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAGIAAAHIhKAEQAAAMADAHQADAIAIAEQAIADANAAQAJAAAJgBQAJgCAHgEIAAAQIgJADIgNADIgPABQgQAAgLgFgAFcgjQgHAFgCAIQgDAIAAALIA6gFQAAgHgCgIQgCgHgFgFQgGgDgMAAQgMAAgHADgAgUA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAPAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhJAEQAAAMAEAHQADAIAIAEQAHADAMAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgPAAgMgFgAgMgjQgHAFgDAIQgCAIgBALIA5gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgMAAgGADgAroA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgArggjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgAx+A2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgAx2gjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgA5RA1QgIgFgDgKIgCATIgPAAIAAiYIARAAIAABAQADgKAIgGQAJgGAPAAQASAAAKAHQAKAHAEANQADAMAAARQAAAPgDANQgEANgKAHQgKAIgSAAQgPAAgJgGgA5PgiQgIAGgDAJQgDAJAAANQAAAMADAJQADAKAIAFQAHAFANAAQANAAAGgGQAGgFACgKQACgKAAgKQAAgLgCgKQgCgJgGgFQgGgHgNABQgNAAgHAEgA9kA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgA9cgjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgEAisAA6QgFAAgDAAQgDgCgBgDQgBgCAAgGQAAgHADgDQADgDAHABQAHgBADADQADADAAAHQAAAGgCACQgBADgDACIgEAAIgDAAgAnNA6QgFAAgCAAQgDgCgBgDQgCgCAAgGQAAgHADgDQADgDAHABQAHgBADADQADADAAAHQAAAGgBACQgBADgDACIgFAAIgDAAgAV8A3QgHgCgDgIQgEgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIASAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQABAFAEACQADACAGgBIAHAAIAFAAIAAAOIgGABIgGAAIgDAAQgKAAgGgDgACSA3QgHgCgDgIQgEgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIASAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQABAFAEACQADACAGgBIAHAAIAFAAIAAAOIgGABIgGAAIgDAAQgKAAgGgDgA1BA3QgHgCgDgIQgDgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIARAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQACAFADACQADACAHgBIAGAAIAGAAIAAAOIgGABIgGAAIgEAAQgJAAgHgDgAj3A1QgGgGAAgMIAAiCIARAAIAAB+QAAAHADADQACADAGgBIAEAAIAEAAIAAAOIgFABIgHAAIgCAAQgKAAgGgFgEghHAA1QgGgGAAgMIAAiCIARAAIAAB+QAAAHADADQACADAGgBIAEAAIAEAAIAAAOIgFABIgHAAIgCAAQgKAAgGgFgAIGA6IgLAAIgMgBIgIgDIAAgOIAJACIALABIALABQANAAAGgDQAGgFAAgJQABgGgCgEQgCgDgFgCQgGgDgKgCQgMgDgHgEQgGgCgDgHQgDgGAAgIQABgOAJgIQAKgIAUAAIAPABIAMADIgBAOQgFgCgHAAQgHgCgHAAQgMAAgFADQgGAEAAAJQAAAGABADQACADAFABQAEACAJACQAMADAIADQAHAEADAGQAEAGAAAKQAAARgLAIQgKAHgSAAIgDAAgEAh2AA5IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAHAAIAlgsIAWAAIguAyIAxA6gAX5A5IAAhEQAAgIgCgHQgBgFgFgEQgEgDgJABQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAiYIARAAIAAA7QADgGAGgEQAGgEAGgCIAOgBQAOAAAIAFQAIAEADAIQAEAIgBAKIAABLgAT3A5IAAheIgSAAIAAgOIASAAIAAgBQAAgSAFgLQAEgJAIgDQAJgEALAAIAGABIAGABIAAANIgFAAIgHAAQgIgBgEADQgEADgCAHQgCAGAAANIAaAAIAAAOIgaAAIAABegAONA5IAAhEQAAgIgBgHQgCgFgEgEQgFgDgIABQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAhsIARAAIAAAPQAEgGAGgEQAFgEAHgCIANgBQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgAEPA5IAAhEQAAgIgCgHQgBgFgFgEQgEgDgJABQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAiYIARAAIAAA7QADgGAGgEQAGgEAGgCIAOgBQAOAAAIAFQAIAEADAIQAEAIgBAKIAABLgAhOA5IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAHAAIAlgsIAWAAIguAyIAxA6gAjDA5IAAhsIARAAIAABsgAloA5IAAiLIATAAIAACLgAqEA5IAAhsIARAAIAAAUQAEgJAGgFQAFgEAHgDIANgBIACAAIAAAQIgDAAQgHgBgGACQgHACgFAGQgFAFgEAKIAABGgAtKA5IgphsIARAAIAhBbIACAAIAghbIASAAIgpBsgAuZA5IAAhsIARAAIAABsgAvlA5IAAhsIARAAIAAAUQADgJAGgFQAGgEAGgDIAOgBIACAAIgBAQIgCAAQgHgBgHACQgGACgGAGQgFAFgDAKIAABGgAzDA5IAAhEQAAgIgCgHQgCgFgEgEQgFgDgIABQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAiYIARAAIAAA7QAEgGAGgEQAFgEAHgCIANgBQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgA+eA5IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAHAAIAlgsIAWAAIguAyIAxA6gEggTAA5IAAhsIARAAIAABsgEgi4AA5IAAiLIATAAIAACLgAoUgsIAFgRIAEgSIACgQIARAAQAAAHgDAJQgCAKgDAIIgIARgAo9gsIAGgRIAEgSIABgQIASAAQAAAHgDAJQgCAKgDAIIgIARgA6ogsQAAgHACgKIAFgSIAIgQIANAAIgGAQIgEASIgBARgA7RgsQAAgHADgKIAFgSIAIgQIANAAIgGAQIgEASIgBARgAjChJQgDgCABgHQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAHgCACQgDACgFAAQgGAAgCgCgAuYhJQgDgCABgHQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAHgCACQgDACgFAAQgGAAgCgCgEggSgBJQgDgCABgHQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAHgCACQgDACgFAAQgGAAgCgCg");
	this.shape.setTransform(269.875,32.2);

	this.instance_1 = new lib.元件32复制5();
	this.instance_1.setTransform(328.85,42.25,1,1,0,0,0,327.9,42.3);
	this.instance_1.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("A3yBSQAJAAAGgDQAGgCAEgGQAEgFADgJIgshsIATAAIAhBaIACAAIAfhaIASAAIgnBoQgFAOgGAKQgGAKgKAFQgJAFgQAAgAfkA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAIARABIAMADIAAAQQgGgCgHgCQgHgBgJAAQgMAAgHADQgHAFgDAJQgDAJAAAPQAAAQADAIQADAKAHADQAIAEAMgBIAPAAQAHgCAGgCIAAAQIgIACIgKACIgLAAQgQAAgLgFgAdlA2QgIgEgEgIQgDgIAAgKIAAhLIASAAIAABEQAAAIABAHQACAGAFADQAEACAJAAQAHABAGgCQAGgCAFgEQAFgFADgJIAAhJIARAAIAABsIgPAAIgCgQQgDAIgGADQgFAEgHACQgGABgHAAQgOAAgIgFgAbiA0QgKgIgDgMQgEgNAAgQQAAgPAEgNQADgMAKgIQAKgIASAAQAQAAAIAGQAIAFADAKIAAg/IASAAIAACYIgPAAIgDgSQgDAJgJAFQgIAGgPAAQgSAAgKgHgAbtggQgGAFgCAKQgCAJAAALQAAALACAKQACAJAHAGQAGAFAMAAQANAAAIgEQAHgGADgJQADgJAAgNQAAgMgDgKQgDgJgHgFQgIgFgNAAQgMgBgHAHgAY/A2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAGIAAAHIhKAEQAAAMADAHQADAIAIAEQAIADANAAQAJAAAJgBQAJgCAHgEIAAAQIgJADIgNADIgPABQgQAAgLgFgAZGgjQgHAFgCAIQgDAIAAALIA6gFQAAgHgCgIQgCgHgFgFQgGgDgMAAQgMAAgHADgASHA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQAMgFAQAAQAQAAALAFQALAFAGANQAGAMAAAVQAAAVgGAMQgGANgLAFQgLAFgQAAQgQAAgMgFgASQgjQgHAEgDAKQgDAIAAAQQAAAQADAIQADAJAHAFQAHADAMAAQAMAAAHgDQAHgFADgJQADgIgBgQQABgQgDgIQgEgKgHgEQgHgDgLAAQgMAAgHADgAPOA0QgKgIgEgMQgEgNAAgQQAAgPAEgNQAEgMAKgIQAJgIASAAQAQAAAIAGQAJAFADAKIAAg/IARAAIAACYIgOAAIgDgSQgDAJgJAFQgJAGgPAAQgSAAgJgHgAPZggQgGAFgCAKQgCAJAAALQAAALACAKQACAJAGAGQAGAFANAAQANAAAHgEQAIgGADgJQADgJgBgNQABgMgDgKQgDgJgIgFQgHgFgNAAQgNgBgGAHgALYA2QgIgEgEgIQgDgIAAgKIAAhLIASAAIAABEQAAAIABAHQACAGAFADQAEACAJAAQAHABAGgCQAGgCAFgEQAFgFADgJIAAhJIARAAIAABsIgPAAIgCgQQgDAIgGADQgFAEgHACQgGABgHAAQgOAAgIgFgAJeA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQAMgFAQAAQAQAAALAFQALAFAGANQAGAMAAAVQAAAVgGAMQgGANgLAFQgLAFgQAAQgQAAgMgFgAJngjQgHAEgDAKQgDAIAAAQQAAAQADAIQADAJAHAFQAHADAMAAQAMAAAHgDQAHgFADgJQADgIgBgQQABgQgDgIQgEgKgHgEQgHgDgLAAQgMAAgHADgAFVA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAGIAAAHIhKAEQAAAMADAHQADAIAIAEQAIADANAAQAJAAAJgBQAJgCAHgEIAAAQIgJADIgNADIgPABQgQAAgLgFgAFcgjQgHAFgCAIQgDAIAAALIA6gFQAAgHgCgIQgCgHgFgFQgGgDgMAAQgMAAgHADgAgUA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAPAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhJAEQAAAMAEAHQADAIAIAEQAHADAMAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgPAAgMgFgAgMgjQgHAFgDAIQgCAIgBALIA5gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgMAAgGADgAroA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgArggjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgAx+A2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgAx2gjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgA5RA1QgIgFgDgKIgCATIgPAAIAAiYIARAAIAABAQADgKAIgGQAJgGAPAAQASAAAKAHQAKAHAEANQADAMAAARQAAAPgDANQgEANgKAHQgKAIgSAAQgPAAgJgGgA5PgiQgIAGgDAJQgDAJAAANQAAAMADAJQADAKAIAFQAHAFANAAQANAAAGgGQAGgFACgKQACgKAAgKQAAgLgCgKQgCgJgGgFQgGgHgNABQgNAAgHAEgA9kA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgA9cgjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgEAisAA6QgFAAgDAAQgDgCgBgDQgBgCAAgGQAAgHADgDQADgDAHABQAHgBADADQADADAAAHQAAAGgCACQgBADgDACIgEAAIgDAAgAnNA6QgFAAgCAAQgDgCgBgDQgCgCAAgGQAAgHADgDQADgDAHABQAHgBADADQADADAAAHQAAAGgBACQgBADgDACIgFAAIgDAAgAV8A3QgHgCgDgIQgEgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIASAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQABAFAEACQADACAGgBIAHAAIAFAAIAAAOIgGABIgGAAIgDAAQgKAAgGgDgACSA3QgHgCgDgIQgEgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIASAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQABAFAEACQADACAGgBIAHAAIAFAAIAAAOIgGABIgGAAIgDAAQgKAAgGgDgA1BA3QgHgCgDgIQgDgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIARAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQACAFADACQADACAHgBIAGAAIAGAAIAAAOIgGABIgGAAIgEAAQgJAAgHgDgAj3A1QgGgGAAgMIAAiCIARAAIAAB+QAAAHADADQACADAGgBIAEAAIAEAAIAAAOIgFABIgHAAIgCAAQgKAAgGgFgEghHAA1QgGgGAAgMIAAiCIARAAIAAB+QAAAHADADQACADAGgBIAEAAIAEAAIAAAOIgFABIgHAAIgCAAQgKAAgGgFgAIGA6IgLAAIgMgBIgIgDIAAgOIAJACIALABIALABQANAAAGgDQAGgFAAgJQABgGgCgEQgCgDgFgCQgGgDgKgCQgMgDgHgEQgGgCgDgHQgDgGAAgIQABgOAJgIQAKgIAUAAIAPABIAMADIgBAOQgFgCgHAAQgHgCgHAAQgMAAgFADQgGAEAAAJQAAAGABADQACADAFABQAEACAJACQAMADAIADQAHAEADAGQAEAGAAAKQAAARgLAIQgKAHgSAAIgDAAgEAh2AA5IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAHAAIAlgsIAWAAIguAyIAxA6gAX5A5IAAhEQAAgIgCgHQgBgFgFgEQgEgDgJABQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAiYIARAAIAAA7QADgGAGgEQAGgEAGgCIAOgBQAOAAAIAFQAIAEADAIQAEAIgBAKIAABLgAT3A5IAAheIgSAAIAAgOIASAAIAAgBQAAgSAFgLQAEgJAIgDQAJgEALAAIAGABIAGABIAAANIgFAAIgHAAQgIgBgEADQgEADgCAHQgCAGAAANIAaAAIAAAOIgaAAIAABegAONA5IAAhEQAAgIgBgHQgCgFgEgEQgFgDgIABQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAhsIARAAIAAAPQAEgGAGgEQAFgEAHgCIANgBQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgAEPA5IAAhEQAAgIgCgHQgBgFgFgEQgEgDgJABQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAiYIARAAIAAA7QADgGAGgEQAGgEAGgCIAOgBQAOAAAIAFQAIAEADAIQAEAIgBAKIAABLgAhOA5IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAHAAIAlgsIAWAAIguAyIAxA6gAjDA5IAAhsIARAAIAABsgAloA5IAAiLIATAAIAACLgAqEA5IAAhsIARAAIAAAUQAEgJAGgFQAFgEAHgDIANgBIACAAIAAAQIgDAAQgHgBgGACQgHACgFAGQgFAFgEAKIAABGgAtKA5IgphsIARAAIAhBbIACAAIAghbIASAAIgpBsgAuZA5IAAhsIARAAIAABsgAvlA5IAAhsIARAAIAAAUQADgJAGgFQAGgEAGgDIAOgBIACAAIgBAQIgCAAQgHgBgHACQgGACgGAGQgFAFgDAKIAABGgAzDA5IAAhEQAAgIgCgHQgCgFgEgEQgFgDgIABQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAiYIARAAIAAA7QAEgGAGgEQAFgEAHgCIANgBQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgA+eA5IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAHAAIAlgsIAWAAIguAyIAxA6gEggTAA5IAAhsIARAAIAABsgEgi4AA5IAAiLIATAAIAACLgAoUgsIAFgRIAEgSIACgQIARAAQAAAHgDAJQgCAKgDAIIgIARgAo9gsIAGgRIAEgSIABgQIASAAQAAAHgDAJQgCAKgDAIIgIARgA6ogsQAAgHACgKIAFgSIAIgQIANAAIgGAQIgEASIgBARgA7RgsQAAgHADgKIAFgSIAIgQIANAAIgGAQIgEASIgBARgAjChJQgDgCABgHQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAHgCACQgDACgFAAQgGAAgCgCgAuYhJQgDgCABgHQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAHgCACQgDACgFAAQgGAAgCgCgEggSgBJQgDgCABgHQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAHgCACQgDACgFAAQgGAAgCgCg");
	this.shape_1.setTransform(269.875,32.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.shape}]}).to({state:[{t:this.instance_1},{t:this.shape_1}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-6,-7.1,537,80);
p.frameBounds = [rect, rect];


(lib.元件21 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));

	// 图层_3
	this.instance = new lib.元件23();
	this.instance.setTransform(261.7,29.7,1.8051,1.0226,0,0,0,125.5,23.5);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.元件23(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// 图层_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A21BSQAKAAAGgDQAGgCAEgGQAEgFACgJIgrhsIATAAIAhBaIABAAIAghaIARAAIgnBoQgFAOgGAKQgGAKgJAFQgKAFgQAAgAfuA0QgKgIgEgMQgEgNAAgQQAAgPAEgNQAEgMAKgIQAJgIASAAQAQAAAIAGQAJAFADAKIAAg/IARAAIAACYIgOAAIgDgSQgDAJgJAFQgJAGgPAAQgSAAgJgHgAf5ggQgGAFgCAKQgCAJAAALQAAALACAKQACAJAGAGQAGAFANAAQANAAAHgEQAIgGADgJQADgJgBgNQABgMgDgKQgDgJgIgFQgHgFgNAAQgNgBgGAHgAb9A1QgIgFgEgKIgCATIgPAAIAAiYIARAAIAABAQAEgKAIgGQAIgGAQAAQASAAAKAHQAKAHADANQAEAMAAARQAAAPgEANQgDANgKAHQgKAIgSAAQgQAAgIgGgAb+giQgHAGgDAJQgDAJAAANQAAAMADAJQADAKAHAFQAIAFANAAQAMAAAHgGQAGgFACgKQACgKAAgKQAAgLgCgKQgCgJgHgFQgGgHgMABQgNAAgIAEgAZIA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAGIAAAHIhKAEQAAAMADAHQADAIAIAEQAIADANAAQAJAAAJgBQAJgCAHgEIAAAQIgJADIgNADIgPABQgQAAgLgFgAZPgjQgHAFgCAIQgDAIAAALIA6gFQAAgHgCgIQgCgHgFgFQgGgDgMAAQgMAAgHADgASQA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQAMgFAQAAQAQAAALAFQALAFAGANQAGAMAAAVQAAAVgGAMQgGANgLAFQgLAFgQAAQgQAAgMgFgASZgjQgHAEgDAKQgDAIAAAQQAAAQADAIQADAJAHAFQAHADAMAAQAMAAAHgDQAHgFADgJQADgIgBgQQABgQgDgIQgEgKgHgEQgHgDgLAAQgMAAgHADgAPXA0QgKgIgEgMQgEgNAAgQQAAgPAEgNQAEgMAKgIQAJgIASAAQAQAAAIAGQAJAFADAKIAAg/IARAAIAACYIgOAAIgDgSQgDAJgJAFQgJAGgPAAQgSAAgJgHgAPiggQgGAFgCAKQgCAJAAALQAAALACAKQACAJAGAGQAGAFANAAQANAAAHgEQAIgGADgJQADgJgBgNQABgMgDgKQgDgJgIgFQgHgFgNAAQgNgBgGAHgALhA2QgIgEgEgIQgDgIAAgKIAAhLIASAAIAABEQAAAIABAHQACAGAFADQAEACAJAAQAHABAGgCQAGgCAFgEQAFgFADgJIAAhJIARAAIAABsIgPAAIgCgQQgDAIgGADQgFAEgHACQgGABgHAAQgOAAgIgFgAJnA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQAMgFAQAAQAQAAALAFQALAFAGANQAGAMAAAVQAAAVgGAMQgGANgLAFQgLAFgQAAQgQAAgMgFgAJwgjQgHAEgDAKQgDAIAAAQQAAAQADAIQADAJAHAFQAHADAMAAQAMAAAHgDQAHgFADgJQADgIgBgQQABgQgDgIQgEgKgHgEQgHgDgLAAQgMAAgHADgAFeA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAGIAAAHIhKAEQAAAMADAHQADAIAIAEQAIADANAAQAJAAAJgBQAJgCAHgEIAAAQIgJADIgNADIgPABQgQAAgLgFgAFlgjQgHAFgCAIQgDAIAAALIA6gFQAAgHgCgIQgCgHgFgFQgGgDgMAAQgMAAgHADgAgLA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAPAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhJAEQAAAMAEAHQADAIAIAEQAGADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgLgFgAgDgjQgHAFgDAIQgCAIgBALIA5gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgFADgAqSA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAGIAAAHIhKAEQAAAMADAHQADAIAIAEQAIADANAAQAJAAAJgBQAJgCAHgEIAAAQIgJADIgNADIgPABQgQAAgLgFgAqLgjQgHAFgCAIQgDAIAAALIA6gFQAAgHgCgIQgCgHgFgFQgGgDgMAAQgMAAgHADgAsHA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAGIAAAHIhKAEQAAAMADAHQADAIAIAEQAIADANAAQAJAAAJgBQAJgCAHgEIAAAQIgJADIgNADIgPABQgQAAgLgFgAsAgjQgHAFgCAIQgDAIAAALIA6gFQAAgHgCgIQgCgHgFgFQgGgDgMAAQgMAAgHADgAxBA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgAw5gjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgA4UA1QgIgFgDgKIgCATIgPAAIAAiYIARAAIAABAQADgKAIgGQAJgGAPAAQASAAAKAHQAKAHAEANQADAMAAARQAAAPgDANQgEANgKAHQgKAIgSAAQgPAAgJgGgA4SgiQgIAGgDAJQgDAJAAANQAAAMADAJQADAKAIAFQAHAFANAAQANAAAGgGQAGgFACgKQACgKAAgKQAAgLgCgKQgCgJgGgFQgGgHgNABQgNAAgHAEgA8nA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgA8fgjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgEAhvAA6QgFAAgDAAQgDgCgBgDQgBgCAAgGQAAgHADgDQADgDAHABQAHgBADADQADADAAAHQAAAGgCACQgBADgDACIgEAAIgDAAgAnEA6QgFAAgCAAQgDgCgBgDQgCgCAAgGQAAgHADgDQADgDAHABQAHgBADADQADADAAAHQAAAGgBACQgBADgDACIgFAAIgDAAgAWFA3QgHgCgDgIQgEgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIASAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQABAFAEACQADACAGgBIAHAAIAFAAIAAAOIgGABIgGAAIgDAAQgKAAgGgDgACbA3QgHgCgDgIQgEgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIASAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQABAFAEACQADACAGgBIAHAAIAFAAIAAAOIgGABIgGAAIgDAAQgKAAgGgDgAuaA3QgHgCgDgIQgEgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIASAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQABAFAEACQADACAGgBIAHAAIAFAAIAAAOIgGABIgGAAIgDAAQgKAAgGgDgA0EA3QgHgCgDgIQgDgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIARAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQACAFADACQADACAHgBIAGAAIAGAAIAAAOIgGABIgGAAIgEAAQgJAAgHgDgAjuA1QgGgGAAgMIAAiCIARAAIAAB+QAAAHADADQACADAGgBIAEAAIAEAAIAAAOIgFABIgHAAIgCAAQgKAAgGgFgEggKAA1QgGgGAAgMIAAiCIARAAIAAB+QAAAHADADQACADAGgBIAEAAIAEAAIAAAOIgFABIgHAAIgCAAQgKAAgGgFgAIPA6IgLAAIgMgBIgIgDIAAgOIAJACIALABIALABQANAAAGgDQAGgFAAgJQABgGgCgEQgCgDgFgCQgGgDgKgCQgMgDgHgEQgGgCgDgHQgDgGAAgIQABgOAJgIQAKgIAUAAIAPABIAMADIgBAOQgFgCgHAAQgHgCgHAAQgMAAgFADQgGAEAAAJQAAAGABADQACADAFABQAEACAJACQAMADAIADQAHAEADAGQAEAGAAAKQAAARgLAIQgKAHgSAAIgDAAgAeWA5IAAhsIARAAIAAAUQAEgJAGgFQAFgEAHgDIANgBIACAAIAAAQIgDAAQgHgBgGACQgHACgFAGQgFAFgEAKIAABGgAdgA5IAAhsIARAAIAABsgAYCA5IAAhEQAAgIgCgHQgBgFgFgEQgEgDgJABQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAiYIARAAIAAA7QADgGAGgEQAGgEAGgCIAOgBQAOAAAIAFQAIAEADAIQAEAIgBAKIAABLgAUAA5IAAheIgSAAIAAgOIASAAIAAgBQAAgSAFgLQAEgJAIgDQAJgEALAAIAGABIAGABIAAANIgFAAIgHAAQgIgBgEADQgEADgCAHQgCAGAAANIAaAAIAAAOIgaAAIAABegAOWA5IAAhEQAAgIgBgHQgCgFgEgEQgFgDgIABQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAhsIARAAIAAAPQAEgGAGgEQAFgEAHgCIANgBQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgAEYA5IAAhEQAAgIgCgHQgBgFgFgEQgEgDgJABQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAiYIARAAIAAA7QADgGAGgEQAGgEAGgCIAOgBQAOAAAIAFQAIAEADAIQAEAIgBAKIAABLgAhFA5IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAHAAIAlgsIAWAAIguAyIAxA6gAi6A5IAAhsIARAAIAABsgAlfA5IAAiLIATAAIAACLgAtkA5IAAhsIARAAIAAAUQADgJAGgFQAGgEAGgDIAOgBIACAAIgBAQIgCAAQgHgBgHACQgGACgGAGQgFAFgDAKIAABGgAyGA5IAAhEQAAgIgCgHQgCgFgEgEQgFgDgIABQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAiYIARAAIAAA7QAEgGAGgEQAFgEAHgCIANgBQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgA9hA5IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAHAAIAlgsIAWAAIguAyIAxA6gA/WA5IAAhsIARAAIAABsgEgh7AA5IAAiLIATAAIAACLgAoLgsIAFgRIAEgSIACgQIARAAQAAAHgDAJQgCAKgDAIIgIARgAo0gsIAGgRIAEgSIABgQIASAAQAAAHgDAJQgCAKgDAIIgIARgA5rgsQAAgHACgKIAFgSIAIgQIANAAIgGAQIgEASIgBARgA6UgsQAAgHADgKIAFgSIAIgQIANAAIgGAQIgEASIgBARgAdhhJQgDgCABgHQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAHgCACQgDACgFAAQgGAAgCgCgAi5hJQgDgCABgHQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAHgCACQgDACgFAAQgGAAgCgCgA/VhJQgDgCABgHQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAHgCACQgDACgFAAQgGAAgCgCg");
	this.shape.setTransform(267.975,32.2);

	this.instance_1 = new lib.元件32复制();
	this.instance_1.setTransform(328.85,42.25,1,1,0,0,0,327.9,42.3);
	this.instance_1.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("A21BSQAKAAAGgDQAGgCAEgGQAEgFACgJIgrhsIATAAIAhBaIABAAIAghaIARAAIgnBoQgFAOgGAKQgGAKgJAFQgKAFgQAAgAfuA0QgKgIgEgMQgEgNAAgQQAAgPAEgNQAEgMAKgIQAJgIASAAQAQAAAIAGQAJAFADAKIAAg/IARAAIAACYIgOAAIgDgSQgDAJgJAFQgJAGgPAAQgSAAgJgHgAf5ggQgGAFgCAKQgCAJAAALQAAALACAKQACAJAGAGQAGAFANAAQANAAAHgEQAIgGADgJQADgJgBgNQABgMgDgKQgDgJgIgFQgHgFgNAAQgNgBgGAHgAb9A1QgIgFgEgKIgCATIgPAAIAAiYIARAAIAABAQAEgKAIgGQAIgGAQAAQASAAAKAHQAKAHADANQAEAMAAARQAAAPgEANQgDANgKAHQgKAIgSAAQgQAAgIgGgAb+giQgHAGgDAJQgDAJAAANQAAAMADAJQADAKAHAFQAIAFANAAQAMAAAHgGQAGgFACgKQACgKAAgKQAAgLgCgKQgCgJgHgFQgGgHgMABQgNAAgIAEgAZIA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAGIAAAHIhKAEQAAAMADAHQADAIAIAEQAIADANAAQAJAAAJgBQAJgCAHgEIAAAQIgJADIgNADIgPABQgQAAgLgFgAZPgjQgHAFgCAIQgDAIAAALIA6gFQAAgHgCgIQgCgHgFgFQgGgDgMAAQgMAAgHADgASQA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQAMgFAQAAQAQAAALAFQALAFAGANQAGAMAAAVQAAAVgGAMQgGANgLAFQgLAFgQAAQgQAAgMgFgASZgjQgHAEgDAKQgDAIAAAQQAAAQADAIQADAJAHAFQAHADAMAAQAMAAAHgDQAHgFADgJQADgIgBgQQABgQgDgIQgEgKgHgEQgHgDgLAAQgMAAgHADgAPXA0QgKgIgEgMQgEgNAAgQQAAgPAEgNQAEgMAKgIQAJgIASAAQAQAAAIAGQAJAFADAKIAAg/IARAAIAACYIgOAAIgDgSQgDAJgJAFQgJAGgPAAQgSAAgJgHgAPiggQgGAFgCAKQgCAJAAALQAAALACAKQACAJAGAGQAGAFANAAQANAAAHgEQAIgGADgJQADgJgBgNQABgMgDgKQgDgJgIgFQgHgFgNAAQgNgBgGAHgALhA2QgIgEgEgIQgDgIAAgKIAAhLIASAAIAABEQAAAIABAHQACAGAFADQAEACAJAAQAHABAGgCQAGgCAFgEQAFgFADgJIAAhJIARAAIAABsIgPAAIgCgQQgDAIgGADQgFAEgHACQgGABgHAAQgOAAgIgFgAJnA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQAMgFAQAAQAQAAALAFQALAFAGANQAGAMAAAVQAAAVgGAMQgGANgLAFQgLAFgQAAQgQAAgMgFgAJwgjQgHAEgDAKQgDAIAAAQQAAAQADAIQADAJAHAFQAHADAMAAQAMAAAHgDQAHgFADgJQADgIgBgQQABgQgDgIQgEgKgHgEQgHgDgLAAQgMAAgHADgAFeA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAGIAAAHIhKAEQAAAMADAHQADAIAIAEQAIADANAAQAJAAAJgBQAJgCAHgEIAAAQIgJADIgNADIgPABQgQAAgLgFgAFlgjQgHAFgCAIQgDAIAAALIA6gFQAAgHgCgIQgCgHgFgFQgGgDgMAAQgMAAgHADgAgLA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAPAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhJAEQAAAMAEAHQADAIAIAEQAGADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgLgFgAgDgjQgHAFgDAIQgCAIgBALIA5gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgFADgAqSA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAGIAAAHIhKAEQAAAMADAHQADAIAIAEQAIADANAAQAJAAAJgBQAJgCAHgEIAAAQIgJADIgNADIgPABQgQAAgLgFgAqLgjQgHAFgCAIQgDAIAAALIA6gFQAAgHgCgIQgCgHgFgFQgGgDgMAAQgMAAgHADgAsHA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAFgNALgFQALgFAQAAQAOAAAJAEQAIAEAFAHQAEAHACAIIACAPIgBAGIAAAHIhKAEQAAAMADAHQADAIAIAEQAIADANAAQAJAAAJgBQAJgCAHgEIAAAQIgJADIgNADIgPABQgQAAgLgFgAsAgjQgHAFgCAIQgDAIAAALIA6gFQAAgHgCgIQgCgHgFgFQgGgDgMAAQgMAAgHADgAxBA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgAw5gjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgA4UA1QgIgFgDgKIgCATIgPAAIAAiYIARAAIAABAQADgKAIgGQAJgGAPAAQASAAAKAHQAKAHAEANQADAMAAARQAAAPgDANQgEANgKAHQgKAIgSAAQgPAAgJgGgA4SgiQgIAGgDAJQgDAJAAANQAAAMADAJQADAKAIAFQAHAFANAAQANAAAGgGQAGgFACgKQACgKAAgKQAAgLgCgKQgCgJgGgFQgGgHgNABQgNAAgHAEgA8nA2QgLgFgGgNQgGgMAAgVQAAgVAGgMQAGgNALgFQALgFAQAAQANAAAJAEQAJAEAEAHQAFAHACAIIABAPIAAAGIgBAHIhKAEQAAAMAEAHQADAIAIAEQAHADANAAQAJAAAKgBQAJgCAGgEIAAAQIgIADIgNADIgPABQgQAAgMgFgA8fgjQgHAFgDAIQgCAIgBALIA6gFQAAgHgBgIQgCgHgGgFQgGgDgLAAQgNAAgGADgEAhvAA6QgFAAgDAAQgDgCgBgDQgBgCAAgGQAAgHADgDQADgDAHABQAHgBADADQADADAAAHQAAAGgCACQgBADgDACIgEAAIgDAAgAnEA6QgFAAgCAAQgDgCgBgDQgCgCAAgGQAAgHADgDQADgDAHABQAHgBADADQADADAAAHQAAAGgBACQgBADgDACIgFAAIgDAAgAWFA3QgHgCgDgIQgEgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIASAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQABAFAEACQADACAGgBIAHAAIAFAAIAAAOIgGABIgGAAIgDAAQgKAAgGgDgACbA3QgHgCgDgIQgEgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIASAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQABAFAEACQADACAGgBIAHAAIAFAAIAAAOIgGABIgGAAIgDAAQgKAAgGgDgAuaA3QgHgCgDgIQgEgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIASAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQABAFAEACQADACAGgBIAHAAIAFAAIAAAOIgGABIgGAAIgDAAQgKAAgGgDgA0EA3QgHgCgDgIQgDgHAAgOIAAg9IgQAAIAAgOIAQAAIAAgaIARAAIAAAaIAbAAIAAAOIgbAAIAAA8IABAMQACAFADACQADACAHgBIAGAAIAGAAIAAAOIgGABIgGAAIgEAAQgJAAgHgDgAjuA1QgGgGAAgMIAAiCIARAAIAAB+QAAAHADADQACADAGgBIAEAAIAEAAIAAAOIgFABIgHAAIgCAAQgKAAgGgFgEggKAA1QgGgGAAgMIAAiCIARAAIAAB+QAAAHADADQACADAGgBIAEAAIAEAAIAAAOIgFABIgHAAIgCAAQgKAAgGgFgAIPA6IgLAAIgMgBIgIgDIAAgOIAJACIALABIALABQANAAAGgDQAGgFAAgJQABgGgCgEQgCgDgFgCQgGgDgKgCQgMgDgHgEQgGgCgDgHQgDgGAAgIQABgOAJgIQAKgIAUAAIAPABIAMADIgBAOQgFgCgHAAQgHgCgHAAQgMAAgFADQgGAEAAAJQAAAGABADQACADAFABQAEACAJACQAMADAIADQAHAEADAGQAEAGAAAKQAAARgLAIQgKAHgSAAIgDAAgAeWA5IAAhsIARAAIAAAUQAEgJAGgFQAFgEAHgDIANgBIACAAIAAAQIgDAAQgHgBgGACQgHACgFAGQgFAFgEAKIAABGgAdgA5IAAhsIARAAIAABsgAYCA5IAAhEQAAgIgCgHQgBgFgFgEQgEgDgJABQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAiYIARAAIAAA7QADgGAGgEQAGgEAGgCIAOgBQAOAAAIAFQAIAEADAIQAEAIgBAKIAABLgAUAA5IAAheIgSAAIAAgOIASAAIAAgBQAAgSAFgLQAEgJAIgDQAJgEALAAIAGABIAGABIAAANIgFAAIgHAAQgIgBgEADQgEADgCAHQgCAGAAANIAaAAIAAAOIgaAAIAABegAOWA5IAAhEQAAgIgBgHQgCgFgEgEQgFgDgIABQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAhsIARAAIAAAPQAEgGAGgEQAFgEAHgCIANgBQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgAEYA5IAAhEQAAgIgCgHQgBgFgFgEQgEgDgJABQgHAAgGABQgHACgFAEQgFAFgDAJIAABJIgRAAIAAiYIARAAIAAA7QADgGAGgEQAGgEAGgCIAOgBQAOAAAIAFQAIAEADAIQAEAIgBAKIAABLgAhFA5IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAHAAIAlgsIAWAAIguAyIAxA6gAi6A5IAAhsIARAAIAABsgAlfA5IAAiLIATAAIAACLgAtkA5IAAhsIARAAIAAAUQADgJAGgFQAGgEAGgDIAOgBIACAAIgBAQIgCAAQgHgBgHACQgGACgGAGQgFAFgDAKIAABGgAyGA5IAAhEQAAgIgCgHQgCgFgEgEQgFgDgIABQgHAAgHABQgGACgFAEQgFAFgEAJIAABJIgRAAIAAiYIARAAIAAA7QAEgGAGgEQAFgEAHgCIANgBQAPAAAIAFQAHAEAEAIQADAIAAAKIAABLgA9hA5IgogzIgGAAIAAAzIgRAAIAAiYIARAAIAABYIAHAAIAlgsIAWAAIguAyIAxA6gA/WA5IAAhsIARAAIAABsgEgh7AA5IAAiLIATAAIAACLgAoLgsIAFgRIAEgSIACgQIARAAQAAAHgDAJQgCAKgDAIIgIARgAo0gsIAGgRIAEgSIABgQIASAAQAAAHgDAJQgCAKgDAIIgIARgA5rgsQAAgHACgKIAFgSIAIgQIANAAIgGAQIgEASIgBARgA6UgsQAAgHADgKIAFgSIAIgQIANAAIgGAQIgEASIgBARgAdhhJQgDgCABgHQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAHgCACQgDACgFAAQgGAAgCgCgAi5hJQgDgCABgHQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAHgCACQgDACgFAAQgGAAgCgCgA/VhJQgDgCABgHQgBgGADgCQACgCAGAAQAFAAADACQACACAAAGQAAAHgCACQgDACgFAAQgGAAgCgCg");
	this.shape_1.setTransform(267.975,32.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.shape}]}).to({state:[{t:this.instance_1},{t:this.shape_1}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-6,-7.1,523,80);
p.frameBounds = [rect, rect];


(lib.元件19 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		var _this=this;
		_this.stop();
		
		_this.addEventListener("click", fl_MouseClickHandler.bind(this));
		function fl_MouseClickHandler(e)
		{
			console.log(e.target.name);
			_this.gotoAndStop(parseInt(e.target.name.split("_")[1]) + 1);
			_this.parent.gotoPage(e.target.name.split("_")[1]);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4));

	// 图层_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AhTCXIDlkSYAJgLgCgPgKgJYgLgJgOABgJAKIj5EBYgOAPAAAYAPAOYAPAPAYAAAPgQYAAAAABgBABgB");
	this.shape.setTransform(-145.7,230.6,0.6696,0.6696,0,0,0,0.7,-0.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AhPgsIBWBwYAPATAbAEATgPYATgOADgcgOgTYgCgCgDgDgDgCIhvhXYgLgIgQACgJAKYgHAKABAMAGAJ");
	this.shape_1.setTransform(-157.45,235.35,0.6696,0.6696,0,0,0,-1.2,-1.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("rgba(52,198,194,0.8)").ss(8,1,1).p("ADYOyQAzAEA0AEQA9AFCjAVQCLASBTAFQFCARAbjhQAPiIgokAQgpkMAHh8QAEhZASilQARiwAFhOQAKiUgFhEQgMh8g9hLQgug4hUgMQg7gJhbANQghAFimAdQh6AVhMAHQkYAUjYgYQhTgIiighQihghhTgJIg6gCQiXAAhfBUQhhBWgQCfQgIBYAHCDQAEBKAHCTQAFDGgjEQQAAAKgcCmQgTB5gBBRQgJDvCMBWQBjA8CGADQBSABCdgcQB+gWCJgKQACAAADAA");
	this.shape_2.setTransform(-147.9579,134.0631);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("rgba(52,198,194,0.8)").ss(8,1,1).p("ADLO0QBAABA0AFQA9AFCjAVQCLASBTAFQFCARAbjhQAPiIgokAQgpkMAHh8QAEhZASilQARiwAFhOQAKiUgFhEQgMh8g9hLQgug4hUgMQg7gJhbANQghAFimAdQh6AVhMAHQkYAUjYgYQhTgIiighQihghhTgJIg6gCQiXAAhfBUQhhBWgQCfQgIBYAHCDQAEBKAHCTQAFDGgjEQQAAAKgcCmQgTB5gBBRQgJDvCMBWQBjA8CGADQBSABCdgcQBxgUCHgF");
	this.shape_3.setTransform(134.7421,133.1631);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("rgba(52,198,194,0.8)").ss(8,1,1).p("ADHOpQBEAMA0AFQA9AFCjAVQCLASBTAFQFCARAbjhQAPiIgokAQgpkMAHh8QAEhZASilQARiwAFhOQAKiUgFhEQgMh8g9hLQgug4hUgMQg7gJhbANQghAFimAdQh6AVhMAHQkYAUjYgYQhTgIiighQihghhTgJIg6gCQiXAAhfBUQhhBWgQCfQgIBYAHCDQAEBKAHCTQAFDGgjEQQAAAKgcCmQgTB5gBBRQgJDvCMBWQBjA8CGADQBSABCdgcQCFgXBzgU");
	this.shape_4.setTransform(416.0921,135.5131);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_2},{t:this.shape_1,p:{x:-157.45,y:235.35}},{t:this.shape,p:{x:-145.7,y:230.6}}]},1).to({state:[{t:this.shape_3},{t:this.shape_1,p:{x:125.15,y:234.85}},{t:this.shape,p:{x:136.85,y:230.1}}]},1).to({state:[{t:this.shape_4},{t:this.shape_1,p:{x:406.05,y:233.85}},{t:this.shape,p:{x:417.8,y:229.05}}]},1).wait(1));

	// 图层_3
	this.pg_2 = new lib.元件20();
	this.pg_2.name = "pg_2";
	this.pg_2.setTransform(410.55,134.65,2.8866,1.8525,0,0,0,52,26.5);
	new cjs.ButtonHelper(this.pg_2, 0, 1, 2, false, new lib.元件20(), 3);

	this.pg_1 = new lib.元件20();
	this.pg_1.name = "pg_1";
	this.pg_1.setTransform(129.4,134.4,2.8866,1.8525,0,0,0,52,26.5);
	new cjs.ButtonHelper(this.pg_1, 0, 1, 2, false, new lib.元件20(), 3);

	this.pg_0 = new lib.元件20();
	this.pg_0.name = "pg_0";
	this.pg_0.setTransform(-152.15,134.95,2.8602,1.8355,0,0,0,52.1,26.4);
	new cjs.ButtonHelper(this.pg_0, 0, 1, 2, false, new lib.元件20(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.pg_0},{t:this.pg_1},{t:this.pg_2}]}).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-260.4,32,787.7,203);
p.frameBounds = [rect, new cjs.Rectangle(-263.7,29.7,791,212.6), new cjs.Rectangle(-260.4,28.8,787.7,213), new cjs.Rectangle(-260.4,31.1,792.3,209.6)];


(lib.d1_1复制2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.instance = new lib.位图19();
	this.instance.setTransform(-95,-113,0.5245,0.5246);

	this.dia = new lib.元件21复制3();
	this.dia.name = "dia";
	this.dia.setTransform(108.4,-54.1,1,1,0,0,0,122.4,20.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.dia},{t:this.instance}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.d1_1复制2, rect = new cjs.Rectangle(-95,-113,612,111.9), [rect]);


(lib.d1_1复制 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.instance = new lib.位图19();
	this.instance.setTransform(-95,-113,0.5245,0.5246);

	this.dia = new lib.元件21复制4();
	this.dia.name = "dia";
	this.dia.setTransform(108.4,-54.1,1,1,0,0,0,122.4,20.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.dia},{t:this.instance}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.d1_1复制, rect = new cjs.Rectangle(-95,-113,550,111.9), [rect]);


(lib.d1_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 图层_1
	this.instance = new lib.位图19();
	this.instance.setTransform(-95,-113,0.5245,0.5246);

	this.dia = new lib.元件21();
	this.dia.name = "dia";
	this.dia.setTransform(108.4,-54.1,1,1,0,0,0,122.4,20.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.dia},{t:this.instance}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.d1_1, rect = new cjs.Rectangle(-95,-113,598,111.9), [rect]);


// stage content:
(lib.index = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		
		var _this = this;
		
		_this.pgId;
		_this.diaAry;
		_this.diaMcAry;
		_this.data;
		_this.curId = 0;
		_this.curPgDia; //存储当前页的所有对话mc
		_this.clickMode = false;
		_this.canClick = false;
		_this.start = false;
		_this.isEnded = false;
		//点击单词声音
		_this.audio;
		
		if (!this.isinit) {
			//console.log("第一次进入")
			this.isinit = true;
			init();
		}
		
		/*function playSoundBySrc(src) {
			audio.currentTime = 0;
			audio.pause();
			audio.src = src;
			console.log(audio.src);
			audio.play();
			_this.isEnded = false;
			_this._onp.setStu(false);
		}*/
		function playSoundBySrc(src) {
		    // 如果新源与当前源相同，不必重新设置
		    if (audio.src !== src) {
		        audio.pause(); // 暂停当前音频
		        audio.src = src; // 设置新音频源
		        audio.currentTime = 0; // 重置播放时间
		        
		        // 确保音频加载完成后再播放
		        audio.oncanplaythrough = function() {
		            audio.play().catch(function(error) {
		                console.error("播放错误:", error);
		            });
		            _this.isEnded = false;
		            _this._onp.setStu(false);
		            audio.oncanplaythrough = null; // 清除事件监听器
		        };
		        
		        // 触发加载
		        audio.load();
		    } else {
		        audio.currentTime = 0; // 如果源相同，重置播放时间并播放
		        audio.play().catch(function(error) {
		            console.error("播放错误:", error);
		        });
		        _this.isEnded = false;
		        _this._onp.setStu(false);
		    }
		}
		
		
		function init() {
			_this.pgId = 0;
			_this.diaAry = [2, 2, 2];
			_this.data = lesdata;
			hideDia();
		
			audio = new Audio();
			audio.addEventListener('play', function () {
				//console.log('被点击的单词开始播放');
			});
			audio.addEventListener('ended', function () {
				//播放结束事件。
				//console.log("播放结束。");
				_this.isEnded = true;
				resetDia();
				if (_this.clickMode) {
					_this._onp.setStu(true);
					//_this.clickMode=false;
					return;
				} //点读模式
				nextFun();
			});
		
		    //隐藏播放和清除按钮
		    _this._onp.visible=false;
		}
		
		_this.gotoPage = function (_pg) {
			if (_this.pgId == _pg && _this.start == true) {
				return;
			}
			//reset();
			_this.isEnded = true;
			_this.start = true;
			_this.pgId = _pg;
			_this.curId = 0;
			if(audio)audio.pause();
			_this.canClick = false;
			_this.clickMode = false;
			_this.gotoAndStop(_this.pgId);
			hideDia();
			updata();
		
			//reset();
			//console.log(_this.diaMcAry);
			//setTimeout(reset,1000);
		}
		
		function hideDia() {
			_this.curPgDia = [];
			//for(var i=1;i<=_this.diaAry[_this.pgId];i++){
			//console.log("##############################");
			//console.log(_this.data);
		    //console.log(_this.data[_this.pgId]);
			console.log(_this.data);
			for (var i = 1; i <= _this.data[_this.pgId].length; i++) {
				_this["dia_" + (parseInt(_this.pgId) + 1) + "_" + i].visible = false;
				_this["dia_" + (parseInt(_this.pgId) + 1) + "_" + i]["dia"].addEventListener("click", ondiamc);
				_this.curPgDia.push(_this["dia_" + (parseInt(_this.pgId) + 1) + "_" + i]);
				console.log("dia_" + (parseInt(_this.pgId) + 1) + "_" + i);
			}
		}
		function resetDia() {
			for (var v of _this.curPgDia) {
				v.dia.gotoAndStop(0);
			}
		}
		function updata() {
			_this.curPgDia[_this.curId].visible = true;
			_this._onp.visible=true;
			resetDia();
			_this.curPgDia[_this.curId].dia.gotoAndStop(1);
			playSoundBySrc(_this.data[_this.pgId][_this.curId].soundPath);
		}
		function nextFun() {
			//
			/*console.log("下一个");
			console.log(_this.curId);
			console.log(_this.curPgDia.length-1);*/
			if (_this.curId < _this.curPgDia.length - 1) {
				_this.curId += 1;
				updata();
			} else {
				_this.canClick = true;
				_this._onp.setStu(true);
				return;
			}
		}
		function prevFun() {
			//
			_this.curId += 1;
		}
		
		
		function ondiamc(e) {
			if (!_this.canClick) {
				return
			}
			_this.clickMode = true;
			for (var item of _this.curPgDia) {
				item.gotoAndStop(0);
			}
			e.currentTarget.gotoAndStop(1);
			const lastChar = e.currentTarget.parent.name.slice(-1);
			_this.curId = Number(lastChar) - 1; // 将 lastChar 转为数字并减去 1
			console.log(_this.curId);
			//点击对话框
			updata();
		}
		
		//子机控制父级
		_this.onPause = function () {
			if (!audio.paused && !audio.ended) {
				audio.pause();
			}
		};
		
		_this.onPlay = function () {
			//if (audio.paused || audio.ended) {
			if (_this.canClick && _this.isEnded) {
				_this.curId = 0;
				_this.clickMode = false;
				_this.canClick = false;
				hideDia();
				updata();
				return;
			} else if (audio.paused) {
				audio.play();
			}
		};
		_this.onClear = function () {
			if (!audio.paused && !audio.ended) {
				audio.pause();
			}
			_this.curId = 0;
			_this.clickMode = false;
			_this.canClick = true;
			_this.isEnded = true;
			hideDia();
			_this._onp.setStu(true);
			//updata();
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(3));

	// 跳转按钮
	this._onp = new lib.暂停播放组();
	this._onp.name = "_onp";
	this._onp.setTransform(943.55,641.9,1,1,0,0,0,37.5,20.4);

	this.gotoBtnMc = new lib.元件19();
	this.gotoBtnMc.name = "gotoBtnMc";
	this.gotoBtnMc.setTransform(662.55,263.35,1.183,1.183,0,0,0,153.1,153.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.gotoBtnMc},{t:this._onp}]}).wait(3));

	// 标题
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AgSAbQgGgCgDgGQgBgHAAgMQAAgMABgGQADgGAGgDQAGgCAMABQAMgBAGACQAHADACAGQACAGAAAMQAAAMgCAHQgCAGgHACQgGACgMAAQgMAAgGgCg");
	this.shape.setTransform(951.1,57.52);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231F20").s().p("AhGBRQAPAAAJgDQAJgDAGgGQAFgGACgIIhFiwIA1AAIApB+IACAAIAoh+IAzAAIg8CgQgIAZgJAPQgJARgLAIQgMAKgQAEQgQAEgXAAg");
	this.shape_1.setTransform(936.075,54.65);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#231F20").s().p("AgTBbQgZAAgRgMQgQgNgJgYQgDgJgBgLIgCgVIAAgHQAAgYAKgTQAKgSATgOQAJgFAJgDQAIgBAJAAIAJAAQAPAAAMAEQAKAGAHAKIAAABIABABIAAAAIAAgFIABgBIAuAAIABAAIAAABIgCA6QAAAmACAYQADAYAEALIABACIABAFIgCABIgtAAIgCgHIgHgSIgBAAQgGANgKAHQgLAGgPAAgAgdgtQgLAKgHAVIgCAKIAAAGQAAAUAHANQAHANANAFIALACIAKABQAMABAIgFQAJgEAFgKQADgGABgLQACgJAAgNQAAgSgEgNQgGgMgIgGQgEgDgGgBQgFgBgHAAIAAAAQgRAAgLAKg");
	this.shape_2.setTransform(915.7,51.25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#231F20").s().p("AgHBcQgQAAgOgCIgagEIAAgoQANAEAOACQAOACANAAQANABAIgEQAHgEAAgKQAAgIgCgEQgEgEgGgDQgHgDgPgDQgSgFgKgGQgLgFgEgJQgDgKAAgPQgBgZARgOQAQgOAmAAQAOAAAOACQANACAHACIgCAlIgMgDIgQgDIgRgBQgOAAgGAEQgHAEABAJQgBAFACADQADADAHADIAVAGQASAFAMAGQAKAGAFAKQAEAKAAAQQgBAfgSANQgTANgfAAIgDAAg");
	this.shape_3.setTransform(898.05,51.2759);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#231F20").s().p("Ag6B0QgQgMgGgUQgGgVABgcQgBgaAGgUQAGgVAQgMQAPgNAdAAQAXAAAMAHQANAHAFAMIAAhfIAvAAIAAD6IgrAAIgEgZQgFAMgMAIQgNAIgXAAQgdAAgPgLgAgXgNQgIAIgDALQgCANAAAQQAAAQACANQADAMAIAHQAIAIAPAAQAQAAAJgHQAJgGAEgNQADgMAAgSQAAgRgEgNQgDgMgJgHQgJgHgQAAQgPAAgIAIg");
	this.shape_4.setTransform(870.4231,47.875);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#231F20").s().p("AAiBbIAAhsQAAgSgGgIQgHgIgQAAQgPAAgJAGQgKAFgDAOIAAB1IgxAAIAAixIAxAAIAAAVQAHgNAPgGQANgGAUAAQAVAAANAHQANAHAGANQAGANgBAUIAAB5g");
	this.shape_5.setTransform(849.85,51.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#231F20").s().p("AgTBbQgZAAgRgMQgQgNgJgYQgDgJgBgLIgCgVIAAgHQABgYAJgTQAKgSATgOQAJgFAIgDQAJgBAJAAIAJAAQAPAAAMAEQAKAGAHAKIAAABIAAABIABAAIAAgFIABgBIAuAAIABAAIAAABIgCA6QAAAmACAYQADAYAEALIABACIABAFIgCABIgtAAIgCgHIgHgSIgBAAQgFANgLAHQgLAGgPAAgAgdgtQgLAKgHAVIgBAKIgBAGQAAAUAHANQAHANAOAFIAKACIAKABQAMABAIgFQAJgEAFgKQACgGACgLQACgJAAgNQAAgSgEgNQgGgMgIgGQgEgDgGgBQgFgBgHAAIAAAAQgRAAgLAKg");
	this.shape_6.setTransform(828.5,51.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#231F20").s().p("AAXB9IgwhMIgHAAIAABMIgxAAIAAj5IAxAAIAACJIAKAAIAthBIA4AAIg/BSIBBBfg");
	this.shape_7.setTransform(802.15,47.725);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#231F20").s().p("AgaBVQgUgIgKgVQgLgUAAgkQAAgjALgUQAKgUAUgIQATgJAbABQAOAAAMABQAMACAIACIAAApQgJgEgKgBQgJgCgMAAQgPAAgKAEQgJAFgFAMQgFAMAAATQAAAVAFALQAFAMAJAEQAKAFAQAAIAVgCQAKgBAKgEIAAAoIgNADIgRADIgSAAIgDAAQgZAAgSgHg");
	this.shape_8.setTransform(783.425,51.3251);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#231F20").s().p("AgXB/IAAixIAvAAIAACxgAgPhNQgGgBgDgGQgCgFAAgMQAAgLACgFQADgFAGgCQAFgCAKABQALgBAGACQAFACADAFQACAFAAALQAAAMgCAFQgDAGgFABQgGACgLAAQgKAAgFgCg");
	this.shape_9.setTransform(770.425,47.595);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#231F20").s().p("AgYByIAAi3Ig8AAIAAgtICpAAIAAAtIg8AAIAAC3g");
	this.shape_10.setTransform(756.6,48.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#231F20").s().p("AgbBzQgGgCgCgFQgDgHAAgLQAAgMADgFQACgHAGgBQAGgDAMABQAKgBAGADQAGABADAHQACAFAAAMQAAALgCAHQgDAFgGACQgGADgKAAQgMAAgGgDgAgeAoIAAgPQAAgJACgHQADgHAFgHQAGgHAKgIIAJgKQAEgFACgFQABgEAAgHQAAgPgIgEQgGgGgUABIgVABQgLACgIADIAAgqQAJgCANgBQANgCAPAAQAaAAARAEQARAFAHANQAIANAAAXQAAAPgDAKQgCAKgHAJQgHAHgLAIIgOAMQgGAFgCAEQgCAFAAAFIAAAIg");
	this.shape_11.setTransform(731.775,48.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#231F20").s().p("ABUBbIAAhsQAAgSgFgIQgHgIgPAAQgOAAgIAGQgJAGgDAOIAAB0IgvAAIAAhsQAAgSgFgIQgHgIgOAAQgOAAgIAGQgIAFgDANIAAB2IgwAAIAAixIAwAAIAAAUQAHgMAMgGQAMgGATAAQAUAAANAHQALAGAGAMQAIgNANgGQAPgGAUAAQAdAAAQAPQAOAQAAAhIAAB1g");
	this.shape_12.setTransform(708.7,51.1742);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#231F20").s().p("AgpBVQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQAUgJAbABQAeAAARAKQARAKAGARQAGASAAAXIgBANIgBALIhyAHQACATALAJQAMAJAXAAQALAAALgCQAMgCAJgDQAKgCAGgEIAAAmQgJAFgSAEQgSADgYAAIgDAAQgYAAgSgHgAgYgtQgJAJgBAWIBIgGQABgKgDgIQgCgIgHgEQgHgFgOAAQgVAAgJAKg");
	this.shape_13.setTransform(683.4518,51.3251);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#231F20").s().p("AAABcQgbABgTgIQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQATgJAbABQAcgBATAJQAUAIAKAUQAKAUAAAjQAAAkgKAUQgKAVgUAIQgSAHgaAAIgDAAgAgWgzQgIAGgEAMQgDANAAAUQAAAWADAMQAEAMAIAFQAJAFANAAQAPAAAIgFQAIgFAEgMQADgMAAgWQAAgUgDgNQgEgMgIgGQgJgFgOAAQgOAAgIAFg");
	this.shape_14.setTransform(663.525,51.3251);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#231F20").s().p("AhVB8IAAjzIAwAAIAAAVQAFgKANgHQAMgHAWgBQAdAAAQAMQAPALAGAVQAGAUgBAdQABAagGATQgGAVgPAMQgQANgdAAQgWAAgNgHQgMgHgFgMIAABZgAgYhQQgJAGgEANQgDANAAASQAAARADAMQAEAMAJAHQAJAHAPAAQARAAAIgIQAIgIACgLQADgNAAgPQAAgRgDgNQgDgMgIgIQgIgHgQAAQgPAAgJAHg");
	this.shape_15.setTransform(643.1769,54.475);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#231F20").s().p("AgpBVQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQAUgJAbABQAeAAARAKQARAKAGARQAGASAAAXIgBANIgBALIhyAHQACATALAJQAMAJAXAAQALAAALgCQAMgCAJgDQAKgCAGgEIAAAmQgJAFgSAEQgSADgYAAIgDAAQgYAAgSgHgAgYgtQgJAJgBAWIBIgGQABgKgDgIQgCgIgHgEQgHgFgOAAQgVAAgJAKg");
	this.shape_16.setTransform(614.0018,51.3251);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#231F20").s().p("AAiB9IAAhtQgBgRgFgIQgHgIgRABQgNgBgKAGQgKAGgEANIAAB1IgvAAIAAj5IAvAAIAABeQAIgNAOgGQAOgGATAAQAWAAANAHQANAGAGAOQAFANABASIAAB6g");
	this.shape_17.setTransform(593.85,47.725);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#231F20").s().p("AgGBqQgNgFgFgNQgGgNAAgXIAAhSIgXAAIAAgmIAXAAIAAgqIAvAAIAAAqIAlAAIAAAmIglAAIAABOQAAAPAEAGQAEAFAMAAIAIAAIAHgBIAAAlIgLABIgNAAIgDAAQgTAAgMgFg");
	this.shape_18.setTransform(577.4,49.3271);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#231F20").s().p("AgfB+IAAiMIgbAAIAAglIAbAAIAAgCQAAgeAJgQQAJgPAOgGQAQgFAWAAIAKABIAKABIAAAiIgHgBIgHAAQgMAAgGADQgHADgCAJQgCAJAAAPIAjAAIAAAlIgjAAIAACMg");
	this.shape_19.setTransform(557.625,47.6479);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#231F20").s().p("AAABcQgbABgTgIQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQATgJAbABQAcgBATAJQAUAIAKAUQAKAUAAAjQAAAkgKAUQgKAVgUAIQgSAHgaAAIgDAAgAgWgzQgIAGgEAMQgDANAAAUQAAAWADAMQAEAMAIAFQAJAFANAAQAPAAAIgFQAIgFAEgMQADgMAAgWQAAgUgDgNQgEgMgIgGQgJgFgOAAQgOAAgIAFg");
	this.shape_20.setTransform(541.025,51.3251);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#231F20").s().p("AgFBqQgOgFgFgNQgGgNAAgXIAAhSIgXAAIAAgmIAXAAIAAgqIAvAAIAAAqIAlAAIAAAmIglAAIAABOQAAAPAEAGQAFAFALAAIAIAAIAGgBIAAAlIgKABIgNAAIgDAAQgTAAgLgFg");
	this.shape_21.setTransform(516.4,49.3271);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#231F20").s().p("AgzBbIAAixIAwAAIAAAgQAFgPAIgIQAIgHAKgDQAJgDALAAIAEAAIgCArIgEAAQgMAAgKADQgKADgIAJQgGAIgDAOIAABlg");
	this.shape_22.setTransform(504.875,51.175);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#231F20").s().p("AgTBbQgZAAgRgMQgQgNgJgYQgDgJgBgLIgCgVIAAgHQABgYAJgTQAKgSATgOQAJgFAJgDQAIgBAJAAIAJAAQAPAAAMAEQAKAGAHAKIAAABIAAABIABAAIAAgFIABgBIAuAAIABAAIAAABIgCA6QAAAmACAYQADAYAEALIABACIABAFIgCABIgtAAIgCgHIgHgSIgBAAQgFANgLAHQgLAGgPAAgAgdgtQgLAKgHAVIgBAKIgBAGQAAAUAHANQAHANAOAFIAKACIAKABQAMABAIgFQAJgEAFgKQADgGABgLQACgJAAgNQAAgSgEgNQgGgMgIgGQgEgDgGgBQgFgBgHAAIAAAAQgRAAgLAKg");
	this.shape_23.setTransform(486.5,51.25);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#231F20").s().p("AhVB8IAAjzIAwAAIAAAVQAFgKANgHQAMgHAWgBQAdAAAQAMQAPALAGAVQAGAUgBAdQABAagGATQgGAVgPAMQgQANgdAAQgWAAgNgHQgMgHgFgMIAABZgAgYhQQgJAGgEANQgDANAAASQAAARADAMQAEAMAJAHQAJAHAPAAQARAAAIgIQAIgIACgLQADgNAAgPQAAgRgDgNQgDgMgIgIQgIgHgQAAQgPAAgJAHg");
	this.shape_24.setTransform(466.7769,54.475);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#231F20").s().p("AgpBVQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQAUgJAbABQAeAAARAKQARAKAGARQAGASAAAXIgBANIgBALIhyAHQACATALAJQAMAJAXAAQALAAALgCQAMgCAJgDQAKgCAGgEIAAAmQgJAFgSAEQgSADgYAAIgDAAQgYAAgSgHgAgYgtQgJAJgBAWIBIgGQABgKgDgIQgCgIgHgEQgHgFgOAAQgVAAgJAKg");
	this.shape_25.setTransform(437.6018,51.3251);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#231F20").s().p("AgFBqQgNgFgGgNQgGgNAAgXIAAhSIgXAAIAAgmIAXAAIAAgqIAvAAIAAAqIAlAAIAAAmIglAAIAABOQAAAPAEAGQAFAFAMAAIAHAAIAGgBIAAAlIgKABIgMAAIgEAAQgTAAgLgFg");
	this.shape_26.setTransform(422,49.3271);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#231F20").s().p("AgXB/IAAixIAvAAIAACxgAgPhNQgGgBgDgGQgCgFAAgMQAAgLACgFQADgFAGgCQAFgCAKABQALgBAGACQAFACADAFQACAFAAALQAAAMgCAFQgDAGgFABQgGACgLAAQgKAAgFgCg");
	this.shape_27.setTransform(411.425,47.595);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#231F20").s().p("AgzBbIAAixIAwAAIAAAgQAFgPAIgIQAIgHAKgDQAJgDALAAIAEAAIgCArIgEAAQgMAAgKADQgKADgIAJQgGAIgDAOIAABlg");
	this.shape_28.setTransform(401.025,51.175);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#231F20").s().p("AgUBaQgWAAgNgGQgNgHgGgNQgGgNAAgUIAAh5IAwAAIAABsQAAASAGAIQAGAIARAAQANAAAKgGQAJgFAEgOIAAh1IAwAAIAACxIgrAAIgEgVQgHANgOAGQgNAGgRAAIgDgBg");
	this.shape_29.setTransform(382.975,51.5019);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#231F20").s().p("AAABcQgbABgTgIQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQATgJAbABQAcgBATAJQAUAIAKAUQAKAUAAAjQAAAkgKAUQgKAVgUAIQgSAHgaAAIgDAAgAgWgzQgIAGgEAMQgDANAAAUQAAAWADAMQAEAMAIAFQAJAFANAAQAPAAAIgFQAIgFAEgMQADgMAAgWQAAgUgDgNQgEgMgIgGQgJgFgOAAQgOAAgIAFg");
	this.shape_30.setTransform(362.425,51.3251);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#231F20").s().p("AgdBZIhAixIA1AAIAoB/IABAAIAqh/IAzAAIhBCxg");
	this.shape_31.setTransform(342.65,51.35);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#231F20").s().p("AgUBbQgYAAgQgMQgRgNgJgYQgDgJgCgLIgBgVIAAgHQAAgYAKgTQAKgSAUgOQAIgFAJgDQAIgBAJAAIAIAAQARAAALAEQAKAGAGAKIABABIABABIAAAAIABgFIABgBIAtAAIABAAIAAABIgCA6QAAAmACAYQADAYAFALIAAACIABAFIgBABIgtAAIgEgHIgFgSIgBAAQgHANgKAHQgLAGgPAAgAgdgtQgMAKgGAVIgCAKIAAAGQAAAUAHANQAHANANAFIAKACIAKABQANABAIgFQAJgEAEgKQADgGADgLQABgJAAgNQAAgSgFgNQgEgMgJgGQgEgDgFgBQgHgBgGAAIgBAAQgQAAgLAKg");
	this.shape_32.setTransform(322.3,51.25);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#231F20").s().p("AgfB+IAAiMIgbAAIAAglIAbAAIAAgCQAAgeAJgQQAJgPAOgGQAQgFAWAAIAKABIAKABIAAAiIgHgBIgHAAQgMAAgGADQgHADgCAJQgCAJAAAPIAjAAIAAAlIgjAAIAACMg");
	this.shape_33.setTransform(307.275,47.6479);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#231F20").s().p("AgzBbIAAixIAwAAIAAAgQAFgPAIgIQAIgHAKgDQAJgDALAAIAEAAIgCArIgEAAQgMAAgKADQgKADgIAJQgGAIgDAOIAABlg");
	this.shape_34.setTransform(286.725,51.175);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#231F20").s().p("AgUBaQgWAAgNgGQgNgHgGgNQgGgNAAgUIAAh5IAwAAIAABsQAAASAGAIQAGAIARAAQANAAAKgGQAJgFAEgOIAAh1IAwAAIAACxIgrAAIgEgVQgHANgOAGQgNAGgRAAIgDgBg");
	this.shape_35.setTransform(268.675,51.5019);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#231F20").s().p("AAABcQgbABgTgIQgUgIgKgVQgKgUAAgkQAAgjAKgUQAKgUAUgIQATgJAbABQAcgBATAJQAUAIAKAUQAKAUAAAjQAAAkgKAUQgKAVgUAIQgSAHgaAAIgDAAgAgWgzQgIAGgEAMQgDANAAAUQAAAWADAMQAEAMAIAFQAJAFANAAQAPAAAIgFQAIgFAEgMQADgMAAgWQAAgUgDgNQgEgMgIgGQgJgFgOAAQgOAAgIAFg");
	this.shape_36.setTransform(248.125,51.3251);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#231F20").s().p("AhGBRQAPAAAJgDQAJgDAGgGQAFgGACgIIhFiwIA1AAIApB+IACAAIAoh+IAzAAIg8CgQgIAZgJAPQgJARgLAIQgMAKgQAEQgQAEgXAAg");
	this.shape_37.setTransform(228.325,54.65);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#231F20").s().p("AgHBcQgPAAgPgCIgagEIAAgoQAMAEAPACQAOACAMAAQAOABAIgEQAHgEAAgKQAAgIgDgEQgDgEgGgDQgHgDgPgDQgSgFgLgGQgKgFgEgJQgDgKgBgPQAAgZARgOQAQgOAmAAQAPAAANACQANACAIACIgDAlIgMgDIgQgDIgRgBQgPAAgFAEQgHAEAAAJQAAAFACADQADADAIADIAUAGQASAFALAGQALAGAFAKQADAKAAAQQABAfgUANQgSANgfAAIgDAAg");
	this.shape_38.setTransform(202.2,51.2759);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#231F20").s().p("AgXB/IAAixIAvAAIAACxgAgPhNQgGgBgDgGQgCgFAAgMQAAgLACgFQADgFAGgCQAFgCAKABQALgBAGACQAFACADAFQACAFAAALQAAAMgCAFQgDAGgFABQgGACgLAAQgKAAgFgCg");
	this.shape_39.setTransform(189.375,47.595);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#231F20").s().p("AgGBqQgNgFgFgNQgGgNAAgXIAAhSIgXAAIAAgmIAXAAIAAgqIAvAAIAAAqIAlAAIAAAmIglAAIAABOQAAAPAEAGQAEAFAMAAIAIAAIAHgBIAAAlIgLABIgNAAIgDAAQgTAAgMgFg");
	this.shape_40.setTransform(170.25,49.3271);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#231F20").s().p("AgTBbQgZAAgRgMQgQgNgJgYQgDgJgCgLIgBgVIAAgHQABgYAJgTQAKgSATgOQAJgFAIgDQAJgBAJAAIAJAAQAPAAALAEQAMAGAGAKIAAABIAAABIABAAIAAgFIABgBIAuAAIABAAIAAABIgCA6QAAAmADAYQACAYAEALIABACIABAFIgCABIgtAAIgDgHIgGgSIgBAAQgFANgLAHQgLAGgPAAgAgdgtQgMAKgGAVIgBAKIgBAGQAAAUAHANQAHANAOAFIAKACIAKABQALABAJgFQAJgEAFgKQACgGACgLQACgJAAgNQAAgSgEgNQgFgMgJgGQgEgDgGgBQgFgBgHAAIAAAAQgRAAgLAKg");
	this.shape_41.setTransform(153.6,51.25);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#231F20").s().p("AAhB9IAAhtQABgRgHgIQgGgIgQABQgPgBgJAGQgKAGgDANIAAB1IgxAAIAAj5IAxAAIAABeQAHgNAOgGQANgGAVAAQAVAAANAHQANAGAGAOQAGANgBASIAAB6g");
	this.shape_42.setTransform(133.55,47.725);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#231F20").s().p("AAjByIgjiQIgBAAIgkCQIg/AAIgxjkIA0AAIAhCpIACAAIAjiTIA5AAIAhCTIACAAIAhipIA1AAIg1Dkg");
	this.shape_43.setTransform(107.35,48.8);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("ABYCZIgahMIh7AAIgbBMIhFAAIBykxIBYAAIBxExgAAqAWIgnhzIgFAAIgoBzIBUAAg");
	this.shape_44.setTransform(46.625,45.175);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#0D8075").s().p("AirCsQhHhHAAhlQAAhkBHhIQBHhGBkAAQBlAABHBGQBHBIAABkQAABlhHBHQhHBHhlAAQhkAAhHhHg");
	this.shape_45.setTransform(46.725,47.675);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(2));

	// 图层_2
	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#231815").s().p("ApfCGQAQAAAKgFQAKgEAGgJQAHgKAEgOIhIixIAfAAIA3CTIACAAIAziTIAdAAIhACrQgIAXgKAQQgJAQgQAIQgQAJgaAAgEg8NACGQAPAAAKgFQAKgEAHgJQAGgKAEgOIhHixIAfAAIA2CTIACAAIA0iTIAcAAIhACrQgIAXgJAQQgKAQgQAIQgPAJgaAAgEA5iABfIgIAAQgaAAgSgNQgSgOgJgcIgCgOIgBgNIAAgKQAAgbALgVQALgUAXgOQAJgFAJgCQAIgCAJAAIADAAQAeAAAUAgIAAgIIABgBIAbAAIABABIAAAAIAABeIABAhQACAQADAOIgCABIgbAAQgBAAgBgIIgDgVIgGAJIgHAIQgIAHgKADQgJADgJAAIgDAAgEA5FgA1QgOAKgIAUIgDANIgBANIAAAHQAAASAGAOQAHAOAOAKQAFADAGACQAGABAGAAIAGAAQAzAAAAg+IAAgLQAAgZgJgQQgJgPgRgFIgHAAIgEgBIgBAAQgUAAgOAKgEAyvABXQgSgIgKgUQgKgVAAgjQAAgiAKgUQAJgVASgIQATgJAZABQAXAAAOAHQAOAGAHALQAIALADANQADANgBANIAAAJIgBALIh5AIQAAATAFANQAGAMAMAGQANAGAVAAQAPAAAPgDQAPgDALgFIAAAaQgFADgKACIgVAEIgYABIgDAAQgZAAgRgIgEAy7gA6QgLAHgEANQgFANAAATIBegHQABgOgDgMQgDgLgKgIQgJgHgTAAQgUAAgLAHgAKXBXQgSgIgKgUQgKgVAAgjQAAgiAKgUQAJgVASgIQATgJAZABQAXAAAOAHQAOAGAHALQAIALADANQADANgBANIAAAJIgBALIh5AIQAAATAFANQAGAMAMAGQANAGAVAAQAPAAAPgDQAPgDALgFIAAAaQgFADgKACIgVAEIgYABIgDAAQgZAAgRgIgAKjg6QgLAHgEANQgFANAAATIBegHQABgOgDgMQgDgLgKgIQgJgHgTAAQgUAAgLAHgAABBXQgRgIgKgUQgKgVAAgjQAAgiAKgUQAJgVARgIQATgJAZABQAXAAAOAHQAOAGAHALQAIALADANQADANgBANIAAAJIgBALIh4AIQAAATAFANQAFAMAMAGQANAGAVAAQAPAAAPgDQAPgDALgFIAAAaQgFADgKACIgVAEIgYABIgDAAQgZAAgRgIgAANg6QgLAHgDANQgFANAAATIBdgHQABgOgDgMQgDgLgKgIQgJgHgTAAQgUAAgLAHgEgnvABXQgSgIgKgUQgJgVAAgjQAAgiAJgUQAKgVASgIQASgJAaABQAWAAAOAHQAOAGAIALQAIALACANQADANAAANIgBAJIgBALIh5AIQAAATAGANQAFAMANAGQAMAGAVAAQAQAAAPgDQAPgDAKgFIAAAaQgFADgJACIgVAEIgZABIgDAAQgYAAgSgIgEgnjgA6QgLAHgEANQgEANgBATIBfgHQAAgOgDgMQgDgLgJgIQgJgHgTAAQgVAAgLAHgEgqtABXQgSgIgKgUQgKgVAAgjQAAgiAKgUQAJgVASgIQATgJAZABQAXAAAOAHQAOAGAHALQAIALADANQADANgBANIAAAJIgBALIh5AIQAAATAFANQAGAMAMAGQANAGAVAAQAPAAAPgDQAPgDALgFIAAAaQgFADgKACIgVAEIgYABIgDAAQgZAAgRgIgEgqhgA6QgLAHgEANQgFANAAATIBegHQABgOgDgMQgDgLgKgIQgJgHgTAAQgUAAgLAHgEgytABXQgSgIgKgUQgJgVAAgjQAAgiAJgUQAKgVASgIQASgJAaABQAWAAAOAHQAOAGAIALQAIALACANQADANAAANIgBAJIgBALIh5AIQAAATAGANQAFAMANAGQAMAGAVAAQAQAAAPgDQAPgDAKgFIAAAaQgFADgJACIgVAEIgZABIgDAAQgYAAgSgIgEgyhgA6QgLAHgEANQgEANgBATIBfgHQAAgOgDgMQgDgLgJgIQgJgHgTAAQgVAAgLAHgAr5BWQgOgJgFgQIgDAfIgZAAIAAj5IAcAAIAABoQAFgQAOgKQAOgJAZAAQAdAAARAMQAQALAGAVQAGAVAAAaQAAAZgGAVQgGAVgQANQgRAMgdAAQgaAAgNgJgAr3g4QgMAIgFAPQgFAQAAAUQAAAVAFAPQAFAPAMAJQAMAIAVAAQAVAAAKgKQALgJADgQQADgPAAgSQAAgSgDgPQgEgQgKgJQgKgJgVAAQgVAAgMAIgEg+oABWQgNgJgFgQIgEAfIgZAAIAAj5IAdAAIAABoQAFgQANgKQAOgJAZAAQAeAAAQAMQAQALAGAVQAGAVAAAaQAAAZgGAVQgGAVgQANQgQAMgeAAQgZAAgOgJgEg+mgA4QgMAIgFAPQgFAQAAAUQAAAVAFAPQAFAPAMAJQAMAIAWAAQAVAAAKgKQAKgJADgQQAEgPgBgSQABgSgEgPQgDgQgLgJQgKgJgUAAQgWAAgMAIgEAtwABaQgMgFgFgMQgFgMAAgXIAAhjIgaAAIAAgYIAaAAIAAgqIAdAAIAAAqIAsAAIAAAYIgsAAIAABhQgBAOACAHQACAIAGADQAGADAKgBIALAAIAJgBIAAAYIgKABIgKAAIgEAAQgRAAgLgEgAk9BaQgMgFgFgMQgFgMAAgXIAAhjIgaAAIAAgYIAaAAIAAgqIAdAAIAAAqIAsAAIAAAYIgsAAIAABhQgBAOACAHQACAIAGADQAGADAKgBIALAAIAJgBIAAAYIgKABIgKAAIgEAAQgRAAgLgEgEgudABaQgMgFgFgMQgFgMAAgXIAAhjIgaAAIAAgYIAaAAIAAgqIAdAAIAAAqIAsAAIAAAYIgsAAIAABhQgBAOACAHQACAIAGADQAGADAKgBIALAAIAJgBIAAAYIgKABIgKAAIgEAAQgRAAgLgEgEg3rABaQgMgFgFgMQgFgMAAgXIAAhjIgbAAIAAgYIAbAAIAAgqIAcAAIAAAqIAsAAIAAAYIgsAAIAABhQAAAOACAHQACAIAFADQAGADALgBIAKAAIAJgBIAAAYIgKABIgKAAIgDAAQgRAAgLgEgEA+7ABcIAAhwQAAgNgCgKQgDgKgHgFQgIgFgOAAQgLAAgLACQgKADgIAIQgJAHgFAQIAAB3IgcAAIAAixIAcAAIAAAZQAGgLAJgGQAJgGALgDQALgCALAAQAXAAANAHQANAIAGANQAFANAAARIAAB6gEA7uABcIAAixIAdAAIAACxgEA2nABcIAAixIAdAAIAAAgQAFgOAKgIQAJgIALgDQALgCAKAAIAEAAIgBAZIgEAAQgMAAgKAEQgLADgJAIQgIAJgFAQIAABzgEAw9ABcIAAhwQAAgNgDgKQgDgKgHgFQgIgFgOAAQgLAAgLACQgKADgIAIQgJAHgFAQIAAB3IgcAAIAAj5IAcAAIAABhQAGgLAJgGQAJgGALgDQALgCALAAQAXAAANAHQANAIAGANQAFANAAARIAAB6gEAqsABcIAAhwQAAgNgCgKQgDgKgHgFQgIgFgOAAQgLAAgLACQgKADgIAIQgJAHgFAQIAAB3IgcAAIAAixIAcAAIAAAZQAGgLAJgGQAJgGALgDQALgCALAAQAXAAANAHQANAIAGANQAFANAAARIAAB6gEAnfABcIAAixIAdAAIAACxgAM6BcIAAixIAdAAIAAAgQAFgOAKgIQAJgIALgDQALgCAKAAIAEAAIgBAZIgEAAQgMAAgKAEQgLADgJAIQgIAJgFAQIAABzgAH3BcIhDixIAdAAIA2CVIACAAIA0iVIAeAAIhDCxgAF2BcIAAixIAdAAIAACxgAD5BcIAAixIAdAAIAAAgQAFgOAKgIQAJgIALgDQALgCAKAAIAEAAIgBAZIgEAAQgMAAgKAEQgLADgJAIQgIAJgFAQIAABzgAhwBcIAAhwQAAgNgDgKQgDgKgHgFQgIgFgOAAQgLAAgLACQgKADgIAIQgJAHgFAQIAAB3IgcAAIAAj5IAcAAIAABhQAGgLAJgGQAJgGALgDQALgCALAAQAXAAANAHQANAIAGANQAFANAAARIAAB6gEgtFABcIAAixIAcAAIAAAgQAGgOAJgIQAJgIALgDQALgCALAAIADAAIgBAZIgEAAQgLAAgLAEQgLADgIAIQgJAJgFAQIAABzgEg0fABcIAAhwQAAgNgDgKQgCgKgIgFQgHgFgOAAQgMAAgKACQgLADgIAIQgIAHgFAQIAAB3IgdAAIAAj5IAdAAIAABhQAFgLAJgGQAKgGALgDQALgCALAAQAXAAANAHQANAIAFANQAGANgBARIAAB6gEA79gB2QgJABgEgEQgFgDABgKQgBgLAFgDQAEgEAJABQAJgBAEAEQAEADAAALQAAAKgEADQgEADgHAAIgCAAgEAnugB2QgJABgEgEQgFgDABgKQgBgLAFgDQAEgEAJABQAJgBAEAEQAEADAAALQAAAKgEADQgEADgHAAIgCAAgAGFh2QgJABgEgEQgFgDABgKQgBgLAFgDQAEgEAJABQAJgBAEAEQAEADAAALQAAAKgEADQgEADgHAAIgCAAg");
	this.shape_46.setTransform(641.7271,399.625);

	this.instance = new lib.位图18();
	this.instance.setTransform(156,99,0.56,0.56);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_46}]}).wait(3));

	// 对话内容
	this.dia_1_1 = new lib.d1_1();
	this.dia_1_1.name = "dia_1_1";
	this.dia_1_1.setTransform(441.6,1007.45,1,1,0,0,0,159.4,40.5);

	this.dia_1_2 = new lib.d1_1();
	this.dia_1_2.name = "dia_1_2";
	this.dia_1_2.setTransform(467.6,633.5,1,1,0,0,0,159.4,40.5);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f().s("#FE8659").ss(8,1,1).p("EhHCgC2IACiXIAFmoQAAgIABgIQALiPBbhoQBph4CUAAMCDJAAAQCUAABpB4QBjBwAGCdQAAACAAACQAAACAAADIgIJrEBHNgB7IgBAcIgBC/EBHNgC2IAAA7IAAAcEBHBAHDIgBAMIAAAHIgDEGQAACphoB3QhpB4iVAAMiDIAAAQiVAAhph4Qhoh3AAipIAJpKEBHBAHDIAAAGIgBANEBHBAGWIAAAtEBHJABgIgDE2EhHIgAxIABgiIABj6EhHIgAxIAAgiEhHKADiIAAhQEhHKADiIABhQIABjDEhHOAGWIAEhiEhHKAGWIAAhiIAAhS");
	this.shape_47.setTransform(640,564.4);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("EhBxAR0QiVAAhoh3Qhph4AAipIAJpKIAEAAIABAAIAABQIAAhQIABjDIABgiIABj6IAGAAIgCCXIACiXIAFmoIABgQQALiPBbhoQBph3CVAAMCDIAAAQCUAABpB3QBiBwAGCdIAAAEIAAAFIgHJrIgDAAIAAg7IAAA7IgBAcIgBC/IgCAAIgDE2IgFAAIgBAuIAAALIAAAIIAAgIIAAgGIAAAOIgDEFQAACphoB4QhpB3iVAAgEhHJAE0IgBBiIABhiIAAhSgEhHOAGWIAFhigEhHJADiIgBhQgEhHIgBTIABAAIgBAigEhHHgBTgEBHMgBfIABgcIAAAcgEhHAgFNg");
	this.shape_48.setTransform(640,564.4);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f().s("#FCE0CE").ss(18,1,1).p("EhHCgC2IACiXIAFmoQAAgIABgIQALiPBbhoQBph4CUAAMCDJAAAQCUAABpB4QBjBwAGCdQAAACAAACQAAACAAADIgIJrEBHNgB7IAAAcEBHNgC2IAAA7IgBAcIgBC/EBHAAHWIgDEGQAACphoB3QhpB4iVAAMiDIAAAQiVAAhph4Qhoh3AAipIAJpKEBHBAGWIAAAtIAAAGIgBANEBHBAHDIgBAMIAAAHEBHJABgIgDE2EhHKADiIABhQIABjDIAAgiEhHKADiIAAhQEhHIgAxIABgiIABj6EhHKAGWIAAhiEhHOAGWIAEhiIAAhS");
	this.shape_49.setTransform(640,564.4);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("EhBxAR0QiVAAhoh3Qhph4AAipIAJpKIAEAAIABAAIAABQIAAhQIABjDIABgiIABj6IAGAAIgCCXIACiXIAFmoIABgQQALiPBbhoQBph3CVAAMCDIAAAQCUAABpB3QBiBwAGCdIAAAEIAAAFIgHJrIgDAAIAAg7IAAA7IgBAcIgBC/IgCAAIgDE2IgFAAIgBAuIAAALIAAgGIAAAOIAAgIIAAAIIgDEFQAACphoB4QhpB3iVAAgEhHKAGWIABhiIAAhSIgBhQIABBQIAABSIgFBiIAFhigEhHIgBTIABAAIgBAigEBHMgBfIABgcIAAAcgEhHAgFNg");
	this.shape_50.setTransform(640,564.4);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f().s("#FE8659").ss(8,1,1).p("Eg4LgRLMBwXAAAQCVAABoB3QBpB4AACqIAAVlQAACphpB4QhoB4iVAAMhwXAAAQiVAAhph4Qhnh4AAipIAA1lQAAiqBnh4QBph3CVAAg");
	this.shape_51.setTransform(578.6,568.45);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("Eg4LARMQiVAAhoh4Qhoh3AAiqIAA1lQAAipBoh4QBoh4CVAAMBwXAAAQCVAABoB4QBpB4AACpIAAVlQAACqhpB3QhoB4iVAAg");
	this.shape_52.setTransform(578.6,568.45);

	this.dia_2_1 = new lib.d1_1复制2();
	this.dia_2_1.name = "dia_2_1";
	this.dia_2_1.setTransform(454.6,974.45,1,1,0,0,0,159.4,40.5);

	this.dia_2_2 = new lib.d1_1复制2();
	this.dia_2_2.name = "dia_2_2";
	this.dia_2_2.setTransform(467.6,633.5,1,1,0,0,0,159.4,40.5);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f().s("#FE8659").ss(8,1,1).p("EhHCgC2IACiXIAFmoQAAgIABgIQALiPBbhoQBph4CUAAMCDJAAAQCUAABpB4QBjBwAGCdQAAACAAACQAAACAAADIgIJrEBHNgB7IAAAcEBHNgC2IAAA7IgBAcIgBC/EBHAAHWIgDEGQAACphoB3QhpB4iVAAMiDIAAAQiVAAhph4Qhoh3AAipIAJpKEBHBAGWIAAAtIAAAGIgBANEBHBAHDIgBAMIAAAHEBHJABgIgDE2EhHKADiIABhQIABjDIAAgiEhHKADiIAAhQEhHIgAxIABgiIABj6EhHKAGWIAAhiEhHOAGWIAEhiIAAhS");
	this.shape_53.setTransform(640,564.4);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f().s("#FCE0CE").ss(18,1,1).p("EhHCgC2IACiXIAFmoQAAgIABgIQALiPBbhoQBph4CUAAMCDJAAAQCUAABpB4QBjBwAGCdQAAACAAACQAAACAAADIgIJrEBHNgB7IgBAcIgBC/EBHNgC2IAAA7IAAAcEBHBAHDIgBAMIAAAHIgDEGQAACphoB3QhpB4iVAAMiDIAAAQiVAAhph4Qhoh3AAipIAJpKEBHBAHDIAAAGIgBANEBHBAGWIAAAtEBHJABgIgDE2EhHIgAxIABgiIABj6EhHIgAxIAAgiEhHKADiIAAhQEhHKADiIABhQIABjDEhHOAGWIAEhiEhHKAGWIAAhiIAAhS");
	this.shape_54.setTransform(640,564.4);

	this.dia_3_1 = new lib.d1_1复制();
	this.dia_3_1.name = "dia_3_1";
	this.dia_3_1.setTransform(446.6,972.45,1,1,0,0,0,159.4,40.5);

	this.dia_3_2 = new lib.d1_1复制();
	this.dia_3_2.name = "dia_3_2";
	this.dia_3_2.setTransform(467.6,633.5,1,1,0,0,0,159.4,40.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.dia_1_2},{t:this.dia_1_1}]}).to({state:[{t:this.shape_52},{t:this.shape_51},{t:this.shape_48},{t:this.shape_54},{t:this.shape_50},{t:this.shape_53},{t:this.dia_2_2},{t:this.dia_2_1}]},1).to({state:[{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.dia_3_2},{t:this.dia_3_1}]},1).wait(1));

	// diban
	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("rgba(255,255,255,0.8)").s().p("EhkVAEsIAApXMDIrAAAIAAJXg");
	this.shape_55.setTransform(639.9,690.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_55).wait(3));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = rect = new cjs.Rectangle(637.7,366.2,1284.5,959.7);
p.frameBounds = [rect, new cjs.Rectangle(637.7,366.2,1284.5,926.7), new cjs.Rectangle(637.7,366.2,1284.5,924.7)];
// library properties:
lib.properties = {
	id: 'E637B31863A9224E9952B4D82164A654',
	width: 1280,
	height: 720,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/index_atlas_1.png", id:"index_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['E637B31863A9224E9952B4D82164A654'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;